Repository openobserve/openobserve, pull requests merged in 2023-09, with the labels that each got.

#1474 fix: 1471 Increase the precision of the duration field to nanoseconds
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: breakingChange

#1529 fix: Syslog ingestion message values are 'cut off' #1514
  src/handler/tcp_udp/mod.rs
Labels: In Progress

#1548 fix: grpc header issue
  src/common/infra/config.rs
  web/src/locales/languages/en.json
Labels: bug

#1559 feat: folders for dashboards
  src/common/meta/dashboards/mod.rs
  src/common/meta/dashboards/v1/mod.rs
  src/common/meta/dashboards/v2/mod.rs
  src/common/meta/prom.rs
  src/common/meta/stream.rs
  src/handler/http/request/dashboards/folders.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/main.rs
  src/service/dashboards.rs
  src/service/dashboards/folders.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/folders.rs
  src/service/db/dashboards/mod.rs
  src/service/db/mod.rs
Labels: ✏️ Feature

#1561 fix: dynamodb changes for dashboard
  src/common/infra/db/dynamo.rs
  src/service/dashboards/folders.rs
  src/service/db/dashboards/folders.rs
Labels: ☢️ Bug

#1560 fix: Chunking of Data Prevents Uploads of Large CSV Files to Enrichment Tables
  src/common/infra/config.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#1565 fix: all labels to have string values
  src/service/metrics/json.rs
  src/service/metrics/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
Labels: ☢️ Bug

#1568 fix: revert zo grpc org header key
  src/common/infra/config.rs
  src/common/migration/dashboards.rs
  src/main.rs
Labels: ☢️ Bug

#1566 fix: Clippy errors in tests
  src/common/meta/telemetry.rs
  src/common/utils/http.rs
  src/common/utils/notification.rs
  src/common/utils/stream.rs
  src/service/alerts/mod.rs
  src/service/ingestion/grpc.rs
  src/service/logs/syslog.rs
  src/service/promql/common.rs
  src/service/promql/value.rs
  src/service/search/mod.rs
  tests/integration_test.rs
Labels: ☢️ Bug, 🧹 Updates

#1543 fix: file list issues
  src/common/infra/config.rs
  src/common/infra/db/dynamo.rs
  src/common/infra/db/etcd.rs
  src/common/infra/db/mod.rs
  src/common/infra/db/postgres.rs
  src/common/infra/db/sled.rs
  src/common/infra/db/sqlite.rs
  src/common/infra/file_list/dynamo.rs
  src/common/infra/file_list/mod.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/infra/mod.rs
  src/common/migration/mod.rs
  src/common/utils/time.rs
  src/job/files/mod.rs
  src/job/mod.rs
  src/main.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/file_list/mod.rs
  src/service/db/file_list/remote.rs
  src/service/metrics/json.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#1581 fix: timeseries panels are not rendering for custom query
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1585 fix: default folder rename issue
  src/handler/http/request/dashboards/folders.rs
  src/service/dashboards/folders.rs
  src/service/dashboards/mod.rs
Labels: ☢️ Bug

#1577 feat: optimize file list
  Cargo.lock
  Cargo.toml
  build.rs
  proto/cluster/common.proto
  proto/cluster/event.proto
  proto/cluster/filelist.proto
  proto/cluster/metrics.proto
  proto/cluster/search.proto
  proto/cluster/usage.proto
  src/common/infra/cluster.rs
  src/common/infra/config.rs
  src/common/infra/db/mod.rs
  src/common/infra/db/postgres.rs
  src/common/infra/db/sqlite.rs
  src/common/infra/file_list/dynamo.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/meta/common.rs
  src/common/migration/file_list.rs
  src/handler/grpc/request/event.rs
  src/handler/grpc/request/filelist.rs
  src/handler/grpc/request/logs.rs
  src/handler/grpc/request/mod.rs
  src/handler/grpc/request/search.rs
  src/handler/grpc/request/traces.rs
  src/job/file_list.rs
  src/job/files/broadcast.rs
  src/job/files/disk.rs
  src/job/files/memory.rs
  src/job/files/mod.rs
  src/main.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/file_list/local.rs
  src/service/db/file_list/mod.rs
  src/service/db/schema.rs
  src/service/file_list.rs
  src/service/logs/otlp_grpc.rs
  src/service/metrics/prom.rs
  src/service/promql/search/grpc/storage.rs
  src/service/schema.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug, ✏️ Feature
