Repository openobserve/openobserve, pull requests merged in 2023-11, with the labels that each got.

#1823 fix: language text
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#1825 fix: ingestion page ui changes
  web/src/components/CopyContent.vue
  web/src/components/MenuLink.vue
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/logs/Curl.vue
  web/src/components/ingestion/logs/FileBeat.vue
  web/src/components/ingestion/logs/FluentBit.vue
  web/src/components/ingestion/logs/Fluentd.vue
  web/src/components/ingestion/logs/GcpPubSub.vue
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/logs/SysLog.vue
  web/src/components/ingestion/logs/SyslogNg.vue
  web/src/components/ingestion/logs/Vector.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/components/ingestion/traces/Index.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/styles/app.scss
Labels: ☢️ Bug

#1826 fix: dashboard add panel autocomplete metric suggestions
  web/src/components/dashboards/QueryEditor.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, ✏️ Feature

#1829 fix: update rum configuration
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
Labels: ☢️ Bug, 🧹 Updates

#1834 fix: #1833
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#1832 fix: Proxy url for fetching css assets in RUM sessions
  web/public/rumCssWorker.js
  web/src/components/rum/VideoPlayer.vue
Labels: ☢️ Bug

#1836 fix: removed kinesis firehose and gcp ingestion tabs from opensource version
  web/src/components/ingestion/logs/Index.vue
  web/src/composables/shared/useIngestionRoutes.ts
Labels: ☢️ Bug, 🧹 Updates

#1837 fix: metric tooltip overflow
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1838 fix: Kinesis firehose API
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/handler/http/auth/mod.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/functions.rs
Labels: ☢️ Bug

#1841 fix: RUM UI issues
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/utils/rum/errors.json
  web/src/utils/rum/web_vitals.json
Labels: ☢️ Bug

#1840 fix: removed everything after -- from all lines
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#1844 fix: Update useLogs.ts
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#1845 fix: issues reported in sentry related to dashboard
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1846 fix: unit calculation error
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug

#1847 fix: show no data when missing axis value which is required for plotting charts
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#1848 fix: fixed token issue
  web/src/views/Ingestion.vue
Labels: ☢️ Bug

#1849 fix: fixed RUM css worker path
  web/src/components/rum/VideoPlayer.vue
Labels: ☢️ Bug

#1851 fix: OTEL label
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
Labels: ☢️ Bug

#1820 feat: Overcome the cors issue using a proxy
  src/common/meta/mod.rs
  src/common/meta/proxy.rs
  src/handler/http/auth/mod.rs
  src/handler/http/router/mod.rs
  src/main.rs
Labels: ✏️ Feature

#1850 fix: added rum worker file inside src
  web/src/components/rum/VideoPlayer.vue
  web/src/workers/rumcssworker.js
Labels: ☢️ Bug, ✏️ Feature

#1852 feat: support sidecar querier for ingester
  src/common/infra/config.rs
  src/job/file_list.rs
  src/job/files/disk.rs
  src/job/files/mod.rs
  src/main.rs
Labels: ✏️ Feature

#1854 fix: fixed rum UI issues
  web/package-lock.json
  web/package.json
  web/src/components/rum/VideoPlayer.vue
  web/src/components/rum/errorTracking/view/ErrorTag.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/components/rum/sessionReplay/SessionLocationColumn.vue
  web/src/layouts/MainLayout.vue
  web/src/utils/rum/api.json
  web/src/utils/rum/errors.json
  web/src/utils/rum/overview.json
  web/src/utils/rum/web_vitals.json
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppPerformance.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#1855 fix: data type conflict for traces
  src/handler/http/router/mod.rs
  src/handler/http/router/ui.rs
  src/job/files/disk.rs
  src/service/ingestion/grpc.rs
  src/service/logs/otlp_grpc.rs
  src/service/metrics/otlp_grpc.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#1858 fix: dashboard on query exception loading indicator doesn't disappear
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#1860 fix: fixed duplicated editor id's
  web/src/components/logstream/explore/SearchBar.vue
  web/src/components/rum/SearchBar.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/rum/usePerformance.ts
  web/src/plugins/traces/SearchBar.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/RealUserMonitoring.vue
  web/src/views/RUM/SessionViewer.vue
  web/vite.config.ts
Labels: ☢️ Bug

#1864 perf: improve language
  web/src/components/alerts/AddTemplate.vue
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/logs/Index.vue
  web/src/components/ingestion/metrics/Index.vue
  web/src/components/ingestion/traces/Index.vue
  web/src/locales/languages/de.json
  web/src/locales/languages/en.json
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/locales/languages/hi.json
  web/src/locales/languages/it.json
  web/src/locales/languages/ja.json
  web/src/locales/languages/ko.json
  web/src/locales/languages/nl.json
  web/src/locales/languages/pt.json
  web/src/locales/languages/tr.json
  web/src/locales/languages/zh.json
Labels: 🧹 Updates

#1863 ci: update release note
  .github/release-drafter.yml
Labels: 🧹 Updates

#1866 ci: update release note
  .github/release-drafter.yml
Labels: 🧹 Updates

#1872 fix: k8s events stream name
  web/package-lock.json
  web/src/components/ingestion/Custom.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
Labels: ☢️ Bug

#1868 fix: language translation label
  web/src/views/Ingestion.vue
Labels: ☢️ Bug

#1874 fix: support sidecar querier for ingester
  src/common/infra/cluster.rs
  src/main.rs
Labels: ☢️ Bug, ✏️ Feature

#1875 fix: ui issue on logs, metrics, traces
  web/src/components/AutoRefreshInterval.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/metrics/SyntaxGuideMetrics.vue
  web/src/plugins/traces/SearchBar.vue
Labels: ☢️ Bug

#1876 fix: overlap issue
  web/src/styles/app.scss
Labels: ☢️ Bug

#1878 fix: custom error handling for dashboard components
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/utils/rum/overview.json
Labels: ☢️ Bug

#1879 fix: date picker auto close on relative / absolute date change
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#1882 fix: delete Recommended icon for ingestion
  web/src/components/ingestion/logs/Index.vue
Labels: ☢️ Bug

#1884 fix: Issue 1870 overlap issue
  web/src/components/DateTimePicker.vue
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/functions/AddEnrichmentTable.vue
  web/src/components/functions/AssociatedStreamFunction.vue
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/logs/Index.vue
  web/src/components/ingestion/logs/SysLog.vue
  web/src/components/ingestion/metrics/Index.vue
  web/src/components/ingestion/rum/Index.vue
  web/src/components/ingestion/traces/Index.vue
  web/src/components/login/Login.vue
  web/src/components/rum/ErrorsList.vue
  web/src/components/rum/SessionsList.vue
  web/src/components/rum/VideoPlayer.vue
  web/src/components/rum/errorTracking/view/ErrorEvents.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/shared/filter/FilterCreatorPopup.vue
  web/src/components/tickets/AddUpdateTicket.vue
  web/src/enterprise/components/billings/plans.vue
  web/src/enterprise/components/settings/ApiKeys.vue
  web/src/locales/languages/de.json
  web/src/locales/languages/en.json
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/locales/languages/hi.json
  web/src/locales/languages/it.json
  web/src/locales/languages/ja.json
  web/src/locales/languages/ko.json
  web/src/locales/languages/nl.json
  web/src/locales/languages/pt.json
  web/src/locales/languages/tr.json
  web/src/locales/languages/zh.json
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/DetailTable.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/styles/app.scss
  web/src/views/About.vue
  web/src/views/Dashboards/ImportDashboard.vue
  web/src/views/DetailTable.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#1886 fix: translation issue
  web/src/components/dashboards/AddFolder.vue
  web/src/locales/languages/de.json
  web/src/locales/languages/en.json
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/locales/languages/hi.json
  web/src/locales/languages/it.json
  web/src/locales/languages/ja.json
  web/src/locales/languages/ko.json
  web/src/locales/languages/nl.json
  web/src/locales/languages/pt.json
  web/src/locales/languages/tr.json
  web/src/locales/languages/zh.json
Labels: ☢️ Bug

#1887 fix: improve language
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/logs/Index.vue
  web/src/components/ingestion/metrics/Index.vue
  web/src/components/ingestion/traces/Index.vue
  web/src/locales/languages/de.json
  web/src/locales/languages/en.json
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/locales/languages/hi.json
  web/src/locales/languages/it.json
  web/src/locales/languages/ja.json
  web/src/locales/languages/ko.json
  web/src/locales/languages/nl.json
  web/src/locales/languages/pt.json
  web/src/locales/languages/tr.json
  web/src/locales/languages/zh.json
Labels: ☢️ Bug, 🧹 Updates

#1889 fix: on time change, flicker issue for variable dependent chart
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#1888 fix: Consistent date time in all RUM tabs
  web/src/components/DateTime.vue
  web/src/components/rum/performance/PerformanceOverview.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/composables/rum/useRum.ts
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppPerformance.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/RealUserMonitoring.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#1891 fix: RUM dashboard overlay
  web/src/components/rum/errorTracking/view/ErrorHeader.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/utils/rum/overview.json
  web/src/views/RUM/SessionViewer.vue
  web/vite.config.ts
Labels: ☢️ Bug

#1895 fix: typo in label in add panel page
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
Labels: ☢️ Bug

#1894 feat: add musl release binary for arm64 architecture
  .cargo/config.toml
  .github/workflows/release.yml
Labels: ✏️ Feature

#1896 fix: Filter out empty rows in search results.
  src/service/search/mod.rs
Labels: ☢️ Bug

#1899 fix: Logs field values filtering in sql mode
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#1898 fix: enable compact for distinct_values
  src/common/infra/wal.rs
  src/handler/grpc/request/metrics/querier.rs
  src/job/files/disk.rs
  src/job/files/memory.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#1905 fix: Session events were not getting fetched correctly
  web/src/components/rum/VideoPlayer.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#1906 fix: capitalize issue and no data for pie and donut
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
Labels: ☢️ Bug

#1908 fix: fix the copy/paste instructions for linux systems
  web/src/components/ingestion/recommended/LinuxConfig.vue
Labels: ☢️ Bug

#1909 fix: comment out the musl build for arm64 for now
  .github/workflows/release.yml
Labels: ☢️ Bug, 📒 Documentation

#1911 feat: set pushdown_filters only for normal query
  src/common/meta/search.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ✏️ Feature

#1913 fix: time show error
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug

#1914 fix: dashboards table list max record label overlap issue for francais language
  web/src/components/shared/grid/Pagination.vue
Labels: ☢️ Bug

#1916 fix: clean up the windows installation instruction for otel
  web/src/components/ingestion/recommended/WindowsConfig.vue
Labels: ☢️ Bug

#1919 fix: Minor UI fixes in RUM error tracking
  web/src/components/rum/errorTracking/view/ErrorHeader.vue
  web/src/components/rum/errorTracking/view/ErrorTags.vue
Labels: ☢️ Bug

#1920 fix: partition key filter with In and Or
  src/common/meta/sql.rs
  src/service/promql/engine.rs
  src/service/promql/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#1917 fix: return 404 if the delete target not exists
  src/service/alerts/templates.rs
  src/service/dashboards/mod.rs
Labels: ☢️ Bug

#1922 fix: del alert error return status change
  src/service/alerts/destinations.rs
Labels: ☢️ Bug

#1924 feat: delete API should return 200, 404 or 500
  src/common/utils/notification.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/dashboards/folders.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/functions/mod.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  src/service/dashboards/folders.rs
  src/service/dashboards/mod.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/mod.rs
  src/service/db/alerts/templates.rs
  src/service/functions.rs
  src/service/triggers.rs
Labels: ✏️ Feature

#1926 fix: wal locking
  Cargo.lock
  Cargo.toml
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#1928 test: optimize unit tests
  .cargo/config.toml
  src/service/search/mod.rs
Labels: 🧹 Updates

#1923 docs: Explanation
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/LinuxConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
Labels: 📒 Documentation

#1930 fix: alert deletion & notification panic
  .cargo/config.toml
  src/common/meta/alert.rs
  src/common/utils/notification.rs
  src/main.rs
  src/service/alert_manager.rs
  src/service/alerts/mod.rs
  src/service/db/alerts/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  src/service/triggers.rs
Labels: ☢️ Bug

#1938 fix: change instrumenter to per language
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ☢️ Bug

#1939 docs: defaultPrivacyLevel added for RUM
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
Labels: ✏️ Feature, 📒 Documentation

#1941 fix: date format
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug

#1945 fix: date format
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug

#1942 fix: ip logger show
  src/main.rs
Labels: ☢️ Bug

#1956 fix: dashboard make title mandatory
  src/service/db/dashboards/mod.rs
Labels: ☢️ Bug

#1625 feat: implement bloom filter
  Cargo.lock
  Cargo.toml
  deploy/build/buildspec-test.yml
  src/common/infra/cache/file_data/disk.rs
  src/common/infra/cache/file_data/memory.rs
  src/common/infra/config.rs
  src/common/meta/sql.rs
  src/common/utils/auth.rs
  src/handler/grpc/request/search.rs
  src/handler/http/request/search/mod.rs
  src/job/files/disk.rs
  src/job/files/memory.rs
  src/job/mod.rs
  src/service/alert_manager.rs
  src/service/compact/merge.rs
  src/service/dashboards/folders.rs
  src/service/db/enrichment_table.rs
  src/service/db/file_list/mod.rs
  src/service/ingestion/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/prom.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
  src/service/usage/stats.rs
Labels: 🧹 Updates, ✏️ Feature

#1958 docs: add RUM
  README.md
Labels: ✏️ Feature, 📒 Documentation

#1959 fix: steam not updated when stream type is changed in add dashboard panel
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug

#1960 fix: query cache error in concurrency
  src/common/infra/cache/file_data/disk.rs
  src/common/infra/cache/file_data/memory.rs
  src/common/infra/db/sqlite.rs
Labels: ☢️ Bug

#1961 fix: web/deps add resolved and integrity to package-lock
  web/package-lock.json
Labels: ☢️ Bug, ✏️ Feature

#1963 fix: query merge error in some case
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#1966 fix: metrics ingest calculate
  src/common/infra/config.rs
  src/service/metrics/json.rs
  src/service/metrics/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/search/datafusion/mod.rs
Labels: ☢️ Bug

#1971 fix: fix absolute time range change issue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#1962 fix: Traces UI enhancements
  web/src/composables/useTraces.ts
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/TraceBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceTree.vue
  web/src/utils/traces/convertTraceData.ts
Labels: ☢️ Bug

#1978 fix: Traces UI Issues
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/TraceBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceHeader.vue
  web/src/plugins/traces/TraceTree.vue
Labels: ☢️ Bug

#1982 fix: migration with file_list_deleted
  src/common/infra/db/mysql.rs
  src/common/infra/db/postgres.rs
  src/common/migration/file_list.rs
  src/common/migration/meta.rs
  src/main.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/mod.rs
Labels: ☢️ Bug

#1983 fix: trace timeline in trace details
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceHeader.vue
Labels: ☢️ Bug

#1987 fix: Logs & Traces page time format
  web/package-lock.json
  web/package.json
  web/src/components/DateTime.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/utils/logs/convertLogData.ts
  web/src/utils/traces/convertTraceData.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#1986 fix: judge body is empty
  src/service/alerts/templates.rs
Labels: ☢️ Bug

#1985 fix: don't need to send broadcast with mysql
  README.md
  src/common/infra/cluster.rs
  src/common/infra/db/mysql.rs
  src/common/infra/file_list/mysql.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
Labels: ☢️ Bug, 📒 Documentation

#1995 fix: Updated new url for fetching traces
  web/src/composables/useTraces.ts
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/services/search.ts
Labels: ☢️ Bug, 🧹 Updates

#1990 fix: change latest traces data api to get
  src/handler/http/request/traces/mod.rs
  src/service/alerts/templates.rs
Labels: ☢️ Bug, 🧹 Updates

#1996 fix: parse file_list when got an invalid json
  src/service/db/file_list/local.rs
  src/service/db/file_list/remote.rs
Labels: ☢️ Bug

#1999 fix: add _timestamp for the traces latest data query
  src/handler/http/request/traces/mod.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2002 fix: wal search on windows
  src/common/utils/file.rs
  src/handler/grpc/request/metrics/querier.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#2006 fix: the metric name format is incorrect. (#2003)
  src/service/metrics/otlp_grpc.rs
Labels: ☢️ Bug

#2007 feat: Issue 970 saved views
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/locales/languages/es.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/services/saved_views.ts
  web/src/stores/index.ts
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#2010 fix: traces pagination issues
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchResult.vue
Labels: ☢️ Bug

#2011 feat:append data to enrichment tables
  src/handler/http/request/enrichment_table/mod.rs
  src/service/enrichment_table/mod.rs
  web/src/components/functions/AddEnrichmentTable.vue
  web/src/locales/languages/en.json
  web/src/services/jstransform.ts
Labels: ✏️ Feature

#2014 fix: histogram type processing
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
Labels: ☢️ Bug

#1756 feat: implement ability to save search views
  src/common/meta/mod.rs
  src/common/meta/saved_view.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/saved_view.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/db/mod.rs
  src/service/db/saved_view.rs
  tests/saveviews.json
Labels: ✏️ Feature

#2016 fix: safari issue on ingestion page
  web/src/views/Ingestion.vue
Labels: ☢️ Bug

#2012 feat: add table format for search response
  src/common/meta/search.rs
  src/common/utils/notification.rs
  src/handler/grpc/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/saved_view.rs
  src/handler/http/request/traces/mod.rs
  src/service/alerts/mod.rs
  src/service/metrics/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#2023 fix: saved view issues
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2027 fix: otlp http json metrics ingestion fixes
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
Labels: ☢️ Bug

#2031 fix: Update saved views
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates

#2032 fix: Update saved views
  web/src/plugins/logs/SearchBar.vue
Labels: 🧹 Updates

#2033 fix: typo dialog box
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2035 fix: blank space in view name
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2029 fix: single_distinct_aggregation_to_group_by
  Cargo.lock
  Cargo.toml
  src/common/infra/storage/local.rs
  src/common/infra/storage/mod.rs
  src/common/infra/storage/remote.rs
  src/common/utils/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/tmpfs.rs
Labels: ☢️ Bug

#2038 docs: change license
  LICENSE
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: 📒 Documentation

#2045 fix: Traces run query button was not getting triggered
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
Labels: ☢️ Bug

#2041 fix: run the mmdb downloader everywhere
  src/job/mmdb_downloader.rs
Labels: ☢️ Bug

#2048 feat: Update ApiKeys.vue
  web/src/enterprise/components/settings/ApiKeys.vue
Labels: 🧹 Updates, ✏️ Feature

#2052 fix: user and locations details on session viewer page
  web/src/composables/useSessionReplay.ts
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#2051 fix: otlp http changes
  src/common/utils/flatten.rs
  src/service/ingestion/mod.rs
  src/service/ingestion/otlp_json.rs
  src/service/logs/otlp_http.rs
  src/service/metrics/otlp_http.rs
Labels: ☢️ Bug

#2053 feat: logger time format setup
  src/common/infra/config.rs
  src/handler/mod.rs
  src/main.rs
Labels: ✏️ Feature

#2054 fix: loader issue
  web/src/locales/languages/en.json
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2058 fix: Api access control
  web/package-lock.json
  web/package.json
  web/src/aws-exports.ts
  web/src/enterprise/components/settings/AddUserKey.vue
  web/src/locales/languages/en.json
  web/src/main.ts
Labels: Invalid PR Title

#2060 fix: validation
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2063 feat: support some new functions
  src/handler/mod.rs
  src/main.rs
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug, ✏️ Feature

#2070 fix: package version change
  web/package-lock.json
  web/package.json
Labels: ☢️ Bug

#2073 fix: convert timestamp value on x-axis as timeseries
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2077 fix: saved view applied
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2081 fix: vector enrichment commit id
  Cargo.lock
  Cargo.toml
Labels: ☢️ Bug

#2083 ci: add missing integrity to package lock
  web/package-lock.json
Labels: ☢️ Bug, ✏️ Feature

#2082 fix: rum browser sdk sends keys with updated o2 prefix
  src/common/meta/middleware_data.rs
  src/handler/http/auth/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#2095 fix: removed newline
  web/src/components/ingestion/recommended/LinuxConfig.vue
Labels: ☢️ Bug, 🧹 Updates

#2096 fix: timezone issue
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/de.json
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/locales/languages/hi.json
  web/src/locales/languages/it.json
  web/src/locales/languages/ja.json
  web/src/locales/languages/ko.json
  web/src/locales/languages/nl.json
  web/src/locales/languages/pt.json
  web/src/locales/languages/tr.json
  web/src/locales/languages/zh.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/stores/index.ts
Labels: ☢️ Bug

#2098 fix: savedview openapi
  src/common/meta/saved_view.rs
  src/handler/http/request/search/saved_view.rs
  src/handler/http/router/openapi.rs
  src/service/db/saved_view.rs
Labels: ☢️ Bug
