Repository openobserve/openobserve, pull requests merged in 2023-12, with the labels that each got.

#2114 feat:use arrow ipc streams for data in wal
  proto/cluster/metrics.proto
  src/common/infra/cache/tmpfs.rs
  src/common/infra/config.rs
  src/common/infra/wal.rs
  src/common/meta/ingestion.rs
  src/common/meta/stream.rs
  src/handler/grpc/request/metrics/querier.rs
  src/handler/http/router/mod.rs
  src/job/files/disk.rs
  src/job/files/memory.rs
  src/service/ingestion/mod.rs
  src/service/ingestion/otlp_json.rs
  src/service/logs/bulk.rs
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/wal.rs
  src/service/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/tmpfs.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#2116 fix: download mmdb files and initialize the client
  src/job/mmdb_downloader.rs
Labels: ☢️ Bug

#2110 fix: logs page editor height reduced to three lines and metrics page …
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/Index.vue
Labels: ☢️ Bug

#2123 fix: fields not getting populated with custom namecal
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#2124 fix: added support for @, -, _ characters
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, ✏️ Feature

#2125 fix: duplicate values in autocomplete logs page query editor
  web/src/composables/useSuggestions.ts
Labels: ☢️ Bug

#2126 fix: Alerts UI fixes
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/DestinationList.vue
  web/src/components/alerts/FieldsInput.vue
  web/src/components/alerts/TemplateList.vue
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#2127 fix: Duplicate name field list
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2030 feat: maximize panel in dashboard
  web/src/components/AutoRefreshInterval.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#2133 chore: arrow streams for traces
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#1994 feat: built in support for top N results
  src/common/meta/dashboards/v2/mod.rs
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/SortByBtnGrp.vue
  web/src/components/icons/AscSort.vue
  web/src/components/icons/DescSort.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#2143 feat: add bloomfilter for setting API
  src/common/meta/stream.rs
  src/service/schema.rs
Labels: ✏️ Feature

#2090 feat: specify interval for histogram aggregation function
  src/common/meta/dashboards/v2/mod.rs
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/HistogramIntervalDropDown.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
Labels: ✏️ Feature

#2148 feat: add aggregation support for alert
  Cargo.toml
  src/common/meta/alerts/mod.rs
  src/handler/http/router/openapi.rs
  src/service/alerts/mod.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ✏️ Feature

#2145 feat: ldap integration - enterprise
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/handler/grpc/auth/mod.rs
  src/handler/http/auth/mod.rs
  src/job/mod.rs
  src/main.rs
  src/service/db/user.rs
  src/service/organization.rs
  src/service/users.rs
Labels: ✏️ Feature

#2153 feat: apply stream level bloom filter settings
  src/job/files/disk.rs
  src/job/files/memory.rs
  src/service/compact/merge.rs
  src/service/db/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/stream.rs
Labels: ✏️ Feature

#2157 fix: traces with upto
  src/common/meta/traces.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#1902 feat: gauge chart in dashboard for sql and promql queries
  src/common/meta/dashboards/v2/mod.rs
  web/src/assets/images/dashboard/charts/Gauge.png
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/calculateGridForSubPlot.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#2159 fix: dashboard query editor scroll and query error message issue
  web/src/components/dashboards/QueryEditor.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
Labels: ☢️ Bug

#2160 feat: remove requirement of powershell6+
  web/src/components/ingestion/recommended/WindowsConfig.vue
Labels: 🧹 Updates, ✏️ Feature

#2155 fix: added aggregation support in alerts and fixed UI issues
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/DestinationList.vue
  web/src/components/alerts/FieldsInput.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature

#2163 fix: #2147
  src/handler/http/request/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#2167 feat: timeseries hover across all charts
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/logs/convertLogData.ts
  web/src/utils/traces/convertTraceData.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#2172 fix: compaction issues
  src/common/infra/file_list/dynamo.rs
  src/common/infra/file_list/mod.rs
  src/common/infra/file_list/mysql.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/infra/storage/mod.rs
  src/handler/grpc/request/metrics/querier.rs
  src/job/compact.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/search/grpc/wal.rs
  src/service/usage/stats.rs
Labels: ☢️ Bug

#2173 feat: redirect user to ingestion page if ingestion not started
  web/src/composables/shared/router.ts
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/main.ts
  web/src/utils/zincutils.ts
  web/src/views/HomeView.vue
Labels: ✏️ Feature

#2146 fix: billing changes
  src/common/meta/usage.rs
  src/service/usage/mod.rs
  web/src/enterprise/components/billings/plans.vue
  web/src/enterprise/components/login/Login.vue
  web/src/enterprise/components/organizations/Organization.vue
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#2182 ci: add license check
  .github/workflows/cargo-deny.yml
  .github/workflows/pr-title-checker.yml
  .github/workflows/release-drafter.yml
  deny.toml
Labels: ✏️ Feature

#2118 feat: add openobserve specific config to syslog-ng
  web/src/components/ingestion/logs/SyslogNg.vue
Labels: ✏️ Feature

#2183 ci: fix license checker
  .github/workflows/cargo-deny.yml
Labels: ☢️ Bug

#2184 fix: add empty name check
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/functions/mod.rs
  src/handler/http/request/kv/mod.rs
  src/handler/http/request/search/saved_view.rs
  src/handler/http/request/users/mod.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  src/service/dashboards/folders.rs
  src/service/db/dashboards/mod.rs
  src/service/functions.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#2189 fix: Alerts UI Issues
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
Labels: ☢️ Bug

#2191 fix: add keyword search for values API
  src/handler/http/request/search/mod.rs
  src/service/distinct_values.rs
Labels: ☢️ Bug, ✏️ Feature

#2194 fix: add psql for debugging
  deploy/build/Dockerfile.aarch64
  deploy/build/Dockerfile.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
Labels: ☢️ Bug, ✏️ Feature

#2195 fix: improve memory_circuit_breaker, add session_id to log
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2197 fix: added new environment variable to configure organization identif…
  web/src/aws-exports.ts
  web/src/main.ts
Labels: ☢️ Bug, ✏️ Feature

#2202 fix: check_memory_circuit_breaker bug fix
  src/service/search/grpc/mod.rs
Labels: ☢️ Bug

#2192 feat: dashboard fields drag & reorder in add/edit panel
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#2207 fix: #2201
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/templates.rs
Labels: ☢️ Bug

#2212 fix: gauge chart issue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#2213 fix: zoom issue for non timeseries charts
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#2217 fix: monaco editor value rendering issue after navigation
  web/src/components/QueryEditor.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2219 fix: dashboard drag and reorder issue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#2222 chore: update datafusion to 34
  Cargo.lock
  Cargo.toml
  src/cli/basic/cli.rs
  src/cli/basic/mod.rs
  src/cli/data/cli.rs
  src/cli/data/export.rs
  src/cli/data/import.rs
  src/cli/data/mod.rs
  src/cli/mod.rs
  src/common/meta/http.rs
  src/common/meta/search.rs
  src/common/meta/stream.rs
  src/common/utils/hasher.rs
  src/handler/grpc/mod.rs
  src/handler/http/request/prom/mod.rs
  src/main.rs
  src/service/file_list.rs
  src/service/functions.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/syslog.rs
  src/service/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/stream.rs
  src/service/usage/ingestion_service.rs
Labels: 🧹 Updates

#2225 feat: save function ui change logs page
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/stores/index.ts
Labels: ✏️ Feature

#2115 feat: dynamic filters
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/QueryInspector.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/variables/variablesUtils.ts
  web/src/utils/query/promQLUtils.ts
  web/src/utils/query/sqlUtils.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#2226 fix: Gauge chart error message issue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#2216 fix: Updated traces field list UI
  web/src/components/alerts/AddTemplate.vue
  web/src/components/common/AppTabs.vue
  web/src/composables/useTraces.ts
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/fields-sidebar/AdvancedValuesFilter.vue
  web/src/plugins/traces/fields-sidebar/BasicValuesFilter.vue
  web/src/services/stream.ts
Labels: ☢️ Bug, 🧹 Updates

#2232 fix: UI minor changes
  web/src/components/MenuLink.vue
  web/src/components/logstream/explore/StreamDataTable.vue
  web/src/components/logstream/schema.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2228 fix: parsing of o2tags + ootags
  src/common/meta/middleware_data.rs
Labels: ☢️ Bug

#2230 feat: support structured logging
  Cargo.lock
  Cargo.toml
  src/common/infra/config.rs
  src/main.rs
Labels: ✏️ Feature

#2241 fix: Fixed some small issues
  src/common/infra/config.rs
  src/common/meta/alerts/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/tcp_udp/mod.rs
Labels: ☢️ Bug

#2244 feat: impl alert row template
  src/common/infra/config.rs
  src/main.rs
  src/service/alerts/mod.rs
Labels: ✏️ Feature

#2245 fix: added user to rum data
  web/src/enterprise/components/login/Login.vue
Labels: ☢️ Bug, ✏️ Feature

#2247 fix: add/edit panel zoom, tooltip highlight and histogram field should use ASC as a default in sort by field issue
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, ✏️ Feature

#2248 fix: RUM session replay issues
  web/src/components/rum/VideoPlayer.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#2251 docs: grpc on router is now available
  web/src/components/ingestion/logs/OtelConfig.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
Labels: 📒 Documentation

#2253 fix: dashboard drag reorder issues
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#2246 fix: added user to rum data
  web/src/enterprise/components/login/Login.vue
Labels: ☢️ Bug, ✏️ Feature

#2249 fix: RUM session replay issues
  web/src/components/rum/VideoPlayer.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#2255 feat: share logs page url
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ✏️ Feature

#2237 fix: absolute date time issue for dashboard
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#2257 feat: row template element added
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#2211 feat: masked email id, and passcode from ingestion and user page
  web/src/components/CopyContent.vue
  web/src/components/ingestion/logs/Curl.vue
  web/src/components/ingestion/logs/FileBeat.vue
  web/src/components/ingestion/logs/FluentBit.vue
  web/src/components/ingestion/logs/Fluentd.vue
  web/src/components/ingestion/logs/GcpPubSub.vue
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/logs/SyslogNg.vue
  web/src/components/ingestion/logs/Vector.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/LinuxConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/components/users/User.vue
  web/src/enterprise/components/users/User.vue
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#2259 fix: disable sql mode histogram not rendered in full width
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#2264 docs: otlp grpc support 2
  web/src/components/ingestion/traces/OpenTelemetry.vue
Labels: 📒 Documentation

#2265 docs: add header for grpc
  web/src/components/ingestion/traces/OpenTelemetry.vue
Labels: ✏️ Feature, 📒 Documentation

#2266 fix: maximize panel pass same time whether relative or absolute
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#2267 feat: share dashboard functionality
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#2273 feat: control redirection of a user to ingestions
  src/common/infra/config.rs
  src/handler/http/request/status/mod.rs
Labels: ✏️ Feature

#2272 fix: environment variable added for route guard
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature

#2275 feat: Expandable Spans in Trace details
  web/src/composables/useTraces.ts
  web/src/locales/languages/en.json
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/SpanDetails.vue
  web/src/plugins/traces/SpanRenderer.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceHeader.vue
  web/src/plugins/traces/TraceTree.vue
Labels: ☢️ Bug, ✏️ Feature

#2277 feat: dex integration
  .gitignore
  Cargo.lock
  Cargo.toml
  src/cli/basic/cli.rs
  src/common/infra/errors.rs
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/common/utils/jwt.rs
  src/common/utils/mod.rs
  src/handler/grpc/auth/mod.rs
  src/handler/http/auth/mod.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/organization/mod.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/service/db/user.rs
  src/service/organization.rs
  src/service/users.rs
  web/package-lock.json
  web/package.json
  web/src/aws-exports.ts
  web/src/enterprise/components/login/Login.vue
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/router/index.ts
  web/src/services/auth.ts
  web/src/services/http.ts
  web/src/services/organizations.ts
  web/src/stores/index.ts
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#2279 chore: Bump buildx to v0.12.0
  deploy/build/buildspec-arm.yml
  deploy/build/buildspec.yml
Labels: 🤖 Dependencies

#2281 fix: Alerts and Traces UI issues
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/FieldsInput.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/alerts/VariablesInput.vue
  web/src/composables/shared/router.ts
  web/src/layouts/MainLayout.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#2285 fix: metric stream drop-down for dark mode
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
Labels: ☢️ Bug

#2287 fix: logs page ui and login issue for cloud
  web/src/enterprise/components/login/Login.vue
  web/src/enterprise/composables/router.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/services/http.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#2283 fix: parse ldap dn changes
  src/common/utils/jwt.rs
Labels: ☢️ Bug

#2286 fix: reverse order issue for h bar
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2291 fix: logs chart y-axis overlapping issue in logs page
  web/src/utils/logs/convertLogData.ts
Labels: ☢️ Bug

#2290 fix: replaced function icon
  web/src/assets/images/common/function.svg
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/mixins/mainLayout.mixin.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2278 chore: Bump Node.js to v18.19.0
  deploy/build/Dockerfile
  deploy/build/Dockerfile.aarch64
  deploy/build/Dockerfile.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
Labels: 🤖 Dependencies

#2280 refactor: Complete refactoring of the README file
  README.md
Labels: 🧹 Updates, 📒 Documentation

#2294 fix: user api checks
  src/cli/basic/cli.rs
  src/common/utils/auth.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/users/mod.rs
  src/job/mod.rs
  src/service/db/user.rs
  src/service/organization.rs
  src/service/users.rs
Labels: ☢️ Bug

#2297 fix: Typo in recommended ingestion page
  web/src/components/ingestion/Recommended.vue
Labels: ☢️ Bug

#2301 ci: update rust version
  deploy/build/Dockerfile
  deploy/build/Dockerfile.sccache.aarch64
  deploy/build/Dockerfile.sccache.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/buildspec-test.yml
  rust-toolchain.toml
  src/common/infra/wal.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
Labels: 🧹 Updates

#2299 chore: Bump Debian to 12 (Bookworm)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  deploy/build/Dockerfile
  deploy/build/Dockerfile.aarch64
  deploy/build/Dockerfile.amd64
  deploy/build/Dockerfile.sccache.aarch64
  deploy/build/Dockerfile.sccache.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/buildspec-arm.yml
  deploy/build/buildspec.yml
Labels: 🤖 Dependencies

#2302 fix: Fixed the problem that the front-end menu "Function" has an unnecessary string "1"
  web/src/mixins/mainLayout.mixin.ts
Labels: ☢️ Bug

#2304 docs: Add new screenshots
  README.md
  screenshots/alert_realtime.jpg
  screenshots/alert_scheduled.jpg
  screenshots/alerts.png
  screenshots/create-panel.png
  screenshots/dashboard.png
  screenshots/dashboard2.png
  screenshots/error-tracking.png
  screenshots/ingestion.webp
  screenshots/ingestion1.png
  screenshots/ingestion2.png
  screenshots/logs.png
  screenshots/logs.webp
  screenshots/map.png
  screenshots/performance.png
  screenshots/session-replay.png
  screenshots/streams.png
  screenshots/traces-overall.png
  screenshots/traces.png
  screenshots/traces.webp
  screenshots/zo_home.png
  screenshots/zo_streams.png
Labels: ✏️ Feature, 📒 Documentation

#2303 feat: add API for alert preview
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/alerts/mod.rs
Labels: ✏️ Feature

#2306 fix: vrl function for query execution
  src/handler/http/request/search/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2308 feat: maxmind asn db as vrl enrichment table
  src/common/infra/config.rs
  src/common/utils/functions.rs
  src/job/mmdb_downloader.rs
  src/service/enrichment_table/geoip.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#2312 fix: test ids for e2e test cases for dashboard folders
  web/src/components/dashboards/AddFolder.vue
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/views/Dashboards/Dashboards.vue
Labels: 🧹 Updates, ✏️ Feature

#2309 fix: add human friendly geoip URL
  src/common/infra/config.rs
  web/src/locales/languages/en.json
  web/src/views/HomeView.vue
Labels: ☢️ Bug, ✏️ Feature

#2314 fix: logs chart decimal point issue in yaxis and show grid lines
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/logs/convertLogData.ts
Labels: ☢️ Bug

#2315 fix: vrl functions on query
  src/service/search/mod.rs
Labels: ☢️ Bug

#2316 feat: dashboard panel description
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
Labels: ✏️ Feature

#2317 feat: delete popup for panel
  web/src/components/dashboards/PanelContainer.vue
Labels: ✏️ Feature

#2318 fix: dashboard e2e testcases
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug, 🧹 Updates

#2319 fix: dashboard test ids for panel popup
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug, 🧹 Updates

#2320 fix: organisation check for jwt auth flow
  src/handler/http/auth/token.rs
Labels: ☢️ Bug

#2250 feat: integrate API integration testing using pytest
  .github/workflows/api-testing.yml
  tests/api-testing/.gitignore
  tests/api-testing/.python-version
  tests/api-testing/Makefile
  tests/api-testing/README.md
  tests/api-testing/ci/Dockerfile.openobserve
  tests/api-testing/ci/statefulset.yaml
  tests/api-testing/pyproject.toml
  tests/api-testing/requirements-dev.lock
  tests/api-testing/requirements.lock
  tests/api-testing/src/main.py
  tests/api-testing/tests/conftest.py
  tests/api-testing/tests/test_alerts.py
  tests/api-testing/tests/test_folders.py
  tests/api-testing/tests/test_functions.py
  tests/api-testing/tests/test_kinesis.py
  tests/api-testing/tests/test_logs.py
  tests/api-testing/tests/test_metrics.py
  tests/api-testing/tests/test_organisations.py
  tests/api-testing/tests/test_prod.py
  tests/api-testing/tests/test_rum.py
  tests/api-testing/tests/test_users.py
Labels: 🧹 Updates, ✏️ Feature, 📒 Documentation

#2324 refactor: API Integration Tests workflow
  .github/workflows/api-testing.yml
  tests/api-testing/.python-version
  tests/api-testing/ci/Dockerfile.openobserve
  tests/api-testing/ci/statefulset.yaml
  tests/api-testing/pyproject.toml
Labels: 🧹 Updates

#2325 fix: run query button not working in metrics page
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useMetricsExplorer.ts
  web/src/plugins/metrics/Index.vue
Labels: ☢️ Bug
