Repository openobserve/openobserve, pull requests merged in 2023-10, with the labels that each got.

#1589 fix: optimize file list broadcast
  src/common/infra/cluster.rs
  src/common/infra/config.rs
  src/handler/http/request/status/mod.rs
  src/job/mod.rs
  src/service/db/file_list/local.rs
Labels: ☢️ Bug

#1590 fix: dashboard migration
  src/common/migration/dashboards.rs
Labels: ☢️ Bug

#1527 fix: logs ingestion refactor
  src/common/meta/ingestion.rs
  src/handler/grpc/request/usage.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/router/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
Labels: ☢️ Bug, 🧹 Updates

#1592 fix: change the log::info -> debug for missing vector
  src/service/logs/mod.rs
  src/service/promql/engine.rs
Labels: ☢️ Bug

#1591 feat: use the node which has the latest file_list
  src/common/infra/cluster.rs
  src/handler/grpc/request/file_list.rs
  src/handler/grpc/request/mod.rs
  src/job/mod.rs
  src/main.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/db/file_list/broadcast.rs
  src/service/file_list.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/usage/ingestion_service.rs
Labels: 🧹 Updates, ✏️ Feature

#1594 feat: folders for dashboards ui
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/AddFolder.vue
  web/src/components/dashboards/ExportDashboard.vue
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/components/dashboards/PanelHeader.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/services/dashboards.ts
  web/src/stores/index.ts
  web/src/utils/commons.ts
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/ImportDashboard.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#1593 fix: change ZO_GRPC_ORG_HEADER_KEY to organization
  src/common/infra/config.rs
Labels: ☢️ Bug

#1596 fix: stream stats with usage report
  src/service/stream.rs
Labels: ☢️ Bug

#1597 fix: logs stream with daily partition
  src/service/logs/bulk.rs
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
Labels: ☢️ Bug

#1598 fix: timeseries issue for line charts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1583 fix: calendar datatime reset issue fix
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#1572 fix: function issue
  web/src/components/functions/FunctionList.vue
Labels: ☢️ Bug

#1604 fix: folders not refreshing occasionally on org change
  web/src/layouts/MainLayout.vue
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug

#1569 fix: Issue 1550 monaco editor scroll fast
  web/src/assets/images/common/query-editor.png
  web/src/assets/images/common/vrl-function.png
  web/src/components/QueryEditor.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/Index.vue
Labels: ☢️ Bug

#1571 fix: where keyword in sql mode to avoid syntax error
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#1605 fix: Issue 357 rum api
  web/src/components/CopyContent.vue
  web/src/components/ingestion/logs/Curl.vue
  web/src/components/ingestion/logs/FileBeat.vue
  web/src/components/ingestion/logs/FluentBit.vue
  web/src/components/ingestion/logs/Fluentd.vue
  web/src/components/ingestion/logs/GcpPubSub.vue
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/logs/SyslogNg.vue
  web/src/components/ingestion/logs/Vector.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/rum/Index.vue
  web/src/components/ingestion/rum/Web.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/components/settings/General.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/router.ts
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/composables/useLogs.ts
  web/src/enterprise/components/settings/AddUserKey.vue
  web/src/enterprise/components/settings/ApiKeys.vue
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/router/index.ts
  web/src/router/routes.ts
  web/src/services/api_keys.ts
  web/src/stores/index.ts
  web/src/utils/zincutils.ts
  web/src/views/Ingestion.vue
Labels: ☢️ Bug

#1607 fix: dashboard tooltips for single item only
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1613 Fix/rum dd sentry integration
  web/src/composables/activityTracking2.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1614 feat: added icons for functions and fields
  web/src/composables/useSuggestions.ts
Labels: ✏️ Feature

#1615 fix: stream rename & logs partitioning
  src/common/infra/config.rs
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/mod.rs
  src/service/schema.rs
Labels: ☢️ Bug

#1619 fix: move file to storage panic when parse thread id
  src/common/infra/wal.rs
Labels: ☢️ Bug

#1621 feat: add schedule for cluster node
  src/common/infra/cluster.rs
  src/service/db/file_list/broadcast.rs
Labels: ✏️ Feature

#1624 feat: read/write QPS metrics for S3 stroage
  Cargo.lock
  src/common/infra/metrics.rs
  src/common/infra/storage/local.rs
  src/common/infra/storage/remote.rs
  src/job/metrics.rs
Labels: ✏️ Feature

#1618 fix:stats calculation
  src/job/stats.rs
  src/service/usage/ingestion_service.rs
Labels: ☢️ Bug

#1630 fix: #1510
  src/common/infra/config.rs
  src/common/infra/storage/remote.rs
Labels: ☢️ Bug

#1632 fix: read cpu & memory limits from cgroup
  src/common/utils/cgroup.rs
Labels: ☢️ Bug

#1635 fix: generalize view dashboard page to utilize on other part of the application
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#1638 fix: filter does not allow integer values to be saved and dashboard error message
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#1640 fix: dashboard sentry issues
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/utils/commons.ts
  web/src/views/Dashboards/ImportDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#1646 fix: get cgroup limit
  .gitignore
  src/common/utils/cgroup.rs
Labels: ☢️ Bug

#1633 feat: dashboard map panel
  src/common/meta/dashboards/v2/mod.rs
  web/package-lock.json
  web/package.json
  web/src/assets/images/dashboard/charts/geomap.png
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/addPanel/PanelSidebar.vue
  web/src/components/dashboards/addPanel/QueryTypeSelector.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/panels/GeoMapRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertMapData.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/convertTableData.ts
  web/src/utils/dashboard/leaflet-echarts/LeafletCoordSys.js
  web/src/utils/dashboard/leaflet-echarts/LeafletModel.js
  web/src/utils/dashboard/leaflet-echarts/LeafletView.js
  web/src/utils/dashboard/leaflet-echarts/export.d.ts
  web/src/utils/dashboard/leaflet-echarts/export.js
  web/src/utils/dashboard/leaflet-echarts/helper.js
  web/src/utils/dashboard/leaflet-echarts/index.d.ts
  web/src/utils/dashboard/leaflet-echarts/index.js
  web/src/utils/dashboard/leaflet-echarts/lmap.js
  web/src/utils/dashboard/leaflet-echarts/types.d.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#1653 refactor: small memory-bound optimizations in schema
  src/service/schema.rs
Labels: 🧹 Updates

#1654 fix: fixes the create-folder docs in #1649
  src/handler/http/request/dashboards/folders.rs
  src/service/db/functions.rs
  src/service/functions.rs
Labels: ☢️ Bug, ✏️ Feature, 📒 Documentation

#1656 fix: function name with invalid chars issue
  src/service/search/sql.rs
Labels: ☢️ Bug

#1661 feat: improve parquet writing
  .github/workflows/release.yml
  src/common/infra/cache/file_data/memory.rs
  src/common/infra/config.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#1623 fix: "Search around" button remains disabled
  web/src/enterprise/components/users/User.vue
  web/src/plugins/logs/DetailTable.vue
Labels: ☢️ Bug

#1517 feat: #357 rum api
  web/src/components/CopyContent.vue
  web/src/components/ingestion/logs/Curl.vue
  web/src/components/ingestion/logs/FileBeat.vue
  web/src/components/ingestion/logs/FluentBit.vue
  web/src/components/ingestion/logs/Fluentd.vue
  web/src/components/ingestion/logs/GcpPubSub.vue
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/logs/SyslogNg.vue
  web/src/components/ingestion/logs/Vector.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/rum/Index.vue
  web/src/components/ingestion/rum/Web.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/components/settings/General.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/router.ts
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/composables/useLogs.ts
  web/src/enterprise/components/settings/AddUserKey.vue
  web/src/enterprise/components/settings/ApiKeys.vue
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/router/index.ts
  web/src/router/routes.ts
  web/src/services/api_keys.ts
  web/src/stores/index.ts
  web/src/utils/zincutils.ts
  web/src/views/Ingestion.vue
Labels: ✏️ Feature

#1664 fix: remove plotly and migrate dependent charts to echarts
  web/package-lock.json
  web/package.json
  web/src/components/MetricLineChart.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelHeader.vue
  web/src/components/dashboards/addPanel/ChartRender.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/logBarChart.vue
  web/src/composables/useMetricsExplorer.ts
  web/src/enterprise/components/billings/usage.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/TraceChart.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/test/unit/plugins/logs/SearchResult.spec.ts
  web/src/utils/billing/convertBillingData.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/logs/convertLogData.ts
  web/src/utils/traces/convertTraceData.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/vite.config.ts
Labels: ☢️ Bug, 🧹 Updates

#1670 fix: #1647
  src/service/search/mod.rs
Labels: ☢️ Bug

#1671 feat: added vrl functions to otlp endpoints & syslogs
  src/common/meta/functions.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/search/datafusion/exec.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ✏️ Feature

#1673 fix: reset stream stats can't work
  src/common/infra/db/mod.rs
  src/common/infra/db/sqlite.rs
  src/common/infra/file_list/sqlite.rs
  src/main.rs
Labels: ☢️ Bug

#1674 feat: support delete fields
  src/common/meta/stream.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/search/grpc/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
Labels: ✏️ Feature

#1675 fix: heatmap timeseries issue, tooltip unit converting
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1684 fix: reordering to put related charts together in add panel page
  web/src/components/dashboards/addPanel/ChartSelection.vue
Labels: ☢️ Bug, ✏️ Feature

#1683 fix: transparent image
  web/src/assets/images/common/query-editor.png
  web/src/assets/images/common/vrl-function.png
  web/src/components/QueryEditor.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#1686 fix: query WAL when the wal file is writing
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#1641 fix: improve data ingestion
  src/common/infra/cluster.rs
  src/common/infra/config.rs
  src/common/meta/ingestion.rs
  src/handler/http/request/logs/ingest.rs
  src/job/files/disk.rs
  src/main.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/router/mod.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug, 🧹 Updates

#1608 feat: integrate organization level settings
  src/common/infra/config.rs
  src/common/meta/organization.rs
  src/handler/http/request/organization/mod.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/organization.rs
Labels: ✏️ Feature

#1691 fix: tooltip scroll issue for sql charts
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#1690 fix: improve stream stats for local mode
  src/common/infra/cache/stats.rs
  src/common/infra/db/etcd.rs
  src/common/infra/file_list/sqlite.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/db/file_list/mod.rs
  src/service/db/organization.rs
Labels: ☢️ Bug, 🧹 Updates

#1698 fix: #1696
  src/service/compact/retention.rs
Labels: ☢️ Bug

#1697 fix: dashboard metric text, tooltip dark mode, table loading indicators
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#1669 fix: 473 the timestamp field get rendered using browser timezone
  web/package-lock.json
  web/package.json
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/stores/index.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/logs/convertLogData.ts
  web/src/utils/traces/convertTraceData.ts
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#1713 feat: refactor actix-http responses
  src/common/meta/http.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/handler/http/request/kv/mod.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/rum/ingest.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/saved_view.rs
Labels: 🧹 Updates, ✏️ Feature

#1715 fix: dashboard chart default horizontal zoom enabled
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#1665 feat: rate interval variables for promql in dashboard
  web/src/components/settings/General.vue
  web/src/components/settings/index.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/layouts/MainLayout.vue
  web/src/services/organizations.ts
  web/src/stores/index.ts
Labels: ✏️ Feature

#1717 fix: data partitioning for logs using otlp
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
Labels: ☢️ Bug

#1718 fix: use a const to represent the org-setting-key
  src/handler/http/request/organization/settings.rs
  src/service/db/organization.rs
Labels: ☢️ Bug

#1719 feat: delete unused label
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
  web/src/services/stream.ts
Labels: 🧹 Updates, ✏️ Feature

#1721 fix: Update schema.vue
  web/src/components/logstream/schema.vue
Labels: 🧹 Updates

#1737 fix: removed duplicate key
  web/src/views/Dashboards/ViewDashboard.vue
Labels: 🧹 Updates

#1711 feat: improve files deletion
  Cargo.lock
  Cargo.toml
  src/common/infra/config.rs
  src/common/infra/db/mod.rs
  src/common/infra/db/sqlite.rs
  src/common/infra/file_list/dynamo.rs
  src/common/infra/file_list/mod.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/meta/http.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/handler/http/request/kv/mod.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/rum/ingest.rs
  src/job/compact.rs
  src/job/mmdb_downloader.rs
  src/job/mod.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/db/compact/organization.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/multi.rs
Labels: 🧹 Updates, ✏️ Feature

#1727 docs: Update 1-bug-report.yaml
  .github/ISSUE_TEMPLATE/1-bug-report.yaml
Labels: ☢️ Bug, 🧹 Updates, 📒 Documentation

#1738 feat: add new configure for control query queue
  src/common/infra/config.rs
  src/common/infra/dist_lock.rs
  src/handler/http/request/search/mod.rs
Labels: ✏️ Feature

#1741 fix: Left Menu Navigation Bar Functionality
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/src/views/RUM/ErrorViewer.vue
Labels: ☢️ Bug

#1731 fix: refactor the setting of default scrape-interval
  src/handler/http/request/organization/settings.rs
  src/job/mmdb_downloader.rs
  src/service/db/organization.rs
Labels: ☢️ Bug, 🧹 Updates

#1743 fix: trace histogram timezone issue
  web/src/components/QueryEditor.vue
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
Labels: ☢️ Bug

#1745 fix: dark mode css and background color fix
  web/src/components/AppTable.vue
  web/src/components/rum/ErrorDetail.vue
  web/src/components/rum/PlayerEventsSidebar.vue
  web/src/components/rum/errorTracking/view/ErrorEvents.vue
  web/src/components/rum/errorTracking/view/ErrorHeader.vue
  web/src/components/rum/errorTracking/view/ErrorSessionReplay.vue
  web/src/components/rum/errorTracking/view/ErrorStackTrace.vue
  web/src/components/rum/errorTracking/view/ErrorTag.vue
  web/src/components/rum/errorTracking/view/ErrorTags.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#1749 fix: query editor fix and ui changes
  web/src/components/ingestion/rum/Web.vue
  web/src/components/logstream/explore/SearchBar.vue
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug

#1751 feat: RUM Performance dashboard UI
  web/src/components/AppTable.vue
  web/src/components/common/AppTabs.vue
  web/src/components/rum/performance/ApiDashboard.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/PerformanceOverview.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/components/shared/grid/NoPanel.vue
  web/src/composables/rum/usePerformance.ts
  web/src/composables/shared/router.ts
  web/src/plugins/traces/Index.vue
  web/src/utils/rum/api.json
  web/src/utils/rum/errors.json
  web/src/utils/rum/overview.json
  web/src/utils/rum/web_vitals.json
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/RUM/AppPerformance.vue
  web/src/views/RUM/RealUserMonitoring.vue
Labels: ✏️ Feature

#1753 fix: stream name with hyphen
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/mod.rs
Labels: ☢️ Bug

#1758 fix: merge result is wrong in some cases
  src/service/schema.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#1755 fix: chart loading indicator does not go away if the value of the dependent variables is not present
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#1759 fix: updated RUM Performance section tabs in url path
  web/src/components/rum/performance/ApiDashboard.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/composables/shared/router.ts
  web/src/utils/rum/errors.json
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/RUM/AppPerformance.vue
  web/src/views/RUM/RealUserMonitoring.vue
Labels: ☢️ Bug, 🧹 Updates

#1767 fix: RUM UI issues
  web/src/components/rum/VideoPlayer.vue
  web/src/composables/shared/router.ts
  web/src/composables/useSessionReplay.ts
  web/src/layouts/MainLayout.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppPerformance.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/ErrorViewer.vue
  web/src/views/RUM/RealUserMonitoring.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#1772 fix: absolute time pass based on timezone selection in search query
  web/src/components/DateTime.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#1765 feat: Issue 1730 stream explorer
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/traces/Index.vue
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#1776 fix: Rum UI Issues
  web/src/components/rum/errorTracking/view/ErrorTags.vue
  web/src/composables/rum/usePerformance.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/views/RUM/AppPerformance.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/RealUserMonitoring.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#1773 feat: implement distinct_values
  src/common/infra/config.rs
  src/common/infra/errors.rs
  src/common/meta/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/job/files/disk.rs
  src/main.rs
  src/service/distinct_values.rs
  src/service/logs/bulk.rs
  src/service/logs/gcs_pub_sub.rs
  src/service/logs/ingest.rs
  src/service/logs/json.rs
  src/service/logs/kinesis_firehose.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/mod.rs
  src/service/search/datafusion/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ✏️ Feature

#1774 fix: on creation of new function the page should refresh to show the newly created function
  web/src/components/functions/FunctionList.vue
Labels: ☢️ Bug, ✏️ Feature

#1780 fix: add to dashboard not working from metric explorer
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/plugins/metrics/Index.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, ✏️ Feature

#1782 fix: add panel page throws some warnings when we switch from the geomap panel
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/panels/GeoMapRenderer.vue
Labels: ☢️ Bug, ✏️ Feature

#1771 feat: dashboard new units - KB, MB
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ✏️ Feature

#1775 fix: ui issue for logs page dropdown and left navigation overlap
  web/src/styles/app.scss
Labels: ☢️ Bug

#1784 feat: dashboard add panel metric steams shows metric type icon next to stream name
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ✏️ Feature

#1786 fix: added folder selection in add to dashboard from metrics page
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/plugins/metrics/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#1789 fix: resource/span attributes retain data types
  src/service/ingestion/grpc.rs
  src/service/logs/otlp_grpc.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#1781 fix: use u64 for start_time & end_time for traces
  src/common/utils/mod.rs
  src/common/utils/schema.rs
  src/job/files/disk.rs
  src/job/files/memory.rs
  src/service/ingestion/mod.rs
  src/service/metrics/json.rs
  src/service/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#1787 fix: onupdated hook added
  web/src/components/ingestion/Custom.vue
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/logs/Curl.vue
  web/src/components/ingestion/logs/FileBeat.vue
  web/src/components/ingestion/logs/FluentBit.vue
  web/src/components/ingestion/logs/Fluentd.vue
  web/src/components/ingestion/logs/GcpPubSub.vue
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/logs/SysLog.vue
  web/src/components/ingestion/logs/SyslogNg.vue
  web/src/components/ingestion/logs/Vector.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/layouts/MainLayout.vue
  web/src/styles/app.scss
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#1793 fix: add to dashboard from metric explore page
  web/src/plugins/metrics/AddToDashboard.vue
Labels: ☢️ Bug, ✏️ Feature

#1797 perf: cache schema when setting
  src/service/db/schema.rs
Labels: ☢️ Bug

#1805 fix: added onupdated hook
  web/src/components/settings/index.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#1795 fix: invalidate the local cache with rumtoken
  src/service/db/user.rs
  src/service/organization.rs
  src/service/users.rs
Labels: ☢️ Bug

#1806 fix: UI isues fix
  web/src/components/settings/index.vue
  web/src/views/RUM/RealUserMonitoring.vue
Labels: ☢️ Bug

#1807 fix: wrong timestamps in add panel page values API
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug, ✏️ Feature

#1809 fix: revert traces data type changes
  src/service/traces/mod.rs
  web/package-lock.json
Labels: ☢️ Bug

#1785 fix: added toggle play/pause video on clicking player
  web/package-lock.json
  web/src/components/AppTable.vue
  web/src/components/rum/VideoPlayer.vue
  web/src/styles/app.scss
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug, ✏️ Feature

#1810 fix: Swagger was missing a rum-model
  src/handler/http/router/openapi.rs
Labels: ☢️ Bug

#1816 fix: issue #1813
  src/job/mod.rs
  src/service/db/file_list/remote.rs
  web/package-lock.json
Labels: ☢️ Bug

#1819 fix: distinct_values use search api
  src/common/utils/http.rs
  src/common/utils/stream.rs
Labels: ☢️ Bug
