Repository openobserve/openobserve, pull requests merged in 2024-11, with the labels that each got.

#4964 ci: add docker build for Pi
  deploy/build/buildspec-tag-arm64-pi.yml
Labels: ✏️ Feature

#4970 feat: fixing logstash url
  web/src/components/ingestion/logs/LogstashDatasource.vue
Labels: ☢️ Bug, ✏️ Feature

#4978 fix: capital stream can't search
  src/service/search/cluster/flight.rs
Labels: ☢️ Bug

#4925 test: dashboard table transpose
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboard-transpose.spec.js
  web/src/components/dashboards/settings/GeneralSettings.vue
Labels: 🧹 Updates

#4976 fix: pipeline rbac fixes
  src/common/infra/ofga.rs
  src/common/utils/auth.rs
  src/handler/http/request/pipeline.rs
  src/service/pipeline/mod.rs
  web/src/components/iam/roles/EditRole.vue
Labels: ☢️ Bug

#4989 chore: cherry-pick commits related to usage reporting
  src/config/src/config.rs
  src/job/stats.rs
  src/service/usage/mod.rs
  src/service/usage/stats.rs
Labels: Invalid PR Title, 🧹 Updates

#4883 fix: fixed unit test cases
  web/package-lock.json
  web/package.json
  web/src/test/__mocks__/canvas.ts
  web/src/test/unit/components/alerts/__snapshots__/AlertList.spec.ts.snap
  web/src/test/unit/components/logstream/Schema.spec.ts
  web/src/test/unit/helpers/setupTests.ts
  web/src/test/unit/helpers/store.ts
  web/src/test/unit/mockData/home.ts
  web/src/test/unit/mockData/streams.ts
  web/src/test/unit/views/LogStream.spec.ts
  web/src/views/RUM/SessionViewer.vue
  web/vite.config.ts
Labels: ☢️ Bug, 🧹 Updates

#4988 feat: configurable thread number for usage reporting job
  src/config/src/config.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#4998 fix: set ownership for metadata streams only in the first time
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
Labels: ☢️ Bug

#4997 fix: Do not prefix email subjects
  benchmarks/pyroscope/README.md
  src/report_server/src/report.rs
  src/service/alerts/alert.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug, 📒 Documentation

#4977 test: e2e test case for report
  .github/workflows/playwright.yml
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/pages/ingestionPage.js
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/pages/reportsPage.js
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
Labels: 🧹 Updates

#5014 fix: search event type error
  src/config/src/meta/search.rs
Labels: ☢️ Bug

#5011 fix: fixed issue on aggregating field with non-existent alias and expand log detail
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/LinuxConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/JsonPreview.vue
  web/src/stores/index.ts
  web/src/test/unit/helpers/store.ts
Labels: ☢️ Bug

#5020 fix: panic when the inverted index file is empty
  src/config/src/utils/parquet.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#4961 feat: Expand logs query editor with a button
  web/src/plugins/logs/SearchBar.vue
Labels: ✏️ Feature

#5021 feat: improve replay wal to avoid OOM
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/metrics/ingest.rs
  src/ingester/src/immutable.rs
  src/ingester/src/lib.rs
  src/ingester/src/wal.rs
  src/job/files/parquet.rs
  src/service/metrics/otlp_http.rs
  src/service/search/datafusion/exec.rs
Labels: 🧹 Updates, ✏️ Feature

#5033 docs: update readme
  README.md
  screenshots/ingestion2.png
  screenshots/ingestion2.webp
  screenshots/o2_intro.webp
  screenshots/zo_intro_youtube.png
Labels: 🧹 Updates, 📒 Documentation

#5026 fix: table chart override popup, if override has duplicate name then show error
  web/src/components/dashboards/OverrideConfigPopup.vue
Labels: ☢️ Bug

#5035 fix: dashboard markdown renderer issue
  web/package-lock.json
  web/package.json
  web/src/components/dashboards/panels/HTMLRenderer.vue
  web/src/components/dashboards/panels/MarkdownRenderer.vue
  web/tailwind.config.js
Labels: ☢️ Bug

#5037 fix: Added AWS, GCP and Azure Data Sources to recommended tab
  web/src/assets/images/ingestion/aws.svg
  web/src/assets/images/ingestion/aws.webp
  web/src/assets/images/ingestion/azure.png
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/logs/Index.vue
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/recommended/AWSConfig.vue
  web/src/components/ingestion/recommended/AzureConfig.vue
  web/src/components/ingestion/recommended/GCPConfig.vue
  web/src/composables/shared/useIngestionRoutes.ts
Labels: ☢️ Bug, ✏️ Feature

#4994 feat: dashboard charts colors options
  web/src/components/dashboards/addPanel/ColorPaletteDropDown.vue
  web/src/utils/dashboard/colorPalette.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#5034 fix: partition key with none-english chars
  src/config/src/meta/stream.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#4995 fix: delete related pipelines when deleting functions and streams
  src/common/utils/auth.rs
  src/config/src/meta/pipeline/mod.rs
  src/handler/http/request/functions/mod.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/db/pipeline.rs
  src/service/functions.rs
  src/service/stream.rs
  web/src/components/functions/FunctionList.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/services/jstransform.ts
Labels: ☢️ Bug

#4991 fix: cheery-pick ingestion error logging
  src/common/meta/organization.rs
  src/config/src/meta/usage.rs
  src/config/src/metrics.rs
  src/handler/http/request/organization/settings.rs
  src/service/db/organization.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/schema.rs
  src/service/usage/mod.rs
  web/src/components/settings/OrganizationSettings.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, 📒 Documentation

#4993 fix: pipeline issues
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/pipeline/NodeForm/AssociateFunction.vue
  web/src/components/pipeline/NodeForm/Condition.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelineView.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/plugins/pipelines/CustomNode.vue
  web/src/plugins/pipelines/PipelineFlow.vue
  web/src/plugins/pipelines/useDnD.ts
  web/src/views/Functions.vue
Labels: ☢️ Bug

#5044 feat: skip auto-refresh if api is pending
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#5040 feat: dashboard folder UI changes
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#4990 test: dashboard settings
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboards/dashboard-general-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-tabs-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-variables-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/dashboards/variable.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  tests/ui-testing/playwright-tests/dashboards/vrl.spec.js
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/views/Dashboards/DashboardSettings.vue
Labels: 🧹 Updates

#4897 fix: e2e test coverage setup
  .github/workflows/playwright.yml
  tests/ui-testing/.gitignore
  tests/ui-testing/.nycrc
  tests/ui-testing/package-lock.json
  tests/ui-testing/package.json
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/baseFixtures.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/dashboards/variable.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  tests/ui-testing/playwright-tests/dashboards/vrl.spec.js
  tests/ui-testing/playwright-tests/functions.spec.js
  tests/ui-testing/playwright-tests/indexquery.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/pipeline.spec.js
  tests/ui-testing/playwright-tests/region.spec.js
  tests/ui-testing/playwright-tests/reports.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
  web/package-lock.json
  web/package.json
  web/postcss.config.js
  web/tailwind.config.js
  web/vite.config.ts
Labels: ☢️ Bug, 🧹 Updates

#5052 fix: parquet and index should have same row
  src/config/src/meta/puffin_directory/mod.rs
  src/config/src/meta/puffin_directory/writer.rs
  src/job/files/parquet.rs
  src/service/search/datafusion/distributed_plan/codec.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
Labels: ☢️ Bug

#5048 fix: Search history disable when usage report disabled
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#5056 feat: use range request for tantivy inverted index
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/inverted_index/mod.rs
  src/config/src/meta/inverted_index/reader.rs
  src/config/src/meta/inverted_index/search.rs
  src/config/src/meta/inverted_index/writer.rs
  src/config/src/meta/mod.rs
  src/config/src/meta/puffin_directory/reader/file_reader.rs
  src/config/src/meta/puffin_directory/reader/mem_reader.rs
  src/config/src/utils/file.rs
  src/config/src/utils/inverted_index.rs
  src/infra/src/cache/mod.rs
  src/infra/src/cache/storage.rs
  src/infra/src/storage/mod.rs
  src/job/files/parquet.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/tantivy/mod.rs
  src/service/search/tantivy/puffin/mod.rs
  src/service/search/tantivy/puffin/reader.rs
  src/service/search/tantivy/puffin/writer.rs
  src/service/search/tantivy/puffin_directory/mod.rs
  src/service/search/tantivy/puffin_directory/reader.rs
  src/service/search/tantivy/puffin_directory/writer.rs
  src/wal/Cargo.toml
  src/wal/src/writer.rs
Labels: ✏️ Feature

#4130 test: dashboard vrl testcases
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboards/dashboard-general-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-tabs-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-variables-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/variable.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  tests/ui-testing/playwright-tests/dashboards/vrl.spec.js
Labels: 🧹 Updates

#5045 fix: clean the session data after merge files
  Cargo.lock
  src/config/Cargo.toml
  src/config/src/config.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#5071 feat: Add new CRDs
  web/src/components/ingestion/Recommended.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ✏️ Feature

#5065 feat: we can remove filter in sql when enable inverted index
  src/config/src/config.rs
  src/handler/grpc/flight/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/tantivy/puffin_directory/reader.rs
  src/service/search/utils.rs
Labels: 🧹 Updates, ✏️ Feature

#5075 fix: enterprise build
  src/config/src/config.rs
  src/handler/http/request/organization/es.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#5062 fix: DerivedStream query period
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#5083 fix: Simplify recommended setup for Elastic Beats
  web/src/components/ingestion/logs/FileBeat.vue
Labels: ☢️ Bug

#5084 feat: compatible new es api
  src/config/src/config.rs
  src/handler/http/request/organization/es.rs
  src/handler/http/router/mod.rs
Labels: ✏️ Feature

#5085 fix: schema mismatch in memtable
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#5099 fix: mark union queries as complex to avoid adding _timestamp
  src/config/src/utils/sql.rs
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#5098 feat: add tantivy mmap search
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster/mod.rs
  src/common/infra/wal.rs
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/asynchronism/file.rs
  src/config/src/utils/file.rs
  src/handler/grpc/request/metrics/querier.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/cache/storage.rs
  src/infra/src/storage/mod.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/job/stats.rs
  src/service/compact/deleted.rs
  src/service/db/file_list/local.rs
  src/service/db/file_list/mod.rs
  src/service/db/file_list/remote.rs
  src/service/exporter/mod.rs
  src/service/exporter/otlp_o2_metrics_exporter.rs
  src/service/file_list.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/mod.rs
  src/service/search/datafusion/storage/tmpfs.rs
  src/service/search/datafusion/storage/wal.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/tantivy/puffin_directory/mod.rs
  src/service/search/tantivy/puffin_directory/reader.rs
Labels: ✏️ Feature

#3023 feat: dashboard geojson map
  src/common/meta/dashboards/v5/mod.rs
  web/src/assets/dashboard/maps/map.json
  web/src/assets/images/dashboard/charts/world-map.png
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardGeoMapsQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardMapsQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/panels/MapsRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertGeoMapData.ts
  web/src/utils/dashboard/convertMapsData.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#5074 fix: refactoring organization handling
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
  web/src/layouts/MainLayout.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, 🧹 Updates

#5076 feat: allow limit in query to have dynamic variables
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#5095 feat: move `Folder` model into config crate (part 1/3 of feature 5069)
  src/common/meta/dashboards/mod.rs
  src/common/utils/http.rs
  src/config/src/meta/folder.rs
  src/config/src/meta/mod.rs
  src/handler/http/request/dashboards/folders.rs
  src/handler/http/router/openapi.rs
  src/service/dashboards/folders.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/folders.rs
Labels: ✏️ Feature

#5096 feat: move `folders` modules out of parent `dashboards` modules (part 2/3 of feature 5069)
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/folders.rs
  src/handler/http/request/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/mod.rs
  src/service/db/folders.rs
  src/service/db/mod.rs
  src/service/folders.rs
  src/service/mod.rs
Labels: ✏️ Feature

#5053 feat: self-report for both usage and errors
  Cargo.lock
  src/config/src/meta/mod.rs
  src/config/src/meta/pipeline/mod.rs
  src/config/src/meta/self_reporting/error.rs
  src/config/src/meta/self_reporting/mod.rs
  src/config/src/meta/self_reporting/usage.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/request/ingest.rs
  src/handler/grpc/request/mod.rs
  src/handler/grpc/request/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/main.rs
  src/proto/build.rs
  src/proto/proto/cluster/usage.proto
  src/proto/src/generated/cluster.rs
  src/proto/src/lib.rs
  src/service/alerts/scheduler.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/ingestion_service.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/pipeline/batch_execution.rs
  src/service/promql/search/mod.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/http.rs
  src/service/search/mod.rs
  src/service/self_reporting/ingestion.rs
  src/service/self_reporting/mod.rs
  src/service/self_reporting/queues.rs
  src/service/traces/mod.rs
  src/service/usage/ingestion_service.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#5105 fix: report pdf must have .pdf extension
  src/report_server/src/report.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug

#5091 fix: dashboard css & stream select in add panel issue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/addPanel/QueryTypeSelector.vue
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug, ✏️ Feature

#5109 feat: implement tantivy index cache
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
  src/service/search/grpc/storage.rs
  src/service/search/tantivy/puffin_directory/mod.rs
  src/service/search/tantivy/puffin_directory/reader_cache.rs
Labels: ✏️ Feature

#5111 fix: add filter back in ingester
  src/job/files/parquet.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/codec.rs
  src/service/search/datafusion/distributed_plan/empty_exec.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/table_provider/empty_table.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/index.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#5116 fix: distinct query is complex
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#5117 feat: regexp_matches udf
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/udf/mod.rs
  src/service/search/datafusion/udf/regexp_matches_udf.rs
Labels: ✏️ Feature

#5118 fix: update chromiumoxide
  Cargo.lock
  Cargo.toml
Labels: ☢️ Bug, 🧹 Updates

#5120 fix: Pipeline minor improvements
  web/src/components/functions/FunctionList.vue
  web/src/components/pipeline/PipelineView.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/plugins/pipelines/PipelineFlow.vue
Labels: ☢️ Bug, 🧹 Updates

#5122 fix: Report all stream names for joins when usage reporting
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#5123 fix: track_totals_hits for union
  src/service/search/sql.rs
Labels: ☢️ Bug

#5125 fix: Interesting field selection join query
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#5128 test: pytest-join-queries testcases
  tests/api-testing/tests/test_joinqueries.py
  tests/test-data/joinqueries.json
Labels: 🧹 Updates

#5007 feat: allow dynamic stream name in pipeline destinations
  src/service/db/pipeline.rs
  src/service/functions.rs
  src/service/pipeline/batch_execution.rs
  src/service/pipeline/mod.rs
  src/service/search/datafusion/udf/regexp_matches_udf.rs
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/plugins/pipelines/useDnD.ts
Labels: ✏️ Feature

#5112 fix: pipeline init error due to functions fail to compile
  src/config/src/meta/self_reporting/error.rs
  src/job/mmdb_downloader.rs
  src/job/mod.rs
  src/service/db/pipeline.rs
  src/service/pipeline/batch_execution.rs
  src/service/self_reporting/queues.rs
Labels: ☢️ Bug

#5113 feat: move `dashboards` module to `config` crate (part 1/2 of feature 5068)
  Cargo.lock
  Cargo.toml
  src/common/infra/config.rs
  src/common/meta/mod.rs
  src/common/migration/schema.rs
  src/config/Cargo.toml
  src/config/src/meta/dashboards/mod.rs
  src/config/src/meta/dashboards/reports.rs
  src/config/src/meta/dashboards/v1/mod.rs
  src/config/src/meta/dashboards/v2/mod.rs
  src/config/src/meta/dashboards/v3/mod.rs
  src/config/src/meta/dashboards/v4/mod.rs
  src/config/src/meta/dashboards/v5/mod.rs
  src/config/src/meta/mod.rs
  src/handler/http/request/alerts/alert.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/dashboards/reports.rs
  src/handler/http/router/openapi.rs
  src/service/alerts/scheduler.rs
  src/service/dashboards/mod.rs
  src/service/dashboards/reports.rs
  src/service/db/dashboards/mod.rs
  src/service/db/dashboards/reports.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#5130 feat: implement preload for tantivy
  Cargo.lock
  Cargo.toml
  src/service/compact/merge.rs
  src/service/search/grpc/storage.rs
  src/service/search/tantivy/puffin/mod.rs
  src/service/search/tantivy/puffin_directory/caching_directory.rs
  src/service/search/tantivy/puffin_directory/footer_cache.rs
  src/service/search/tantivy/puffin_directory/mod.rs
  src/service/search/tantivy/puffin_directory/reader.rs
  src/service/search/tantivy/puffin_directory/writer.rs
Labels: ✏️ Feature

#5137 fix: add index_condition when do not have index file
  src/job/files/parquet.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/codec.rs
  src/service/search/datafusion/distributed_plan/empty_exec.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/table_provider/empty_table.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/index.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#5135 fix: set organization details on organization change
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#5138 fix: consider the org identifier from url
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#5129 fix: Interesting field desection
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#5133 feat: JSON-indpendent hashing of dashboard models
  Cargo.lock
  src/config/Cargo.toml
  src/config/src/meta/dashboards/mod.rs
  src/config/src/meta/dashboards/v1/mod.rs
  src/config/src/meta/dashboards/v2/mod.rs
  src/config/src/meta/dashboards/v3/mod.rs
  src/config/src/meta/dashboards/v4/mod.rs
  src/config/src/meta/dashboards/v5/mod.rs
  src/service/db/dashboards/mod.rs
  tests/api-testing/tests/test_folders.py
Labels: ✏️ Feature

#5145 refactor: group flight request fields
  src/handler/grpc/flight/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/grpc/flight.rs
  src/service/search/request.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: 🧹 Updates

#5140 fix: org selection and change organization flow
  web/src/components/login/Login.vue
  web/src/enterprise/components/login/Login.vue
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/src/utils/common.ts
  web/src/views/Login.vue
Labels: ☢️ Bug

#5149 feat: add optimize rule for simple topN
  src/config/src/meta/inverted_index.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#5153 fix: enterprise build
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#5150 fix: organization not getting displayed after login
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#5155 fix: drop problematic `folders.created_at` column
  src/infra/src/table/entity/folders.rs
  src/infra/src/table/folders.rs
  src/infra/src/table/migration/m20241116_000002_drop_folders_created_at_column.rs
  src/infra/src/table/migration/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#5146 feat: migrate dashboards out of `meta` table and into their own table
  src/config/src/meta/dashboards/mod.rs
  src/config/src/meta/dashboards/v1/mod.rs
  src/config/src/meta/dashboards/v2/mod.rs
  src/config/src/meta/dashboards/v3/mod.rs
  src/config/src/meta/dashboards/v4/mod.rs
  src/config/src/meta/dashboards/v5/mod.rs
  src/infra/src/errors/mod.rs
  src/infra/src/table/dashboards.rs
  src/infra/src/table/entity/dashboards.rs
  src/infra/src/table/entity/folders.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/folders.rs
  src/infra/src/table/migration/m20241119_000001_create_dashboards_table.rs
  src/infra/src/table/migration/m20241119_000002_populate_dashboards_table.rs
  src/infra/src/table/migration/m20241119_000003_delete_metas.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/service/dashboards/mod.rs
  src/service/dashboards/reports.rs
  src/service/db/dashboards/mod.rs
  tests/api-testing/tests/test_folders.py
Labels: ✏️ Feature

#5154 feat: add more optimize rule for tantivy
  src/config/src/config.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
Labels: ✏️ Feature

#5159 fix: dashboard bugs
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5162 fix: don't report dashboard search as logs stream type
  src/service/search/mod.rs
Labels: ☢️ Bug

#5166 fix: order by with histogram logic
  src/service/search/sql.rs
Labels: ☢️ Bug

#5170 ci: add workspace unit tests to coverage tests
  coverage.sh
  src/config/src/config.rs
  src/infra/src/cache/file_data/mod.rs
Labels: 🧹 Updates

#5169 fix: dashboard org redirection fixes
  web/src/utils/commons.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#5176 fix: undefined call fix
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/layouts/MainLayout.vue
  web/src/views/HomeView.vue
Labels: ☢️ Bug

#5107 test: Update coverage report
  .github/workflows/playwright.yml
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/pages/ingestionPage.js
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/managementPage .js
  tests/ui-testing/pages/reportsPage.js
  tests/ui-testing/playwright-tests/attachment/imagesAuto.png
  tests/ui-testing/playwright-tests/join.spec.js
  tests/ui-testing/playwright-tests/logoManagement.spec.js
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
  tests/ui-testing/playwright-tests/secondsPrecisionAdded.spec.js
Labels: 🧹 Updates

#5178 fix: compactor: Tiny typo fix
  src/service/compact/merge.rs
Labels: ☢️ Bug

#5181 fix: local storage doesn't support multi part put
  src/infra/src/storage/local.rs
Labels: ☢️ Bug

#5184 fix: use search type to choose query group on router
  src/router/http/mod.rs
Labels: ☢️ Bug

#5182 feat: maps-support-for-visualization
  web/src/components/dashboards/addPanel/DashboardMapsQueryBuilder.vue
Labels: ✏️ Feature

#5192 fix: serde default & flatten overlap
  src/config/src/meta/search.rs
Labels: ☢️ Bug

#5171 feat: add `title` param to `ListDashboard` API for cross-folder searching
  src/config/src/meta/dashboards/mod.rs
  src/handler/http/request/dashboards/mod.rs
  src/infra/Cargo.toml
  src/infra/src/table/dashboards.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/mod.rs
  src/service/folders.rs
Labels: ✏️ Feature
