Repository openobserve/openobserve, pull requests merged in 2024-09, with the labels that each got.

#4417 fix: histogram interval
  src/common/meta/search.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4423 fix: table columns reordering issue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4425 fix: share link issue for dashboard
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#4418 fix: ofga should sync in super cluster
  src/common/infra/mod.rs
  src/common/infra/ofga.rs
  src/infra/src/storage/remote.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/ofga.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#4429 fix: removed duplicated table columns
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates

#4270 feat: use FST for inverted indexing
  Cargo.lock
  Cargo.toml
  coverage.sh
  src/cli/data/export.rs
  src/common/utils/http.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/inverted_index/mod.rs
  src/config/src/meta/inverted_index/reader.rs
  src/config/src/meta/inverted_index/search.rs
  src/config/src/meta/inverted_index/writer.rs
  src/config/src/meta/mod.rs
  src/config/src/meta/puffin/mod.rs
  src/config/src/meta/puffin/reader.rs
  src/config/src/meta/puffin/writer.rs
  src/config/src/meta/search.rs
  src/config/src/utils/inverted_index.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/stats.rs
Labels: ✏️ Feature

#4369 chore: update ChartRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
Labels: 🧹 Updates

#4341 style: improved german translations
  web/src/locales/languages/de.json
Labels: 🧹 Updates

#4442 fix: match all panic
  src/config/src/meta/inverted_index/search.rs
  src/config/src/utils/inverted_index.rs
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3957 feat: AND, OR, group condition for dashboard filter
  src/common/meta/dashboards/mod.rs
  src/common/meta/dashboards/v5/mod.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/mod.rs
  tests/ui-testing/playwright-tests/dashboard.spec.js
  tests/ui-testing/playwright-tests/visualize.spec.js
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/utils/dashboard/convertDashboardSchemaVersion.ts
  web/src/utils/query/sqlUtils.ts
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/addPanel/AddCondition.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/src/views/Dashboards/addPanel/DashboardFiltersOption.vue
  web/src/views/Dashboards/addPanel/Group.vue
Labels: ✏️ Feature

#4446 fix: use cache duration to update query duration
  src/common/meta/search.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4443 fix: realtime alert can't be trigger
  src/common/meta/dashboards/v5/mod.rs
  src/service/alerts/alert.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4321 feat: add datafusion json functions
  Cargo.lock
  Cargo.toml
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#4454 test: api test search queries
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates

#4456 fix: use ofga mapping in tuple object type for search permission checking
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
Labels: ☢️ Bug

#4449 fix: UI fixes in alert list and DateTime selection
  web/src/components/DateTime.vue
  web/src/components/QueryEditor.vue
  web/src/components/alerts/AlertList.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/TenstackTable.vue
  web/vite.config.ts
Labels: ☢️ Bug

#4436 feat: add URI query fields for alert list filtering
  src/common/meta/alerts/alert.rs
  src/handler/http/request/alerts/alert.rs
  src/service/alerts/alert.rs
  web/src/components/alerts/AlertList.vue
Labels: ✏️ Feature

#4340 feat: new config for dashboard variables
  src/common/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature

#4459 fix: Query Editor rendering issue in logs page
  web/src/components/QueryEditor.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/styles/app.scss
Labels: ☢️ Bug

#4461 fix: vrl as query UDF
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/udf/transform_udf.rs
Labels: ☢️ Bug

#4463 fix: vrl as UDF
  src/service/search/datafusion/udf/transform_udf.rs
Labels: ☢️ Bug

#4466 fix:vrl error from cache
  src/service/search/cache/mod.rs
Labels: Invalid PR Title, ☢️ Bug

#4435 fix: unify the trace ingestion handling
  Cargo.lock
  Cargo.toml
  src/handler/grpc/request/traces.rs
  src/handler/http/request/traces/mod.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  tests/api-testing/tests/test_traces.py
Labels: ☢️ Bug

#4467 fix: Logs table UI fixes
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
Labels: ☢️ Bug

#4472 fix: vrl error for cache & histogram interval changes
  src/service/search/cache/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#4484 fix: target partition for noCache
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#4287 feat: cache dashboard panel data
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/common/RelativeTime.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/dashboard/usePanelCache.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/src/views/RUM/AppPerformance.vue
Labels: ✏️ Feature

#4482 fix: remove start date change for cache duration
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4480 fix: list only permitted for enrichment tables list
  src/handler/http/request/stream/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/stream.rs
Labels: ☢️ Bug

#4494 fix: Pagination partition fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4498 fix: use hashset to check if a realtime alert is already evaluated
  src/service/logs/mod.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#4496 fix: dashboard cache issues
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#4325 feat: destination-less report
  src/common/meta/dashboards/reports.rs
  src/handler/http/request/dashboards/reports.rs
  src/report_server/src/models.rs
  src/report_server/src/report.rs
  src/report_server/src/router.rs
  src/service/dashboards/reports.rs
Labels: ✏️ Feature

#4504 fix: scheduled dashboards UI issues
  web/src/views/Dashboards/ScheduledDashboards.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#4499 fix: metadata resource type permission issue
  web/src/components/iam/roles/EditRole.vue
Labels: ☢️ Bug

#3866 feat: Dashboard Cancel Query
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DashboardErrors.vue
  web/src/composables/dashboard/useCancelQuery.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#4507 fix: Can't enable a partition key after disable it
  web/src/composables/useStreams.ts
Labels: ☢️ Bug

#4509 fix: dashboard show time range differ warning when cache data is used
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelCache.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#4514 fix: Dashboard UI fix
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/src/views/Dashboards/addPanel/DashboardFiltersOption.vue
Labels: ☢️ Bug

#4512 fix: improve consistent hashing
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/dist_lock.rs
  src/service/compact/flatten.rs
  src/service/compact/mod.rs
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4517 fix: consistent hashing
  src/service/compact/mod.rs
Labels: ☢️ Bug

#4515 fix: use browser.wait() after browser.close()
  src/config/src/meta/usage.rs
  src/report_server/src/report.rs
  src/service/alerts/scheduler.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug

#4521 fix: nats lock with node id
  src/infra/src/db/nats.rs
Labels: ☢️ Bug

#4458 fix: use timezone offset for cron based derived streams
  web/src/components/pipeline/StreamRouting.vue
Labels: ☢️ Bug

#4522 fix: dashboard, folder, tab on search filtering in create report
  web/src/components/reports/CreateReport.vue
  web/src/views/Dashboards/ScheduledDashboards.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug, ✏️ Feature

#4520 fix: on dashboard panel zoom, refresh whole dashboard
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#4523 fix: dashboard undefined error for promql error message
  web/src/composables/dashboard/useCancelQuery.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#4526 fix: In create report tab options not getting set
  web/src/components/reports/CreateReport.vue
Labels: ☢️ Bug, ✏️ Feature

#4527 fix: delta dedup for multi cache
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4530 fix: usage report duplicated
  src/common/infra/wal.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4529 fix: added search in dropdown of clone alert
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug, ✏️ Feature

#4511 feat: search_history api
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
Labels: ✏️ Feature

#4531 fix: showing not found error in preview while selecting some streams
  web/src/components/alerts/AddAlert.vue
Labels: ☢️ Bug

#4471 feat: add env variable to toggle full text search type
  src/config/src/config.rs
  src/config/src/meta/inverted_index/search.rs
  src/config/src/meta/search.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/storage.rs
Labels: ✏️ Feature

#4534 fix: add more tracing for search
  src/service/search/datafusion/exec.rs
  src/service/search/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4537 fix: cache - duplicate records issue
  src/service/db/syslog.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#3693 feat: variables support to pass current selected time for URL drilldown
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
Labels: ✏️ Feature

#4536 fix: add timezone key to alert and derived stream
  src/common/meta/alerts/mod.rs
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/pipeline/ScheduledPipeline.vue
  web/src/components/pipeline/StreamRouting.vue
  web/src/components/reports/CreateReport.vue
  web/src/utils/date.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature

#4547 fix: stream status incorrect
  src/common/infra/cluster/mod.rs
  src/config/src/cluster.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: ☢️ Bug

#4548 fix: stream stats incorrect
  src/config/src/meta/stream.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: ☢️ Bug

#4553 feat: variable to pass current query for dashboard drilldown
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
Labels: ✏️ Feature

#4556 fix: In Dashboard general setting, date time was not getting save as auto apply was false by default
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
Labels: ☢️ Bug

#4551 fix: add max_lifetime for db connection pool
  src/config/src/config.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
Labels: ☢️ Bug, ✏️ Feature

#4376 feat: store original unflattened JSON record
  src/common/meta/ingestion.rs
  src/config/src/ider.rs
  src/config/src/meta/stream.rs
  src/infra/src/schema/mod.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/trace_list_index.rs
  src/service/schema.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
  web/src/components/logstream/schema.vue
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/JsonPreview.vue
Labels: ✏️ Feature

#4550 fix: fixed trace span start time issue
  web/src/composables/shared/router.ts
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetails.vue
Labels: ☢️ Bug

#4560 fix: only compare variables which depends on that panel loading for caching
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#4562 fix: reuse gRPC channel for enterprise
  src/service/search/cluster/http.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#4563 fix: Added by default timezone for send now schedule
  web/src/components/reports/CreateReport.vue
Labels: ☢️ Bug, ✏️ Feature

#4468 fix: add custom sorting function for docNum column
  web/src/views/LogStream.vue
Labels: ☢️ Bug, ✏️ Feature

#4567 fix: log related issues
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug

#4573 fix: optimise file list fetch from db
  src/config/src/config.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: ☢️ Bug

#4569 feat: for view panel and visualization applied cancel query
  tests/ui-testing/playwright-tests/visualize.spec.js
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ✏️ Feature

#4585 fix: Log issues to be release
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug

#4586 fix: for custom variable show its label not value when selected
  web/src/components/dashboards/settings/VariableCustomValueSelector.vue
Labels: ☢️ Bug

#4584 fix: release wal parquet files
  src/common/infra/wal.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#4575 fix: alert improvements
  src/config/src/config.rs
  src/config/src/meta/usage.rs
  src/job/alert_manager.rs
  src/service/alerts/alert.rs
  src/service/alerts/scheduler.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4518 feat: optimise file list querying for better search perf
  Cargo.lock
  Cargo.toml
  src/config/src/meta/search.rs
  src/handler/grpc/request/file_list.rs
  src/handler/grpc/request/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/main.rs
  src/proto/build.rs
  src/proto/proto/cluster/filelist.proto
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/file_list.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
Labels: ✏️ Feature

#4600 fix: origin field should not be select
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#4602 fix: skip fetching file list for aggregate query
  src/service/search/mod.rs
Labels: ☢️ Bug

#4608 fix: track total hits of distinct
  src/service/search/sql.rs
Labels: ☢️ Bug

#4611 fix: search partition follow query order by
  src/config/src/meta/search.rs
  src/config/src/meta/sql.rs
  src/service/search/cache/cacher.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#4604 fix: sort partition api response
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#4492 docs: Fix typos
  .typos.toml
  CONTRIBUTING.md
  Cargo.lock
  openobserve.cdx.xml
  src/cli/basic/cli.rs
  src/common/infra/ofga.rs
  src/common/meta/dashboards/reports.rs
  src/common/utils/http.rs
  src/config/src/meta/puffin/writer.rs
  src/config/src/utils/flatten.rs
  src/config/src/utils/str.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/db/nats.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/job/alert_manager.rs
  src/main.rs
  src/report_server/Cargo.toml
  src/report_server/src/models.rs
  src/report_server/src/report.rs
  src/report_server/src/router.rs
  src/service/alerts/alert.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/dashboards/reports.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/promql/binaries/vector_operations.rs
  src/service/promql/value.rs
  src/service/schema.rs
  src/service/search/cache/cacher.rs
  src/service/search/cluster/cache_multi.rs
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/users.rs
  tests/input.json
  tests/integration_test.rs
Labels: ☢️ Bug, 📒 Documentation

#4613 fix:default sort when no sort specified
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
Labels: ☢️ Bug

#4616 fix: compactor with puffin
  src/infra/src/storage/mod.rs
Labels: ☢️ Bug

#4620 fix: cache issue for multiple group by clause
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4624 fix: generate partition key with null if the field is not exists
  src/job/files/parquet.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#4628 fix: added support to edit dashboard panel layout height
  web/src/components/dashboards/PanelContainer.vue
  web/src/locales/languages/en.json
  web/src/views/Dashboards/PanelLayoutSettings.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug, ✏️ Feature

#4632 fix: add pagination height while calculating row count
  web/src/locales/languages/en.json
  web/src/views/Dashboards/PanelLayoutSettings.vue
Labels: ☢️ Bug, ✏️ Feature

#4592 feat: dashboard transpose and dynamic columns
  src/common/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature

#4636 fix: added logs page redirection and rename label
  web/src/components/functions/EnrichmentTableList.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature

#4618 feat: check indices exists before running create index commands
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/infra/src/schema/history/sqlite.rs
Labels: ✏️ Feature

#4639 fix: Updated dashboard panel height row count logic
  web/src/views/Dashboards/PanelLayoutSettings.vue
Labels: ☢️ Bug, 🧹 Updates

#4633 fix: add request timeout for tonic requests
  src/handler/grpc/auth/mod.rs
  src/service/db/file_list/broadcast.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/cache_multi.rs
  src/service/search/cluster/cacher.rs
  src/service/search/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4626 feat: multi search with multiple time ranges
  src/config/src/meta/search.rs
  src/handler/http/request/search/multi_streams.rs
Labels: ✏️ Feature

#4641 fix: fixed input validation of panel layout input
  web/src/locales/languages/en.json
  web/src/views/Dashboards/PanelLayoutSettings.vue
Labels: ☢️ Bug

#4635 fix: added icon for enrichment table redirection to logs and rename d…
  web/src/components/functions/EnrichmentTableList.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature

#4609 feat: add without connection pool mode for router
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/handler/http/router/mod.rs
  src/router/http/mod.rs
Labels: ✏️ Feature

#4648 fix: multi query enterprise 0.12.1
  src/config/src/meta/search.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/alerts/mod.rs
Labels: Invalid PR Title

#4643 fix: add file list id cache
  src/config/src/config.rs
  src/infra/src/db/mod.rs
  src/infra/src/dist_lock.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/lib.rs
  src/job/mod.rs
  src/service/db/file_list/remote.rs
  src/service/file_list.rs
  src/service/search/cluster/flight.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug, ✏️ Feature

#4658 fix: add partial response warning
  Cargo.lock
  src/handler/http/request/search/multi_streams.rs
Labels: ☢️ Bug, ✏️ Feature

#4656 feat: Search history introduced in the logs page
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  web/src/components/DateTime.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchHistory.vue
  web/src/services/search.ts
Labels: ✏️ Feature

#4659 perf: remove unnecessary setting for parquet writer
  src/config/src/utils/parquet.rs
  src/ingester/src/partition.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
Labels: 🧹 Updates

#4662 fix: multi resp changes
  src/handler/http/request/search/multi_streams.rs
Labels: ☢️ Bug

#4644 feat: add multipart upload
  src/config/src/config.rs
  src/infra/src/storage/mod.rs
  src/infra/src/storage/remote.rs
Labels: ✏️ Feature

#4667 fix: search history bugs fixed
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchHistory.vue
Labels: ☢️ Bug

#4668 fix: drilldown query variable issue with variable
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug
