Repository openobserve/openobserve, pull requests merged in 2024-06, with the labels that each got.

#3657 fix: Time Selection popup gets hidden behind Date-Time UI
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#3658 feat: add limit -1 for query
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/meta/sql.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/sql.rs
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/test/unit/mockData/alerts.ts
Labels: ✏️ Feature

#3659 fix: recordbatch format
  src/config/src/utils/record_batch_ext.rs
Labels: ☢️ Bug

#3661 fix: datetime-picker-z-index-issue
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#3660 feat: allow disable gxhash dependency
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/cluster.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/hash/gxhash.rs
  src/config/src/utils/hash/mod.rs
  src/config/src/utils/schema_ext.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/db/postgres.rs
Labels: ✏️ Feature

#3627 fix: inverted index query count
  src/config/src/config.rs
  src/service/compact/merge.rs
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/datafusion/mod.rs
  src/service/search/sql.rs
  tests/api-testing/tests/test_search.py
Labels: ☢️ Bug, 📒 Documentation

#3663 test: e2e-backfill-logdata
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#3664 fix: format timestamp for dashboard table chart
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#3648 feat: include search type in search calls
  src/cli/data/export.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/mod.rs
  src/service/usage/stats.rs
  web/src/components/alerts/PreviewAlert.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/components/rum/performance/ApiDashboard.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
  web/src/services/search.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/ErrorViewer.vue
  web/src/views/RUM/SessionViewer.vue
  web/src/views/StreamExplorer.vue
Labels: ✏️ Feature

#3620 fix: removed _timestamp and order by restriction from sql mode
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug, 🧹 Updates

#3672 fix: move usage reporting to cron jobs
  src/job/mod.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3673 fix: reduce CPU const for merging
  src/config/src/utils/record_batch_ext.rs
  src/infra/src/db/postgres.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#3679 fix: default for ZO_USAGE_PUBLISH_INTERVAL not loaded
  src/config/src/config.rs
Labels: ☢️ Bug

#3584 fix: several PromQL functions
  src/service/promql/aggregations/mod.rs
  src/service/promql/engine.rs
  src/service/promql/exec.rs
  src/service/promql/functions/histogram.rs
  src/service/promql/functions/irate.rs
  src/service/promql/value.rs
Labels: ☢️ Bug

#3677 test: table type dashboard
  tests/ui-testing/package-lock.json
  tests/ui-testing/package.json
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
Labels: 🧹 Updates

#3675 fix: In IAM on deleting user, user actions were getting disabled
  web/src/components/iam/users/User.vue
Labels: ☢️ Bug

#3670 fix: add searchtype params to dashboard url for reports
  src/report_server/src/report.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug, ✏️ Feature

#3680 feat: nano second as unit for dashboard
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ✏️ Feature

#3687 fix: view panel parser issue due to lazy load
  web/src/components/dashboards/viewPanel/ViewPanel.vue
Labels: ☢️ Bug

#3676 fix: dashboard filter option value format and added more operators in variables settings filter
  web/src/components/dashboards/addPanel/CommonAutoComplete.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/composables/useSearchInputUsingRegex.ts
  web/src/utils/query/sqlUtils.ts
  web/src/views/Dashboards/DashboardSettings.vue
Labels: ☢️ Bug, ✏️ Feature

#3667 feat: support presigned GET URLS
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/config/src/config.rs
  src/handler/grpc/auth/mod.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
  src/service/db/user.rs
  src/service/organization.rs
  src/service/users.rs
  web/src/components/iam/users/AddUser.vue
Labels: ✏️ Feature

#3685 feat: add _min & _max for otlp metrics
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
Labels: ✏️ Feature

#3697 fix: dashboard datetime picker toggle issue from relative to absolute
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#3702 fix: the upgrade of awc lib broke rum proxy
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#3696 fix: multiple timestamp columns issue on grid
  tests/ui-testing/playwright-tests/schema.spec.js
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3703 fix: include trace_id in search usage reporting
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/service/promql/search/mod.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3714 chore: Add download script
  download.sh
Labels: ✏️ Feature

#3715 fix: Use hash for mysql lock key
  src/infra/src/db/mysql.rs
Labels: ☢️ Bug

#3722 test: fix logs breaking test
  tests/ui-testing/playwright-tests/logspage.spec.js
Labels: ☢️ Bug, 🧹 Updates

#3713 feat: streams memtable hashing & dedicated memtables configuration
  src/config/src/config.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/service/logs/bulk.rs
Labels: ✏️ Feature

#3723 fix: multiple timestamp columns displayed on result grid
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3727 test: pytest logs search queries
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates

#3678 perf: improve ingestion
  .github/workflows/release.yml
  Cargo.lock
  deploy/build/Dockerfile.tag-simd.amd64
  src/cli/data/import.rs
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/config/src/utils/parquet.rs
  src/handler/grpc/request/logs.rs
  src/handler/grpc/request/metrics/ingester.rs
  src/handler/grpc/request/traces.rs
  src/handler/grpc/request/usage.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/metrics/ingest.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/rum/ingest.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/ingester/Cargo.toml
  src/ingester/src/immutable.rs
  src/ingester/src/lib.rs
  src/ingester/src/memtable.rs
  src/ingester/src/partition.rs
  src/ingester/src/stream.rs
  src/ingester/src/wal.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/main.rs
  src/router/grpc/ingest/logs.rs
  src/router/grpc/ingest/metrics.rs
  src/router/grpc/ingest/traces.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: 🧹 Updates

#3730 feat: optimize default NDV of bloom filter
  src/config/src/utils/parquet.rs
Labels: ✏️ Feature

#3734 chore(deps): update to datafusion 39
  Cargo.lock
  Cargo.toml
  src/config/src/meta/sql.rs
  src/infra/src/storage/local.rs
  src/infra/src/storage/mod.rs
  src/infra/src/storage/remote.rs
  src/service/search/datafusion/rewrite.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/tmpfs.rs
  src/service/search/datafusion/storage/wal.rs
Labels: 🧹 Updates

#3704 feat: introduce UDFs applicable on array fields
  src/service/search/datafusion/arr_descending_udf.rs
  src/service/search/datafusion/arrcount_udf.rs
  src/service/search/datafusion/arrindex_udf.rs
  src/service/search/datafusion/arrjoin_udf.rs
  src/service/search/datafusion/arrsort_udf.rs
  src/service/search/datafusion/arrzip_udf.rs
  src/service/search/datafusion/cast_to_arr_udf.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/spath_udf.rs
  src/service/search/datafusion/string_to_array_v2_udf.rs
Labels: ✏️ Feature

#3738 feat: sync hotfix from v0.10.6-rc3
  src/config/src/config.rs
  src/config/src/utils/record_batch_ext.rs
  src/handler/http/request/stream/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/ingester/src/errors.rs
  src/ingester/src/immutable.rs
  src/ingester/src/lib.rs
  src/ingester/src/partition.rs
  src/ingester/src/writer.rs
  src/job/compactor.rs
  src/job/files/parquet.rs
  src/job/flatten_compactor.rs
  src/service/compact/file_list.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3737 feat: add `to_array_string(array)` udf
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/to_arr_string_udf.rs
Labels: ✏️ Feature

#3721 fix: Decode URL-safe base64 encoded JWT tokens
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#3739 feat: set bloom filter for index stream
  Cargo.lock
  Cargo.toml
  src/infra/src/schema/mod.rs
  src/job/files/parquet.rs
Labels: ✏️ Feature

#3746 fix: the base_url didnt contain web+base_uri for presigned url
  src/handler/http/request/users/mod.rs
Labels: ☢️ Bug

#3747 fix: ensure that dashmap isnt getting deadlocked + more logs
  src/handler/http/auth/validator.rs
  src/service/users.rs
Labels: ☢️ Bug

#3716 feat: null value drop
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/datetimeStartPoint.ts
Labels: ✏️ Feature

#3751 fix: traces UI issues
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceTree.vue
Labels: ☢️ Bug

#3752 fix: dashboard-tooltip-unit-for-null-value
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug

#3748 feat: support formatting large numbers
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ✏️ Feature

#3756 fix: pass original timestamp for table chart drilldown
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#3754 fix: missing/invalid token in cache and in db??
  src/service/users.rs
Labels: ☢️ Bug

#3760 test: fix schema breaking testcase
  tests/ui-testing/playwright-tests/schema.spec.js
Labels: ☢️ Bug, 🧹 Updates

#3766 fix: query converted to lowercase issue fix
  web/src/plugins/logs/SearchBar.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#3768 fix: inverted index report Offset overflow for BinaryArray
  src/config/src/config.rs
  src/config/src/meta/sql.rs
  src/config/src/utils/inverted_index.rs
  src/config/src/utils/mod.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/service/search/cluster/mod.rs
  src/service/traces/otlp_http.rs
  src/wal/src/lib.rs
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3769 fix: generate inverted index on compactor
  src/job/files/parquet.rs
Labels: ☢️ Bug

#3770 fix: Multi stream debug log
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
Labels: Invalid PR Title, ☢️ Bug

#3774 fix: reset field list sequence while switching between UDS and all fi…
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#3771 test: added some tests for token-splitting for inverted-index
  src/config/src/utils/inverted_index.rs
Labels: Invalid PR Title, 🧹 Updates, ✏️ Feature

#3779 fix: dashboard bugs for null values and table chart
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#3758 fix: include login calls into auditing
  src/common/utils/auth.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/job/mod.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3782 fix: partition time level check for compactor job
  Cargo.lock
  Cargo.toml
  src/config/src/utils/inverted_index.rs
  src/service/compact/mod.rs
Labels: ☢️ Bug

#3786 feat: added help about immutable configs in NATS
  src/config/src/config.rs
Labels: ✏️ Feature

#3790 feat: support user level search work group
  src/common/utils/auth.rs
  src/config/src/meta/search.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/search/job.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/schema/mod.rs
  src/ingester/src/partition.rs
  src/proto/proto/cluster/search.proto
  src/service/compact/merge.rs
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#3789 feat: add setting for query range per stream
  src/config/src/meta/search.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/search/mod.rs
  src/service/metadata/trace_list_index.rs
  web/src/components/logstream/schema.vue
Labels: ✏️ Feature

#3791 perf: improve user level search group
  src/infra/src/db/nats.rs
  src/service/search/cluster/mod.rs
Labels: 🧹 Updates

#3797 perf: increase datafusion target partitions
  src/service/search/datafusion/exec.rs
Labels: 🧹 Updates

#3801 fix: dashboard gauge chart getAxesOnZeroOf issue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#3803 fix: need clean search queue with got error
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3806 feat: add tracing for get file list
  Cargo.lock
  src/infra/Cargo.toml
  src/infra/src/file_list/mod.rs
  src/service/file_list.rs
  src/service/search/cluster/mod.rs
Labels: ✏️ Feature

#3808 feat: Exclude _all field for select *
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/flatten.rs
  src/service/logs/mod.rs
  src/service/schema.rs
  src/service/search/grpc/mod.rs
Labels: ✏️ Feature

#3810 fix: dashboard pie, donut chart getAxesOnZeroOf issue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#3812 fix: panic when the stream have no pipeline
  src/config/src/config.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
Labels: ☢️ Bug

#3811 test: e2e schema test fix
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
Labels: ☢️ Bug, 🧹 Updates

#3804 feat: Dashboard query range per stream
  src/handler/http/request/search/mod.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#3665 fix: use severity number for otlp grpc ingestion when severity text is missing
  src/service/logs/otlp_grpc.rs
Labels: ☢️ Bug

#3788 fix: greyed our run query button
  web/src/components/DateTime.vue
  web/src/components/logstream/schema.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/vite.config.ts
Labels: ☢️ Bug

#3784 feat: added multi delete option for running queries
  web/src/components/queries/RunningQueriesList.vue
  web/src/services/search.ts
Labels: ✏️ Feature

#3819 fix: Multiple query cancellation issue
  web/src/components/queries/RunningQueriesList.vue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3818 refactor: strip "tbl." prefix from field names in merge_write_recordbatch
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug, 🧹 Updates

#3825 fix: less hour selected in absolute time shouldn't change to query range
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3831 test: e2e-stream-multiselect
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
Labels: 🧹 Updates

#3832 fix: cancel the request in queue
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3830 feat: support subquery in same stream
  src/config/src/meta/sql.rs
  src/service/search/cluster/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/rewrite.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#3845 feat: use global lock replace select for update for file list jobs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: 🧹 Updates, ✏️ Feature

#3847 fix: def val for start_at column
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: ☢️ Bug

#3848 test: e2e-cache-data-scenario
  tests/api-testing/tests/test_search.py
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#3844 feat: fast-mode by partition key
  src/service/search/sql.rs
Labels: ✏️ Feature

#3846 feat: add custom table provider
  src/handler/http/request/status/mod.rs
  src/service/promql/engine.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/table_provider/test_util.rs
  src/service/search/datafusion/udf/arr_descending_udf.rs
  src/service/search/datafusion/udf/arrcount_udf.rs
  src/service/search/datafusion/udf/arrindex_udf.rs
  src/service/search/datafusion/udf/arrjoin_udf.rs
  src/service/search/datafusion/udf/arrsort_udf.rs
  src/service/search/datafusion/udf/arrzip_udf.rs
  src/service/search/datafusion/udf/cast_to_arr_udf.rs
  src/service/search/datafusion/udf/date_format_udf.rs
  src/service/search/datafusion/udf/match_udf.rs
  src/service/search/datafusion/udf/mod.rs
  src/service/search/datafusion/udf/regexp_udf.rs
  src/service/search/datafusion/udf/spath_udf.rs
  src/service/search/datafusion/udf/string_to_array_v2_udf.rs
  src/service/search/datafusion/udf/time_range_udf.rs
  src/service/search/datafusion/udf/to_arr_string_udf.rs
  src/service/search/datafusion/udf/transform_udf.rs
Labels: ✏️ Feature

#3823 feat: cache query results
  src/common/meta/mod.rs
  src/common/meta/search.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/utils/time.rs
  src/handler/grpc/request/mod.rs
  src/handler/grpc/request/query_cache.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/cache/meta.rs
  src/infra/src/cache/mod.rs
  src/main.rs
  src/proto/build.rs
  src/proto/proto/cluster/querycache.proto
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/result_utils.rs
  src/service/search/cluster/cacher.rs
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#3855 refactor: simple table provider
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/table_provider/test_util.rs
Labels: 🧹 Updates

#3853 fix: set right partitioning config as default
  src/config/src/config.rs
Labels: ☢️ Bug

#3856 fix: ci change as -> AS in Dockerfiles
  deploy/build/Dockerfile
  deploy/build/Dockerfile.aarch64
  deploy/build/Dockerfile.amd64
  deploy/build/Dockerfile.pr.amd64
  deploy/build/Dockerfile.profiling.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/Dockerfile.tokio-console.amd64
Labels: ☢️ Bug

#3851 fix: partial result
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3854 fix: Remove trailing slash from otlphttp configuration
  web/src/components/ingestion/logs/OtelConfig.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
Labels: ☢️ Bug, 🧹 Updates

#3857 chore: add license header
  src/common/meta/search.rs
  src/handler/grpc/request/query_cache.rs
  src/infra/src/cache/meta.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/result_utils.rs
  src/service/search/cluster/cacher.rs
Labels: ✏️ Feature

#3858 test: e2e test skip
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#3859 fix: discard last x min of cached data
  src/config/src/config.rs
  src/handler/http/request/search/mod.rs
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug
