Repository openobserve/openobserve, pull requests merged in 2024-03, with the labels that each got.

#2835 fix: pin rye to 0.27.0
  .github/workflows/api-testing.yml
Labels: ☢️ Bug

#2833 test: run logs breaking testcase
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2838 fix: schema evolution
  src/config/src/utils/schema_ext.rs
  src/service/schema.rs
Labels: ☢️ Bug

#2837 fix: inverted index failure
  src/service/search/mod.rs
Labels: ☢️ Bug

#2760 feat: dashboard print
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/stores/index.ts
  web/src/utils/dashboard/useCustomDebouncer.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#2825 feat: introduce alert emails in backend
  src/common/meta/alerts/destinations.rs
  src/common/meta/alerts/templates.rs
  src/handler/http/request/alerts/destinations.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
Labels: ✏️ Feature

#2834 feat: impl FIFO for query cache
  src/config/src/config.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
Labels: ✏️ Feature

#2843 fix: some comments
  CONTRIBUTING.md
  src/common/infra/mod.rs
  src/common/utils/auth.rs
Labels: Invalid PR Title, ☢️ Bug, 📒 Documentation

#2845 fix: UI improvements in alerts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/locales/languages/en.json
  web/src/locales/languages/zh.json
Labels: ☢️ Bug, 🧹 Updates

#2847 fix: inverted index issue
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#2854 fix: inverted index min ts issue
  src/common/infra/wal.rs
  src/job/files/idx.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#2859 fix: missing drilldown name data-test id
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
Labels: ☢️ Bug, 🧹 Updates

#2860 fix: search got parquet not found
  src/infra/src/cache/tmpfs.rs
  src/job/compact.rs
  src/job/files/parquet.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/grpc/wal.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#2857 fix: inverted index switch file format
  src/job/files/idx.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
  src/service/ingestion/index_writer.rs
  src/service/ingestion/mod.rs
  src/service/search/grpc/mod.rs
Labels: ☢️ Bug

#2862 fix: provide stream names for deleting function
  src/service/functions.rs
Labels: ☢️ Bug

#2864 fix: data-test for drilldown pop up
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
Labels: ☢️ Bug, 🧹 Updates

#2867 test: alerts testcases run
  .github/workflows/ui-testing.yml
  tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/edit_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
Labels: 🧹 Updates

#2875 fix: functions issue add same function again
  src/service/functions.rs
Labels: Invalid PR Title, ☢️ Bug, ✏️ Feature

#2872 fix: added test id's for functions
  web/src/components/functions/AssociatedStreamFunction.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FunctionList.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2871 feat: fast mode added on logs page
  tests/ui-testing/cypress.config.js
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ✏️ Feature

#2880 fix: limit got removed in full sql mode with partition implementation.
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2876 feat: add fast mode for query
  Cargo.lock
  Cargo.toml
  proto/cluster/search.proto
  src/cli/data/export.rs
  src/common/meta/search.rs
  src/config/src/config.rs
  src/handler/grpc/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/job/files/parquet.rs
  src/service/alerts/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#2883 fix: remove functions via watchers only
  src/service/functions.rs
Labels: ☢️ Bug, 🧹 Updates

#2884 fix: add prometheus operator CRDs
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ☢️ Bug, ✏️ Feature

#2886 fix: add some debug logs for index
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#2888 fix: logout user functionality
  web/src/components/iam/users/AddUser.vue
Labels: ☢️ Bug

#2889 fix: generate index with array distinct
  src/common/meta/http.rs
  src/common/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/service/file_list.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2890 test: fastmode testcases
  .github/workflows/ui-testing.yml
  tests/ui-testing/cypress/e2e/tests/logs_fastmode.cy.js
Labels: 🧹 Updates

#2895 fix: Custom logo text single line
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/components/login/Login.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#2896 fix: optimise inverted index generation
  src/common/meta/sql.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2898 fix: config variables
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
Labels: ☢️ Bug

#2900 test: remove quick mode testcases
  .github/workflows/ui-testing.yml
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2902 feat: fast_mode rebased
  src/common/infra/cluster.rs
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#2903 fix: count on inverted index
  src/job/files/parquet.rs
Labels: ☢️ Bug

#2904 fix: spell wrong
  src/job/files/parquet.rs
Labels: ☢️ Bug

#2905 fix: total with limit in sql_mode
  src/service/search/sql.rs
Labels: ☢️ Bug

#2907 fix: changed hits to events and limit count fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#2910 test: add functions testcases
  tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2912 fix: after reset filter records per page not getting reflected
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2911 fix: fast mode field not found
  src/config/src/config.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#2915 fix: cache latest schema
  src/common/infra/config.rs
  src/service/db/schema.rs
Labels: ☢️ Bug, 🧹 Updates

#2917 test: fix logs testcases
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: ☢️ Bug, 🧹 Updates

#2918 test: logs limit testcases
  .github/workflows/ui-testing.yml
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2920 feat: dashboard tutorial button
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#2922 fix: about text
  web/src/views/About.vue
Labels: ☢️ Bug

#2923 fix: fix for delete track_total_flag for sql mode with limit
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2926 fix: debug inverted index
  src/service/compact/merge.rs
Labels: ☢️ Bug

#2928 fix: inverted index count
  src/common/meta/search.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2931 test: inverted index value for queries testcase
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
Labels: 🧹 Updates

#2933 fix: issue #2921
  src/service/db/schema.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
Labels: ☢️ Bug

#2934 fix: debug quick mode
  src/common/meta/organization.rs
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/mod.rs
  src/service/db/alerts/templates.rs
  src/service/db/alerts/triggers.rs
  src/service/db/functions.rs
  src/service/db/kv.rs
  src/service/db/metrics.rs
  src/service/db/ofga.rs
  src/service/db/organization.rs
  src/service/db/schema.rs
  src/service/db/syslog.rs
  src/service/db/user.rs
  src/service/organization.rs
  src/service/schema.rs
  src/service/search/sql.rs
  web/src/components/logstream/schema.vue
  web/src/composables/useStreams.ts
  web/src/locales/languages/en.json
  web/src/views/Functions.vue
  web/src/views/HomeView.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#2942 build: update rust version
  .github/workflows/api-testing.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/ui-testing.yml
  .github/workflows/unit-tests.yml
  coverage.sh
  deploy/build/Dockerfile
  deploy/build/Dockerfile.sccache.aarch64
  deploy/build/Dockerfile.sccache.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/buildspec-test.yml
  rust-toolchain.toml
  src/common/infra/cluster.rs
  src/common/infra/wal.rs
  src/common/meta/alerts/mod.rs
  src/common/meta/middleware_data.rs
  src/common/meta/sql.rs
  src/common/meta/stream.rs
  src/config/src/meta/usage.rs
  src/handler/grpc/auth/mod.rs
  src/handler/grpc/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/db/mod.rs
  src/ingester/src/partition.rs
  src/lib.rs
  src/main.rs
  src/service/db/alerts/triggers.rs
  src/service/db/user.rs
  src/service/ingestion/grpc.rs
  src/service/ingestion/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/promql/common.rs
  src/service/promql/functions/label_replace.rs
  src/service/promql/value.rs
  src/service/schema.rs
  src/service/search/datafusion/date_format_udf.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/match_udf.rs
  src/service/search/datafusion/regexp_udf.rs
  src/service/search/datafusion/time_range_udf.rs
  src/service/search/mod.rs
  src/service/stream.rs
  src/wal/src/writer.rs
  tests/integration_test.rs
Labels: 🧹 Updates

#2930 fix: debug inverted index
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#2906 fix: use sqlparser-rs rewrite count_distinct
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/rewrite.rs
Labels: ☢️ Bug

#2891 chore: fix some typos
  src/infra/src/file_list/dynamo.rs
  src/infra/src/file_list/sqlite.rs
  src/job/files/parquet.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug, 📒 Documentation

#2819 feat: use NATS as cluster coordinator
  .github/workflows/build-pr-image.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/ofga.rs
  src/common/meta/telemetry.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/meta/meta_store.rs
  src/config/src/utils/base64.rs
  src/handler/http/request/status/mod.rs
  src/infra/Cargo.toml
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/nats.rs
  src/infra/src/dist_lock.rs
  src/infra/src/errors/mod.rs
  src/infra/src/file_list/mod.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/job/telemetry.rs
  src/main.rs
  src/router/grpc/ingest/logs.rs
  src/router/grpc/ingest/metrics.rs
  src/router/grpc/ingest/mod.rs
  src/router/grpc/ingest/traces.rs
  src/router/http/mod.rs
  src/service/alerts/alert_manager.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/schema.rs
  src/service/file_list.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/schema.rs
  src/service/search/datafusion/rewrite.rs
  src/service/search/datafusion/string_to_array_v2_udf.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/ingestion_service.rs
  src/service/usage/stats.rs
  src/service/users.rs
Labels: ✏️ Feature

#2950 test: add dashboard testcases run
  tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2946 perf: improve ingester speed
  src/job/files/parquet.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: 🧹 Updates

#2943 fix: stacked area chart color filling issue
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2951 fix: refresh with sql mode on sending duplicate requests
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#2929 fix: On copy prevent conversion of Log column value to JSON strings
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2953 fix: allowed "-" & "_" in saved view name
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2944 fix: search with replay WAL field not found
  Cargo.lock
  Cargo.toml
  src/common/infra/config.rs
  src/common/meta/sql.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/db/mod.rs
  src/ingester/src/errors.rs
  src/ingester/src/wal.rs
  src/main.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  src/service/db/file_list/local.rs
  src/service/db/schema.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, 🧹 Updates

#2952 fix: remove where clause use sqlparser
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
Labels: ☢️ Bug, 🧹 Updates

#2935 feat: introduce cron jobs for alerts
  Cargo.lock
  Cargo.toml
  src/common/meta/alerts/mod.rs
  src/service/alerts/alert_manager.rs
  src/service/alerts/mod.rs
Labels: ✏️ Feature

#2959 fix: remove ZO_FEATURE_FULLTEXT_ON_ALL_FIELDS
  src/config/src/config.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2964 test: added logs and menu testcases
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  tests/ui-testing/cypress/e2e/tests/menu_tests.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2955 fix: cache latest file & cache stream fields
  Cargo.lock
  src/common/infra/cluster.rs
  src/common/infra/config.rs
  src/common/meta/sql.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/main.rs
  src/service/compact/merge.rs
  src/service/db/file_list/local.rs
  src/service/db/schema.rs
  src/service/search/sql.rs
  web/package-lock.json
  web/package.json
  web/src/layouts/MainLayout.vue
  web/src/main.ts
Labels: ☢️ Bug, 🧹 Updates

#2965 feat: add RUM config
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/package-lock.json
  web/package.json
  web/src/layouts/MainLayout.vue
  web/src/main.ts
Labels: ✏️ Feature

#2958 fix: ensure trim and split on different chars
  src/config/src/config.rs
  src/job/files/parquet.rs
  src/service/search/datafusion/string_to_array_v2_udf.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2967 fix: field not found when merging
  src/config/src/config.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2968 fix: allowed "-" & "_" in saved view name
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2970 fix: duplicate request on page refresh while sql mode on
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#2971 fix: stream page loading state
  web/src/components/logstream/schema.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#2972 fix: field not found when merging
  src/config/src/config.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2957 fix: added loading state on stream page
  web/src/components/logstream/schema.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, ✏️ Feature

#2954 fix: dashboard performance improvement
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/panels/GeoMapRenderer.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/vite.config.ts
Labels: ☢️ Bug, 🧹 Updates

#2977 fix: added v-else
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug, ✏️ Feature

#2978 fix: add group by field to select
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/config.rs
  src/main.rs
  src/service/distinct_values.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
Labels: ☢️ Bug, ✏️ Feature

#2981 fix: RUM session and error explorer issues
  web/src/components/rum/AppTable.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#2975 fix: dashboard null and ' ' value for variables dropdown
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#2989 fix: search field not found
  src/common/meta/sql.rs
  src/service/db/file_list/broadcast.rs
Labels: ☢️ Bug

#2987 fix: search field not found
  src/common/meta/sql.rs
  src/service/db/file_list/broadcast.rs
Labels: ☢️ Bug

#2993 fix: root user should have access to everything
  src/handler/http/auth/validator.rs
Labels: ☢️ Bug

#2994 fix: root user should have access to everything
  src/handler/http/auth/validator.rs
Labels: ☢️ Bug

#2990 fix: RUM error explorer UI issues
  web/src/components/logstream/schema.vue
  web/src/components/rum/PlayerEventsSidebar.vue
  web/src/components/rum/performance/ApiDashboard.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#2996 fix: search error with group by
  src/common/meta/sql.rs
  src/service/search/datafusion/rewrite.rs
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug

#2999 fix: search field not found
  src/common/meta/sql.rs
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug

#2997 feat: support add min and max mysql,postgresql,sqlite connection pool size env variables
  src/config/src/config.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
Labels: ✏️ Feature

#2980 fix: show absoulte time with timezone in header for printmode
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#2991 fix: added str_match function in syntax guide and query editor autoco…
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/useSuggestions.ts
  web/src/plugins/logs/QueryEditor.vue
  web/src/plugins/logs/SyntaxGuide.vue
  web/src/plugins/traces/QueryEditor.vue
  web/src/plugins/traces/SyntaxGuide.vue
Labels: ☢️ Bug, ✏️ Feature

#3008 fix: set rum user for non cloud
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#2893 fix: Restrict default search on flag
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3010 fix: set user for rum
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#3006 fix: search field not found
  src/config/src/config.rs
  src/handler/http/request/search/mod.rs
  src/service/distinct_values.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  web/src/composables/useErrorTracking.ts
Labels: ☢️ Bug

#3007 fix: search field not found
  src/config/src/config.rs
  src/handler/http/request/search/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  web/src/composables/useErrorTracking.ts
Labels: ☢️ Bug

#3017 fix: IAM fixes
  web/src/enterprise/components/organizations/Organization.vue
  web/src/enterprise/composables/router.ts
  web/src/enterprise/mixins/mainLayout.mixin.ts
Labels: ☢️ Bug

#3027 fix: Disabled user email field for filtering RUM sessions
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#3032 fix: removed redirection
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, 🧹 Updates

#3035 feat: update datafusion to 36
  Cargo.lock
  Cargo.toml
  src/cli/basic/cli.rs
  src/cli/data/cli.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/search/mod.rs
  src/infra/src/dist_lock.rs
  src/infra/src/file_list/dynamo.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/service/alerts/alert_manager.rs
  src/service/alerts/mod.rs
  src/service/compact/file_list.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/db/file_list/remote.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/prom.rs
  src/service/promql/functions/time_operations.rs
  src/service/search/datafusion/date_format_udf.rs
  src/service/search/datafusion/match_udf.rs
  src/service/search/datafusion/string_to_array_v2_udf.rs
  src/service/search/datafusion/time_range_udf.rs
  src/service/search/datafusion/transform_udf.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: 🧹 Updates, ✏️ Feature

#3036 fix: report user email for values & search around
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#3037 fix: pagination disable on limit query
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#3040 fix: add debug for task panic & etcd lock error
  src/job/files/parquet.rs
  src/service/schema.rs
Labels: ☢️ Bug, ✏️ Feature

#3051 feat: add queue to infra
  Cargo.toml
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/config/src/config.rs
  src/infra/src/db/nats.rs
  src/infra/src/errors/mod.rs
  src/infra/src/lib.rs
  src/infra/src/queue/mod.rs
  src/infra/src/queue/nats.rs
  src/infra/src/queue/nop.rs
  src/service/compact/mod.rs
  src/service/search/datafusion/regexp_udf.rs
  src/service/search/datafusion/transform_udf.rs
Labels: ✏️ Feature

#3053 fix: change in api endpoint
  web/src/services/settings.ts
Labels: ☢️ Bug

#3046 test: added testcase for search queries
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates, ✏️ Feature

#3034 feat: introduce enterprise api for uploading/deleting custom logo
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
Labels: ✏️ Feature

#3026 feat: dashboard table text wrap
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature

#3033 fix: tabs default edit delete
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/settings/TabsDeletePopUp.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#3043 fix: error on blank input in dashboard panel config
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/panels/GeoMapRenderer.vue
  web/src/utils/dashboard/convertMapData.ts
Labels: ☢️ Bug

#3049 fix: fixed event filtering condition in Session Viewer events query
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug

#3052 fix: updated traces duration filter functionality
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
Labels: ☢️ Bug, 🧹 Updates

#3059 fix: enabled metadata streams in streams page
  web/src/components/iam/roles/EditRole.vue
  web/src/composables/useStreams.ts
Labels: ☢️ Bug, ✏️ Feature

#3064 test: added aggregation queries and folders testcase fix
  tests/api-testing/tests/test_search.py
  tests/ui-testing/cypress/e2e/tests/dashboard/folders.cy.js
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#3068 feat: add quick mode fields
  .github/workflows/ui-testing.yml
  proto/cluster/search.proto
  src/cli/data/export.rs
  src/common/meta/search.rs
  src/config/src/config.rs
  src/handler/grpc/mod.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/service/alerts/mod.rs
  src/service/search/sql.rs
  tests/api-testing/tests/test_search.py
  tests/ui-testing/cypress/e2e/tests/logs_fastmode.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ✏️ Feature

#3058 feat: Interesting fields UI changes
  src/common/meta/search.rs
  src/service/search/mod.rs
  tests/ui-testing/cypress/e2e/allfunctions/logs.js
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  web/src/components/DateTime.vue
  web/src/components/settings/General.vue
  web/src/composables/useLogs.ts
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/services/stream.ts
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#3070 test: added drilldown tests
  tests/ui-testing/cypress/e2e/tests/dashboard/drilldown.cy.js
  tests/ui-testing/cypress/support/commons.js
Labels: 🧹 Updates, ✏️ Feature

#3072 fix: minor changes
  web/src/components/settings/General.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#3075 fix: disk cache with s3 bucket prefix
  src/infra/src/cache/file_data/disk.rs
Labels: ☢️ Bug

#3061 fix: url safe encoding.
  src/config/src/utils/base64.rs
  src/service/alerts/mod.rs
  web/src/components/CopyContent.vue
  web/src/components/ingestion/logs/OtelConfig.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/LinuxConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/components/login/Login.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#3079 feat: Quick mode fixes
  web/src/components/settings/General.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, ✏️ Feature

#3082 fix: fixed custom logo spacing issue & add remove interesting field
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#3083 fix: Update IndexList.vue
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug, 🧹 Updates

#3085 fix: deselect all field should replace *
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#3021 fix: schema versions as separate key
  src/cli/basic/cli.rs
  src/common/infra/cluster/nats.rs
  src/common/migration/dashboards.rs
  src/common/migration/meta.rs
  src/common/migration/mod.rs
  src/common/migration/schema.rs
  src/config/src/config.rs
  src/handler/http/auth/validator.rs
  src/infra/src/db/dynamo.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sled.rs
  src/infra/src/db/sqlite.rs
  src/service/compact/merge.rs
  src/service/db/alerts/alert_manager.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/mod.rs
  src/service/db/alerts/templates.rs
  src/service/db/alerts/triggers.rs
  src/service/db/compact/file_list.rs
  src/service/db/compact/files.rs
  src/service/db/compact/organization.rs
  src/service/db/compact/retention.rs
  src/service/db/compact/stats.rs
  src/service/db/dashboards/folders.rs
  src/service/db/dashboards/mod.rs
  src/service/db/functions.rs
  src/service/db/kv.rs
  src/service/db/metrics.rs
  src/service/db/mod.rs
  src/service/db/ofga.rs
  src/service/db/organization.rs
  src/service/db/saved_view.rs
  src/service/db/schema.rs
  src/service/db/syslog.rs
  src/service/db/user.rs
  src/service/db/version.rs
  src/service/search/grpc/storage.rs
  src/service/usage/stats.rs
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3090 feat: add new endpoint for health check
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#3093 fix: added pagination in logs and stream page for schema field list
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  web/src/components/logstream/schema.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug, ✏️ Feature

#3097 feat: add query start_time and end_time for reporting a search query usage
  src/handler/http/request/search/mod.rs
  src/service/promql/search/mod.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#3101 fix: dashboard variable dropdown on typing getting error
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
Labels: ☢️ Bug

#3106 fix: function icon
  web/src/enterprise/mixins/mainLayout.mixin.ts
Labels: ☢️ Bug

#3103 fix: added order by _timestamp desc in logs query
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#3105 fix: Saved views
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#3108 fix: append condition
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3110 feat: schema lock per request per stream
  src/common/meta/ingestion.rs
  src/config/src/config.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ✏️ Feature

#3111 test: Improve secret handling in forks
  .github/workflows/ui-testing.yml
Labels: 🧹 Updates

#3098 feat: Dashboard Reporting UI
  web/package-lock.json
  web/package.json
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/common/sidebar/FieldList.vue
  web/src/components/reports/CreateReport.vue
  web/src/components/reports/ReportList.vue
  web/src/composables/shared/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/services/reports.ts
  web/src/styles/quasar-overrides.scss
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/Dashboards.vue
Labels: ✏️ Feature

#3114 fix: schema settings to be retained
  src/config/src/config.rs
  src/service/db/schema.rs
  src/service/logs/bulk.rs
Labels: ☢️ Bug

#3112 fix: saved view issues
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3115 test: use full name before checking out the repo
  .github/workflows/build-pr-image.yml
Labels: 🧹 Updates

#3117 fix: prod panic debug
  src/job/files/parquet.rs
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#3123 fix: blocked streams
  src/service/logs/bulk.rs
Labels: ☢️ Bug

#3102 feat: frequently check for span element render for dashboard report
  Cargo.lock
  src/service/dashboards/reports.rs
Labels: ✏️ Feature

#3125 feat: add custom hide menu field in the /config
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/dashboards/reports.rs
  web/src/components/reports/CreateReport.vue
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/layouts/MainLayout.vue
  web/src/mixins/mainLayout.mixin.ts
Labels: ✏️ Feature

#3126 fix: stream names with hyphen (-) were not getting parsed correctly
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#3127 fix: schema inference issue
  src/config/src/utils/schema.rs
  src/service/schema.rs
Labels: ☢️ Bug

#3128 fix: schema inference issue
  src/config/src/utils/schema.rs
  src/service/logs/mod.rs
Labels: ☢️ Bug

#3124 test: testcases for quick mode
  .github/workflows/ui-testing.yml
  tests/ui-testing/cypress/e2e/tests/logs_quickmode.cy.js
Labels: 🧹 Updates

#3104 chore: fix some typos
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, 📒 Documentation

#3080 fix: some typos
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, 📒 Documentation
