Repository openobserve/openobserve, pull requests merged in 2024-02, with the labels that each got.

#2624 fix: cache is full, release_size bug
  src/common/infra/cache/file_data/memory.rs
Labels: ☢️ Bug

#2579 feat: Issue 2561
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/services/search.ts
Labels: ✏️ Feature

#2626 fix: deletion streams
  .github/workflows/build-pr-image.yml
  src/service/compact/retention.rs
Labels: ☢️ Bug

#2292 feat: tabs on dashboard
  src/common/meta/dashboards/mod.rs
  src/common/meta/dashboards/v3/mod.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/mod.rs
  web/package-lock.json
  web/package.json
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/settings/SinglePanelMove.vue
  web/src/components/dashboards/settings/TabsDeletePopUp.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/tabs/AddTab.vue
  web/src/components/dashboards/tabs/TabList.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/performance/WebVitalsDashboard.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/plugins/metrics/Index.vue
  web/src/utils/commons.ts
  web/src/utils/dashboard/convertDashboardSchemaVersion.ts
  web/src/views/Dashboards/DashboardSettings.vue
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#2627 fix: RBAC compilation issue
  src/common/meta/user.rs
  src/common/utils/jwt.rs
  src/handler/http/auth/jwt.rs
Labels: ☢️ Bug

#2628 fix: #2619
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/db/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#2630 fix: delete unused logs
  src/service/usage/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#2631 fix: remove unused logs
  src/handler/grpc/request/usage.rs
Labels: ☢️ Bug, 🧹 Updates

#2632 fix: alert name should not contain /
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
Labels: ☢️ Bug

#2634 feat: rbac changes
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/service/db/mod.rs
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/PermissionsTable.vue
  web/src/components/iam/users/enterprise/User.vue
  web/src/locales/languages/en.json
  web/src/services/iam.ts
  web/src/ts/interfaces/iam.ts
  web/src/views/Login.vue
  web/src/views/User.vue
Labels: ✏️ Feature

#2633 fix: Chinese language
  web/src/locales/languages/zh.json
Labels: ☢️ Bug

#2635 fix: Replace src with s_src in SyslogNg.vue
  web/src/components/ingestion/logs/SyslogNg.vue
Labels: ☢️ Bug, 🧹 Updates

#2636 fix: when RBAC is disabled
  src/common/utils/auth.rs
Labels: ☢️ Bug

#2637 fix: fixed IAM routes
  web/src/composables/shared/router.ts
  web/src/composables/shared/useIamRoutes.ts
  web/src/views/IdentityAccessManagement.vue
  web/src/views/User.vue
Labels: ☢️ Bug

#2638 fix: load RBAC store id
  src/job/mod.rs
  src/service/db/mod.rs
Labels: ☢️ Bug

#2640 feat: search queue
  deploy/build/Dockerfile
  deploy/build/Dockerfile.aarch64
  deploy/build/Dockerfile.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  proto/cluster/search.proto
  src/common/meta/search.rs
  src/handler/grpc/mod.rs
  src/handler/http/request/authz/fga.rs
  src/ingester/src/immutable.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#2641 fix: logs search no record partition
  web/src/composables/useLogs.ts
Labels: Invalid PR Title

#2639 fix: increase number of columns for panel grid
  web/src/utils/commons.ts
  web/src/utils/dashboard/convertDashboardSchemaVersion.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#2642 fix: in some case the search request duplicated
  src/service/promql/search/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2644 chore: update dependencies
  Cargo.lock
  Cargo.toml
  deny.toml
  src/handler/http/request/search/mod.rs
  src/service/search/datafusion/exec.rs
Labels: 🤖 Dependencies, 🧹 Updates

#2645 fix: IAM UI fixes
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/organizations/AppOrganizations.vue
  web/src/components/iam/roles/AddRole.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/users/enterprise/User.vue
  web/src/composables/shared/useIamRoutes.ts
  web/src/enterprise/components/organizations/Organization.vue
Labels: ☢️ Bug

#2646 fix: compactor with block org
  src/ingester/src/writer.rs
  src/service/compact/mod.rs
Labels: ☢️ Bug

#2643 fix: add delete for roles & groups
  src/common/utils/auth.rs
  src/common/utils/http.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/service/schema.rs
  src/service/stream.rs
  web/src/components/iam/groups/AppGroups.vue
  web/src/components/iam/roles/AppRoles.vue
  web/src/services/http.ts
  web/src/services/iam.ts
Labels: ☢️ Bug, ✏️ Feature

#2651 test: logs to stream navigation testcases
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2654 refactor: optimize traces write
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug, 🧹 Updates

#2652 test: updated locators for alerts
  tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2659 fix: ReBAC issues
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/saved_view.rs
  web/src/composables/useLogs.ts
  web/src/services/search.ts
Labels: ☢️ Bug

#2655 fix: IAM ui issues
  web/src/components/AppTable.vue
  web/src/components/iam/groups/AppGroups.vue
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/groups/GroupList.vue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/organizations/AppOrganizations.vue
  web/src/components/iam/organizations/ListOrganizations.vue
  web/src/components/iam/roles/AppRoles.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/EntityPermissionTable.vue
  web/src/components/iam/roles/PermissionSelector.vue
  web/src/components/iam/roles/PermissionsTable.vue
  web/src/components/iam/roles/permissions.ts
  web/src/components/iam/users/enterprise/User.vue
  web/src/composables/shared/useIamRoutes.ts
  web/src/layouts/MainLayout.vue
  web/src/views/IdentityAccessManagement.vue
  web/src/views/User.vue
Labels: ☢️ Bug

#2661 fix: schema chk
  src/common/infra/config.rs
  src/common/meta/telemetry.rs
  src/common/migration/file_list.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/job/metrics.rs
  src/service/compact/file_list.rs
  src/service/compact/mod.rs
  src/service/compact/stats.rs
  src/service/db/file_list/remote.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/functions.rs
  src/service/ingestion/mod.rs
  src/service/schema.rs
  src/service/stream.rs
  src/service/usage/stats.rs
Labels: Invalid PR Title, ☢️ Bug

#2663 fix: RBAC bug fixes
  src/common/meta/user.rs
  src/common/utils/auth.rs
Labels: ☢️ Bug

#2611 feat: dashboard widget with custom HTML
  src/common/meta/dashboards/v3/mod.rs
  web/package-lock.json
  web/package.json
  web/src/assets/images/dashboard/charts/HTML.png
  web/src/assets/images/dashboard/charts/Markdown.svg
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/CustomHTMLEditor.vue
  web/src/components/dashboards/addPanel/CustomMarkdownEditor.vue
  web/src/components/dashboards/addPanel/MonacoHTMLEditor.vue
  web/src/components/dashboards/addPanel/MonacoMarkdownEditor.vue
  web/src/components/dashboards/panels/HTMLRenderer.vue
  web/src/components/dashboards/panels/MarkdownRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#2666 fix: sql mode partition fix
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#2667 feat: Login UI Revamp
  web/src/assets/images/common/sso.svg
  web/src/components/login/Login.vue
  web/src/components/login/SsoLogin.vue
  web/src/services/http.ts
  web/src/services/httpsearch.ts
  web/src/utils/zincutils.ts
  web/src/views/Login.vue
Labels: ✏️ Feature

#2668 chore: refactor rbac code
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/job/mod.rs
Labels: 🧹 Updates

#2672 fix: Fixed IAM users functionality
  src/service/users.rs
  web/src/components/RouteTabs.vue
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/users/User.vue
  web/src/components/login/Login.vue
  web/src/locales/languages/en.json
  web/src/ts/interfaces/iam.ts
  web/src/views/IdentityAccessManagement.vue
  web/src/views/User.vue
Labels: ☢️ Bug, ✏️ Feature

#2675 fix: added the missing org_id before creating the sql
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#2673 fix: dashboard geolocation issue
  web/src/utils/dashboard/convertMapData.ts
Labels: ☢️ Bug

#2664 feat: compactor supports lock on stream level
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster.rs
  src/common/meta/stream.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/ider.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/hash/default.rs
  src/config/src/utils/hash/fnv.rs
  src/config/src/utils/hash/mod.rs
  src/config/src/utils/schema_ext.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/search/mod.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/storage/remote.rs
  src/ingester/src/immutable.rs
  src/job/compact.rs
  src/job/files/json.rs
  src/job/files/parquet.rs
  src/lib.rs
  src/service/alerts/alert_manager.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/compact/files.rs
  src/service/db/compact/retention.rs
  src/service/db/file_list/local.rs
  src/service/db/file_list/mod.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/file_list.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/promql/search/grpc/storage.rs
  src/service/schema.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/stream.rs
  src/service/usage/stats.rs
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#2677 fix: need delete merged files from ingester cache db
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster.rs
  src/common/meta/stream.rs
  src/config/Cargo.toml
  src/config/src/utils/hash/cityhash.rs
  src/config/src/utils/hash/fnv.rs
  src/config/src/utils/hash/gxhash.rs
  src/config/src/utils/hash/mod.rs
  src/config/src/utils/hash/murmur3.rs
  src/handler/grpc/request/event.rs
  src/infra/src/errors/mod.rs
  src/service/compact/file_list.rs
  src/service/compact/stats.rs
  src/service/db/file_list/broadcast.rs
  src/wal/src/writer.rs
Labels: ☢️ Bug

#2679 fix: 0.8.1-rc1 build issue
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/utils/schema_ext.rs
Labels: ☢️ Bug

#2680 fix: remove xxhash
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/utils/schema_ext.rs
  src/ingester/src/wal.rs
Labels: ☢️ Bug, 🧹 Updates

#2683 fix: support native users in rbac
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/common/utils/jwt.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/stream.rs
  src/service/users.rs
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/users/AddUser.vue
  web/src/components/iam/users/User.vue
  web/src/components/login/Login.vue
  web/src/services/users.ts
  web/src/ts/interfaces/iam.ts
  web/src/views/IdentityAccessManagement.vue
  web/src/views/User.vue
Labels: ☢️ Bug

#2687 fix: search around error when order by _timestamp asc
  src/handler/http/auth/token.rs
  src/service/search/datafusion/exec.rs
  src/service/users.rs
Labels: ☢️ Bug

#2686 fix: disable internal login
  src/common/utils/auth.rs
  src/handler/http/request/status/mod.rs
  web/src/components/login/Login.vue
Labels: ☢️ Bug

#2688 fix: router panic
  src/router/http/mod.rs
Labels: ☢️ Bug

#2690 fix: fixed IAM Permissions issue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/views/IdentityAccessManagement.vue
Labels: ☢️ Bug

#2689 fix: search around error when order by _timestamp asc
  src/handler/http/request/search/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#2692 fix: IAM UI fixes
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/iam/groups/AddGroup.vue
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/roles/AddRole.vue
  web/src/components/iam/roles/EditRole.vue
Labels: ☢️ Bug

#2695 fix: ofga large number of streams
  src/common/infra/mod.rs
  src/common/infra/ofga.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/ofga.rs
Labels: ☢️ Bug

#2696 fix: added IAM roles test ids
  web/src/components/common/AppTabs.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/PermissionsTable.vue
Labels: ☢️ Bug, 🧹 Updates

#2703 fix: wrong notification on dashboard error
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/AddFolder.vue
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/components/dashboards/tabs/AddTab.vue
  web/src/utils/commons.ts
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/ImportDashboard.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#2700 fix: dynamic filter icon
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
  web/src/components/icons/DynamicFilterIcon.vue
Labels: ☢️ Bug

#2705 fix: during compaction in single node mode, the uuids were different
  src/common/infra/cluster.rs
Labels: ☢️ Bug

#2678 feat: Sankey chart
  src/common/meta/dashboards/v3/mod.rs
  web/src/assets/images/dashboard/charts/sankey.svg
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertSankeyData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#2708 perf: improve traces ingestion
  Cargo.lock
  Cargo.toml
  src/common/infra/config.rs
  src/common/infra/mod.rs
  src/common/meta/stream.rs
  src/handler/grpc/request/search.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/storage/remote.rs
  src/main.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug, 🧹 Updates

#2713 fix: pagination sorting issue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#2715 fix: added missing test id's in IAM
  web/src/components/iam/groups/AddGroup.vue
  web/src/components/iam/groups/AppGroups.vue
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/roles/AddRole.vue
  web/src/components/iam/roles/AppRoles.vue
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2718 fix: fixed editing non aggregated alerts
  web/src/components/alerts/ScheduledAlert.vue
Labels: ☢️ Bug

#2719 feat: add freqency for alert API
  src/handler/http/request/alerts/mod.rs
  src/ingester/src/entry.rs
  src/ingester/src/immutable.rs
  src/ingester/src/memtable.rs
  src/ingester/src/partition.rs
  src/ingester/src/stream.rs
  src/service/alerts/mod.rs
Labels: ✏️ Feature

#2720 fix: added frequency input in alerts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#2721 fix: chart type switching with sankey
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#2724 fix: templates & destination permissions
  src/common/utils/auth.rs
Labels: ☢️ Bug

#2723 fix: fixed filtering on stream resources in IAM
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/PermissionsTable.vue
  web/src/ts/interfaces/iam.ts
Labels: ☢️ Bug

#2729 fix: pagination unwanted call
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#2732 fix: map group claim to role
  src/common/meta/user.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#2734 perf: cache latest files
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/infra/src/cache/file_data/mod.rs
Labels: 🧹 Updates

#2735 fix: added dashboard id in column
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug, ✏️ Feature

#2736 fix: generate password
  src/service/users.rs
Labels: ☢️ Bug

#2738 fix(alert): support sql mode in alert_url
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#2739 feat: unit for dashboard table chart
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature

#2741 fix: set node online again
  src/common/infra/cluster.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/router/http/mod.rs
Labels: ☢️ Bug

#2660 feat: dashboard drilldown to another dashboard
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/Drilldown.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: testing, ✏️ Feature

#2744 fix: _value API with query_context
  src/common/infra/cluster.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/handler/http/request/search/mod.rs
  src/job/file_list.rs
  src/job/files/mod.rs
  src/main.rs
  src/service/db/file_list/broadcast.rs
Labels: ☢️ Bug

#2726 fix: capture payment detail
  web/src/locales/languages/en.json
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#2745 fix: dashboard permissions issue
  src/common/utils/auth.rs
Labels: ☢️ Bug

#2743 fix: performance improvement
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, 🧹 Updates

#2742 feat: IAM adding permissions in JSON format
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/PermissionsJSON.vue
Labels: ✏️ Feature

#2752 perf: improve per thread lock
  src/config/src/config.rs
  src/ingester/src/entry.rs
  src/ingester/src/memtable.rs
  src/ingester/src/partition.rs
  src/ingester/src/stream.rs
  src/ingester/src/writer.rs
  src/main.rs
  src/service/alerts/mod.rs
Labels: 🧹 Updates

#2753 fix: create file logs for ingester
  src/ingester/src/writer.rs
Labels: ☢️ Bug, ✏️ Feature

#2748 fix: streams optimization
  web/src/components/alerts/AddAlert.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
  web/src/components/functions/AssociatedStreamFunction.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/add.vue
  web/src/components/iam/organizations/ListOrganizations.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/login/Login.vue
  web/src/components/logstream/schema.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/iam/usePermissions.ts
  web/src/composables/useLoading.ts
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/enterprise/components/login/Login.vue
  web/src/enterprise/components/organizations/Organization.vue
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/layouts/MainLayout.vue
  web/src/mixins/mainLayout.mixin.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/metrics/MetricList.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/services/stream.ts
  web/src/stores/index.ts
  web/src/utils/common.ts
  web/src/utils/zincutils.ts
  web/src/views/HomeView.vue
  web/src/views/LogStream.vue
  web/src/views/Login.vue
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/RealUserMonitoring.vue
Labels: ☢️ Bug

#2756 fix: dashboard streams not loaded when switched between chart types like HTML and Markdown
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug

#2599 fix: RUM UI fixes
  web/package-lock.json
  web/package.json
  web/src/components/AppTable.vue
  web/src/components/common/sidebar/FieldList.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/rum/VideoPlayer.vue
  web/src/components/rum/performance/ApiDashboard.vue
  web/src/components/rum/performance/ErrorsDashboard.vue
  web/src/components/rum/performance/PerformanceSummary.vue
  web/src/components/rum/sessionReplay/SessionLocationColumn.vue
  web/src/plugins/traces/Index.vue
  web/src/utils/rum/api.json
  web/src/utils/rum/errors.json
  web/src/utils/rum/overview.json
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/RealUserMonitoring.vue
  web/src/views/RUM/SessionViewer.vue
Labels: ☢️ Bug, 🧹 Updates

#2757 fix: on chart type change stream field list rendering issue in add panel
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug, ✏️ Feature

#2758 fix: refresh stats adding streams on list
  web/src/views/LogStream.vue
Labels: ☢️ Bug, ✏️ Feature

#2761 fix: unit test issue
  coverage.sh
  src/common/infra/cluster.rs
Labels: ☢️ Bug, 🧹 Updates

#2522 fix: dashboard maps filters
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertMapData.ts
Labels: ☢️ Bug

#2763 fix: dashboard drilldown url creation issue for new tab
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#2764 perf: improve enrichmentTable
  src/common/infra/mod.rs
  src/config/src/config.rs
  src/service/db/schema.rs
  src/service/search/mod.rs
Labels: 🧹 Updates

#2768 fix: RBAC get all streams issues
  web/src/composables/useStreams.ts
Labels: ☢️ Bug

#2769 feat: add an option to enable bloom filter on all fields
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#2766 fix: on folder delete show correct error message
  web/src/utils/commons.ts
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug

#2770 fix: rewrite count(distinct(field)) to three phase to get correct result
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#2781 fix: dashboard geomap initial saved panels size
  web/src/utils/dashboard/convertMapData.ts
Labels: ☢️ Bug

#2783 fix: dashboard tooltip and drilldown issue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#2778 feat: Updated stream creation and stream settings
  src/common/utils/http.rs
  src/config/src/meta/stream.rs
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/StreamFieldInputs.vue
  web/src/components/logstream/schema.vue
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchResult.vue
  web/src/views/LogStream.vue
Labels: 🧹 Updates, ✏️ Feature

#2785 fix: list should return only allowed objects
  Cargo.lock
  src/common/utils/auth.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/dashboards/folders.rs
  src/handler/http/request/functions/mod.rs
  src/handler/http/request/stream/mod.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  src/service/dashboards/folders.rs
  src/service/db/functions.rs
  src/service/functions.rs
  src/service/organization.rs
  src/service/stream.rs
Labels: ☢️ Bug

#2786 fix: can't create same name alerts
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  src/service/db/alerts/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#2791 fix: histogram fix
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2795 fix: Search around logs page
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: Invalid PR Title

#2798 fix: watchers to read from db
  .vscode/launch.json
  Cargo.lock
  src/infra/src/db/dynamo.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/mod.rs
  src/service/db/alerts/templates.rs
  src/service/db/alerts/triggers.rs
  src/service/db/functions.rs
  src/service/db/metrics.rs
  src/service/db/ofga.rs
  src/service/db/organization.rs
  src/service/db/schema.rs
Labels: ☢️ Bug

#2797 fix: fixed issues in add and update streams
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/schema.vue
  web/src/composables/useStreams.ts
  web/src/views/LogStream.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2802 fix: organization change not loads stream data
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#2803 fix: change ZO_RESTRICTED_ROUTES_ON_EMPTY_DATA default to false
  src/config/src/config.rs
Labels: ☢️ Bug

#2806 fix: organization change not refresh the page data
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#2808 fix: streams filtering
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#2809 test: removed stream settings testcase
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2810 feat: introduce SMTP env configurations
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/config.rs
Labels: ✏️ Feature, 📒 Documentation

#2811 perf: add a new configure to enable infer schema in datafusion
  src/config/src/config.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#2794 perf: Imporve ingester speed
  src/service/logs/mod.rs
  src/service/schema.rs
Labels: ☢️ Bug

#2816 feat: merge setting fields and default fields
  src/config/src/utils/parquet.rs
  src/ingester/src/partition.rs
  src/job/files/json.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#2817 fix: issue 2793
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
Labels: ☢️ Bug

#2821 feat: inverted index v1
  src/common/infra/wal.rs
  src/common/utils/http.rs
  src/common/utils/record_batch_parquet_ext.rs
  src/config/src/config.rs
  src/infra/src/storage/mod.rs
  src/job/compact.rs
  src/job/files/idx.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/lib.rs
  src/main.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/ingestion/index_writer.rs
  src/service/ingestion/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/useSuggestions.ts
  web/src/plugins/logs/QueryEditor.vue
Labels: ✏️ Feature

#2818 fix: Improve Korean translations
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/ko.json
Labels: ☢️ Bug, 🧹 Updates

#2823 fix: change value length for meta in MySQL
  src/infra/src/db/mysql.rs
Labels: ☢️ Bug

#2830 fix: change the placeholders
  web/src/enterprise/components/billings/paymentCard.vue
  web/src/enterprise/components/billings/paymentMethods.vue
  web/src/enterprise/components/billings/plans.vue
Labels: ☢️ Bug

#2824 fix: Incorrect logs displayed on switching sql mode on and off & fixe…
  web/src/components/rum/SearchBar.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug
