Repository openobserve/openobserve, pull requests merged in 2024-07, with the labels that each got.

#3863 test: api-search-tests
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates

#3867 fix: if function_error is not found getting errors
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug

#3868 chore: add trace id to cache logs
  src/handler/grpc/request/query_cache.rs
  src/handler/http/request/search/mod.rs
  src/proto/proto/cluster/querycache.proto
  src/service/search/cache/cacher.rs
  src/service/search/cluster/cacher.rs
Labels: ☢️ Bug, ✏️ Feature

#3865 feat: original size and compressed size unit in query management
  web/src/components/queries/QueryList.vue
Labels: ☢️ Bug, ✏️ Feature

#3871 fix: inverted index search on longest token of all terms
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3869 fix:cache only histogram aggregate query
  src/service/search/cache/cacher.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#3875 fix: query management size units initial value unit is in mb not bytes
  web/src/components/queries/QueryList.vue
Labels: ☢️ Bug

#3876 fix: schema read lock
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#3718 chore: added tailwind css
  web/package-lock.json
  web/package.json
  web/postcss.config.js
  web/src/main.ts
  web/src/styles/tailwind.css
  web/tailwind.config.js
Labels: ✏️ Feature

#3881 fix: nats reconnection
  src/infra/src/db/etcd.rs
  src/infra/src/db/nats.rs
Labels: ☢️ Bug

#3878 feat: add `time_wait_in_queue` in search usage reporting
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#3767 feat: dashboard breakdown fields
  src/common/meta/dashboards/mod.rs
  src/common/meta/dashboards/v4/mod.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/mod.rs
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertDashboardSchemaVersion.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#3872 fix: added traces ids support in search requests
  src/common/utils/http.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/mod.rs
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/services/search.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature

#3888 fix: promql selector regex pattern wrongly escaped
  src/service/promql/engine.rs
Labels: ☢️ Bug

#3887 fix: query cache remove hits
  src/config/src/meta/search.rs
  src/handler/grpc/request/query_cache.rs
  src/handler/http/request/search/mod.rs
  src/proto/proto/cluster/querycache.proto
  src/service/search/cache/cacher.rs
  src/service/search/cache/result_utils.rs
  src/service/search/cluster/cacher.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, 🧹 Updates

#3890 fix: sort record batches when persist to parquet
  Cargo.lock
  src/common/meta/dashboards/v4/mod.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/utils/record_batch_ext.rs
  src/ingester/Cargo.toml
  src/ingester/src/errors.rs
  src/ingester/src/partition.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#3894 fix: dashboard breakdown fields issues
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#3886 feat: dashboard message toast added cancel button
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/AddFolder.vue
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/components/dashboards/tabs/AddTab.vue
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useNotifications.ts
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/ImportDashboard.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#3885 fix: logs time period in url was getting changed on refreshing page
  tests/ui-testing/playwright-tests/schema.spec.js
  web/src/composables/useLogs.ts
  web/src/main.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/styles/tailwind.css
Labels: ☢️ Bug

#3873 feat: auto enable user-defined schema
  src/config/src/config.rs
  src/service/schema.rs
Labels: ✏️ Feature

#3899 chore: improve message
  web/src/components/queries/RunningQueriesList.vue
Labels: 🧹 Updates

#3900 fix: openai schema
  src/config/src/meta/search.rs
  src/handler/http/router/openapi.rs
Labels: ☢️ Bug

#3829 feat: schema check per req for all logs ingestion APIs
  src/cli/data/import.rs
  src/common/meta/ingestion.rs
  src/common/meta/stream.rs
  src/config/src/meta/usage.rs
  src/handler/grpc/request/usage.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/rum/ingest.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  src/service/usage/ingestion_service.rs
Labels: ✏️ Feature

#3893 feat: add metrics for query lifetime
  src/config/src/metrics.rs
  src/handler/grpc/request/search/intra_cluster.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/errors/mod.rs
  src/service/metrics/prom.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#3841 fix: include org_id in list_objects for rbac
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
Labels: ☢️ Bug

#3902 fix: error while using arrow_cast with percentile function
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#3903 fix: Added more meaningful error messages
  tests/ui-testing/playwright-tests/logspage.spec.js
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, ✏️ Feature

#3908 fix: pending query metrics
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3909 fix: cancel query for super cluster
  src/config/src/meta/sql.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/job.rs
  src/proto/proto/cluster/search.proto
  src/service/search/mod.rs
Labels: ☢️ Bug

#3731 feat: dashboard folder UI changes
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/views/Dashboards/Dashboards.vue
Labels: ✏️ Feature

#3914 fix: dark theme issue on role and group and logs page along with name…
  web/src/components/iam/groups/AddGroup.vue
  web/src/components/iam/roles/AddRole.vue
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#3915 fix: inverted index search
  src/service/search/sql.rs
Labels: ☢️ Bug

#3913 fix: extra path was added in cancel, need only org
  src/handler/http/request/search/job.rs
Labels: ☢️ Bug, ✏️ Feature

#3916 fix: trace's span name
  src/common/utils/http.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#3917 fix: unnecessary null field during compaction
  .github/workflows/unit-tests.yml
  rust-toolchain.toml
  src/config/src/utils/record_batch_ext.rs
  src/config/src/utils/schema_ext.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#3922 feat: ugprade rust to 2024-07-07
  .github/workflows/api-testing.yml
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/playwright.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  Cargo.lock
  Cargo.toml
  deploy/build/Dockerfile
  deploy/build/Dockerfile.sccache.aarch64
  deploy/build/Dockerfile.sccache.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/buildspec-test.yml
  rust-toolchain.toml
  src/infra/src/db/etcd.rs
  src/infra/src/db/nats.rs
  src/infra/src/queue/nats.rs
  src/infra/src/schema/mod.rs
  src/service/compact/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/promql/mod.rs
  src/service/search/cluster/mod.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/stream.rs
Labels: ✏️ Feature

#3895 fix: query result cache v2
  Cargo.lock
  src/common/meta/search.rs
  src/common/utils/http.rs
  src/handler/grpc/request/query_cache.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/meta.rs
  src/proto/proto/cluster/querycache.proto
  src/service/search/cache/cacher.rs
  src/service/search/cluster/cacher.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#3928 fix: inverted index can't get result when the min_timestamp mismatch
  src/common/infra/wal.rs
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/parquet.rs
  src/job/mod.rs
  src/service/compact/merge.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/wal.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#3911 fix: when adding existing user to another org, given role should be correct
  src/common/utils/auth.rs
  src/handler/http/request/users/mod.rs
  src/service/users.rs
Labels: ☢️ Bug, ✏️ Feature

#3926 fix: histogram time to match partition time range
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3933 fix: added plus sign for getcount call & removed duplicate call from …
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#3930 feat: parallelize the tests
  .github/workflows/playwright.yml
Labels: 🧹 Updates, ✏️ Feature

#3937 fix: avoid otlp tracing being split into parts
  src/handler/grpc/request/search/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/cluster/cacher.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#3946 fix: query with inverted index
  src/config/src/config.rs
  src/config/src/utils/json.rs
  src/config/src/utils/record_batch_ext.rs
  src/service/logs/mod.rs
  src/service/search/cluster/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#3905 fix: enable rbac for index streams
  src/common/utils/auth.rs
  src/handler/http/request/stream/mod.rs
  web/src/components/iam/roles/EditRole.vue
Labels: ☢️ Bug

#3948 fix: use _timestamp in TriggerData for triggers usage
  src/config/src/meta/usage.rs
  src/service/alerts/alert_manager.rs
  src/service/ingestion/mod.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3949 fix: invalid peer certificate: UnknownIssuer for report traces
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/service/promql/functions/math_operations.rs
  src/service/promql/functions/time_operations.rs
  src/service/promql/name_visitor.rs
Labels: ☢️ Bug

#3943 chore: debug query result cache issue
  src/service/search/cache/cacher.rs
  src/service/search/cluster/cacher.rs
Labels: ☢️ Bug

#3951 ci: remove mimalloc on windows
  .github/workflows/release.yml
Labels: 🧹 Updates

#3952 fix: cancel all internal trace_ids
  src/handler/grpc/request/search/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#3955 fix: schema version filter for query
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/service/db/schema.rs
Labels: ☢️ Bug

#3959 fix: Index stream rbac migration
  src/common/infra/ofga.rs
  src/job/files/parquet.rs
Labels: ☢️ Bug

#3961 fix: delete wal file when stream already deleted
  src/job/files/parquet.rs
  web/src/locales/languages/en.json
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#3960 feat: role-group based node selection
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/proto/proto/cluster/search.proto
  src/service/search/cache/mod.rs
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#3643 fix: sql function change with syntax guide
  src/service/search/datafusion/udf/mod.rs
  tests/ui-testing/cypress/e2e/tests/logs_fastmode.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  tests/ui-testing/playwright-tests/indexquery.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  web/src/components/HighLight.vue
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/useSuggestions.ts
  web/src/plugins/logs/SyntaxGuide.vue
  web/src/plugins/metrics/SyntaxGuideMetrics.vue
  web/src/plugins/traces/SyntaxGuide.vue
  web/src/test/unit/helpers/setupTests.ts
  web/src/test/unit/helpers/store.ts
Labels: ☢️ Bug

#3962 feat: add short vs long query in query manager
  src/config/src/meta/search.rs
  src/handler/grpc/request/search/mod.rs
  src/proto/proto/cluster/search.proto
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#3963 feat: Introduce otel grpc endpoint to export traces
  src/config/src/config.rs
  src/main.rs
Labels: ☢️ Bug, ✏️ Feature

#3923 feat: cron feature on alert page
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/locales/languages/en.json
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#3964 fix: inverted index search with fast mode
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3968 ci: bump datafusion to 40
  Cargo.lock
  Cargo.toml
Labels: 🤖 Dependencies

#3967 fix: inverted index fast mode
  src/service/file_list.rs
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3969 fix: inverted index query
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3529 feat: visualization for logs page
  tests/ui-testing/playwright-tests/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/reports.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  tests/ui-testing/playwright-tests/variable.spec.js
  web/src/components/QueryEditor.vue
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/SelectDashboardDropdown.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/components/dashboards/SelectTabDropdown.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/Drilldown.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/addPanel/QueryTypeSelector.vue
  web/src/components/dashboards/addPanel/SortByBtnGrp.vue
  web/src/components/dashboards/settings/SinglePanelMove.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/tabs/AddTab.vue
  web/src/components/dashboards/tabs/TabList.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/plugins/metrics/Index.vue
  web/src/utils/query/sqlUtils.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#3972 fix: Add PRIMARY KEY constraint to tables in postgres
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/postgres.rs
Labels: Invalid PR Title, ✏️ Feature

#3974 fix: log result cache ratio to usage & delta scan size
  src/config/src/meta/usage.rs
  src/service/search/cache/mod.rs
  src/service/usage/mod.rs
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3978 fix: consistent hashing with querier group
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/meta/telemetry.rs
  src/config/src/cluster.rs
  src/config/src/lib.rs
  src/config/src/meta/cluster.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/status/mod.rs
  src/job/alert_manager.rs
  src/job/compactor.rs
  src/job/file_list.rs
  src/job/files/mod.rs
  src/job/flatten_compactor.rs
  src/job/metrics.rs
  src/job/mod.rs
  src/job/prom.rs
  src/job/stats.rs
  src/main.rs
  src/router/http/mod.rs
  src/service/compact/file_list.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/compact/files.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/metrics.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/file_list.rs
  src/service/ingestion/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/cacher.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  src/service/usage/stats.rs
Labels: ☢️ Bug

#3982 fix: rate calculate
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#3983 fix: result cache histogram issue
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#3986 feat: support swagger enable open
  src/config/src/config.rs
  src/handler/http/router/mod.rs
Labels: ✏️ Feature

#3985 feat: add CPU limit for work group
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#3989 fix: optimize default setting for single node
  src/config/src/config.rs
Labels: ☢️ Bug

#3991 chore: add result stats to status api
  src/handler/http/request/status/mod.rs
  src/infra/src/cache/file_data/disk.rs
Labels: Invalid PR Title, ✏️ Feature

#3970 feat: Routing support for all ingestion APIs
  src/handler/grpc/request/search/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
Labels: ✏️ Feature

#3787 feat: add span metrics for traces
  Cargo.toml
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/handler/grpc/request/traces.rs
  src/job/metrics.rs
  src/job/mod.rs
  src/main.rs
  src/service/exporter/mod.rs
  src/service/exporter/otlp_o2_metrics_exporter.rs
  src/service/mod.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3992 fix: ScanSize label
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3993 fix: visualization stream selection issue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#3999 fix: enable cache by default & scan size lable issue
  src/config/src/config.rs
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3997 feat: use cache for value API
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/sql.rs
  src/handler/http/request/search/mod.rs
  src/infra/Cargo.toml
  src/infra/src/cache/file_data/disk.rs
  src/job/metrics.rs
  src/service/search/cache/cacher.rs
  src/service/search/cluster/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  tests/ui-testing/playwright-tests/logspage.spec.js
Labels: ✏️ Feature

#4002 fix: visualization css issues
  web/src/components/dashboards/SelectDashboardDropdown.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/components/dashboards/SelectTabDropdown.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/plugins/metrics/AddToDashboard.vue
Labels: ☢️ Bug

#4004 fix: result cache panic when there is no _timestamp
  src/service/search/cache/result_utils.rs
Labels: ☢️ Bug

#4006 test: e2e quick mode without timestamp
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  web/src/components/ingestion/traces/OpenTelemetry.vue
Labels: 🧹 Updates

#4005 fix: rate calculate for count
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
Labels: ☢️ Bug

#4009 fix: search partition with order by time asc
  Cargo.lock
  Cargo.toml
  src/config/src/meta/search.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/search.proto
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#3998 fix: Logs page histogram api duplicate call
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4013 feat: value API without count
  src/handler/http/request/search/mod.rs
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4014 test: assert records to be unique
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates

#4015 fix: default web url and correct report server endpoint
  src/config/src/config.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug

#4017 fix: caching issue
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4019 fix: cache historical log records
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4020 fix: remove count of value from values api
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/composables/useDashboardPanel.ts
  web/src/services/stream.ts
Labels: ☢️ Bug, 🧹 Updates

#4016 fix: #4008 fixed string selection in sql mode
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#4027 Fix: package version
  web/package-lock.json
  web/package.json
Labels: Invalid PR Title, ☢️ Bug, 🧹 Updates

#4030 fix: Separate runtime for grpc server
  src/config/src/config.rs
  src/main.rs
Labels: ☢️ Bug

#4032 feat: clean nats locks
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/common/migration/schema.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/nats.rs
  src/infra/src/dist_lock.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/search/cluster/mod.rs
  src/service/usage/stats.rs
Labels: ✏️ Feature

#4034 fix: new thread for grpc runtime to avoid nested runtime error
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/common/migration/schema.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/nats.rs
  src/infra/src/dist_lock.rs
  src/main.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/search/cluster/mod.rs
  src/service/usage/stats.rs
Labels: ☢️ Bug

#4035 feat: add multiple tokio runtime
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/ofga.rs
  src/config/src/config.rs
  src/infra/src/dist_lock.rs
  src/main.rs
  src/service/usage/stats.rs
Labels: ✏️ Feature

#4029 fix: 4021 logs page additional error information
  web/package-lock.json
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug, ✏️ Feature

#4001 feat: add `apply_before_flattening` option to function StreamOrder
  src/common/meta/functions.rs
  src/service/functions.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  web/src/components/functions/AssociatedStreamFunction.vue
Labels: testing, In Progress, ✏️ Feature

#4037 fix: additional error handling
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#4044 fix: Page count request failed will display error user will be able t…
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#4047 fix: #4046 undefined trace id while changing stream while currently a…
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4045 fix: #4042 fixed an Error on removing wrong stream and entering correct stream
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#4049 fix: cacher panic for json deserialisation
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#4022 feat: vrl function support for dashboard
  src/common/meta/dashboards/v4/mod.rs
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/panels/GeoMapRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#4050 fix: count error when limit 0
  src/service/search/sql.rs
Labels: ☢️ Bug

#4052 fix: get querier node panic
  Cargo.toml
  src/service/search/cluster/cacher.rs
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#4054 fix: alerts attrs created but not saved
  src/service/alerts/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4057 fix: stream list issue for visualization page
  web/src/components/dashboards/addPanel/QueryTypeSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#4058 feat: apply vrl functions over hits as array
  src/service/search/cluster/http.rs
  src/service/search/cluster/super_cluster.rs
Labels: ✏️ Feature

#4062 fix: caching to consider query fn when caching
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4063 fix: panic when the parentSpanId is null
  src/config/src/utils/json.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#4065 fix:result caching issue
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4066 fix: dashboard table chart migration issue
  web/src/utils/dashboard/convertDashboardSchemaVersion.ts
Labels: ☢️ Bug

#4069 fix: alert query duration
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/PreviewAlert.vue
Labels: ☢️ Bug

#4074 fix:clean in memory cache references
  src/infra/src/cache/file_data/disk.rs
Labels: ☢️ Bug

#4068 fix: panic when the ip_address is invalid
  src/common/meta/middleware_data.rs
Labels: ☢️ Bug, ✏️ Feature

#4076 fix: added wrong _timestamp with distinct
  src/service/search/cache/result_utils.rs
Labels: ☢️ Bug, ✏️ Feature

#4078 fix: remove ZO_BLOOM_FILTER_ON_ALL_FIELDS
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
Labels: ☢️ Bug, 🧹 Updates

#4081 fix: return single partition if this is an aggregation query
  src/service/search/mod.rs
Labels: ☢️ Bug

#4082 feat: predefined function support for dashboard
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/composables/useDashboardPanel.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#4088 feat: add median support for aggregation
  src/common/meta/alerts/mod.rs
  src/common/meta/dashboards/v1/mod.rs
  src/common/meta/dashboards/v2/mod.rs
  src/common/meta/dashboards/v3/mod.rs
  src/common/meta/dashboards/v4/mod.rs
  src/service/alerts/mod.rs
  src/service/search/cache/result_utils.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#4089 feat: remove sql_mode, query_context and aggs from search API
  coverage.sh
  src/cli/data/export.rs
  src/config/src/meta/search.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/sql.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/proto/proto/cluster/search.proto
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/result_utils.rs
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/stats.rs
  tests/api-testing/tests/test_logs.py
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates, ✏️ Feature

#4039 fix: Reduced vertical spacing between and in the folders of the dashboard
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug

#4040 fix: #3975 fixed incorrect logs count showing on query search at first
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4023 fix: #3630 solved cmd + enter issue
  web/package-lock.json
  web/package.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#4070 fix: no preview message for SQL mode
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/PreviewAlert.vue
Labels: ☢️ Bug

#4095 fix: logs page histogram resize issue while toggle from visualize to logs
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug
