Repository openobserve/openobserve, pull requests merged in 2024-10, with the labels that each got.

#4670 fix: fixed unlimited calls when going back and forth
  web/src/plugins/logs/SearchHistory.vue
Labels: ☢️ Bug

#4672 fix: make trigger.data optional for serde
  src/infra/src/scheduler/mod.rs
Labels: ☢️ Bug

#3976 feat: SMTP support in alert destinations
  src/common/meta/alerts/templates.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/alerts/DestinationList.vue
  web/src/components/alerts/TemplateList.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/ts/interfaces/alert.ts
Labels: ✏️ Feature

#4674 fix: partition data order issue with desc in the query
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#4680 fix: when frequency and period are not same, involve the delay for alert timerange
  src/service/alerts/scheduler.rs
Labels: ☢️ Bug

#4673 fix: search history should not contain the search related to usage org
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  web/src/plugins/logs/SearchHistory.vue
Labels: ☢️ Bug

#4683 fix: validate response for dashboard query with vrl
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#4678 fix: fixed ingestion links style
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/plugins/logs/SyntaxGuide.vue
  web/src/plugins/metrics/SyntaxGuideMetrics.vue
  web/src/plugins/traces/SyntaxGuide.vue
  web/src/views/About.vue
  web/src/views/Dashboards/ScheduledDashboards.vue
Labels: ☢️ Bug

#4686 fix: fixed sorting functionality in search history
  web/src/plugins/logs/SearchHistory.vue
  web/src/services/search.ts
Labels: ☢️ Bug

#4685 fix: search partition
  src/service/search/mod.rs
Labels: ☢️ Bug

#4693 feat: remove user_email field from the search history response
  src/config/src/meta/search.rs
Labels: Invalid PR Title, 🧹 Updates

#4694 fix: Updated Search History
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchHistory.vue
  web/src/services/search.ts
Labels: ☢️ Bug, 🧹 Updates

#4700 fix: Updated Search History (#4694)
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchHistory.vue
  web/src/services/search.ts
Labels: ☢️ Bug, 🧹 Updates

#4701 fix: search partition with seconds
  src/service/search/mod.rs
Labels: ☢️ Bug

#4702 fix: Add more fields to SearchHistoryHitResponse for search history and reuse it
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  web/src/plugins/logs/SearchHistory.vue
Labels: ☢️ Bug

#4704 test: unflattened testcases
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/unflattened.spec.js
Labels: 🧹 Updates

#4705 fix: search partition with max_query_range
  src/service/search/mod.rs
Labels: ☢️ Bug

#4699 feat: support for seconds in query time range date-time selector
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  web/src/components/CustomDateTimePicker.vue
  web/src/components/DateTime.vue
  web/src/utils/date.ts
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#4710 fix: handle db pool timeout issue by releasing lock in case of an issue
  src/infra/src/db/mysql.rs
  src/infra/src/file_list/mysql.rs
Labels: ☢️ Bug

#4713 feat: enforce at least 4 DB connections
  src/config/src/config.rs
Labels: ✏️ Feature

#4687 feat: hash check when updating dashboards
  src/common/meta/dashboards/mod.rs
  src/handler/http/request/dashboards/mod.rs
  src/service/dashboards/mod.rs
  src/service/db/dashboards/mod.rs
  tests/api-testing/tests/test_folders.py
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/components/dashboards/tabs/AddTab.vue
  web/src/composables/useNotifications.ts
  web/src/plugins/metrics/AddToDashboard.vue
  web/src/services/dashboards.ts
  web/src/stores/index.ts
  web/src/utils/commons.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#4676 feat: add metrics for db realated requests
  src/config/src/metrics.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/service/file_list.rs
Labels: ✏️ Feature

#4708 feat: multi historical timerange evaluation for sql based alerts
  src/common/meta/alerts/mod.rs
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler.rs
  src/service/ingestion/mod.rs
  src/service/search/mod.rs
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/ScheduledAlert.vue
Labels: ✏️ Feature

#4716 feat: add db metrics
  src/config/src/metrics.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
Labels: ✏️ Feature

#4719 feat: multi historical timerange evaluation for sql based alerts (#4708)
  src/common/meta/alerts/mod.rs
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler.rs
  src/service/ingestion/mod.rs
  src/service/search/mod.rs
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/ScheduledAlert.vue
Labels: ✏️ Feature

#4720 fix: removed index on original_url for short_url service
  src/handler/http/router/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/infra/src/short_url/mysql.rs
  src/infra/src/short_url/postgres.rs
  src/infra/src/short_url/sqlite.rs
Labels: ☢️ Bug, 🧹 Updates

#4665 fix: histogram partition error
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4727 fix: dashboard hash undefined issue
  web/src/utils/commons.ts
Labels: ☢️ Bug

#4730 fix: short_url post to include org_id for enterprise
  src/handler/http/request/short_url/mod.rs
Labels: ☢️ Bug

#4729 fix: issue #4721
  web/src/enterprise/components/login/Login.vue
  web/src/utils/common.ts
Labels: ☢️ Bug

#4731 fix: short_url post to include org_id in path
  src/handler/http/request/short_url/mod.rs
Labels: ☢️ Bug

#4737 Revert "feat: use one trace_id for all query in query cache"
  src/cli/data/export.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/usage/stats.rs
Labels: Invalid PR Title, ☢️ Bug, ✏️ Feature

#4736 test: vrl error message validation fix
  tests/ui-testing/playwright-tests/logspage.spec.js
Labels: ☢️ Bug, 🧹 Updates

#4728 fix: issue #4723 shorten url on logs page
  web/src/enterprise/components/login/Login.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/router/index.ts
  web/src/services/short_url.ts
  web/src/utils/common.ts
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Login.vue
Labels: ☢️ Bug

#4746 test: e2e logs search history
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#4750 fix: short_url auth, redirect to `/web` if auth fails
  src/common/utils/mod.rs
  src/common/utils/redirect_response.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/short_url/mod.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#4754 fix: short_url auth, redirect to `/web` if auth fails (#4750)
  src/common/utils/mod.rs
  src/common/utils/redirect_response.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/short_url/mod.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#4756 refactor: construct_short_url helper
  src/service/short_url.rs
Labels: 🧹 Updates

#4758 feat: redirect response builder with query params & handle `Result` for AuthExtractor in oo_validator
  src/common/utils/redirect_response.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/short_url/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4762 fix: upgrade dependencies
  Cargo.lock
  Cargo.toml
Labels: 🤖 Dependencies, ☢️ Bug

#4763 fix: invalid short url redirect
  src/handler/http/request/short_url/mod.rs
Labels: ☢️ Bug

#4596 feat: value mapping for dashboard table chart
  src/common/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/ValueMapping.vue
  web/src/components/dashboards/addPanel/ValueMappingPopUp.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature

#4764 fix: `shorten` api error handling
  src/handler/http/request/short_url/mod.rs
Labels: ☢️ Bug

#4709 feat: add prefix based paritioning for index
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/request/metrics/querier.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/ingester/src/immutable.rs
  src/ingester/src/writer.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/file_list.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug, ✏️ Feature

#4320 feat: Accept CloudWatch streams OTLP output format to allow CloudWatch metrics ingestion
  src/service/logs/ingest.rs
  web/src/components/ingestion/metrics/CloudWatchMetrics.vue
Labels: ✏️ Feature

#4771 fix: query start with work group
  src/handler/grpc/request/search/mod.rs
  src/service/search/cluster/mod.rs
  src/service/search/grpc/mod.rs
Labels: ☢️ Bug

#4773 fix: Short url fixes
  src/common/utils/auth.rs
  src/common/utils/redirect_response.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/short_url/mod.rs
  src/handler/http/router/mod.rs
  src/service/alerts/alert.rs
  src/service/dashboards/reports.rs
  src/service/short_url.rs
  web/src/router/index.ts
Labels: ☢️ Bug

#4772 fix: query start with work group
  src/handler/grpc/request/search/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/mod.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#4775 feat: add option for control min datafusion partition
  src/config/src/config.rs
  src/handler/grpc/request/search/mod.rs
  src/service/logs/ingest.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#4776 fix:caching changes
  src/common/meta/ingestion.rs
  src/config/src/config.rs
  src/config/src/meta/usage.rs
  src/config/src/utils/json.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#4778 feat: support partital result if some node return error
  src/config/src/meta/search.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/utlis.rs
Labels: ✏️ Feature

#4642 fix: traces UI fixes
  web/src/composables/useTraces.ts
  web/src/locales/languages/en.json
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/SpanDetails.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/utils/query/sqlUtils.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#4796 fix: do not use unwrap panic when parsing to SqlValue from Value::Number float
  src/config/src/meta/sql.rs
Labels: ☢️ Bug

#4789 fix: increase file field size in file_list* tables
  src/infra/src/db/mysql.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
Labels: ☢️ Bug

#4785 fix: optimize nats watcher
  src/config/src/config.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/nats.rs
  src/service/compact/retention.rs
  src/service/metrics/prom.rs
Labels: ☢️ Bug

#4791 feat: add new ENV for control logo
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/job/compactor.rs
  src/service/compact/file_list_deleted.rs
  src/service/search/cache/mod.rs
  web/src/components/login/Login.vue
  web/src/layouts/MainLayout.vue
Labels: ✏️ Feature

#4800 fix: improve delay deletion
  src/config/src/config.rs
  src/service/compact/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4784 feat: add short and long to usage report
  src/common/utils/http.rs
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#4801 feat: add reload config for ent
  src/common/infra/ofga.rs
  src/common/migration/schema.rs
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/clusters/mod.rs
  src/handler/http/request/search/job.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
  src/job/alert_manager.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/scheduler.rs
  src/service/db/schema.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/usage/mod.rs
  src/service/users.rs
Labels: ✏️ Feature

#4802 fix: Ensure Vector Performs External Health Check for OpenObserve
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#4745 fix: Dashboard chart UI issues
  tests/ui-testing/playwright-tests/visualize.spec.js
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#4808 fix: join and subquery with cache
  src/config/src/utils/sql.rs
Labels: ☢️ Bug

#4816 fix: short_url schema
  src/infra/src/short_url/mod.rs
  src/infra/src/short_url/mysql.rs
  src/infra/src/short_url/postgres.rs
  src/infra/src/short_url/sqlite.rs
  src/service/db/short_url.rs
Labels: ☢️ Bug

#4817 fix: select star for _original
  src/service/search/mod.rs
Labels: ☢️ Bug

#4818 fix: select star for _original
  src/service/search/sql.rs
Labels: ☢️ Bug

#4755 feat: add VEX file with vulnerabilities information to SBOM
  openobserve.cdx.xml.vex.json
Labels: Invalid PR Title, ✏️ Feature

#4247 feat: Amazon SNS Support for alert destinations
  Cargo.lock
  Cargo.toml
  src/common/meta/alerts/destinations.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#4827 feat: add short and long query to usage reported
  src/common/utils/http.rs
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#4813 fix: UI freezes on enabling histogram
  web/src/components/iam/roles/EntityPermissionTable.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4831 feat: sync data retention for index stream
  src/handler/http/request/stream/mod.rs
Labels: ✏️ Feature

#4833 feat: use approximation for partitioning
  src/config/src/meta/stream.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/mod.rs
  src/service/stream.rs
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#4811 fix: added additional function error in case of no record found. It w…
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#4824 feat: Alerts support SNS destination
  Cargo.lock
  Cargo.toml
  src/common/meta/alerts/destinations.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#4840 feat: bring per_thread_lock back
  src/cli/data/import.rs
  src/config/src/config.rs
  src/handler/grpc/request/ingest.rs
  src/handler/grpc/request/logs.rs
  src/handler/grpc/request/usage.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/rum/ingest.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/main.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature

#4804 fix: moved restore URL params before api calls
  tests/ui-testing/playwright-tests/unflattened.spec.js
  web/src/components/DateTime.vue
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4782 fix: #4752 issue selecting same timestamp for every query
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchHistory.vue
Labels: ☢️ Bug

#4843 fix: custom logo issues
  web/src/components/settings/General.vue
Labels: ☢️ Bug

#4842 fix: On cancel query undefined error shown on UI
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4849 fix: update cert-manager
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ☢️ Bug, 🧹 Updates

#4853 feat: improve wal file lock processing
  src/common/infra/wal.rs
  src/job/files/parquet.rs
Labels: 🧹 Updates, ✏️ Feature

#4856 fix: Fixed logic to restore logs expanded rows on run query
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4857 fix: add _timestamp to sql when we can
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#4864 fix: search history seconds precision issue fixed #4863
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4861 fix: Prefix partition fix
  web/src/components/logstream/schema.vue
  web/src/components/settings/General.vue
Labels: ☢️ Bug

#4866 fix: vertical layout on about us page.
  web/src/views/About.vue
Labels: ☢️ Bug

#4841 fix: include exxclude search based on data type
  web/src/composables/useLogs.ts
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
Labels: ☢️ Bug

#4770 fix: E2e seconds precision updated
  .github/workflows/playwright.yml
  tests/ui-testing/pages/CommonLocator.js
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/reportsPage.js
  tests/ui-testing/pages/tracesPage.js
  tests/ui-testing/playwright-tests/secondsPrecisionAdded.spec.js
Labels: ☢️ Bug, 🧹 Updates

#4874 fix: add prefix partition in add stream section
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/StreamFieldInputs.vue
Labels: ☢️ Bug, ✏️ Feature

#4846 fix: rename menu label
  web/src/locales/languages/de.json
  web/src/locales/languages/en.json
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/locales/languages/it.json
  web/src/locales/languages/ja.json
  web/src/locales/languages/ko.json
  web/src/locales/languages/nl.json
  web/src/locales/languages/pt.json
  web/src/locales/languages/tr.json
  web/src/locales/languages/zh.json
Labels: ☢️ Bug

#4751 feat: O2 node sql parser implemetation
  web/package-lock.json
  web/package.json
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useLogs.ts
  web/src/composables/useParser.ts
  web/src/locales/languages/es.json
  web/src/locales/languages/fr.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/utils/query/sqlUtils.ts
Labels: ✏️ Feature

#4867 fix: can't query data in the case with multiple memtable buckets
  Cargo.lock
  src/common/infra/wal.rs
  src/common/meta/alerts/derived_streams.rs
  src/common/meta/stream.rs
  src/config/Cargo.toml
  src/config/src/meta/stream.rs
  src/config/src/utils/schema.rs
  src/handler/grpc/request/metrics/querier.rs
  src/handler/http/request/pipelines.rs
  src/handler/http/request/stream/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/ingester/src/immutable.rs
  src/ingester/src/memtable.rs
  src/ingester/src/partition.rs
  src/ingester/src/stream.rs
  src/ingester/src/writer.rs
  src/job/file_list.rs
  src/service/alerts/alert.rs
  src/service/alerts/mod.rs
  src/service/db/file_list/local.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/pipelines.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#4879 fix: Add new ENV to decide whether to pause alert after retrying for `ZO_SCHEDULER_MAX_RETRIES`
  src/config/src/config.rs
  src/service/alerts/scheduler.rs
Labels: ☢️ Bug, ✏️ Feature

#4828 fix: cases where _original/_o2_id missing when user defined schema
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/schema.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#4880 perf: improve `format_key` that is heavily used to flatten json
  src/config/src/utils/flatten.rs
Labels: 🧹 Updates

#4812 fix: skip alert if the delay is big
  src/common/meta/alerts/mod.rs
  src/config/src/config.rs
  src/config/src/meta/usage.rs
  src/config/src/utils/rand.rs
  src/service/alerts/scheduler.rs
  src/service/db/scheduler.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#4826 fix: Reduced streams page table vertical padding
  web/src/plugins/logs/TenstackTable.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, ✏️ Feature

#4882 fix: set span status message
  src/service/traces/mod.rs
Labels: ☢️ Bug

#4902 test:Updated logs
  tests/ui-testing/playwright-tests/secondsPrecisionAdded.spec.js
Labels: 🧹 Updates

#4905 test: add unflattened testcase and POM
  tests/ui-testing/cypress/e2e/allfunctions/logs.js
  tests/ui-testing/cypress/e2e/allfunctions/menufunctions.js
  tests/ui-testing/cypress/e2e/dashboard/AddDashboard.cy.js
  tests/ui-testing/cypress/e2e/dashboard/Dashboard.cy.js
  tests/ui-testing/cypress/e2e/dashboard/EditDashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/drilldown.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/edit_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/folders.cy.js
  tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_fastmode.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_queries.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_quickmode.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/menu_tests.cy.js
  tests/ui-testing/pages/unflattened.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
Labels: 🧹 Updates, ✏️ Feature

#4886 fix: trim before and after space in query editor and vrl function
  web/src/components/QueryEditor.vue
  web/src/components/alerts/AddAlert.vue
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#4900 fix: After maximum alert retries, skip to the next run of the alert
  src/common/meta/alerts/mod.rs
  src/config/src/config.rs
  src/config/src/meta/usage.rs
  src/config/src/utils/rand.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/job/alert_manager.rs
  src/service/alerts/scheduler.rs
  src/service/db/scheduler.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#4910 test: join queries testcases
  tests/api-testing/tests/test_joinqueries.py
Labels: 🧹 Updates

#4911 fix: after alert is retried max time, skip to next trigger time
  src/config/src/config.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/job/alert_manager.rs
  src/service/alerts/scheduler.rs
Labels: ☢️ Bug

#4912 chore: add search type to query manager
  src/config/src/meta/search.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#4888 fix: when updating organization settings only consider the updated value
  src/common/meta/organization.rs
  src/handler/http/request/organization/settings.rs
Labels: ☢️ Bug, 🧹 Updates

#4916 fix: bugs of v0.13.0-rc1
  Cargo.lock
  Cargo.toml
  src/common/meta/organization.rs
  src/common/meta/stream.rs
  src/common/meta/telemetry.rs
  src/common/migration/schema.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/meta/sql.rs
  src/config/src/meta/stream.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/stats.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/service/compact/merge.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/organization.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#4901 feat: use stream stats for partitioning api
  src/config/src/meta/stream.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/mod.rs
  tests/ui-testing/playwright-tests/visualize.spec.js
  web/package-lock.json
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#4917 fix: Old stream schema and editor value was shown on selecting metrics stream
  web/src/plugins/metrics/MetricList.vue
Labels: ☢️ Bug

#4830 feat: added new options for histogram intervals
  web/src/components/dashboards/addPanel/HistogramIntervalDropDown.vue
Labels: ✏️ Feature

#4926 fix: change some print to logs
  Cargo.lock
  Cargo.toml
  src/infra/src/db/sqlite.rs
  src/job/files/idx.rs
Labels: ☢️ Bug

#4928 fix: #4927
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/job/files/parquet.rs
Labels: ☢️ Bug

#4869 feat: if print mode hide unnecessary empty space
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ✏️ Feature

#4617 feat: Dashboard Config Option
  src/common/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/icons/dashboards/LinearIcon.vue
  web/src/components/icons/dashboards/NoSymbol.vue
  web/src/components/icons/dashboards/Smooth.vue
  web/src/components/icons/dashboards/StepAfter.vue
  web/src/components/icons/dashboards/StepBefore.vue
  web/src/components/icons/dashboards/StepMiddle.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#4761 feat: implement job for ingesting self-metrics
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/prom_json_encoder.rs
  src/handler/grpc/request/ingest.rs
  src/job/mod.rs
  src/job/prom_self_consume.rs
Labels: ✏️ Feature

#4798 feat: dashboard table override
  src/common/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/OverrideConfigPopup.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/OverrideConfig.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature

#4877 feat: Stream name to be available as Dashboard variable
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#4945 fix: add db operation related traces
  src/infra/src/db/etcd.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/infra/src/schema/history/sqlite.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#4941 fix:#4937
  web/src/locales/languages/zh.json
Labels: ☢️ Bug

#4929 test: add alert integration tests regarding scheduler
  src/common/utils/redirect_response.rs
  src/config/src/meta/search.rs
  src/service/db/alerts/alert.rs
  tests/integration_test.rs
Labels: 🧹 Updates, ✏️ Feature

#4943 fix: dashboard compare against issue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#4950 fix: remove trace from match_source
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, 🧹 Updates

#4948 fix: unit test for join order
  src/common/meta/dashboards/v5/mod.rs
  src/service/search/datafusion/optimizer/join_reorder.rs
Labels: ☢️ Bug, 🧹 Updates

#4774 feat: color palette for dashboard chart
  src/common/meta/dashboards/v5/mod.rs
  web/package-lock.json
  web/package.json
  web/src/components/dashboards/addPanel/ColorPaletteDropDown.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/colorPalette.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#4903 feat: add logs and metrics for ingestion errors
  src/common/meta/organization.rs
  src/config/src/meta/usage.rs
  src/config/src/metrics.rs
  src/handler/http/request/organization/settings.rs
  src/service/db/organization.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/schema.rs
  src/service/usage/mod.rs
  src/service/usage/stats.rs
  web/src/components/settings/OrganizationSettings.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#4951 chore: don't ignore cargo test failure in unit tests ci
  coverage.sh
Labels: 🧹 Updates

#4931 test: clone alert
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/alerts/AlertList.vue
Labels: 🧹 Updates

#4957 feat: added Logstash data source in logs
  web/src/assets/images/ingestion/logstash.svg
  web/src/components/ingestion/logs/Index.vue
  web/src/components/ingestion/logs/LogstashDatasource.vue
  web/src/composables/shared/useIngestionRoutes.ts
Labels: ✏️ Feature

#4952 feat: add jobs for compact old data
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/utils/time.rs
  src/handler/http/auth/validator.rs
  src/handler/http/router/mod.rs
  src/infra/src/errors/grpc.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/compactor.rs
  src/job/files/parquet.rs
  src/service/alerts/scheduler.rs
  src/service/compact/file_list.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/db/compact/retention.rs
  src/service/db/file_list/remote.rs
  src/service/file_list.rs
Labels: ✏️ Feature

#4958 fix: parquet move_files split prefix to more columns for prefix_date
  src/job/files/parquet.rs
Labels: ☢️ Bug

#4949 feat: channel-based usage queue for async usage reporting
  src/config/src/config.rs
  src/job/stats.rs
  src/service/usage/mod.rs
  src/service/usage/stats.rs
Labels: ✏️ Feature

#4940 fix: issue #4935
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4962 fix: prefix partition key with inverted index
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/request/ingest.rs
  src/handler/grpc/request/logs.rs
  src/handler/grpc/request/metrics/ingester.rs
  src/handler/grpc/request/traces.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#4934 feat: SearchEventContext for search usage reports
  src/cli/data/export.rs
  src/common/utils/http.rs
  src/config/src/meta/search.rs
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/openapi.rs
  src/report_server/src/report.rs
  src/report_server/src/router.rs
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler.rs
  src/service/dashboards/reports.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/usage/mod.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/services/search.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature
