Repository openobserve/openobserve, pull requests merged in 2024-04, with the labels that each got.

#3132 chore: update native login & openapi specs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/openapi.rs
Labels: 🧹 Updates

#3135 fix: only alert_manager should init the scheduler
  src/infra/src/lib.rs
  src/infra/src/scheduler/mod.rs
  src/job/alert_manager.rs
Labels: ☢️ Bug

#3137 fix: On sharing URL link, by default 1st tab was getting selected
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#3141 chore: code refactor
  src/config/src/utils/parquet.rs
  src/ingester/src/partition.rs
Labels: 🧹 Updates

#3142 fix: try with workflow-dispatch event
  .github/workflows/build-pr-image.yml
Labels: ☢️ Bug

#3107 feat: use database lock replace etcd lock
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster/mod.rs
  src/common/infra/config.rs
  src/common/migration/meta.rs
  src/common/migration/mod.rs
  src/common/migration/schema.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/meta_store.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/hash/gxhash.rs
  src/config/src/utils/hash/mod.rs
  src/handler/http/request/status/mod.rs
  src/infra/Cargo.toml
  src/infra/src/cache/tmpfs.rs
  src/infra/src/db/dynamo.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sled.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/file_list/dynamo.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/ingester/src/partition.rs
  src/ingester/src/wal.rs
  src/ingester/src/writer.rs
  src/job/compact.rs
  src/job/files/parquet.rs
  src/job/telemetry.rs
  src/main.rs
  src/router/grpc/ingest/logs.rs
  src/router/grpc/ingest/metrics.rs
  src/router/grpc/ingest/mod.rs
  src/router/grpc/ingest/traces.rs
  src/router/http/mod.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/stats.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/schema.rs
  src/service/file_list.rs
  src/service/ingestion/mod.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/schema.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/stream.rs
  src/service/usage/ingestion_service.rs
Labels: 🧹 Updates, ✏️ Feature

#3145 test: disable recording of tests
  .github/workflows/ui-testing.yml
Labels: 🧹 Updates

#3140 fix: query contains full-width characters encounter error
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#3020 feat: add file cache gc
  src/config/src/config.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/distinct_values.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#3134 fix: save report if both report_user_name and report_user_password envs are non-empty
  src/service/dashboards/reports.rs
Labels: ☢️ Bug

#3147 fix: use latest specific commit for chromiumoxide
  Cargo.lock
  Cargo.toml
Labels: ☢️ Bug, 🧹 Updates

#3138 fix: IAM resource type permissions
  Cargo.lock
  src/common/utils/auth.rs
  web/packages/rrweb-player/public/index.html
  web/src/components/iam/roles/EditRole.vue
Labels: ☢️ Bug

#3149 fix: add some check for move file to s3
  Cargo.lock
  src/ingester/src/immutable.rs
  src/job/files/parquet.rs
Labels: ☢️ Bug, ✏️ Feature

#3118 fix: csp unsafe-eval fixes
  web/package-lock.json
  web/package.json
  web/serve.json
  web/src/components/login/Login.vue
  web/src/components/rum/VideoPlayer.vue
  web/src/layouts/MainLayout.vue
  web/src/views/StreamExplorer.vue
  web/vite.config.ts
Labels: ☢️ Bug

#3095 feat: improve trace
  src/main.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/mod.rs
  src/service/promql/aggregations/mod.rs
  src/service/promql/binaries/mod.rs
  src/service/promql/functions/mod.rs
  src/service/promql/mod.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#3151 fix: accept the precision loss prevention of js on time_unix_nano
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#3155 fix: use get_lock for mysql
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/infra/Cargo.toml
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/errors/mod.rs
  src/lib.rs
  src/main.rs
  src/service/db/mod.rs
  src/service/db/schema.rs
  src/service/file_list.rs
  src/service/functions.rs
  src/service/kv.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/mod.rs
  src/service/mod.rs
  src/service/organization.rs
  src/service/promql/aggregations/mod.rs
  src/service/promql/binaries/mod.rs
  src/service/promql/binaries/scalar_operations.rs
  src/service/promql/binaries/vector_operations.rs
  src/service/promql/functions/mod.rs
  src/service/promql/mod.rs
  src/service/schema.rs
  src/service/stream.rs
Labels: ☢️ Bug

#3162 perf: Search parquet on ingester no need load into memory
  src/config/src/utils/parquet.rs
  src/infra/src/storage/mod.rs
  src/job/files/parquet.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/mod.rs
  src/service/search/datafusion/storage/wal.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates

#3167 fix: Sanitized HTML Rendered with v-html
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
  web/src/views/MemberSubscription.vue
Labels: ☢️ Bug

#3166 fix: print better error message with NATS server address for which failed to connect
  src/infra/src/db/nats.rs
Labels: ☢️ Bug, ✏️ Feature

#3165 feat: add auth cookie max age to 30 days
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  web/src/services/http.ts
Labels: ✏️ Feature

#3164 fix: missing module date-fns. Fixes #2709
  web/package.json
Labels: ☢️ Bug

#3170 fix: node cache status
  src/handler/http/request/status/mod.rs
  src/service/db/schema.rs
Labels: ☢️ Bug

#3158 feat: publish usage report to external url
  src/config/src/config.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#3175 fix: add tokio console
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: ☢️ Bug, ✏️ Feature

#3181 fix: use tokio::select to replace timeout
  src/service/metadata/distinct_values.rs
  src/service/metadata/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#3183 ci: Profiling CPU for OpenObserve
  Cargo.lock
  Cargo.toml
  deploy/build/Dockerfile.profiling.amd64
  deploy/build/buildspec-profiling.yml
  src/config/src/config.rs
  src/main.rs
Labels: ☢️ Bug, 🧹 Updates

#3184 fix: wal on windows
  src/ingester/src/wal.rs
Labels: ☢️ Bug

#3186 refactor: separate search structure to config crate
  Cargo.lock
  Cargo.toml
  src/cli/basic/cli.rs
  src/cli/data/export.rs
  src/cli/data/import.rs
  src/cli/data/mod.rs
  src/common/meta/mod.rs
  src/common/meta/stream.rs
  src/config/Cargo.toml
  src/config/src/meta/mod.rs
  src/config/src/meta/search.rs
  src/config/src/meta/sql.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/mod.rs
  src/handler/grpc/request/traces.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/openapi.rs
  src/proto/src/lib.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/file_list.rs
  src/service/metrics/prom.rs
  src/service/promql/exec.rs
  src/service/promql/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
  src/service/usage/stats.rs
Labels: 🧹 Updates

#3187 fix: traces metadata write error
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/utils/base64.rs
  src/config/src/utils/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/users/mod.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/nats.rs
  src/service/alerts/mod.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#3191 fix: trace details share link was not working
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug

#3193 fix: use async walkdir
  Cargo.lock
  Cargo.toml
  src/common/migration/schema.rs
  src/config/Cargo.toml
  src/config/src/utils/file.rs
  src/handler/grpc/request/metrics/querier.rs
  src/infra/src/cache/file_data/disk.rs
  src/ingester/Cargo.toml
  src/ingester/src/wal.rs
  src/job/file_list.rs
  src/job/files/json.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/job/mod.rs
  src/service/db/file_list/local.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#3194 chore: add debug for schema versions
  src/service/schema.rs
Labels: ☢️ Bug, ✏️ Feature

#3197 feat: add SBOM
  README.md
  openobserve.cdx.xml
  src/config/config.cdx.xml
  src/infra/infra.cdx.xml
  src/ingester/ingester.cdx.xml
  src/proto/proto.cdx.xml
  src/wal/wal.cdx.xml
Labels: ✏️ Feature, 📒 Documentation

#3195 fix: cookies implementation
  web/src/composables/shared/router.ts
  web/src/enterprise/components/login/Login.vue
  web/src/enterprise/composables/router.ts
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/layouts/MainLayout.vue
  web/src/router/index.ts
Labels: ☢️ Bug, ✏️ Feature

#3200 fix: unwanted code
  web/package-lock.json
  web/package.json
  web/src/components/D3Chart.vue
  web/src/layouts/MainLayout.vue
  web/src/main.ts
  web/src/plugins/traces/TraceDetails.vue
  web/src/services/segment_analytics.ts
  web/src/test/__mocks__/index.ts
  web/src/test/__mocks__/open-replay-tracker.ts
  web/vite.config.ts
Labels: ☢️ Bug

#3201 perf: optimise ingester functions
  src/common/migration/dashboards.rs
  src/common/migration/file_list.rs
  src/common/migration/meta.rs
  src/common/migration/mod.rs
  src/common/migration/schema.rs
  src/config/src/config.rs
  src/config/src/utils/asynchronism/file.rs
  src/config/src/utils/file.rs
  src/infra/src/db/nats.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/job/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3205 fix: debug cluster id
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
Labels: ☢️ Bug

#3206 fix: modify cancel query status code to 429
  src/handler/http/request/search/job.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
Labels: ☢️ Bug

#3204 feat: replace `sessiond_id` to `trace_id` when enable tracing
  src/common/meta/http.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/handler/grpc/mod.rs
  src/handler/grpc/request/search.rs
  src/handler/http/request/search/job.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/job/files/parquet.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/search.proto
  src/service/alerts/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3208 fix: parquet file job should be concurrent
  src/config/src/utils/file.rs
  src/handler/grpc/request/metrics/querier.rs
  src/ingester/src/wal.rs
  src/job/file_list.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/service/db/file_list/local.rs
  src/service/schema.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#3022 feat: cascading variables for dashboard
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/components/dashboards/settings/VariablesDependenciesGraph.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/dashboard/useCustomDebouncer.ts
  web/src/utils/dashboard/variables/variablesDependencyUtils.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ✏️ Feature

#3212 fix: add logout endpoint
  src/handler/http/router/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3213 fix: parquet job panic when the file not exist
  src/common/meta/dashboards/v3/mod.rs
  src/job/files/parquet.rs
Labels: ☢️ Bug

#3039 feat: super cluster
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/handler/grpc/request/search.rs
  src/handler/http/auth/validator.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/queue/mod.rs
  src/infra/src/queue/nats.rs
  src/job/alert_manager.rs
  src/job/files/parquet.rs
  src/main.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/search.proto
  src/service/db/compact/stats.rs
  src/service/db/mod.rs
  src/service/db/ofga.rs
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#3218 perf: improve ingestion load and flatten
  src/config/src/config.rs
  src/config/src/utils/flatten.rs
  src/job/files/parquet.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
Labels: ✏️ Feature

#3223 fix: Login issue fix
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/utils/zincutils.ts
Labels: Invalid PR Title, ☢️ Bug

#3225 fix: trace get_file_list
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3210 fix: ensure that rum proxy endpoint uses cookies
  src/handler/http/auth/validator.rs
  web/src/components/rum/VideoPlayer.vue
  web/src/workers/rumcssworker.js
Labels: ☢️ Bug

#3224 fix: update check for schema flow
  src/config/src/utils/schema_ext.rs
Labels: ☢️ Bug, 🧹 Updates

#3226 feat: complete super cluster
  src/cli/data/export.rs
  src/common/infra/config.rs
  src/common/infra/ofga.rs
  src/common/meta/stream.rs
  src/common/meta/telemetry.rs
  src/config/src/meta/search.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/request/event.rs
  src/handler/grpc/request/search.rs
  src/handler/http/request/clusters/mod.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/lib.rs
  src/infra/src/schema/mod.rs
  src/job/files/parquet.rs
  src/service/alerts/mod.rs
  src/service/compact/file_list.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/db/enrichment_table.rs
  src/service/db/mod.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/schema.rs
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  src/service/usage/stats.rs
Labels: ✏️ Feature

#3227 fix: search on wal got error `parquet not found`
  src/common/infra/config.rs
  src/common/infra/wal.rs
  src/config/src/config.rs
  src/infra/src/db/nats.rs
Labels: ☢️ Bug

#3229 fix: create dir panic
  src/infra/src/cache/file_data/disk.rs
Labels: ☢️ Bug, ✏️ Feature

#3228 fix: login page image
  web/src/components/login/Login.vue
Labels: ☢️ Bug

#3237 fix: #3190
  src/common/infra/cluster/mod.rs
Labels: ☢️ Bug

#3239 fix: openAPI spec
  src/handler/http/router/openapi.rs
Labels: ☢️ Bug

#3238 fix: inverted index search not work when search term wrapped around special chars
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3242 feat: upgrade opentelemetry-proto to 0.5, and a little code refactoring
  Cargo.lock
  Cargo.toml
  src/common/infra/wal.rs
Labels: 🧹 Updates, ✏️ Feature

#3243 fix: version compare
  Cargo.lock
  Cargo.toml
  src/common/infra/wal.rs
  src/common/migration/mod.rs
  src/proto/Cargo.toml
Labels: ☢️ Bug

#3247 fix: token issue for different provider
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#3230 feat: only enable tracing in search
  src/config/src/config.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/main.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#3245 fix: dashboard view panel scroll issue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#3231 perf: improve merge parquet speed when fields too many
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
Labels: 🧹 Updates

#3244 fix: cookies issue for SSO
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/router/http/mod.rs
  web/src/services/http.ts
  web/src/utils/zincutils.ts
  web/src/views/Login.vue
Labels: ☢️ Bug

#3255 fix: flush usage report data when server is stopped
  src/main.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3211 feat: add audit trails for enterprise version
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/dashboards/folders.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/dashboards/reports.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#3257 fix: excluded iam route
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#3256 fix: dashboard query inspector time based on its time zone
  web/src/components/dashboards/QueryInspector.vue
Labels: ☢️ Bug

#3259 fix: add order by field to select when need
  src/handler/http/request/dashboards/folders.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/rewrite.rs
Labels: ☢️ Bug, ✏️ Feature

#3219 chore: fix some typos in comments
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug, 📒 Documentation

#3260 fix: improve default list of split characters
  src/config/src/config.rs
Labels: ☢️ Bug, 🧹 Updates

#3264 ci: add tokio-console build
  deploy/build/Dockerfile.tokio-console.amd64
  deploy/build/buildspec-tokio-console.yml
  src/cli/basic/cli.rs
Labels: ✏️ Feature

#3253 feat: add new option allow skip disk cache check when cache in memory
  src/config/src/config.rs
  src/service/search/grpc/storage.rs
Labels: ✏️ Feature

#3266 perf: add a job to clean empty dir to let scan_dir faster
  src/config/src/utils/asynchronism/file.rs
  src/infra/src/db/nats.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
  src/job/mod.rs
Labels: ✏️ Feature

#3267 docs: fix some typos in comments
  src/config/src/config.rs
  src/handler/http/request/search/mod.rs
  src/service/functions.rs
  src/service/logs/ingest.rs
Labels: Invalid PR Title, ☢️ Bug, 📒 Documentation

#3269 fix: flush triggers usage reporting when server is stopped
  src/main.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3268 fix: migration from old TRIGGERS to scheduled jobs
  src/common/migration/mod.rs
  src/common/migration/triggers.rs
  src/infra/src/lib.rs
  src/infra/src/scheduler/mod.rs
  src/job/alert_manager.rs
  src/main.rs
Labels: ☢️ Bug

#3270 fix: correctly parse old trigger details and migrate into scheduled_jobs
  src/common/migration/mod.rs
  src/common/migration/triggers.rs
Labels: ☢️ Bug

#3272 refactor: trigger migration
  src/common/migration/meta.rs
  src/common/migration/mod.rs
  src/common/migration/schema.rs
  src/common/migration/triggers.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/main.rs
  src/service/usage/mod.rs
Labels: 🧹 Updates

#3275 fix: added ingestion message if no data ingested
  web/src/locales/languages/en.json
  web/src/views/Ingestion.vue
Labels: ☢️ Bug, ✏️ Feature

#3276 fix: discard the records when found evolution start_dt smaller than current
  src/service/logs/bulk.rs
  src/service/logs/mod.rs
  src/service/schema.rs
Labels: ☢️ Bug

#3261 fix: only search longest term in multi-terms
  src/job/files/parquet.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3254 feat: routing & user defined schema restrictions
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/stream/mod.rs
  src/infra/src/schema/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/StreamFieldInputs.vue
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#3279 feat: add a new option for limit merge on ingester
  src/config/src/config.rs
  src/job/files/parquet.rs
Labels: ✏️ Feature

#3281 chore: fix some typos in comments
  src/service/compact/merge.rs
  src/service/dashboards/reports.rs
  src/service/db/file_list/local.rs
  src/service/metadata/distinct_values.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ☢️ Bug, 📒 Documentation

#3280 fix: add more debug logs for search
  src/cli/data/export.rs
  src/config/src/meta/search.rs
  src/config/src/utils/schema_ext.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/proto/proto/cluster/search.proto
  src/service/alerts/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#3292 ci: bump up the dependencies of ok-to-test
  .github/workflows/ok-to-test.yml
Labels: 🤖 Dependencies, 🧹 Updates

#3293 fix: for forked pull-requests pick up the correct git ref
  .github/workflows/build-fork-pr-image.yml
Labels: ☢️ Bug

#3295 ci: force retrieve the missing tags
  .github/workflows/build-fork-pr-image.yml
Labels: ☢️ Bug

#3296 ci: force retrieve the missing tags and use v3 of checkout
  .github/workflows/build-fork-pr-image.yml
Labels: ☢️ Bug

#3297 ci: force retrieve the missing tags with git-describe
  .github/workflows/build-fork-pr-image.yml
Labels: ☢️ Bug

#3299 ci: update the status of the run
  .github/workflows/api-testing.yml
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
Labels: 🧹 Updates

#3303 ci: use the GIT_SHA which was requested by the /ok-to-test cmd
  .github/workflows/build-fork-pr-image.yml
Labels: 🧹 Updates

#3278 perf: improve json->recordbatch speed
  src/config/src/utils/record_batch_ext.rs
  src/infra/src/schema/mod.rs
  src/ingester/src/entry.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/grpc/mod.rs
Labels: 🧹 Updates

#3304 fix: sql fields parse error
  src/config/src/meta/sql.rs
Labels: ☢️ Bug

#3274 feat: improve tokio-console config
  src/config/src/config.rs
  src/main.rs
Labels: 🧹 Updates, ✏️ Feature

#3305 fix: added check for duplicate config api call.
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug, ✏️ Feature

#3306 Multi stream integration v4
  src/config/src/meta/search.rs
  src/handler/grpc/request/search/intra_cluster.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/router/mod.rs
  src/service/search/mod.rs
  web/src/assets/images/common/spark-logo-connector.png
  web/src/components/rum/SearchBar.vue
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/services/search.ts
  web/src/utils/zincutils.ts
Labels: Invalid PR Title

#3312 fix: enterprise build
  Cargo.lock
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3311 fix: don't use stream_type from query params for alert create/update
  src/handler/http/request/alerts/mod.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#3314 fix: API rule optimize let search UI works without ingester
  src/handler/grpc/request/search.rs
  src/router/http/mod.rs
Labels: ☢️ Bug

#3284 fix: show savedview and report resources in role permissions and fix `list_objects_for_user` for `_all_{org}`
  src/common/utils/auth.rs
  src/handler/http/request/dashboards/reports.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  src/service/dashboards/folders.rs
  src/service/dashboards/reports.rs
  src/service/functions.rs
  src/service/stream.rs
  web/src/components/iam/roles/EditRole.vue
Labels: ☢️ Bug

#3315 docs: added the generated sbom for js
  README.md
  web/sbom.json
Labels: ✏️ Feature, 📒 Documentation

#3153 feat: auto complete for promql legend, variables, filters, drilldown variables
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/CommonAutoComplete.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/composables/useSearchInputUsingRegex.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#3320 fix: alert url
  src/config/src/config.rs
  src/config/src/utils/record_batch_ext.rs
  src/infra/src/db/nats.rs
  src/service/alerts/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#3323 fix: reply wal error
  src/ingester/src/wal.rs
Labels: ☢️ Bug

#3325 fix: alert url query fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3324 fix: fixed functions menu visibility
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#3328 fix: fix some typos in comments
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  web/src/composables/useLogs.ts
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug, 📒 Documentation

#3327 fix: #3326
  src/config/src/meta/stream.rs
  src/infra/src/schema/mod.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#3329 fix: add querier cache hit ratio
  src/config/src/meta/search.rs
  src/proto/proto/cluster/common.proto
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug, ✏️ Feature

#3330 fix: build for enterprise
  src/service/search/mod.rs
Labels: ☢️ Bug

#3338 fix: schema cache error with prefix
  src/common/infra/mod.rs
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/job/mod.rs
  src/main.rs
  src/service/db/mod.rs
  src/service/db/schema.rs
  web/src/layouts/MainLayout.vue
  web/src/test/unit/helpers/setupTests.ts
  web/src/test/unit/helpers/store.ts
Labels: ☢️ Bug

#3341 feat: introduce cached_ratio to usage reporting for search usage type
  src/config/src/meta/usage.rs
  src/handler/http/request/search/mod.rs
  src/service/usage/mod.rs
Labels: ✏️ Feature

#3342 fix: remove unused code
  src/config/src/config.rs
  src/service/stream.rs
  src/service/usage/mod.rs
  src/service/usage/stats.rs
Labels: ☢️ Bug, 🧹 Updates

#3344 fix: report headless chrome url
  src/service/dashboards/reports.rs
Labels: ☢️ Bug

#3339 fix: histogram pagination fix
  src/service/search/mod.rs
  tests/ui-testing/cypress/e2e/tests/logs_quickmode.cy.js
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#3343 fix: user session id
  Cargo.lock
  src/common/infra/config.rs
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/status/mod.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/session.rs
  src/service/mod.rs
  src/service/session.rs
Labels: ☢️ Bug

#3346 fix: extrace field name in where clause
  src/config/src/meta/sql.rs
Labels: ☢️ Bug

#3348 fix: report cache and alert manager should install chrome
  deploy/build/Dockerfile.pr.amd64
  src/config/src/lib.rs
  src/infra/src/scheduler/mysql.rs
  src/service/alerts/alert_manager.rs
  src/service/dashboards/reports.rs
  src/service/db/dashboards/reports.rs
  web/src/components/reports/ReportList.vue
Labels: ☢️ Bug

#3350 fix: apply saved view error fix
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3351 fix: traces duration conflict
  src/config/src/utils/json.rs
  src/config/src/utils/record_batch_ext.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_http.rs
  src/service/metrics/otlp_http.rs
  src/service/search/datafusion/transform_udf.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#3354 fix: isDashboardLoaded flag issue for print mode
  web/src/utils/dashboard/useCustomDebouncer.ts
Labels: ☢️ Bug

#3356 fix: remove duplicated stream name on cloudwatch logs endpoint
  web/src/components/ingestion/logs/KinesisFirehose.vue
Labels: ☢️ Bug, 🧹 Updates

#3357 fix: added compressed size
  web/src/locales/languages/en.json
  web/src/views/HomeView.vue
Labels: ☢️ Bug, ✏️ Feature

#3358 fix: user login flow fixes
  src/handler/http/auth/jwt.rs
  src/service/db/session.rs
Labels: ☢️ Bug

#3361 fix: load disk query cache
  src/infra/src/cache/file_data/disk.rs
Labels: ☢️ Bug

#3360 fix: id token length issue
  src/common/meta/user.rs
  src/common/utils/jwt.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/status/mod.rs
Labels: ☢️ Bug

#3363 feat: add support for smtp 'reply to' for alerts and reports
  src/service/alerts/mod.rs
  src/service/dashboards/reports.rs
Labels: ✏️ Feature

#3366 fix: Add logo settings to rbac
  src/common/utils/auth.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3364 fix: value API is always waiting
  Cargo.lock
  Cargo.toml
  src/common/infra/mod.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#3369 fix: enrichment table field name format
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#3371 fix: format stream name for _bulk api
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
Labels: ☢️ Bug

#3370 fix: include all search events in usage reporting
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3359 fix: same role and group name in rbac with diff org conflicts
  src/handler/http/auth/jwt.rs
  src/handler/http/request/authz/fga.rs
Labels: ☢️ Bug

#3340 fix: introduce realtime alert triggers cache
  src/common/infra/config.rs
  src/common/migration/meta.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/job/mod.rs
  src/service/alerts/alert_manager.rs
  src/service/db/alerts/mod.rs
  src/service/db/alerts/realtime_triggers.rs
  src/service/db/scheduler.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#3376 perf: improve wal parquet load speed
  src/common/infra/config.rs
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates

#3378 perf: improve wal parquet load speed
  src/ingester/src/lib.rs
  src/ingester/src/partition.rs
  src/job/files/parquet.rs
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates

#3384 fix: removed clear localstorage for 401 redirection. Selected local s…
  web/src/services/http.ts
Labels: ☢️ Bug, 🧹 Updates

#3385 fix: schema version on new field addition
  src/infra/src/schema/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#3383 fix: include next_run_at in the realtime triggers usage reporting
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#3386 fix: allow a few more licenses for js code
  .github/workflows/js-license-checker.yml
Labels: ☢️ Bug

#3387 fix: organization url
  web/src/views/MemberSubscription.vue
Labels: ☢️ Bug

#3390 fix: include ingestion events into usage reporting
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3207 feat: Query Cancellation
  src/handler/http/request/status/mod.rs
  src/infra/src/errors/mod.rs
  web/src/assets/images/common/management_query.svg
  web/src/components/icons/ManagementIcon.vue
  web/src/components/icons/SlackIcon.vue
  web/src/components/queries/QueryList.vue
  web/src/components/queries/RunningQueriesList.vue
  web/src/components/settings/General.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/router.ts
  web/src/composables/shared/useManagementRoutes.ts
  web/src/composables/useIsMetaOrg.ts
  web/src/composables/useLogs.ts
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/services/search.ts
Labels: ✏️ Feature
