Repository openobserve/openobserve, pull requests merged in 2024-08, with the labels that each got.

#4101 fix: multi stream search panic
  src/handler/http/request/search/multi_streams.rs
Labels: ☢️ Bug

#4104 fix: use config timestamp and error message improve
  src/handler/http/request/search/multi_streams.rs
  src/infra/src/errors/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4107 chore: Bump Node.js to v18.20.4
  deploy/build/Dockerfile
  deploy/build/Dockerfile.aarch64
  deploy/build/Dockerfile.amd64
  deploy/build/Dockerfile.profiling.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/Dockerfile.tokio-console.amd64
Labels: 🤖 Dependencies

#4108 chore: Bump PR debian image
  deploy/build/Dockerfile.pr.amd64
Labels: 🤖 Dependencies

#4109 feat: add some logs for alert
  src/service/alerts/alert_manager.rs
Labels: ✏️ Feature

#4102 Logs page histogram partition
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: Invalid PR Title

#4112 fix: histogram will be updated when run query button will be pressed …
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, 🧹 Updates

#4113 fix: add req_node_group back to node selection in search
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4111 fix: allow IPv6 addresses in RUM headers
  src/common/meta/middleware_data.rs
  src/common/utils/http.rs
Labels: ☢️ Bug, ✏️ Feature

#3860 fix: default timestamp column on logs page
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#4061 test: testcases for visualization functionality
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboard.spec.js
  tests/ui-testing/playwright-tests/visualize.spec.js
  tests/ui-testing/playwright-tests/vrl.spec.js
Labels: 🧹 Updates

#4071 fix: #4003 batch deletion feature introduced
  web/src/locales/languages/en.json
  web/src/views/LogStream.vue
Labels: ☢️ Bug, ✏️ Feature

#4096 fix: pagination part fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4118 fix: parse index error when using field is null
  src/service/search/sql.rs
Labels: ☢️ Bug

#4121 chore: modify roadmap and cost
  README.md
Labels: 📒 Documentation

#4120 fix: add check to avoid root user role change
  src/service/users.rs
Labels: ☢️ Bug, ✏️ Feature

#4122 fix: rum token invalid when user update
  src/service/db/user.rs
  src/service/organization.rs
  src/service/users.rs
Labels: ☢️ Bug, 🧹 Updates

#4083 fix: restricting users to use select all (*) while creating alerts in SQL mode
  web/src/components/alerts/AddAlert.vue
Labels: ☢️ Bug

#4041 fix: reduced default settings of total number of events per page
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4132 fix: #4114 error message when entering incorrect old password
  src/service/users.rs
Labels: ☢️ Bug

#4134 fix: value api for number values
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#4135 fix: search pagination error
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/plan.rs
  src/service/users.rs
Labels: ☢️ Bug

#4138 fix: should exit when backend init failed
  .github/workflows/playwright.yml
  src/main.rs
  tests/ui-testing/playwright-tests/dashboard.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: ☢️ Bug

#4140 fix: some small issues of alert
  src/service/alerts/alert_manager.rs
  src/service/alerts/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#4126 fix: do not allow `*` in first column of alert and report cron expression and introduce vrl in alerts
  src/common/meta/alerts/mod.rs
  src/service/alerts/mod.rs
  src/service/dashboards/reports.rs
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/composables/useQuery.ts
Labels: ☢️ Bug

#4128 fix: #4098 loading icon stops when error in values api
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#4143 chore: add debug logs for router
  src/router/http/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#4139 fix: duplicate call on page refresh
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4145 fix: #4142 Histogram chart display in saved view
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#4146 fix: issue#4144 corrected type
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3705 feat: Logs Traces correlation
  src/common/meta/organization.rs
  src/common/meta/traces.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/DateTime.vue
  web/src/components/settings/OrganizationSettings.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/router.ts
  web/src/composables/shared/useManagementRoutes.ts
  web/src/composables/useLogs.ts
  web/src/composables/useTraces.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/SpanDetails.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceTree.vue
  web/src/stores/index.ts
Labels: ☢️ Bug, ✏️ Feature

#4150 fix: added back interesting field icon and eye icon on _timestamp column
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug, ✏️ Feature

#4152 feat: return multiple partition when the query have _timestamp
  src/service/search/cache/cacher.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#4154 fix: use next cron timestamp after silence period
  src/service/alerts/alert_manager.rs
Labels: ☢️ Bug

#4156 fix: plan error in some case
  src/service/search/cache/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/plan.rs
Labels: ☢️ Bug

#4153 fix: use user defined schema for dashboard fieldList
  tests/ui-testing/playwright-tests/dashboard.spec.js
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#4148 fix: request timeout after an error happened
  src/common/utils/http.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#4161 fix: #4124 fixed when histogram toggled the results will be displayed
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#4116 perf: breakdown timechart performance improvement
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: 🧹 Updates

#4087 feat: threshold line for dashboard chart
  src/common/meta/dashboards/v4/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/MarkLineConfig.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#4164 fix: use alert data period for trigger report start time and end time, also report partial send notification error
  src/service/alerts/alert_manager.rs
  src/service/alerts/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#4165 fix: stream name wrapped in quotation as stream name contains hyphen …
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#4172 fix: ingestion time of enrichement table
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#4175 fix: enrichment table ingestion should be always append mode
  src/handler/grpc/request/ingest.rs
Labels: ☢️ Bug

#4176 fix: updated cached enrichment table
  deploy/build/Dockerfile.pr.amd64
  src/config/src/config.rs
  src/job/mod.rs
  src/service/db/enrichment_table.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#4177 fix: for enrichment table use orginal timestamp
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#4178 fix: extrace field in case when
  src/config/src/meta/sql.rs
Labels: ☢️ Bug

#4180 feat: upgrade to datafusion 41
  Cargo.lock
  Cargo.toml
  src/config/src/meta/sql.rs
  src/proto/src/datafusion/emptytable.rs
  src/service/promql/engine.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/udf/arr_descending_udf.rs
  src/service/search/datafusion/udf/arrcount_udf.rs
  src/service/search/datafusion/udf/arrindex_udf.rs
  src/service/search/datafusion/udf/arrjoin_udf.rs
  src/service/search/datafusion/udf/arrsort_udf.rs
  src/service/search/datafusion/udf/arrzip_udf.rs
  src/service/search/datafusion/udf/cast_to_arr_udf.rs
  src/service/search/datafusion/udf/date_format_udf.rs
  src/service/search/datafusion/udf/match_udf.rs
  src/service/search/datafusion/udf/regexp_udf.rs
  src/service/search/datafusion/udf/spath_udf.rs
  src/service/search/datafusion/udf/string_to_array_v2_udf.rs
  src/service/search/datafusion/udf/time_range_udf.rs
  src/service/search/datafusion/udf/to_arr_string_udf.rs
  src/service/search/datafusion/udf/transform_udf.rs
Labels: ✏️ Feature

#4103 fix: convert `[:?#\s'"&%]` characters into `_` while saving alert/report/destination/template names
  src/common/infra/ofga.rs
  src/common/migration/mod.rs
  src/common/migration/schema.rs
  src/common/utils/auth.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/main.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  src/service/alerts/templates.rs
  src/service/dashboards/reports.rs
  src/service/mod.rs
  web/src/services/alert_destination.ts
  web/src/services/alert_templates.ts
  web/src/services/alerts.ts
  web/src/services/reports.ts
Labels: ☢️ Bug

#4181 fix: disabled View Trace btn in logs if traces menu is disabled
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/stores/index.ts
Labels: ☢️ Bug

#4184 fix: Resource name validation
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/reports/CreateReport.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#4185 fix: updated english language flag
  web/src/assets/images/language_flags/en-gb.svg
Labels: ☢️ Bug, 🧹 Updates

#4186 fix: include alert vrl function in the alert url
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#4189 fix: aggregate query check fixes
  src/config/src/utils/sql.rs
Labels: ☢️ Bug

#4192 fix: cache aggregate calculate
  src/config/src/utils/sql.rs
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#4195 fix: logs page datepicker issue fix for restricted time range
  web/src/components/DateTime.vue
Labels: ☢️ Bug

#4191 fix: Improved period (time range) functionality in pipelines derived stream
  src/handler/grpc/request/ingest.rs
  src/service/alerts/scheduler.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  web/src/components/pipeline/ScheduledPipeline.vue
  web/src/components/pipeline/StreamRouting.vue
Labels: ☢️ Bug, 🧹 Updates

#4196 fix:result cache start time fix for histogram
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#4203 feat: impl #4200 support skip format stream name
  src/config/src/config.rs
  src/handler/http/request/stream/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/mod.rs
Labels: ✏️ Feature

#4204 fix: for user define schema explicitly add _timestamp and all columns
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, ✏️ Feature

#4194 fix: auto order by clause removed for sql mode
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, 🧹 Updates

#4207 fix: timestamp not adding to result grid for user defined schema
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, ✏️ Feature

#4209 fix: merge plan panic
  src/handler/grpc/request/ingest.rs
  src/service/alerts/scheduler.rs
  src/service/enrichment_table/mod.rs
  src/service/search/cluster/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#4208 test: assert timestamp and all displayed in fields when uds enabled
  tests/ui-testing/playwright-tests/schema.spec.js
  web/src/plugins/logs/IndexList.vue
Labels: 🧹 Updates

#4210 fix: Result array vrl hint space issue
  src/service/search/cluster/http.rs
Labels: ☢️ Bug

#4202 fix: apply functions for routed streams
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
Labels: ☢️ Bug

#4212 fix: histogram partial loading
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4224 fix: dashboard edit panel two times api call issue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#4240 fix: grpc messge limit for search service
  src/main.rs
Labels: ☢️ Bug

#4244 fix: use ConditionNotSatisfied in triggers reporting for empty derived stream data
  src/service/alerts/scheduler.rs
Labels: ☢️ Bug

#4252 fix: Restricted selection of _timestamp and _all fields as defined schema in stream settings
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug, 🧹 Updates

#4255 fix: search management can't finish job when there is a panic
  src/service/search/cluster/mod.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#4251 feat: results based on multiple caches
  src/common/meta/search.rs
  src/config/src/config.rs
  src/handler/grpc/request/query_cache.rs
  src/proto/proto/cluster/querycache.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
  src/service/search/cluster/cache_multi.rs
  src/service/search/cluster/mod.rs
Labels: ✏️ Feature

#4223 fix: Dashboard panel tooltip improvements
  web/src/composables/useWorker.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug, 🧹 Updates

#4261 fix: use empty table for generate plan
  rustfmt.toml
  src/proto/src/generated/cluster.rs
  src/proto/src/generated/prometheus.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/mod.rs
  src/service/search/datafusion/physical_plan/empty_exec.rs
  src/service/search/datafusion/physical_plan/mod.rs
  src/service/search/datafusion/table_provider/empty_table.rs
  src/service/search/datafusion/table_provider/mod.rs
Labels: ☢️ Bug

#4259 fix: caching logic panic
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#4237 fix: Added currency list in config of dashboard
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug, ✏️ Feature

#4269 feat: align the multiple search partition to avoid override with histogram
  src/service/search/mod.rs
  tests/ui-testing/playwright-tests/dashboard.spec.js
Labels: ☢️ Bug, ✏️ Feature

#4265 feat: add last_triggered_at, owner, last_edited_by, updated_at fields in alerts
  src/common/meta/alerts/alert.rs
  src/handler/http/request/alerts/alert.rs
  src/handler/http/request/dashboards/reports.rs
  src/service/alerts/alert.rs
  src/service/alerts/scheduler.rs
  src/service/dashboards/reports.rs
  src/service/db/alerts/alert.rs
Labels: ✏️ Feature

#4275 fix: #4264 pagination and total events disappears when histogram error
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#4276 fix: issue #4266 histogram bar issue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#4229 fix: #4226 fixed Select all columns condition failing
  web/src/components/alerts/AddAlert.vue
Labels: ☢️ Bug

#4285 fix: add histogram interval for multi result cache
  src/infra/src/cache/meta.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
  src/service/search/cluster/cache_multi.rs
Labels: ☢️ Bug, ✏️ Feature

#4253 fix: use last triggered time for derived stream period to prevent missing data
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler.rs
  src/service/db/scheduler.rs
Labels: ☢️ Bug

#4293 fix: duplicate records when using result cache
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#4300 fix: always return single partition for ResultArray VRL
  src/config/src/meta/search.rs
  src/service/search/cache/multi.rs
  src/service/search/cluster/http.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#4283 fix: do not allow `SELECT *` in alert query
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#4312 fix: search partition with VRL
  src/service/search/mod.rs
Labels: ☢️ Bug

#4258 feat: Dashboard top N results
  src/common/meta/dashboards/v4/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#4296 fix: traces link panic
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ☢️ Bug

#4314 feat: add histogram interval for search partition
  src/config/src/meta/search.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#4308 fix: improved query and VRL function validation in alerts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#4322 fix: cache selection strategy
  src/common/meta/search.rs
  src/config/src/config.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
  src/service/search/cluster/cache_multi.rs
Labels: ☢️ Bug

#4294 fix: use 409 when deleting destination/templates already in use
  src/common/meta/http.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/dashboards/reports.rs
  src/service/alerts/destinations.rs
  src/service/alerts/templates.rs
  src/service/users.rs
Labels: ☢️ Bug

#4324 feat: Show unflattened preview of log in log details
  web/src/components/QueryEditor.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/JsonPreview.vue
Labels: ✏️ Feature

#4330 chore: add took details to cache response
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
Labels: ✏️ Feature

#4334 fix: skip caching for aggregation query with no order by clause
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#4263 feat: dashboard partitions api call support
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/query/sqlUtils.ts
Labels: ✏️ Feature

#4280 chore: remove console logs from Dashboard and Logs page
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/utils/dashboard/convertPanelData.ts
Labels: Invalid PR Title, 🧹 Updates

#4336 feat: added last triggered , owner , cloning in alerts page
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/reports/ReportList.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#4349 chore: Delete spam issue comments containing mediafire
  .github/workflows/spam-cleaner.yml
Labels: 📒 Documentation

#4350 fix: issue #4326 User defined schema settings
  src/config/src/meta/stream.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/stream.rs
  tests/integration_test.rs
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/schema.vue
  web/src/composables/useStreams.ts
  web/src/services/stream.ts
Labels: Invalid PR Title

#4343 fix: Type errors issue in logs optimization
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#4348 fix: Log related issues
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4359 fix: when updating alert first check, if the scheduled_job exist or not
  src/service/alerts/scheduler.rs
  src/service/db/alerts/alert.rs
Labels: ☢️ Bug

#4364 fix: args of histogram( ) or any function to be added to interesting fields in quick mode
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, ✏️ Feature

#4361 fix: logs table timestamp column visibility issue
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4352 feat: impl union plan for single node
  src/common/infra/cluster/mod.rs
  src/common/infra/mod.rs
  src/common/infra/wal.rs
  src/handler/grpc/request/metrics/querier.rs
  src/job/files/parquet.rs
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/physical_plan/empty_exec.rs
  src/service/search/datafusion/plan.rs
  src/service/search/datafusion/table_provider/empty_table.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/table_provider/uniontable.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#4373 fix: Issue stream settings partition keys
  web/src/composables/useStreams.ts
Labels: ☢️ Bug

#4375 fix: Logs cancel query issue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4378 feat: add max_query_range for search partition API
  src/config/src/meta/search.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#4385 fix: Restoring tables column ordering in saved views
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/logstream/schema.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
  web/src/utils/dashboard/convertSQLData.ts
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#4367 fix: remove alert evaluation on save and do not store alert vrl containing only "."
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#4386 fix: Alert cloning issues
  web/src/components/alerts/AlertList.vue
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#4368 feat: add `last_satisfied_at` field in alerts
  src/common/meta/alerts/alert.rs
  src/service/alerts/scheduler.rs
  web/src/components/alerts/AlertList.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#4392 fix: updated alerts preview and query validation time-range to 2mins
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, 🧹 Updates

#4395 fix: allow to query upto given max_query_range for partition
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#4397 fix: wrong timeseries hover issue for dashboard
  web/src/components/dashboards/panels/ChartRenderer.vue
Labels: ☢️ Bug

#4393 fix: improve triggers reporting, update trigger status if alert query is invalid
  src/handler/http/request/alerts/alert.rs
  src/service/alerts/alert.rs
  src/service/alerts/scheduler.rs
Labels: ☢️ Bug, 🧹 Updates

#4398 fix: Table does not gets rendered on applying saved view
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4401 fix: saved views columns not getting restored
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SyntaxGuide.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#4400 fix: Alert cloning issues clicking save button multiple times fixed
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug

#4406 fix: table col rezing fix
  web/src/composables/useLogs.ts
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/utils/zincutils.ts
Labels: Invalid PR Title, ☢️ Bug

#4410 feat: add force quick mode
  src/config/src/config.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#4407 fix: Updated table width on updating columns
  web/src/composables/useLogs.ts
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug, 🧹 Updates

#4413 fix: multi result cache duplicates issue
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
Labels: ☢️ Bug

#4402 fix: debug syslog ingestion
  src/handler/tcp_udp/mod.rs
  src/job/syslog_server.rs
  src/service/logs/syslog.rs
Labels: ☢️ Bug

#4415 feat: add support for aws s3 client retry
  src/config/src/config.rs
  src/infra/src/storage/remote.rs
Labels: ✏️ Feature

#4409 fix: issue# 4408 edit icon replaced on function and enrichment table list page.
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FunctionList.vue
Labels: ☢️ Bug
