Repository openobserve/openobserve, pull requests merged in 2024-01, with the labels that each got.

#2327 feat: decimal point option in config panel
  src/common/meta/dashboards/v2/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#2323 fix: dynamic filters
  src/common/meta/dashboards/v2/mod.rs
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/utils/commons.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2328 feat: dashboard view page enhancements
  web/src/components/dashboards/ExportDashboard.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#2343 fix: build failure fixes
  src/handler/http/auth/token.rs
Labels: ☢️ Bug

#2348 fix: split histogram query on logs page
  web/src/components/MenuLink.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2350 fix: fixed traces and alerts UI issues
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/logstream/explore/SearchBar.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/SpanDetails.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceHeader.vue
  web/src/plugins/traces/TraceTree.vue
  web/src/services/stream.ts
  web/src/views/StreamExplorer.vue
Labels: ☢️ Bug

#2351 fix: size set to zero for histogram request
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2356 fix: dynamic variables for add and maximize panel
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, ✏️ Feature

#2357 fix: no of records out of message changes
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#2349 feat: decimal points for table chart
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature

#2321 fix: keeping optimize search
  .gitignore
  Cargo.lock
  Cargo.toml
  rustfmt.toml
  src/common/infra/file_list/mysql.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/meta/stream.rs
  src/common/utils/flatten.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/utils/hasher.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/parquet.rs
  src/config/src/utils/schema.rs
  src/config/src/utils/schema_ext.rs
  src/handler/http/request/logs/ingest.rs
  src/ingester/Cargo.toml
  src/ingester/src/errors.rs
  src/ingester/src/immutable.rs
  src/ingester/src/lib.rs
  src/ingester/src/memtable.rs
  src/ingester/src/partition.rs
  src/ingester/src/stream.rs
  src/ingester/src/wal.rs
  src/ingester/src/writer.rs
  src/job/files/json.rs
  src/job/files/parquet.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/distinct_values.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/grpc.rs
  src/service/ingestion/mod.rs
  src/service/ingestion/otlp_json.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/search/datafusion/date_format_udf.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/match_udf.rs
  src/service/search/datafusion/time_range_udf.rs
  src/service/search/datafusion/transform_udf.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  src/wal/src/reader.rs
Labels: ☢️ Bug

#2377 feat: capture credit card detail
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/enterprise/components/billings/plans.vue
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#2342 fix: Update zincutils.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, 🧹 Updates

#2384 fix: fixed log breaking testcase
  tests/ui-testing/.gitignore
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: ☢️ Bug, 🧹 Updates

#2386 feat: e2e create dashboard testcases
  tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2385 fix: removed dialog box to capture credit card details
  web/src/enterprise/components/billings/planCard.vue
  web/src/enterprise/components/billings/plans.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, 🧹 Updates

#2388 feat: e2e add dashboard panel testcases
  tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
  tests/ui-testing/cypress/support/commons.js
Labels: 🧹 Updates, ✏️ Feature

#2390 fix: timeseries issue for area stacked chart
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#2392 fix: e2e - added logs testcase to navigate on logs page
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  tests/ui-testing/cypress/fixtures/alpha1.json
  tests/ui-testing/cypress/fixtures/beta1.json
  tests/ui-testing/cypress/support/commands.js
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2389 fix: use geo-location country-iso also in the data
  src/common/meta/middleware_data.rs
  src/job/mmdb_downloader.rs
Labels: ☢️ Bug

#2360 chore: dex integration changes
  src/common/utils/jwt.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/router/http/mod.rs
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/services/http.ts
  web/src/utils/zincutils.ts
Labels: ✏️ Feature

#2398 test: added tests for functions page
  tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
  tests/ui-testing/cypress/fixtures/enrichment_info.csv
  tests/ui-testing/package-lock.json
  tests/ui-testing/package.json
Labels: 🧹 Updates, ✏️ Feature

#2397 fix: tofixed method getting undefined
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#2400 fix: RSS reduction due to lazily loading ua-parser
  src/common/meta/middleware_data.rs
  src/lib.rs
  src/main.rs
Labels: ☢️ Bug

#2401 fix: dashboard edit panel test ids
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/HistogramIntervalDropDown.vue
  web/src/components/dashboards/addPanel/PanelSidebar.vue
  web/src/components/dashboards/addPanel/SortByBtnGrp.vue
  web/src/components/dashboards/settings/VariableAdHocValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/components/shared/grid/NoPanel.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, 🧹 Updates

#2395 fix: ja.json
  web/src/locales/languages/ja.json
Labels: ☢️ Bug

#2403 refactor: use impl From for datafusion error
  src/common/infra/errors.rs
  src/service/search/grpc/errors.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates

#2404 fix: telemetry changes
  src/common/meta/telemetry.rs
  src/job/mod.rs
Labels: ☢️ Bug

#2406 refactor: Remove unnecessary methods
  src/service/search/datafusion/transform_udf.rs
  src/service/traces/mod.rs
Labels: 🧹 Updates

#2405 feat: support building and publishing to registry via actions
  .github/workflows/build-pr-image.yml
  deploy/build/Dockerfile.pr.amd64
Labels: ✏️ Feature

#2410 feat: enabled VRL function and column generated by VRL function doesn…
  web/src/composables/useLogs.ts
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
Labels: ✏️ Feature

#2412 test: logs vrl testcase assertion added
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2379 fix: added exceptions tab in trace details
  web/src/components/common/sidebar/FieldList.vue
  web/src/components/functions/AssociatedStreamFunction.vue
  web/src/locales/languages/en.json
  web/src/plugins/traces/SpanDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceTree.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug, ✏️ Feature

#2415 test: added logs-vrlfunction testcase
  tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates, ✏️ Feature

#2416 fix: pin credentials fetching to use v4
  .github/workflows/build-pr-image.yml
Labels: ☢️ Bug

#2417 test: cypress test changes
  tests/ui-testing/cypress.config.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2378 fix: dashboard legend width and axis width, border
  src/common/meta/dashboards/v2/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2423 fix: dashboard hide legend width unit buttons for some chart type
  web/src/components/dashboards/addPanel/ConfigPanel.vue
Labels: ☢️ Bug

#2426 fix: add error display
  src/ingester/src/errors.rs
  src/ingester/src/wal.rs
  src/wal/src/errors.rs
  src/wal/src/reader.rs
Labels: ☢️ Bug, ✏️ Feature

#2427 fix: merge search result but file not found
  Cargo.lock
  src/service/metrics/prom.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#2430 fix: dashboard unit conversion for negative values
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug

#2429 test:edit dashboard testcases
  tests/ui-testing/cypress/e2e/tests/dashboard/add_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/create_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/dashboard/edit_dashboard.cy.js
  tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
  tests/ui-testing/cypress/fixtures/dashboard.json
Labels: 🧹 Updates

#2437 fix: add dashboard test ids
  web/src/components/dashboards/AddDashboard.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2441 fix: dashboard legend width and title overlap
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2442 fix: dashboard folder test ids
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug, 🧹 Updates

#2424 feat: added preview for alerts
  web/src/assets/inputs.scss
  web/src/assets/main.css
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/FieldsInput.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/alerts/VariablesInput.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/locales/languages/en.json
  web/src/services/alerts.ts
  web/src/styles/quasar-overrides.scss
  web/src/utils/alerts/alertChartData.ts
  web/src/views/AppAlerts.vue
Labels: ✏️ Feature

#2432 feat: alert support PromQL
  src/common/meta/alerts/mod.rs
  src/config/src/config.rs
  src/handler/http/request/traces/mod.rs
  src/job/files/parquet.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ☢️ Bug, ✏️ Feature

#2419 feat: Stream Explorer UI improvements
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2438 feat: Logs page pagination
  Cargo.lock
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/utils/logs/convertLogData.ts
Labels: ✏️ Feature

#2447 fix: dashboard config panel UI
  web/src/components/dashboards/addPanel/ConfigPanel.vue
Labels: ☢️ Bug

#2450 feat: stream selection support in traces
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/services/search.ts
Labels: ☢️ Bug, ✏️ Feature

#2451 test:added alerts testcases and fixed logs tests
  tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2449 fix: Memory leak pagination test
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug, 🧹 Updates

#2452 feat: rebac with openfga
  src/common/utils/auth.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/functions/mod.rs
  src/handler/http/request/stream/mod.rs
  src/service/functions.rs
  src/service/stream.rs
  tests/api-testing/tests/test_alerts.py
  tests/api-testing/tests/test_functions.py
  tests/api-testing/tests/test_logs.py
  tests/api-testing/tests/test_organisations.py
  tests/api-testing/tests/test_rum.py
  web/src/services/index.ts
  web/src/services/jstransform.ts
  web/src/services/stream.ts
Labels: ✏️ Feature

#2456 fix: compact files is too big
  rustfmt.toml
  src/job/files/parquet.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#2457 fix: disabled billing page redirection
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#2458 fix: dashboard maximize panel scroll issue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
Labels: ☢️ Bug

#2460 fix: dashboard legend width for pie and donut chart
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2462 feat: promql support in alerts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/DestinationList.vue
  web/src/components/alerts/FieldsInput.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/alerts/TemplateList.vue
  web/src/components/alerts/VariablesInput.vue
  web/src/styles/quasar-overrides.scss
Labels: ✏️ Feature

#2461 fix: minor issue and redirection
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug

#2467 fix: data test id set
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, 🧹 Updates

#2466 feat: support PromQL for alerts
  src/common/meta/alerts/mod.rs
  src/handler/http/request/mod.rs
  src/main.rs
  src/service/alerts/mod.rs
  src/service/db/alerts/destinations.rs
  src/service/metrics/prom.rs
  src/service/search/sql.rs
  web/src/components/alerts/ScheduledAlert.vue
Labels: ✏️ Feature

#2468 test: logs histogram graph testcase
  tests/ui-testing/cypress/e2e/tests/alerts_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: 🧹 Updates

#2470 fix: PromQL data wrong with multiple metrics
  src/service/alerts/alert_manager.rs
  src/service/compact/mod.rs
  src/service/promql/aggregations/mod.rs
  src/service/promql/engine.rs
  src/service/promql/search/grpc/mod.rs
  src/service/usage/stats.rs
Labels: ☢️ Bug

#2472 feat: migrate from any to any
  src/cli/basic/cli.rs
  src/common/infra/db/dynamo.rs
  src/common/migration/file_list.rs
  src/common/migration/meta.rs
  src/common/migration/mod.rs
Labels: ✏️ Feature

#2475 fix: Alerts UI issues
  src/service/promql/aggregations/bottomk.rs
  src/service/promql/aggregations/count_values.rs
  src/service/promql/aggregations/mod.rs
  src/service/promql/aggregations/quantile.rs
  src/service/promql/aggregations/topk.rs
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/traces/IndexList.vue
  web/src/styles/quasar-overrides.scss
  web/src/ts/interfaces/alert.ts
Labels: ☢️ Bug

#2482 feat: add alert_url variable for alerts
  src/common/infra/cluster.rs
  src/common/utils/base64.rs
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/service/alerts/alert_manager.rs
  src/service/alerts/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ✏️ Feature

#2485 fix: fixed sharing metrics url issue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/metrics/MetricList.vue
Labels: ☢️ Bug

#2486 fix: endpoint sync release v0.8.0
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/services/jstransform.ts
Labels: ☢️ Bug

#2490 ci: update prod docker images
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
Labels: 🧹 Updates

#2488 fix: log UI issues
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
Labels: ☢️ Bug

#2453 fix: ensure that the ci-run names are unique
  .github/workflows/api-testing.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/ui-testing.yml
Labels: ☢️ Bug

#2394 feat: run unit tests on github actions
  .github/workflows/unit-tests.yml
  coverage.sh
Labels: 🧹 Updates, ✏️ Feature

#2491 fix: reset the data when there are no queries to execute
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#2492 fix: chart tooltip wrong legend highlight
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2497 fix: alerts url variable
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#2495 fix: alert preview chart x axis label overlap issue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#2422 fix: dynamic filters disappear issue when change in time
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/utils/date.ts
Labels: ☢️ Bug

#2496 feat: kubernetes tabs integration
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/locales/languages/en.json
Labels: Invalid PR Title

#2502 fix: issue/2501
  src/service/search/grpc/mod.rs
Labels: ☢️ Bug

#2504 fix: Fixed alert silence value validation
  web/src/components/alerts/AddAlert.vue
Labels: ☢️ Bug

#2510 fix: tabs color and label
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#2512 fix: Update useLogs.ts
  web/src/composables/useLogs.ts
Labels: Invalid PR Title, 🧹 Updates

#2513 fix: ensure correct commit-id is fetched during a PR build
  .github/workflows/build-pr-image.yml
Labels: ☢️ Bug

#2515 feat: add length limit for alert variables
  src/common/meta/alerts/templates.rs
  src/service/alerts/mod.rs
  src/service/alerts/templates.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ✏️ Feature

#2519 feat: add search partition API
  src/common/meta/search.rs
  src/config/src/config.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/search/mod.rs
  web/src/components/alerts/ScheduledAlert.vue
Labels: ✏️ Feature

#2523 feat: improve id generate
  Cargo.lock
  Cargo.toml
  src/common/infra/cache/tmpfs.rs
  src/common/infra/cluster.rs
  src/config/Cargo.toml
  src/config/src/ider.rs
  src/config/src/lib.rs
  src/handler/grpc/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/ingester/Cargo.toml
  src/service/alerts/mod.rs
  src/service/db/saved_view.rs
  src/service/promql/search/mod.rs
  src/service/search/mod.rs
  src/service/users.rs
Labels: 🧹 Updates, ✏️ Feature

#2525 fix: id generator
  src/config/src/ider.rs
Labels: ☢️ Bug

#2526 fix: alert url error
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#2530 fix: job id generate for promql
  src/service/promql/search/mod.rs
Labels: ☢️ Bug

#2531 fix: Function icon & text for darkmode
  web/src/components/MenuLink.vue
  web/src/components/icons/FunctionIcon.vue
  web/src/mixins/mainLayout.mixin.ts
Labels: ☢️ Bug

#2536 refactor: avoid record_val clone operation when inferring schemas
  src/common/utils/json.rs
  src/config/src/utils/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: 🧹 Updates

#2539 fix: table chart histogram field by default sortby as desc
  web/src/composables/useDashboardPanel.ts
  web/src/utils/commons.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#2540 chore: add debug logs for grpc
  src/service/enrichment_table/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/search/grpc/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#2454 feat: rebac with openfga
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/common/utils/jwt.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/promql/mod.rs
  src/service/promql/name_visitor.rs
  src/service/schema.rs
  web/src/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/router/index.ts
  web/src/services/http.ts
  web/src/views/Login.vue
Labels: ✏️ Feature

#2538 test: fixed logs breaking testcases
  .github/workflows/ui-testing.yml
  tests/ui-testing/cypress.config.js
  tests/ui-testing/cypress/e2e/allfunctions/logs.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: ☢️ Bug, 🧹 Updates

#2545 fix: ui issue
  web/src/services/http.ts
  web/src/views/Login.vue
Labels: ☢️ Bug

#2546 fix:2532 - OTLP http -json Logs not being ingested
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/service/logs/otlp_http.rs
Labels: ☢️ Bug

#2554 fix: Alerts UI issues
  web/src/components/alerts/AddAlert.vue
  web/src/views/AppAlerts.vue
Labels: ☢️ Bug

#2558 fix: #2555 & #2557
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#2556 fix: panic in users db
  src/common/meta/user.rs
  src/handler/http/auth/jwt.rs
  src/service/db/user.rs
Labels: ☢️ Bug

#2552 refactor: optimize log write procedure
  src/common/utils/json.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
Labels: 🧹 Updates

#2542 fix: unit tests
  coverage.sh
  src/cli/basic/cli.rs
  src/common/infra/db/mod.rs
  src/common/infra/db/sqlite.rs
  src/common/infra/file_list/dynamo.rs
  src/common/infra/file_list/mod.rs
  src/common/infra/file_list/mysql.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/meta/sql.rs
  src/common/migration/file_list.rs
  src/common/utils/json.rs
  src/handler/http/request/organization/org.rs
  src/ingester/src/immutable.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/service/alerts/mod.rs
  src/service/compact/stats.rs
  src/service/ingestion/grpc.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/organization.rs
  src/service/promql/mod.rs
  src/service/schema.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/users.rs
  tests/integration_test.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2563 fix: Update SearchResult.vue
  web/src/plugins/logs/SearchResult.vue
Labels: Invalid PR Title, 🧹 Updates

#2564 fix: ingester logic for error
  src/service/logs/ingest.rs
Labels: ☢️ Bug

#2565 fix: Traces UI Issues
  web/src/components/QueryEditor.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
Labels: ☢️ Bug

#2569 fix: pagination ui issue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2573 fix: fixed traces UI issues
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/fields-sidebar/AdvancedValuesFilter.vue
Labels: ☢️ Bug

#2581 Fix/stream explorer UI fix
  web/src/composables/useLogs.ts
  web/src/composables/useTraces.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/traces/Index.vue
Labels: Invalid PR Title, ☢️ Bug

#2583 fix: removed debug
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates

#2584 fix: stream selection saved view
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2585 fix: additional note
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ☢️ Bug, ✏️ Feature

#2586 feat: update to datafusion 35
  Cargo.lock
  Cargo.toml
  src/service/metrics/otlp_grpc.rs
  src/service/search/datafusion/date_format_udf.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/match_udf.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/mod.rs
  src/service/search/datafusion/storage/tmpfs.rs
  src/service/search/datafusion/time_range_udf.rs
  src/service/search/grpc/errors.rs
Labels: 🧹 Updates, ✏️ Feature

#2589 feat: add records for search partition
  src/common/meta/search.rs
  src/ingester/src/immutable.rs
  src/ingester/src/writer.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#2592 fix: fixed saved views functionality for metrics and traces stream type in logs page
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#2594 fix: debug tokio schedule problem
  src/common/infra/file_list/dynamo.rs
  src/common/infra/file_list/mod.rs
  src/common/infra/file_list/mysql.rs
  src/common/infra/file_list/postgres.rs
  src/common/infra/file_list/sqlite.rs
  src/common/meta/sql.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/ingester/src/immutable.rs
  src/service/db/file_list/remote.rs
  src/service/search/datafusion/storage/tmpfs.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/stats.rs
Labels: ☢️ Bug

#2596 fix: debug ingester persist issue
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/ingester/src/immutable.rs
  src/ingester/src/partition.rs
  src/ingester/src/wal.rs
  src/ingester/src/writer.rs
  src/job/files/json.rs
  src/service/alerts/alert_manager.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#2603 fix: enrichment table query
  src/common/infra/db/sqlite.rs
  src/common/infra/file_list/sqlite.rs
  src/common/meta/search.rs
  src/ingester/src/wal.rs
  src/job/compact.rs
  src/service/compact/file_list_deleted.rs
  src/service/db/enrichment_table.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#2613 test: fix logs testcases
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: ☢️ Bug, 🧹 Updates

#2570 refactor: optimize schema check
  src/common/infra/config.rs
  src/common/meta/stream.rs
  src/service/logs/bulk.rs
  src/service/schema.rs
Labels: 🧹 Updates

#2610 fix: report user email as part of usage reporting
  src/cli/data/import.rs
  src/common/meta/usage.rs
  src/handler/grpc/auth/mod.rs
  src/handler/grpc/request/logs.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/request/search/mod.rs
  src/service/alerts/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/promql/search/mod.rs
  src/service/usage/mod.rs
Labels: ☢️ Bug

#2618 test: fix saved view deletion under logs
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
Labels: ☢️ Bug, 🧹 Updates

#2622 fix: added data-test for function list and saved view list
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#2623 feat: rbac ui
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/schema.rs
  src/service/stream.rs
  web/src/components/AppTable.vue
  web/src/components/RouteTabs.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/iam/groups/AddGroup.vue
  web/src/components/iam/groups/AppGroups.vue
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/groups/GroupList.vue
  web/src/components/iam/groups/GroupRoles.vue
  web/src/components/iam/groups/GroupUsers.vue
  web/src/components/iam/organizations/AppOrganizations.vue
  web/src/components/iam/roles/AddRole.vue
  web/src/components/iam/roles/AppRoles.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/EntityPermissionTable.vue
  web/src/components/iam/roles/PermissionSelector.vue
  web/src/components/iam/roles/PermissionsTable.vue
  web/src/components/iam/roles/permissions.ts
  web/src/components/iam/users/AddUser.vue
  web/src/components/iam/users/UpdateRole.vue
  web/src/components/iam/users/User.vue
  web/src/composables/iam/usePermissions.ts
  web/src/composables/shared/router.ts
  web/src/enterprise/components/users/User.vue
  web/src/enterprise/composables/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/traces/fields-sidebar/AdvancedValuesFilter.vue
  web/src/services/iam.ts
  web/src/styles/quasar-overrides.scss
  web/src/ts/interfaces/iam.ts
  web/src/ts/interfaces/index.ts
  web/src/views/IdentityAccessManagement.vue
  web/src/views/User.vue
Labels: ✏️ Feature
