Repository openobserve/openobserve, pull requests merged in 2024-12, with the labels that each got.

#5202 fix: no need to create tantivy index if the data is empty
  Cargo.lock
  src/common/infra/wal.rs
  src/config/src/utils/async_file.rs
  src/config/src/utils/asynchronism/mod.rs
  src/config/src/utils/file.rs
  src/config/src/utils/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/storage/mod.rs
  src/job/compactor.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
  src/job/flatten_compactor.rs
  src/main.rs
  src/service/compact/merge.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/wal/Cargo.toml
  src/wal/src/writer.rs
Labels: ☢️ Bug, ✏️ Feature

#5219 fix: pipeline condition node incorrect evaluation
  .github/ISSUE_TEMPLATE/2-feature-request.yaml
  src/config/src/meta/stream.rs
  src/service/pipeline/batch_execution.rs
Labels: ☢️ Bug

#5221 feat: index for super cluster
  src/config/src/meta/stream.rs
  src/infra/src/schema/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/stream.rs
Labels: ✏️ Feature

#5226 fix: don't add `\n` in email row templates, add trigger time variables in alert template
  src/service/alerts/alert.rs
  src/service/alerts/scheduler.rs
  src/service/ingestion/mod.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ☢️ Bug, ✏️ Feature

#5225 feat: add option for NATS deliver policy
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/infra/src/queue/nats.rs
  src/infra/src/schema/mod.rs
  src/service/search/tantivy/puffin_directory/footer_cache.rs
Labels: ✏️ Feature

#5227 fix: support both text and html for alert email
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#5087 feat: generalize distinct values
  src/common/migration/dashboards.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/search/mod.rs
  src/infra/src/table/dashboards.rs
  src/infra/src/table/distinct_values.rs
  src/infra/src/table/mod.rs
  src/service/db/dashboards/mod.rs
  src/service/logs/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/datafusion/exec.rs
  src/service/stream.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature

#5232 fix: set text col length to satisfy mysql
  src/infra/src/table/distinct_values.rs
Labels: ☢️ Bug

#5220 feat: divide dashboards "HTTP Layer" and "Service Layer" logic
  src/cli/basic/cli.rs
  src/common/migration/dashboards.rs
  src/handler/http/request/dashboards/mod.rs
  src/service/dashboards/mod.rs
  src/service/dashboards/reports.rs
  src/service/db/dashboards/mod.rs
Labels: ✏️ Feature

#5237 fix: return 429 code when cancel query
  src/service/search/cluster/flight.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#5201 test: Change Org
  .github/workflows/playwright.yml
  tests/ui-testing/pages/aboutPage.js
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/pages/dataPage.js
  tests/ui-testing/pages/homePage.js
  tests/ui-testing/pages/iamPage.js
  tests/ui-testing/pages/ingestionPage.js
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/managementPage .js
  tests/ui-testing/pages/metricsPage.js
  tests/ui-testing/pages/pipelinesPage.js
  tests/ui-testing/pages/reportsPage.js
  tests/ui-testing/pages/rumPage.js
  tests/ui-testing/pages/streamsPage.js
  tests/ui-testing/pages/tracesPage.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
Labels: 🧹 Updates

#5245 fix: limit the cpu and mem for NewListingTable
  src/service/folders.rs
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug

#5247 feat: add tls for grpc
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/config/src/cluster.rs
  src/config/src/config.rs
  src/main.rs
  src/service/grpc.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#5121 fix: Date Time shows incorrect date on UI
  web/src/components/DateTime.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/ts/interfaces/logs.ts
Labels: ☢️ Bug

#5250 fix: typography issue while build and const variable fix
  web/src/plugins/logs/SearchBar.vue
  web/tailwind.config.js
Labels: ☢️ Bug

#5241 feat: Initial left navigation changes
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/package.json
  web/src/components/MenuLink.vue
  web/src/components/ThemeSwitcher.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/traces/Index.vue
  web/src/styles/quasar-variables.sass
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Functions.vue
  web/src/views/IdentityAccessManagement.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/RealUserMonitoring.vue
Labels: ✏️ Feature

#5252 feat: add separate table for work_group
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/table/entity/README.md
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/entity/search_queue.rs
  src/infra/src/table/migration/m20241204_143100_create_table_search_queue.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/search_queue.rs
Labels: ✏️ Feature, 📒 Documentation

#5236 feat: "HTTP Layer" dashboard models
  src/config/src/meta/dashboards/mod.rs
  src/handler/http/models/dashboards.rs
  src/handler/http/models/mod.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/router/openapi.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#5257 fix: search queue table
  src/infra/src/table/migration/m20241204_143100_create_table_search_queue.rs
Labels: ☢️ Bug, 📒 Documentation

#5260 fix: locator issue for management menu
  tests/ui-testing/pages/managementPage .js
Labels: ☢️ Bug

#5262 perf: improve nats lock
  src/infra/src/db/nats.rs
Labels: 🧹 Updates

#5239 feat: Expose new fields for rendering dashboard search results
  src/handler/http/models/dashboards.rs
  src/infra/src/table/dashboards.rs
  src/service/dashboards/mod.rs
Labels: ✏️ Feature

#5263 feat: destination and template movement under management
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/ThemeSwitcher.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/router.ts
  web/src/composables/shared/useManagementRoutes.ts
  web/src/layouts/MainLayout.vue
  web/src/views/AppAlerts.vue
Labels: ✏️ Feature

#5275 fix: index setting updated time
  src/config/src/meta/stream.rs
  src/infra/src/schema/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
  src/service/stream.rs
Labels: ☢️ Bug, 🧹 Updates

#5268 perf: improve nats lock
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/ofga.rs
  src/common/migration/schema.rs
  src/handler/http/router/mod.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/nats.rs
  src/infra/src/dist_lock.rs
  src/job/compactor.rs
  src/main.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/search/cluster/flight.rs
  tests/integration_test.rs
Labels: 🧹 Updates

#5280 feat: support fuzzy query
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/udf/fuzzy_match_udf.rs
  src/service/search/datafusion/udf/match_all_udf.rs
  src/service/search/datafusion/udf/mod.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#5283 fix: update view dashboard sticky header due to header height change
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug, 🧹 Updates

#5284 feat: Limit dashboard search results
  src/config/src/meta/dashboards/mod.rs
  src/handler/http/models/dashboards.rs
  src/infra/src/table/dashboards.rs
Labels: ✏️ Feature

#5285 fix: improve Chinese
  web/src/locales/languages/zh.json
Labels: ☢️ Bug, 🧹 Updates

#5288 fix: use boolQuery replace termSet for tantivy
  src/config/src/config.rs
  src/service/search/index.rs
Labels: ☢️ Bug

#5142 fix: removal of previous node option in pipelines node
  tests/ui-testing/playwright-tests/pipelines.spec.js
  web/src/components/pipeline/NodeForm/AssociateFunction.vue
  web/src/components/pipeline/NodeForm/Condition.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/locales/languages/en.json
  web/src/plugins/pipelines/CustomEdge.vue
  web/src/plugins/pipelines/CustomNode.vue
  web/src/plugins/pipelines/useDnD.ts
Labels: ☢️ Bug

#5265 fix: Stream settings page redesign
  tests/ui-testing/playwright-tests/schema.spec.js
  web/src/components/logstream/StreamFieldInputs.vue
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#5313 test: enrichment table testcase
  tests/test-data/enrichment_info.csv
  tests/ui-testing/playwright-tests/pipelines.spec.js
Labels: 🧹 Updates

#5316 fix: route name updated from "alerts" to "alertList" in multiple components
  web/src/layouts/MainLayout.vue
  web/src/views/AppAlerts.vue
  web/src/views/HomeView.vue
Labels: ☢️ Bug, 🧹 Updates

#5315 fix: support for subqueries in dashboard
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#5310 feat: usage self-reporting enrich dashboard search context
  src/config/src/meta/search.rs
  src/service/dashboards/mod.rs
  src/service/dashboards/reports.rs
  src/service/self_reporting/ingestion.rs
Labels: ✏️ Feature

#5303 fix: save pipeline warn
  web/src/components/pipeline/PipelineEditor.vue
Labels: ☢️ Bug

#5308 chore: mark old migrations as deprecated for v0.14.0 release
  src/cli/basic/cli.rs
  src/common/migration/dashboards.rs
  src/common/migration/mod.rs
  src/common/migration/schema.rs
  src/main.rs
Labels: 🧹 Updates, ✏️ Feature

#5293 fix: merge distinct values if enable the option
  src/config/src/config.rs
  src/ingester/src/entry.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/search/datafusion/exec.rs
  src/service/traces/mod.rs
  src/wal/benches/write.rs
  src/wal/src/writer.rs
  src/wal/tests/wal.rs
Labels: ☢️ Bug

#5326 fix: redirect issue with long url
  src/common/utils/redirect_response.rs
Labels: ☢️ Bug

#5333 fix: max query range should be hour
  .github/workflows/playwright.yml
  src/service/search/mod.rs
Labels: ☢️ Bug

#5318 fix: dashboard search across folders
  web/src/components/dashboards/QueryInspector.vue
  web/src/components/dashboards/addPanel/CommonAutoComplete.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/reports/CreateReport.vue
  web/src/locales/languages/en.json
  web/src/services/dashboards.ts
  web/src/utils/commons.ts
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/addPanel/Group.vue
Labels: ☢️ Bug

#5291 fix: Improve Spanish locale
  web/src/locales/languages/es.json
Labels: ☢️ Bug, 🧹 Updates

#5325 feat: Create `alerts` table
  src/infra/src/table/entity/README.md
  src/infra/src/table/entity/alerts.rs
  src/infra/src/table/entity/folders.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/migration/m20241209_120000_create_alerts_table.rs
  src/infra/src/table/migration/mod.rs
Labels: ✏️ Feature, 📒 Documentation

#5341 fix: 5297 subqueries not being parsed in UI
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#5349 fix: some panics
  src/common/utils/auth.rs
  src/service/compact/mod.rs
  src/service/logs/mod.rs
Labels: ☢️ Bug

#5340 fix: UI fix for stream settings page
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug

#5301 fix: added fuzzy search function guide & autocomplete
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/useSuggestions.ts
  web/src/plugins/logs/SyntaxGuide.vue
Labels: ☢️ Bug, ✏️ Feature

#5359 fix: usage report is zero
  src/common/meta/organization.rs
  src/common/meta/telemetry.rs
  src/config/src/config.rs
  src/config/src/meta/self_reporting/usage.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/infra/src/cache/stats.rs
  src/infra/src/file_list/mod.rs
  src/job/metrics.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/organization.rs
  src/service/self_reporting/mod.rs
Labels: ☢️ Bug

#5361 chore: add k8s cluster name to helm chart instructions
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ✏️ Feature

#5362 fix: Fix ZO_MMDB_GEOLITE_ASNDB_SHA256_URL
  src/config/src/config.rs
Labels: ☢️ Bug

#5365 fix: short_url duplicating to meta
  src/infra/src/table/migration/m20241215_190333_delete_metas.rs
  src/infra/src/table/migration/mod.rs
  src/service/db/short_url.rs
Labels: ☢️ Bug

#5364 fix: Improve English locale
  web/src/locales/languages/en.json
Labels: ☢️ Bug, 🧹 Updates

#5353 fix: fixed explore enrichment table and overlap of logs table cell content
  web/src/components/logstream/schema.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#5367 fix: root permission bug in delete organization user
  src/service/users.rs
Labels: ☢️ Bug

#5369 fix: Removed multiple registrations of autocomplete suggestions in Query Editor
  web/src/components/QueryEditor.vue
  web/src/components/dashboards/QueryEditor.vue
Labels: ☢️ Bug, 🧹 Updates

#5372 fix: values api for single stream selection filter context
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#5375 fix: add deleted migration step back
  src/infra/src/table/migration/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#5258 test: service account API access automation
  .github/workflows/playwright.yml
  tests/ui-testing/pages/iamPage.js
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/pages/managementPage .js
  tests/ui-testing/playwright-tests/aServiceAccount.spec.js
  tests/ui-testing/playwright-tests/join.spec.js
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
  tests/ui-testing/playwright-tests/secondsPrecisionAdded.spec.js
  tests/ui-testing/playwright-tests/serviceAccount.spec.js
Labels: 🧹 Updates

#5338 fix: create destination button in add alert
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/DestinationList.vue
Labels: ☢️ Bug, ✏️ Feature

#5380 test: pipeline-api-tests
  tests/api-testing/tests/test_pipeline.py
  tests/api-testing/tests/test_prod.py
Labels: 🧹 Updates

#5385 test: pytest-scheduled-pipeline
  tests/api-testing/tests/test_pipeline.py
Labels: 🧹 Updates

#5389 fix : distinct values bug
  src/common/migration/dashboards.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/search/mod.rs
  src/infra/src/table/dashboards.rs
  src/service/dashboards/mod.rs
Labels: Invalid PR Title, ☢️ Bug

#5391 feat: Use `folder_type` parameter in internal folder methods
  src/handler/http/request/folders.rs
  src/infra/src/table/folders.rs
  src/service/dashboards/mod.rs
  src/service/folders.rs
Labels: ✏️ Feature

#5374 fix: cache partial responses only if its a range error
  src/handler/http/request/search/mod.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#5376 fix: 403 double popups issue
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/DestinationList.vue
  web/src/components/alerts/TemplateList.vue
  web/src/components/functions/AddEnrichmentTable.vue
  web/src/components/functions/AddFunction.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/iam/groups/AddGroup.vue
  web/src/components/iam/groups/AppGroups.vue
  web/src/components/iam/groups/EditGroup.vue
  web/src/components/iam/roles/AddRole.vue
  web/src/components/iam/roles/AppRoles.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/serviceAccounts/AddServiceAccount.vue
  web/src/components/iam/serviceAccounts/ServiceAccountsList.vue
  web/src/components/iam/users/User.vue
  web/src/components/login/SsoLogin.vue
  web/src/components/logstream/AddStream.vue
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/components/reports/CreateReport.vue
  web/src/components/reports/ReportList.vue
  web/src/layouts/MainLayout.vue
  web/src/views/Ingestion.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#5404 fix: Duplicate Entries in streams page
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#5403 fix: check invalid stream_name during bulk ingestion
  src/service/logs/bulk.rs
  tests/api-testing/tests/test_bulk.py
Labels: ☢️ Bug

#5394 feat: destination migration [STEP1 - create tbl]
  src/infra/src/table/entity/destinations.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/entity/templates.rs
  src/infra/src/table/migration/m20241213_102300_create_destinations_table.rs
  src/infra/src/table/migration/mod.rs
Labels: ✏️ Feature

#5395 feat: destination migration [STEP2 - populate tbl]
  src/infra/src/table/migration/m20241213_133700_populate_destinations_table.rs
  src/infra/src/table/migration/mod.rs
Labels: ✏️ Feature

#5396 feat: destination migration [FINAL - api & new type]
  Cargo.lock
  src/common/infra/config.rs
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/destinations.rs
  src/config/src/meta/mod.rs
  src/handler/http/models/destinations.rs
  src/handler/http/models/mod.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/router/openapi.rs
  src/infra/Cargo.toml
  src/infra/src/errors/mod.rs
  src/infra/src/table/destinations.rs
  src/infra/src/table/entity/destinations.rs
  src/infra/src/table/migration/m20241213_102300_create_destinations_table.rs
  src/infra/src/table/migration/m20241213_133700_populate_destinations_table.rs
  src/infra/src/table/migration/m20241216_153005_delete_metas_destinations.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/templates.rs
  src/job/mod.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  src/service/alerts/templates.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/templates.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#5393 feat: template migration [FINAL]
  src/common/migration/schema.rs
  src/config/src/meta/alerts/destinations.rs
  src/handler/http/request/alerts/templates.rs
  src/infra/src/table/migration/m20241212_132500_populate_templates_table.rs
  src/infra/src/table/migration/m20241212_172300_delete_metas.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/templates.rs
  src/job/mod.rs
  src/service/alerts/templates.rs
  src/service/db/alerts/templates.rs
Labels: ✏️ Feature

#5406 test: Service-Account-updated-automation
  tests/ui-testing/playwright-tests/aServiceAccount.spec.js
Labels: 🧹 Updates

#5413 test: pipeline updated assertions
  .github/workflows/playwright.yml
  tests/api-testing/tests/test_kinesis.py
  tests/ui-testing/playwright-tests/enrichment.spec.js
  tests/ui-testing/playwright-tests/functions.spec.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  tests/ui-testing/playwright-tests/reports.spec.js
Labels: 🧹 Updates

#5354 feat: change api call to get dashboard data and listing of data
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/services/dashboards.ts
  web/src/stores/index.ts
  web/src/utils/commons.ts
  web/src/views/Dashboards/Dashboards.vue
Labels: ✏️ Feature

#5409 fix: metrics page changes
  tests/ui-testing/pages/metricsPage.js
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/locales/languages/en.json
  web/src/plugins/metrics/Index.vue
Labels: ☢️ Bug

#5249 feat: logs support on dashboard drilldown
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
Labels: ✏️ Feature

#5077 feat: on click of refresh button or apply button only apply variables
  tests/ui-testing/playwright-tests/dashboards/dashboard-general-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-variables-setting.spec.js
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/settings/VariableCustomValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/utils/commons.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#5421 fix: add total record & index_size to summary
  src/common/meta/organization.rs
  src/service/organization.rs
Labels: ☢️ Bug, ✏️ Feature

#5342 feat: Red button feature
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/storage/mod.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/metadata/trace_list_index.rs
  src/service/stream.rs
Labels: ✏️ Feature

#5422 fix: add limit for full text search field must by text
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/udf/arr_descending_udf.rs
  src/service/search/datafusion/udf/arrcount_udf.rs
  src/service/search/datafusion/udf/arrindex_udf.rs
  src/service/search/datafusion/udf/arrjoin_udf.rs
  src/service/search/datafusion/udf/arrsort_udf.rs
  src/service/search/datafusion/udf/arrzip_udf.rs
  src/service/search/datafusion/udf/date_format_udf.rs
  src/service/search/datafusion/udf/fuzzy_match_udf.rs
  src/service/search/datafusion/udf/spath_udf.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/datafusion/udf/time_range_udf.rs
  src/service/search/datafusion/udf/transform_udf.rs
  src/service/stream.rs
  tests/integration_test.rs
Labels: ☢️ Bug, ✏️ Feature

#5414 fix: table refresh issue.
  web/src/components/functions/EnrichmentTableList.vue
  web/src/composables/useStreams.ts
Labels: ☢️ Bug

#5390 feat: Migrate alerts data out of `meta` table into `alerts` table
  Cargo.lock
  src/config/src/meta/alerts/alert.rs
  src/config/src/meta/alerts/mod.rs
  src/handler/http/request/folders.rs
  src/infra/Cargo.toml
  src/infra/src/errors/mod.rs
  src/infra/src/table/alerts/intermediate.rs
  src/infra/src/table/alerts/mod.rs
  src/infra/src/table/dashboards.rs
  src/infra/src/table/folders.rs
  src/infra/src/table/migration/m20241217_154900_alter_folders_table_idx.rs
  src/infra/src/table/migration/m20241217_155000_populate_alerts_table.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/service/alerts/alert.rs
  src/service/alerts/scheduler.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
  src/service/db/alerts/alert/old.rs
  src/service/folders.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#5405 feat: New folders endpoints that accept `folder_type` URL parameter
  src/handler/http/models/folders.rs
  src/handler/http/request/folders.rs
  src/handler/http/request/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
Labels: ✏️ Feature

#5425 feat: add grpc search endpoint
  src/config/src/meta/search.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/grpc_search.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#5429 chore: compactor pending jobs metric improvements
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: 🧹 Updates

#5430 fix: series building logic for bar type charts with breakdown field
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5423 feat: additional values for index size and docs count added
  src/common/meta/organization.rs
  src/handler/http/router/openapi.rs
  src/service/organization.rs
  tests/ui-testing/pages/homePage.js
  web/src/locales/languages/en.json
  web/src/views/HomeView.vue
Labels: ✏️ Feature, 📒 Documentation

#5433 feat: add total document count to home page
  src/common/meta/organization.rs
  src/handler/http/router/openapi.rs
  src/service/organization.rs
  web/src/locales/languages/en.json
  web/src/styles/app.scss
  web/src/utils/zincutils.ts
  web/src/views/HomeView.vue
Labels: ✏️ Feature

#5377 fix: before saving alert, check if period exceeds max_query_range for streams
  src/service/alerts/alert.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#5434 fix: removed size from aggregation search api call
  web/src/composables/useLogs.ts
  web/src/styles/app.scss
  web/src/views/HomeView.vue
Labels: ☢️ Bug, 🧹 Updates

#5436 fix: broken MySQL migration for dropping index
  src/cli/basic/cli.rs
  src/infra/src/table/migration/m20241114_000001_create_folders_table.rs
  src/infra/src/table/migration/m20241119_000001_create_dashboards_table.rs
  src/infra/src/table/migration/m20241204_143100_create_table_search_queue.rs
  src/infra/src/table/migration/m20241209_120000_create_alerts_table.rs
  src/infra/src/table/migration/m20241217_154900_alter_folders_table_idx.rs
  src/infra/src/table/mod.rs
Labels: ☢️ Bug

#5426 feat: service layer alert errors
  src/handler/http/request/alerts/alert.rs
  src/handler/http/request/alerts/mod.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
  src/service/db/alerts/alert/old.rs
Labels: ✏️ Feature

#5438 fix: fix ListFolders v2
  src/handler/http/request/folders.rs
Labels: ☢️ Bug

#5440 fix: pipeline play pause issue
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#5441 fix: wrong return type from list_alert route handle
  src/handler/http/request/alerts/alert.rs
  src/service/db/alerts/alert/new.rs
Labels: ☢️ Bug

#5437 fix: pipeline validation at API level
  .github/ISSUE_TEMPLATE/1-bug-report.yaml
  src/config/src/meta/pipeline/mod.rs
  src/handler/http/request/pipeline.rs
  src/service/db/pipeline.rs
  src/service/pipeline/mod.rs
Labels: ☢️ Bug

#5442 fix: check max_query_range for pipeline save
  src/service/alerts/derived_streams.rs
Labels: ☢️ Bug

#5435 test: add fuzzy and values UI test
  tests/api-testing/tests/test_fuzzy.py
  tests/ui-testing/playwright-tests/logsqueries.spec.js
Labels: 🧹 Updates, ✏️ Feature

#5444 fix: changed label
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#5322 feat: impl background job manager
  src/common/utils/auth.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/meta/search.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/job.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/search/utils.rs
  src/handler/http/router/mod.rs
  src/infra/src/storage/mod.rs
  src/infra/src/table/alerts/intermediate.rs
  src/infra/src/table/entity/distinct_value_fields.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/entity/search_job_partitions.rs
  src/infra/src/table/entity/search_job_results.rs
  src/infra/src/table/entity/search_jobs.rs
  src/infra/src/table/migration/m20241222_085111_search_jobs.rs
  src/infra/src/table/migration/m20241222_085135_search_job_partitions.rs
  src/infra/src/table/migration/m20241222_085148_search_job_results.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/search_job/common.rs
  src/infra/src/table/search_job/mod.rs
  src/infra/src/table/search_job/search_job_partitions.rs
  src/infra/src/table/search_job/search_job_results.rs
  src/infra/src/table/search_job/search_jobs.rs
  src/job/alert_manager.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/db/mod.rs
  src/service/db/search_job/mod.rs
  src/service/db/search_job/search_job_partitions.rs
  src/service/db/search_job/search_job_results.rs
  src/service/db/search_job/search_jobs.rs
  src/service/mod.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/grpc_search.rs
  src/service/search/mod.rs
  src/service/search_jobs.rs
Labels: ✏️ Feature, 📒 Documentation

#5447 fix: logs-traces correlation UI issues
  web/src/composables/shared/router.ts
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#5452 feat: support cross stream type join
  src/config/src/config.rs
  src/config/src/meta/sql.rs
  src/config/src/meta/stream.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/table_provider/catalog.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/flight.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  tests/api-testing/tests/test_search.py
Labels: ✏️ Feature

#5454 feat: maxmind enterprise db
  Cargo.lock
  src/common/infra/config.rs
  src/common/utils/functions.rs
  src/config/Cargo.toml
  src/config/src/utils/download_utils.rs
  src/config/src/utils/mod.rs
  src/job/mmdb_downloader.rs
  src/service/enrichment_table/geoip.rs
Labels: ✏️ Feature

#5460 fix: on edit panel, query reset issue
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug

#5461 test: added PyTest for reset passcode
  tests/api-testing/tests/test_organisations.py
Labels: 🧹 Updates, ✏️ Feature

#5457 feat: support grpc search partition
  src/handler/grpc/request/search/mod.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/grpc.rs
  src/service/search/grpc_search.rs
  src/service/search/mod.rs
  src/service/search_jobs.rs
Labels: ✏️ Feature

#5465 test: PyTest organizations Updated
  tests/api-testing/tests/test_organisations.py
Labels: 🧹 Updates

#5466 perf: test parallels calculate data points
  src/service/promql/engine.rs
  src/service/promql/exec.rs
  src/service/promql/search/mod.rs
Labels: 🧹 Updates

#5483 fix: metric chart issue for promql query
  web/src/plugins/metrics/Index.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5469 feat: Alerts API v2 - part 1 - HTTP layer models
  Cargo.lock
  Cargo.toml
  src/config/src/meta/alerts/alert.rs
  src/handler/http/models/alerts/mod.rs
  src/handler/http/models/alerts/requests.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/models/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/errors/mod.rs
  src/infra/src/table/alerts/mod.rs
  src/infra/src/table/folders.rs
Labels: ✏️ Feature

#5470 feat: Alerts API v2 - part 2 - rename methods
  src/handler/http/request/alerts/alert.rs
  src/service/alerts/alert.rs
  src/service/alerts/scheduler.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
  src/service/db/alerts/alert/old.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#5471 feat: Alerts API v2 - part 3 - deprecate old endpoints
  src/handler/http/request/alerts/deprecated.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
Labels: ✏️ Feature

#5472 feat: Alerts API v2 - part 4 - new `GetAlert` (by KSUID) endpoint
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5473 feat: Alerts API v2 - part 5 - new `CreateAlert` (with folder) endpoint
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5474 feat: Alerts API v2 - part 6 - new `UpdateAlert` (by KSUID) endpoint
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: 🧹 Updates, ✏️ Feature

#5475 feat: Alerts API v2 - part 7 - new `Delete`, `Trigger`, `Enable` (by KSUID) endpoints
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5477 feat: Alerts API v2 - part 8 - new `ListAlerts` (with folder) endpoint
  src/config/src/meta/alerts/alert.rs
  src/handler/http/models/alerts/requests.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5487 feat: Alerts API v2 - part 9 - cleanup
  src/handler/http/models/alerts/mod.rs
  src/handler/http/request/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
Labels: ✏️ Feature

#5485 feat: add align point time when cache enabled
  src/common/meta/prom.rs
  src/config/src/config.rs
  src/handler/grpc/mod.rs
  src/handler/http/request/prom/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/errors/mod.rs
  src/job/mmdb_downloader.rs
  src/proto/proto/cluster/metrics.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/promql/engine.rs
  src/service/promql/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/mod.rs
  src/service/promql/value.rs
Labels: ✏️ Feature

#5490 fix: trace_id error of tracing
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
Labels: ☢️ Bug

#5494 fix: pipeline should allow number as variable in stream name
  src/service/pipeline/batch_execution.rs
Labels: ☢️ Bug

#5500 fix: test_histogram
  src/common/utils/websocket.rs
Labels: ☢️ Bug, 🧹 Updates

#5505 feat: introduce root only login
  src/handler/http/auth/validator.rs
  src/handler/http/request/users/mod.rs
Labels: ✏️ Feature

#5416 test: join automation updated
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/join.spec.js
Labels: 🧹 Updates

#5504 fix: search data with WAL for promql
  src/config/src/meta/stream.rs
  src/handler/grpc/request/ingest.rs
  src/handler/grpc/request/metrics/querier.rs
  src/job/prom_self_consume.rs
  src/proto/build.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/ingest.proto
  src/proto/proto/cluster/metrics.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/scheduler.rs
  src/service/promql/engine.rs
  src/service/promql/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/promql/utils.rs
  src/service/search/cluster/flight.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
  src/service/self_reporting/ingestion.rs
Labels: ☢️ Bug

#5516 fix: short_url super cluster support
  src/infra/src/table/short_urls.rs
  src/service/db/short_url.rs
Labels: ☢️ Bug

#5519 fix: alerts OpenAPI docs
  src/handler/http/models/alerts/mod.rs
  src/handler/http/models/alerts/requests.rs
Labels: ☢️ Bug, 📒 Documentation
