Repository openobserve/openobserve, pull requests merged in 2024-05, with the labels that each got.

#3389 fix: bump up node to 20 and test
  .github/workflows/js-license-checker.yml
Labels: 🤖 Dependencies, ☢️ Bug, 🧹 Updates

#3388 fix: realtime alert schedule
  Cargo.lock
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/job/alert_manager.rs
  src/job/files/parquet.rs
  src/service/alerts/alert_manager.rs
  src/service/compact/merge.rs
  src/service/db/alerts/mod.rs
  src/service/db/alerts/realtime_triggers.rs
  src/service/db/scheduler.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#3394 fix: unwanted route path
  web/src/enterprise/composables/router.ts
Labels: ☢️ Bug

#3391 fix: reporting usage remotely
  src/service/usage/mod.rs
Labels: ☢️ Bug

#3396 fix: add compress for schema cache
  Cargo.lock
  src/common/meta/telemetry.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/infra/Cargo.toml
  src/infra/src/db/mysql.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/schema/mod.rs
  src/service/compact/file_list.rs
  src/service/compact/retention.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/stream.rs
Labels: ☢️ Bug, ✏️ Feature

#3400 fix: UI - cloudwatch ingestion endpoints
  web/src/components/ingestion/logs/KinesisFirehose.vue
  web/src/components/ingestion/metrics/CloudWatchMetrics.vue
Labels: ☢️ Bug

#3404 fix: RBAC for native users
  src/handler/http/auth/validator.rs
  src/handler/http/request/stream/mod.rs
Labels: ☢️ Bug

#3408 fix: removed google fonts and loaded to local
  web/index.html
  web/src/styles/fonts/pe0RMImSLYBIv1o4X1M8cce4OdVisMz5nZRqy6cmmmU3t2FQWEAEOvV9wNvrwlNstMKW3Y6K5WMwd-1aLZx3lE4-Hw.woff2
  web/src/styles/fonts/pe0RMImSLYBIv1o4X1M8cce4OdVisMz5nZRqy6cmmmU3t2FQWEAEOvV9wNvrwlNstMKW3Y6K5WMwd-RaLZx3lE4-Hw.woff2
  web/src/styles/fonts/pe0RMImSLYBIv1o4X1M8cce4OdVisMz5nZRqy6cmmmU3t2FQWEAEOvV9wNvrwlNstMKW3Y6K5WMwd-ZaLZx3lE4-Hw.woff2
  web/src/styles/fonts/pe0RMImSLYBIv1o4X1M8cce4OdVisMz5nZRqy6cmmmU3t2FQWEAEOvV9wNvrwlNstMKW3Y6K5WMwd-daLZx3lE4-Hw.woff2
  web/src/styles/fonts/pe0RMImSLYBIv1o4X1M8cce4OdVisMz5nZRqy6cmmmU3t2FQWEAEOvV9wNvrwlNstMKW3Y6K5WMwd-laLZx3lE4.woff2
  web/src/styles/fonts/pe0TMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp7t1R-tQKr51.woff2
  web/src/styles/fonts/pe0TMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp7t4R-tQKr51pE8.woff2
  web/src/styles/fonts/pe0TMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp7t6R-tQKr51pE8.woff2
  web/src/styles/fonts/pe0TMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp7t7R-tQKr51pE8.woff2
  web/src/styles/fonts/pe0TMImSLYBIv1o4X1M8ce2xCx3yop4tQpF_MeTm0lfGWVpNn64CL7U8upHZIbMV51Q42ptCp7txR-tQKr51pE8.woff2
  web/src/styles/quasar-overrides.scss
Labels: ☢️ Bug, 🧹 Updates

#3407 fix: get schema versions fix
  src/infra/src/schema/mod.rs
Labels: ☢️ Bug

#3402 fix(auth): fix password with colons
  src/handler/http/auth/validator.rs
Labels: ☢️ Bug

#3411 fix: german translation of apply
  web/src/locales/languages/de.json
Labels: ☢️ Bug

#3319 feat: multi cache dir for improve disk cache io
  src/config/src/config.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
Labels: 🧹 Updates, ✏️ Feature

#3416 feat: add file_list history for data retention
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/sql.rs
  src/config/src/meta/stream.rs
  src/handler/http/router/ui.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/service/compact/retention.rs
  src/service/search/grpc/wal.rs
Labels: ✏️ Feature

#3399 fix: only get required versions while watching
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/schema/mod.rs
  src/job/files/parquet.rs
  src/service/db/schema.rs
  src/service/logs/bulk.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  tests/ui-testing/cypress/e2e/tests/logs_quickmode.cy.js
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3282 feat: data ingestion pipeline
  src/common/infra/config.rs
  src/common/meta/functions.rs
  src/common/meta/mod.rs
  src/common/meta/pipelines.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/pipelines.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/pipelines.rs
  src/service/ingestion/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/mod.rs
  src/service/pipelines.rs
  tests/ui-testing/cypress/e2e/tests/functions_tests.cy.js
  tests/ui-testing/cypress/e2e/tests/logs_tests.cy.js
  web/package-lock.json
  web/package.json
  web/src/assets/images/pipeline/condition.svg
  web/src/assets/images/pipeline/function.svg
  web/src/assets/images/pipeline/route.svg
  web/src/assets/images/pipeline/stream.svg
  web/src/components/alerts/FieldsInput.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/functions/AddFunction.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/functions/StreamRouting.vue
  web/src/components/pipeline/AssociateFunction.vue
  web/src/components/pipeline/NodeLinks.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelineEditorDemo.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/components/pipeline/StreamRouting.vue
  web/src/components/pipeline/StreamSelection.vue
  web/src/composables/shared/router.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/mixins/mainLayout.mixin.ts
  web/src/plugins/traces/TraceDetails.vue
  web/src/services/pipelines.ts
  web/src/utils/traces/convertTraceData.ts
  web/src/views/Functions.vue
  web/src/views/HomeView.vue
  web/tsconfig.json
Labels: ✏️ Feature

#3418 fix: Ingestion pipeline UI issues
  web/src/composables/shared/router.ts
  web/src/views/Functions.vue
Labels: ☢️ Bug

#3419 feat: add schema history
  src/handler/http/router/ui.rs
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/lib.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/schema/history/mod.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/infra/src/schema/history/sqlite.rs
  src/infra/src/schema/mod.rs
  src/job/files/parquet.rs
  src/service/compact/retention.rs
  src/service/db/schema.rs
  src/service/search/grpc/wal.rs
Labels: ✏️ Feature

#3423 fix: can't query old data
  src/config/src/meta/sql.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#3420 fix: added missing test id's for pipeline UI
  web/src/components/SanitizedHtmlRenderer.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/components/pipeline/AssociateFunction.vue
  web/src/components/pipeline/NodeLinks.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelineEditorDemo.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/components/pipeline/StreamRouting.vue
  web/src/components/pipeline/StreamSelection.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/metrics/Index.vue
  web/src/plugins/traces/Index.vue
  web/src/views/MemberSubscription.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#3428 feat: improve super cluster
  Cargo.lock
  Cargo.toml
  src/cli/data/export.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/mod.rs
  src/proto/proto/cluster/search.proto
  src/router/grpc/ingest/mod.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/db/file_list/broadcast.rs
  src/service/file_list.rs
  src/service/metrics/prom.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/grpc.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/grpc/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/usage/ingestion_service.rs
  src/service/usage/stats.rs
Labels: 🧹 Updates, ✏️ Feature

#3429 fix: value API
  Cargo.lock
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#3431 fix: ofga disable native user bug
  src/handler/http/auth/validator.rs
Labels: ☢️ Bug

#3437 fix: super cluster region filter
  src/handler/http/request/clusters/mod.rs
  src/service/db/schema.rs
  src/service/functions.rs
  src/service/organization.rs
Labels: ☢️ Bug

#3440 feat: add config for super cluster
  src/handler/http/request/status/mod.rs
Labels: ✏️ Feature

#3436 fix: dashboard variables values API context SQL
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ☢️ Bug

#3143 test: logs quickmode playwright tests
  .github/workflows/js-license-checker.yml
  .github/workflows/playwright.yml
  tests/ui-testing/.gitignore
  tests/ui-testing/cypress/fixtures/log.json
  tests/ui-testing/package-lock.json
  tests/ui-testing/package.json
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/functions.spec.js
  tests/ui-testing/playwright-tests/login/auth.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright.config.js
Labels: 🧹 Updates

#3447 fix: pipeline UI issues
  web/src/components/icons/PipelineIcon.vue
  web/src/components/pipeline/AssociateFunction.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/components/pipeline/StreamSelection.vue
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/mixins/mainLayout.mixin.ts
  web/src/views/Functions.vue
Labels: ☢️ Bug

#3449 fix: add region filter to _value and _around API
  src/cli/data/export.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/job/files/parquet.rs
  src/service/alerts/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#3410 fix: bundle split
  web/.eslintrc.cjs
  web/package-lock.json
  web/package.json
  web/src/components/AutoRefreshInterval.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/useTraces.ts
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/router/routes.ts
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/src/views/Login.vue
  web/src/views/MemberSubscription.vue
  web/vite.config.ts
Labels: ☢️ Bug

#3451 test: e2e pipeline testcases
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/functions.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/pipeline.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#3452 fix: bulk api response change
  src/config/src/config.rs
  src/service/logs/bulk.rs
Labels: ☢️ Bug

#3443 fix: misleading or wrong german translations
  web/src/locales/languages/de.json
Labels: ☢️ Bug

#3434 fix: watch session cache for single node
  src/common/utils/auth.rs
  src/job/mod.rs
Labels: ☢️ Bug

#3462 fix: dashboard stacked chart wrong data render issue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#3461 fix: rbac permission for fetching group and role permissions
  src/common/utils/auth.rs
Labels: ☢️ Bug

#3446 feat: region selection on logs page
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SyntaxGuide.vue
  web/src/services/search.ts
  web/src/services/stream.ts
  web/src/stores/index.ts
Labels: ✏️ Feature

#3466 fix: saved view selection
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3468 test: multi-select variables-logs-testcases
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/variable.spec.js
Labels: 🧹 Updates

#3469 fix: saved view region issue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3470 fix: pipeline RBAC issues
  src/common/utils/auth.rs
  src/handler/http/request/pipelines.rs
  src/service/pipelines.rs
Labels: ☢️ Bug

#3476 test: fix flaky testcase
  tests/ui-testing/playwright-tests/pipeline.spec.js
Labels: ☢️ Bug, 🧹 Updates

#3477 feat: User defined schema for existing streams
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/components/common/AppTabs.vue
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/schema.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#3456 fix: logs count call split
  tests/ui-testing/cypress/e2e/tests/logs_quickmode.cy.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#3481 test: e2e-search-around
  tests/ui-testing/playwright-tests/logspage.spec.js
Labels: ☢️ Bug, 🧹 Updates

#3482 fix: user, pipeline list rbac issues
  src/service/pipelines.rs
  src/service/users.rs
Labels: ☢️ Bug

#3454 feat: only write defined schema fields to parquet
  src/config/src/utils/json.rs
  src/config/src/utils/record_batch_ext.rs
  src/config/src/utils/schema_ext.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/schema/mod.rs
  src/ingester/src/entry.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/service/compact/file_list.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/schema.rs
  src/service/search/datafusion/exec.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ✏️ Feature

#3490 test: e2e-region-testcases
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/region.spec.js
Labels: 🧹 Updates

#3484 fix: don't set rbac ownership for creating default folders
  src/service/dashboards/folders.rs
Labels: ☢️ Bug

#3492 fix: region filter for _around API
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#3494 test: e2e-user-defined-schema
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/region.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
Labels: 🧹 Updates

#3497 fix: around API with function
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#3506 fix: case sensitive email replace with lowercase
  web/src/enterprise/components/users/User.vue
Labels: ☢️ Bug

#3505 fix: invalid peer certificate
  Cargo.lock
  Cargo.toml
  src/common/utils/auth.rs
  src/handler/http/auth/token.rs
  src/handler/http/request/search/job.rs
  src/service/ingestion/mod.rs
  web/src/components/queries/RunningQueriesList.vue
  web/src/services/search.ts
Labels: ☢️ Bug

#3510 test: add-dashboard-image-tests
  .github/workflows/playwright.yml
  tests/ui-testing/package-lock.json
  tests/ui-testing/package.json
  tests/ui-testing/playwright-tests/dashboard-snaps/areachart-screenshot.png
  tests/ui-testing/playwright-tests/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates, ✏️ Feature

#3512 feat: add a new new function for read recordbatch from file
  src/config/src/utils/parquet.rs
Labels: ✏️ Feature

#3515 chore: add editions
  README.md
Labels: Invalid PR Title, ✏️ Feature, 📒 Documentation

#3516 fix: pipelines with same name
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#3524 fix: histogram not loading navigating from stream explorer page and a…
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#3527 chore: add QoS to feature list
  README.md
Labels: ✏️ Feature, 📒 Documentation

#3533 test: e2e-match-all-cases-sanity
  tests/ui-testing/playwright-tests/dashboard-snaps/areachart-screenshot.png
  tests/ui-testing/playwright-tests/indexquery.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#3368 fix: GET rbac permission for settings
  src/common/utils/auth.rs
  web/src/components/settings/General.vue
Labels: ☢️ Bug

#3534 chore: Add audit trail feature
  README.md
Labels: ✏️ Feature, 📒 Documentation

#3455 chore: added org_id & stream_name to apply_vrl_fn error logging
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/multi.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp_grpc.rs
  src/service/metrics/otlp_http.rs
  src/service/metrics/prom.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/datafusion/exec.rs
  src/service/traces/mod.rs
  src/service/traces/otlp_http.rs
Labels: ✏️ Feature

#3544 fix: inverted index create error when the recordbatch is empty
  src/config/src/utils/arrow.rs
  src/infra/src/schema/mod.rs
  src/job/files/parquet.rs
  src/service/logs/multi.rs
  src/service/schema.rs
Labels: ☢️ Bug, ✏️ Feature

#3537 fix: Update useLogs.ts
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#3547 refactor: merge parquet files interface
  .github/workflows/unit-tests.yml
  Cargo.lock
  Cargo.toml
  deploy/build/buildspec-test.yml
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
Labels: 🧹 Updates

#3548 fix: hide pipeline menu
  web/src/views/Functions.vue
Labels: ☢️ Bug

#3550 feat: login using basic auth headers
  src/handler/http/request/users/mod.rs
Labels: ✏️ Feature, enterprise feature

#3519 fix: user defined schema option on logs fields panel
  web/src/composables/useLogs.ts
  web/src/composables/useSuggestions.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#3555 test: e2e-schema-testcases
  tests/ui-testing/playwright-tests/schema.spec.js
Labels: 🧹 Updates

#3421 feat: dashboard date-time settings
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/AddDashboard.vue
  web/src/components/dashboards/settings/GeneralSettings.vue
  web/src/composables/shared/router.ts
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#3556 fix: use defined schema for vertical partition merge
  src/config/src/utils/record_batch_ext.rs
  src/job/compact.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/db/schema.rs
  src/service/schema.rs
Labels: ☢️ Bug

#3560 fix: search count wrong
  src/service/search/cluster/mod.rs
Labels: ☢️ Bug

#3564 fix: report issues
  src/common/utils/auth.rs
  src/job/alert_manager.rs
  src/service/alerts/alert_manager.rs
  src/service/dashboards/reports.rs
  src/service/db/dashboards/reports.rs
  src/service/db/scheduler.rs
Labels: ☢️ Bug

#3566 fix: added clusters along with regions on UI
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/services/search.ts
Labels: ☢️ Bug, ✏️ Feature

#3570 fix: su total took for two api endpoints and toLocaleString fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3559 feat: cluster selection in logs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/metrics/ingest.rs
  src/handler/http/request/search/mod.rs
Labels: ✏️ Feature

#3563 feat: use a separate chrome server for report
  src/common/meta/dashboards/reports.rs
  src/config/src/config.rs
  src/service/dashboards/reports.rs
Labels: ✏️ Feature

#3572 fix: report UI issues
  web/src/components/reports/CreateReport.vue
Labels: ☢️ Bug

#3574 fix: add dynamic variables to report and allow v1, v2 dashboards in reports
  src/common/meta/dashboards/reports.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug, ✏️ Feature

#3576 fix: count mismatch
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3571 test: e2e-reports-testcases
  .github/workflows/ui-testing.yml
  tests/ui-testing/playwright-tests/reports.spec.js
Labels: 🧹 Updates

#3577 feat: let consistent hash vnode num become an evironment
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
Labels: ✏️ Feature

#3581 feat: support build-type in configuration
  src/handler/http/request/status/mod.rs
Labels: ✏️ Feature

#3554 fix: fields getting duplicated in user defined schema
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug

#3580 fix: _value api missing "clusters"
  web/src/plugins/logs/IndexList.vue
  web/src/services/stream.ts
Labels: ☢️ Bug

#3582 perf: testing optimise aggeration query
  src/config/src/config.rs
  src/config/src/utils/parquet.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates

#3536 fix: sso member roles for an org should not be changeable via UI
  src/service/users.rs
Labels: ☢️ Bug

#3590 fix: _around api for query with limit
  src/handler/http/request/search/mod.rs
  tests/ui-testing/playwright-tests/dashboard-snaps/areachart-screenshot.png
  tests/ui-testing/playwright-tests/logspage.spec.js
Labels: ☢️ Bug

#3594 fix: fixed rrweb player import
  web/src/components/rum/VideoPlayer.vue
Labels: ☢️ Bug

#3578 fix: get auth headers
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#3586 fix: logs page histogram optimisation
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboardtype.spec.js
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3597 fix: search partition with base64
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3600 fix: evoked updateQueryValue on loading of parser
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
Labels: ☢️ Bug, 🧹 Updates

#3583 feat: integrate embedded reportserver
  Cargo.lock
  Cargo.toml
  deny.toml
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/job/alert_manager.rs
  src/reportserver/Cargo.toml
  src/reportserver/src/lib.rs
  src/reportserver/src/models.rs
  src/reportserver/src/report.rs
  src/reportserver/src/router.rs
  src/reportserver/src/server.rs
  src/service/dashboards/reports.rs
Labels: ✏️ Feature

#3603 fix: ofga check versions before acquiring lock
  src/common/infra/ofga.rs
Labels: ☢️ Bug

#3606 fix: dashboard view panel refresh issue
  web/src/utils/dashboard/convertPanelData.ts
Labels: ☢️ Bug

#3607 feat: add histogram interval for search api
  src/config/src/meta/search.rs
  src/infra/src/db/nats.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#3613 refactor: rename match_all & match_all_indexed
  src/service/search/datafusion/mod.rs
  src/service/search/sql.rs
  tests/api-testing/tests/test_search.py
Labels: 🧹 Updates

#3610 fix: allow add older data with schema change
  Cargo.toml
  src/infra/src/db/etcd.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/service/db/schema.rs
  src/service/logs/bulk.rs
  src/service/logs/mod.rs
  src/service/schema.rs
  src/service/search/cluster/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#3616 test: e2e-sanity -testcases
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#3617 fix: prefetching monaco editor
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/vite.config.ts
Labels: ☢️ Bug

#3608 fix: histogram error sql mode
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#3625 fix: reload .env
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
Labels: ☢️ Bug

#3628 fix: pagination and show message for aggregation query
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#3629 chore: fix some comments
  CONTRIBUTING.md
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 📒 Documentation

#3633 fix: select case when report field not found
  src/config/src/meta/sql.rs
Labels: ☢️ Bug

#3589 feat: add new node role flatten_compactor
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/migration/file_list.rs
  src/common/migration/meta.rs
  src/common/utils/auth.rs
  src/common/utils/stream.rs
  src/config/src/cluster.rs
  src/config/src/meta/cluster.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/request/file_list.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/storage/local.rs
  src/infra/src/storage/remote.rs
  src/job/compactor.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/job/flatten_compactor.rs
  src/job/mod.rs
  src/service/compact/file_list_deleted.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/file_list.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/http.rs
  src/service/search/cluster/mod.rs
  src/service/search/cluster/super_cluster.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#3632 fix: NaN issue on pagination message
  web/src/components/DateTime.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#3634 fix: openapi menu changes
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#3622 perf: improve file move on ingester
  Cargo.lock
  Cargo.toml
  src/common/migration/file_list.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/utils/file.rs
  src/infra/src/db/nats.rs
  src/ingester/src/lib.rs
  src/job/compactor.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
Labels: 🧹 Updates

#3636 fix: change the log level for move file
  src/job/files/parquet.rs
Labels: ☢️ Bug

#3543 feat: dashboard variables adding options
  src/common/meta/dashboards/v3/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DashboardMapQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/components/dashboards/addPanel/Drilldown.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#3523 fix: Auto Complete promql legend on select not getting proper value with {
  web/src/components/dashboards/addPanel/ConfigPanel.vue
Labels: ☢️ Bug

#3639 fix: histogram for aggregation query
  web/src/composables/useLogs.ts
Labels: Invalid PR Title, 🧹 Updates

#3638 perf: improve search limit logic
  src/common/meta/dashboards/v3/mod.rs
  src/config/src/config.rs
  src/infra/src/db/nats.rs
  src/service/search/sql.rs
Labels: 🧹 Updates

#3642 fix: dashboard fullscreen css issues
  web/src/components/AutoRefreshInterval.vue
  web/src/components/DateTime.vue
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
Labels: ☢️ Bug

#3645 fix: revert renaming match_all
  src/service/search/datafusion/mod.rs
  src/service/search/sql.rs
  tests/api-testing/tests/test_search.py
Labels: ☢️ Bug

#3650 fix: format the WHERE IN clause in scheduler mysql pull query
  src/infra/src/scheduler/mysql.rs
Labels: ☢️ Bug

#3651 fix: panic when format recordbatch
  Cargo.toml
  src/config/src/utils/record_batch_ext.rs
Labels: ☢️ Bug

#3647 fix: removed partition api while aggregation query
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug, 🧹 Updates

#3653 fix: Traces query editor issue
  web/src/components/alerts/AlertList.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/QueryEditor.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/TraceDetails.vue
Labels: ☢️ Bug

#3655 fix: removed trackhits from histogram query
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates
