Repository openobserve/openobserve, pull requests merged in 2025-06, with the labels that each got.

#6871 fix: delay for scheduled pipeline
  src/common/migration/pipeline_func.rs
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/pipeline/components.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/search/grpc/storage.rs
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#6992 fix: reset stream stats with limit
  src/cli/basic/cli.rs
  src/service/compact/stats.rs
Labels: ☢️ Bug

#6993 fix: add output format type for external destination(pipeline destination)
  src/handler/http/models/destinations.rs
  web/src/components/alerts/AddDestination.vue
  web/src/components/pipeline/NodeForm/ExternalDestination.vue
  web/src/ts/interfaces/alert.ts
Labels: ☢️ Bug, ✏️ Feature

#6994 fix: reset stream stats with limit
  src/cli/basic/cli.rs
  src/service/compact/stats.rs
Labels: ☢️ Bug

#7006 chore: Update coverage.sh
  coverage.sh
Labels: 🧹 Updates

#7007 fix: scheduled pipeline align query time instead of next_run_at
  src/service/alerts/derived_streams.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#7011 fix: missing coverage import in test-file
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
Labels: ☢️ Bug, 🧹 Updates

#7010 ci: update release pipeline with s3 upload
  .github/workflows/release.yml
Labels: 🧹 Updates

#7013 fix: missing code coverage import in test-file
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: ☢️ Bug, 🧹 Updates

#7016 fix: a corner case for join match one
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/plan/deduplication_exec.rs
Labels: ☢️ Bug

#7015 chore: port scheduled pipeline fix
  src/config/src/meta/alerts/mod.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#6965 fix: fixed auto-refresh-interval for logs http2 streaming
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7023 fix: parquet not found on ingester
  src/job/files/parquet.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#7024 fix: parquet not found on ingester
  src/job/files/parquet.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#7025 fix: allow to select and copy series name from tooltip
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#7026 fix: redirect short url
  src/common/utils/redirect_response.rs
  src/handler/http/request/short_url/mod.rs
  src/service/short_url.rs
  web/src/composables/shared/router.ts
  web/src/services/short_url.ts
  web/src/views/ShortUrl.vue
Labels: ☢️ Bug

#7009 fix: menu , list , item-label at global css should not have fixed width
  web/src/styles/tailwind.css
Labels: ☢️ Bug

#7021 fix: _around api rbac returns 403 error
  src/common/utils/auth.rs
Labels: ☢️ Bug

#7047 fix: deserialize from `member` to `admin`
  src/infra/src/table/migration/m20241227_000400_populate_users_table.rs
Labels: ☢️ Bug

#7050 fix: disable search job popup
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7058 fix: saved views for long queries
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#7054 fix: increase test case coverage
  coverage.sh
  src/common/utils/auth_tests.rs
  src/service/circuit_breaker.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/search/cache/multi.rs
  src/service/search/datafusion/distributed_plan/streaming_aggs_exec.rs
  src/service/search/index.rs
  src/service/search/search_stream.rs
  src/service/search/tantivy/puffin_directory/reader.rs
  src/service/short_url.rs
Labels: ☢️ Bug, 🧹 Updates

#7049 fix: use sql ast to check distinct
  src/config/src/utils/sql.rs
Labels: ☢️ Bug

#7059 fix: pipeline aligned end time boundary should be divisible by the frequency
  src/config/src/meta/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#7065 fix: debug wal file lock issue
  src/handler/grpc/flight/mod.rs
  src/handler/http/request/short_url/mod.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#7066 fix: debug wal file lock issue
  src/handler/grpc/flight/mod.rs
  src/service/circuit_breaker.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#6879 fix: fixed http partition pagination
  tests/ui-testing/pages/streamsPage.js
  tests/ui-testing/pages/tracesPage.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
  web/src/composables/useLogs.ts
  web/src/composables/useStreamingSearch.ts
Labels: ☢️ Bug

#7033 fix: redirect short url (#7026)
  src/common/utils/redirect_response.rs
  src/handler/http/request/short_url/mod.rs
  src/service/short_url.rs
  web/src/composables/shared/router.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/services/short_url.ts
  web/src/test/unit/helpers/handlers.ts
  web/src/views/ShortUrl.spec.ts
  web/src/views/ShortUrl.vue
  web/src/views/__snapshots__/ShortUrl.spec.ts.snap
Labels: ☢️ Bug

#7068 ci: improve unit test coverage
  .gitignore
  coverage.sh
  src/cli/data/mod.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/config.rs
  src/common/infra/wal.rs
  src/common/meta/authz.rs
  src/common/meta/http.rs
  src/common/meta/ingestion.rs
  src/common/meta/proxy.rs
  src/common/meta/search.rs
  src/common/meta/service.rs
  src/common/meta/service_account.rs
  src/common/meta/stream.rs
  src/common/meta/syslog.rs
  src/common/meta/traces.rs
  src/common/meta/user.rs
  src/common/utils/functions.rs
  src/common/utils/http.rs
  src/common/utils/zo_logger.rs
  src/config/src/ider.rs
  src/config/src/meta/function.rs
  src/config/src/router.rs
  src/config/src/utils/arrow.rs
  src/config/src/utils/parquet.rs
  src/config/src/utils/prom_json_encoder.rs
  src/config/src/utils/rand.rs
  src/config/src/utils/size.rs
  src/config/src/utils/sysinfo/os.rs
Labels: 🧹 Updates

#7040 fix: align_time allow frequency to be optional
  src/config/src/meta/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#7060 fix: added regions and clusters in logs URL
  web/src/composables/useLogs.ts
  web/src/views/ShortUrl.vue
Labels: ☢️ Bug, ✏️ Feature

#7043 feat: support hec format for ingestion
  src/common/meta/ingestion.rs
  src/config/src/meta/self_reporting/usage.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/short_url/mod.rs
  src/handler/http/router/mod.rs
  src/service/logs/hec.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  tests/integration_test.rs
Labels: ✏️ Feature, 📒 Documentation

#7055 fix: ai tool changes
  src/handler/http/models/ai.rs
  src/handler/http/request/ai.rs
  src/service/functions.rs
Labels: ☢️ Bug

#7051 test: re_match, partition search and values API pytest
  tests/api-testing/tests/test_streaming.py
Labels: 🧹 Updates

#7069 fix: upgrade node sql parser npm package
  web/package-lock.json
  web/package.json
Labels: ☢️ Bug

#7067 fix: get roles api should be triggered in non enterprise versions
  web/src/components/iam/users/User.vue
Labels: ☢️ Bug

#7083 fix: disable search job popup (#7050)
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7082 fix: use stats for partition api
  src/config/src/meta/stream.rs
  src/service/search/mod.rs
  src/service/stream.rs
Labels: ☢️ Bug

#7079 feat: impl summary_percentile based on summary stream
  src/config/src/utils/sql.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/udaf/mod.rs
  src/service/search/datafusion/udaf/summary_percentile.rs
Labels: ✏️ Feature

#7042 fix: _around api rbac returns 403 error
  src/common/utils/auth.rs
Labels: ☢️ Bug

#7089 fix: pipeline dynamic stream name issue
  web/src/components/pipeline/NodeForm/Stream.vue
Labels: ☢️ Bug

#7074 fix: return header size wal builder
  src/config/src/metrics.rs
  src/main.rs
  src/service/pipeline/batch_execution.rs
  src/wal/src/writer.rs
Labels: ☢️ Bug

#7091 feat: impl summary percentile
  src/config/src/utils/sql.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/udaf/mod.rs
  src/service/search/datafusion/udaf/summary_percentile.rs
Labels: ✏️ Feature

#7090 fix: summary_percentile null value issue
  src/service/search/datafusion/udaf/summary_percentile.rs
Labels: ☢️ Bug

#7092 fix: change stream name label to o2_stream_name
  src/config/src/config.rs
  src/service/logs/loki.rs
  src/service/promql/search/grpc/wal.rs
Labels: ☢️ Bug, Review effort 3/5

#7084 test: use multiple dbs
  .github/workflows/unit-tests.yml
  coverage.sh
  src/handler/grpc/auth/mod.rs
  src/service/users.rs
Labels: 🧹 Updates

#7099 fix: `NOT IN` filter parsing issue for visualization
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#7107 fix: http2 streaming in Safari browser
  web/src/composables/useStreamingSearch.ts
  web/src/workers/streamWorker.js
Labels: ☢️ Bug

#7110 feat: add like to dashboard optimizer
  src/service/search/sql.rs
Labels: ✏️ Feature

#7106 fix: improve streaming output
  Cargo.lock
  Cargo.toml
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/distributed_plan/streaming_aggs_exec.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 3/5

#7114 feat: optimizer dashboard select all
  src/service/search/sql.rs
Labels: ✏️ Feature, Review effort 3/5

#7112 fix: fixed short url redirection issue
  web/src/views/ShortUrl.vue
Labels: ☢️ Bug

#7116 fix: a corner case for join match one
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/plan/deduplication_exec.rs
Labels: ☢️ Bug

#7097 fix: add alert redesign issues
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/FilterCondition.vue
  web/src/components/alerts/FilterGroup.vue
  web/src/components/alerts/ImportAlert.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/common/sidebar/AddFolder.vue
  web/src/components/common/sidebar/SelectFolderDropDown.vue
  web/src/components/pipeline/NodeForm/Stream.vue
Labels: ☢️ Bug, ✏️ Feature, Review effort 4/5

#7118 feat: dashboard variables by default select all values
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/dashboard/useValuesWebSocket.ts
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useSearchWebSocket.ts
  web/src/utils/dashboard/constants.ts
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#7120 fix: should throw error while validating sql query in add alert
  web/src/components/alerts/AddAlert.vue
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#7072 feat: TLS support for Syslog TCP Server
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/handler/tcp_udp/mod.rs
  src/job/syslog_server.rs
  src/service/tls/mod.rs
Labels: ✏️ Feature

#7115 fix: http partition pagination for less number of partition counts
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7127 fix: handle offset pagination on leader in http2 streaming
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#7125 fix: call CryptoProvider::install_default() before this point
  src/job/syslog_server.rs
  src/service/tls/mod.rs
Labels: ☢️ Bug, Review effort 3/5

#7132 fix: handle offset pagination on leader
  src/service/search/search_stream.rs
Labels: ☢️ Bug, Review effort 3/5

#7137 fix: empty relation with optimizer rule
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/utils.rs
Labels: ☢️ Bug

#7138 fix: unit test cases
  src/wal/tests/wal.rs
Labels: ☢️ Bug, 🧹 Updates

#7134 fix: escape quote for variable values
  src/config/src/meta/dashboards/v5/mod.rs
  tests/ui-testing/playwright-tests/dashboards/dashboard-variables-setting.spec.js
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/locales/languages/en.json
Labels: ☢️ Bug, Review effort 3/5

#7139 feat: dashboard values api using http2
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ✏️ Feature

#7135 fix: store dashboard panel cache on indexDB instead of in memory
  web/src/composables/dashboard/usePanelCache.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, Review effort 3/5

#7148 fix: store dashboard panel cache on indexDB instead of in memory
  web/src/composables/dashboard/usePanelCache.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#7149 fix: replace variable with bracket as well
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#7044 feat: dashboard warning icon for partial data
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ✏️ Feature, Review effort 4/5

#6752 feat: dashboard values api using ws
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/dashboard/useValuesWebSocket.ts
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useSearchWebSocket.ts
  web/src/utils/dashboard/constants.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature, Review effort 5/5

#7162 fix: empty user session
  src/handler/http/request/status/mod.rs
  src/service/db/session.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#7154 fix: Modified pagination logic to continue partitions when hits exceed rowsPerPage limit
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7126 test: pagination pytest
  tests/api-testing/tests/test_streaming.py
  tests/ui-testing/playwright-tests/streaming.spec.js
  tests/ui-testing/playwright-tests/usersOrg.spec.js
  tests/ui-testing/playwright.config.js
Labels: 🧹 Updates, Review effort 2/5

#7168 fix: temporarily change size (#7167)
  src/service/search/search_stream.rs
Labels: ☢️ Bug, Review effort 3/5

#7173 fix: add memory circuit breaker for ingester
  src/config/src/config.rs
  src/infra/src/errors/mod.rs
  src/ingester/src/errors.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/search_stream.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#7174 fix: histogram interval update subquery for HTTP2 (#7170)
  src/common/utils/websocket.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 3/5

#7171 fix: add memory circuit breaker for ingester
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/handler/http/router/middlewares/slow_log.rs
  src/infra/src/errors/mod.rs
  src/ingester/src/errors.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/main.rs
  src/proto/proto/loki/loki.proto
  src/proto/src/generated/loki.rs
  src/router/http/mod.rs
  src/service/circuit_breaker.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/hec.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/traces/mod.rs
  src/wal/benches/write.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 4/5

#7181 perf: update grid layout lib to improve performance and memory leaks
  web/package-lock.json
  web/package.json
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: 🧹 Updates, Review effort 4/5

#7189 fix: check 2nd arg for approx percentile fn on visualization page
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug, Review effort 2/5

#7195 fix: dashboard variables search
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
Labels: ☢️ Bug, Review effort 2/5

#7178 chore: port pipeline delete fix
  src/common/infra/config.rs
  src/service/db/pipeline.rs
Labels: ☢️ Bug

#7175 fix: delete realtime pipeline
  src/common/infra/config.rs
  src/service/db/pipeline.rs
Labels: ☢️ Bug, Review effort 3/5

#7196 fix: ts result cache for CTE & subquery (#7183)
  src/config/src/utils/sql.rs
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug, Review effort 3/5

#7199 test: Alerts Module Revamp - Removed old files, accommodated new template changes on the ui in automation scripts
  .github/workflows/playwright.yml
  tests/ui-testing/pages/alertDestination.js
  tests/ui-testing/pages/alertDestinationsPage.js
  tests/ui-testing/pages/alertTemplate.js
  tests/ui-testing/pages/alertTemplatesPage.js
  tests/ui-testing/pages/alertsNew.js
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/pages/commonActions.js
  tests/ui-testing/playwright-tests/alertImportTDA.spec.js
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/alertsNew.spec.js
  tests/ui-testing/playwright-tests/alertsfolders.spec.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
Labels: 🧹 Updates, Review effort 5/5

#7205 fix: UI performance 14.6 rc9
  web/src/components/QueryEditor.vue
  web/src/composables/shared/router.ts
  web/src/composables/shared/useEnterpriseRoutes.ts
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/composables/shared/useManagementRoutes.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#7207 fix: logs page chart render issue on another page switch
  web/src/components/dashboards/panels/ChartRenderer.vue
Labels: ☢️ Bug, Review effort 3/5

#7211 fix: use a single queue for all org-user related info
  src/super_cluster_queue/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#7215 fix: o2_all with inverted index
  src/service/search/sql.rs
Labels: ☢️ Bug

#7214 fix: o2_all with inverted index
  src/service/search/sql.rs
Labels: ☢️ Bug, Review effort 3/5

#7206 feat: dashboard skip values api call if already loading
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/OverrideConfig.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature, Review effort 1/5

#7218 feat: dashboard skip values api call if already loading (#7206)
  web/src/components/DateTime.vue
  web/src/components/DateTimePickerDashboard.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/OverrideConfig.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#7220 fix:aggs cache
  src/cli/data/export.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/metrics.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/search/search_stream.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/mod.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/distributed_plan/streaming_aggs_exec.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
  src/service/search/request.rs
  src/service/search/search_stream.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/values.rs
Labels: Invalid PR Title

#7222 fix: UI performance 14.6 rc9 v1
  web/src/components/DateTime.vue
  web/src/components/DateTimePicker.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#7204 fix: disable mmdb download on compactor
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/job/mod.rs
  src/service/compact/stats.rs
  src/service/db/pipeline.rs
Labels: ☢️ Bug, Review effort 1/5

#7224 fix: role and group names should be formatted using regex
  src/handler/http/auth/jwt.rs
  src/handler/http/request/authz/fga.rs
Labels: ☢️ Bug, Review effort 2/5

#7235 fix: match all doesn't work on ingester
  src/common/utils/auth_tests.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#7232 fix: panel load issue on panel visible
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, Review effort 2/5

#7238 fix: dashboard move to logs
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug, Review effort 2/5

#7245 fix: make `ZO_CREATE_ORG_THROUGH_INGESTION` true by default
  src/config/src/config.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#7252 fix: cancel query issue with http streaming
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, Review effort 2/5

#7164 fix: empty user session (#7162)
  src/handler/http/request/status/mod.rs
  src/service/db/session.rs
Labels: ☢️ Bug, Review effort 3/5

#7259 feat: dashboard variables add custom values from input
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
Labels: ✏️ Feature

#7258 test: limit-pagination-test
  tests/ui-testing/playwright-tests/logspage.spec.js
Labels: 🧹 Updates, Review effort 2/5

#7186 fix: alerts module issues
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/alerts/TemplateList.vue
  web/src/components/common/sidebar/FolderList.vue
  web/src/components/shared/grid/Pagination.vue
Labels: ☢️ Bug, Review effort 3/5

#7261 test: adding organizations revamp playwright
  tests/ui-testing/playwright-tests/usersOrg.spec.js
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5

#7257 fix: `streaming_id` in htttp2 streaming response
  src/common/utils/auth_tests.rs
  src/config/src/meta/search.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#7262 feat: add TopN memory track for datafusion
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/storage.rs
Labels: ✏️ Feature, Review effort 2/5

#7275 fix: improve node status monitor
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/config.rs
  src/job/stats.rs
Labels: ☢️ Bug, 🧹 Updates

#7271 feat: histogram_interval in search api
  src/cli/data/export.rs
  src/common/meta/organization.rs
  src/config/src/meta/search.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/mod.rs
  src/service/search/request.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  web/src/components/settings/General.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#7284 fix: remove streaming_id on search error
  src/handler/http/request/search/mod.rs
  src/service/search/mod.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug, 🧹 Updates

#7279 fix: fixed conflict code changes
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7290 fix: save result cache without vrl
  src/config/src/meta/function.rs
  src/main.rs
  src/service/search/cache/mod.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#7293 fix: dashboards variables loading
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
Labels: ☢️ Bug, Review effort 3/5

#7298 feat: match_field alias for str_match
  src/service/search/datafusion/udf/mod.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/index.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#7302 feat: str_match placeholder and match_field alias
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/search/datafusion/udf/mod.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/index.rs
  src/service/search/sql.rs
Labels: ✏️ Feature, Review effort 4/5

#7303 feat: sync rc7 to rc9
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/config.rs
  src/job/stats.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/table_provider/uniontable.rs
  src/service/search/grpc/flight.rs
Labels: ✏️ Feature

#7306 feat: add typeahead query builder for variable selection
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ✏️ Feature, Review effort 3/5

#7305 fix: update query keywords to lowercase
  tests/ui-testing/pages/dashboardPages/dashboard-chart.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
Labels: ☢️ Bug, 🧹 Updates

#7315 fix: cherry-pick rc9 fixes
  src/cli/data/export.rs
  src/common/meta/organization.rs
  src/config/src/meta/search.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/mod.rs
  src/service/search/request.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  web/src/components/settings/General.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature, Review effort 5/5

#7319 fix: stream_types for join
  src/service/search/cluster/http.rs
Labels: ☢️ Bug

#7320 fix: stream_types for join (#7319)
  src/service/search/cluster/http.rs
Labels: ☢️ Bug, Review effort 2/5

#7347 fix: stream_type for join
  src/service/search/cluster/http.rs
Labels: ☢️ Bug

#7348 fix: stream_type for join
  src/service/search/cluster/http.rs
Labels: ☢️ Bug, Review effort 2/5

#7349 fix: stream_type for join
  src/service/search/cluster/http.rs
Labels: Invalid PR Title, ☢️ Bug

#7352 fix: dashboard build
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
Labels: ☢️ Bug

#7268 test: pagination for streaming in match all and limit playwright
  .github/workflows/playwright.yml
  tests/ui-testing/pages/ingestionPage.js
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/pagination.spec.js
  tests/ui-testing/playwright-tests/websocket.spec.js
Labels: 🧹 Updates, Review effort 3/5

#7355 fix: dashboard hover issue
  web/src/components/dashboards/panels/ChartRenderer.vue
Labels: ☢️ Bug

#7357 fix: node role should be already have value
  src/service/search/cluster/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#7362 fix: set the node unscheduable before start http
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/cluster/scheduler.rs
  src/config/src/cluster.rs
  src/main.rs
Labels: ☢️ Bug

#7368 fix: cache delta start_time (#7367)
  src/service/search/cache/cacher.rs
Labels: Invalid PR Title, ☢️ Bug

#7369 feat: merge partial aggregate result
  Cargo.lock
  Cargo.toml
  src/service/search/cluster/flight.rs
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ✏️ Feature

#7374 fix: diable partital result cache
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#7322 fix: use random tmp directory for concurrent report server chromium instances
  src/report_server/src/report.rs
Labels: ☢️ Bug, Review effort 3/5

#7340 fix: allow pattern search in dropdown
  src/config/src/meta/search.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/query_select_utils.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_job.rs
  src/service/search/search_stream.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#7376 fix: single node schedulable
  src/common/infra/cluster/mod.rs
Labels: ☢️ Bug, Review effort 1/5

#7373 fix: simplify isPartialData logic on complete
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, Review effort 2/5

#7382 fix: Revert "fix: histogram interval for http2 streaming (#7329)"
  src/handler/http/request/search/search_stream.rs
Labels: ☢️ Bug

#7380 feat: add cardinality check for agg cache
  src/handler/http/request/status/mod.rs
  src/service/search/cardinality.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
Labels: ✏️ Feature

#7384 feat: processbar at least show 5%
  web/src/components/common/LoadingProgress.vue
Labels: ✏️ Feature

#7385 fix: ensure minimum loading progress percentage is 5
  web/src/components/common/LoadingProgress.vue
Labels: ☢️ Bug, Review effort 2/5

#7388 fix: deadlock of cardinality
  src/service/search/cardinality.rs
Labels: ☢️ Bug

#7387 fix: dashboard tooltip error
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug, Review effort 3/5

#7389 fix: histogram interval for http2 streaming
  src/config/src/meta/search.rs
  src/handler/http/request/search/search_stream.rs
  src/service/search/cache/cacher.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
  src/service/search/search_stream.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#7377 feat: add stream agg merge time
  Cargo.lock
  Cargo.toml
Labels: ✏️ Feature

#7390 fix: dashboard tooltip error (#7387)
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#7241 fix: http and http2 partition pagination fixes
  web/src/composables/useLogs.ts
  web/src/composables/useStreamingSearch.ts
  web/src/views/ShortUrl.vue
  web/src/workers/streamWorker.js
Labels: ☢️ Bug, Review effort 4/5

#7397 fix: o2 ai changes
  web/src/components/O2AIChat.vue
Labels: ☢️ Bug, Review effort 3/5
