Repository openobserve/openobserve, pull requests merged in 2025-09, with the labels that each got.

#8220 refactor: enhance cache configuration checks in file merging logic
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/tantivy/mod.rs
Labels: 🧹 Updates

#8219 fix: check if cache latest files enabled for cache local file
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/tantivy/mod.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8208 fix: improve write flush logic
  src/ingester/src/writer.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8218 ci: fixed o2 strapi workflow notfication issue
  .github/workflows/github-release-public.yml
  .github/workflows/release.yml
  tests/ui-testing/playwright-tests/Streams/streamname.spec.js
Labels: ☢️ Bug, Review effort 2/5

#8222 fix: cloud sync
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/auth/token.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/errors/mod.rs
  src/infra/src/table/organizations.rs
  src/job/mod.rs
  src/service/db/organization.rs
  src/service/db/user.rs
  src/service/ingestion/mod.rs
  src/service/logs/loki.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/organization.rs
  src/service/traces/mod.rs
  src/service/users.rs
  web/src/components/iam/serviceAccounts/AddServiceAccount.vue
  web/src/components/iam/users/AddUser.vue
  web/src/components/iam/users/InvitationList.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/services/organizations.ts
  web/src/services/users.ts
  web/src/utils/zincutils.ts
  web/src/views/Login.spec.ts
  web/src/views/Login.vue
Labels: ☢️ Bug, Review effort 4/5

#8253 fix: scan_stats for each node info
  src/service/search/datafusion/distributed_plan/decoder_stream.rs
Labels: ☢️ Bug, Review effort 2/5

#8251 fix: scan_stats for each node info
  src/service/search/datafusion/distributed_plan/decoder_stream.rs
Labels: ☢️ Bug, Review effort 2/5

#8258 fix: quick mode by default check explore 15
  web/src/views/LogStream.vue
Labels: ☢️ Bug, Review effort 2/5

#8257 test: e2e-add-to-table-tests
  .github/workflows/playwright.yml
  Cargo.lock
  Cargo.toml
  tests/ui-testing/pages/logsPages/logsPage.js
  tests/ui-testing/playwright-tests/Logs/logstable.spec.js
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5

#8262 fix: Fix/parsing nested with queries rc9
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#8236 fix: fixed traces error handling
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/TraceDetails.vue
Labels: ☢️ Bug, Review effort 2/5

#8248 fix: fixed traces error handling
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/TraceDetails.vue
Labels: ☢️ Bug

#8254 fix: Add field to table in logs
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug, ✏️ Feature

#8239 fix: dashboard unit tests
  web/src/composables/dashboard/useAnnotations.spec.ts
  web/src/composables/dashboard/useAnnotationsData.spec.ts
  web/src/composables/dashboard/useCancelQuery.spec.ts
  web/src/composables/dashboard/usePanelCache.spec.ts
  web/src/composables/dashboard/usePanelDataLoader.spec.ts
  web/src/composables/dashboard/useValuesWebSocket.spec.ts
Labels: ☢️ Bug, 🧹 Updates, Review effort 5/5

#8167 fix: enhance dashboard transpose validation in UI tests
  .github/workflows/playwright.yml
  tests/ui-testing/pages/dashboardPages/dashboard-chart.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8278 fix: print target partition and memory for search
  src/service/promql/search/grpc/wal.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug

#8261 feat: use uuid v7 for internal trace ids
  Cargo.lock
  Cargo.toml
  deny.toml
  src/config/Cargo.toml
  src/config/src/ider.rs
  src/handler/http/request/traces/mod.rs
  web/src/plugins/traces/TraceBlock.spec.ts
  web/src/utils/zincutils.spec.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 3/5

#8256 chore: debug logs for gc and get_ctx_and_physical_plan
  src/infra/src/cache/file_data/disk.rs
  src/service/search/grpc/flight.rs
Labels: ☢️ Bug, Review effort 2/5

#8282 chore: default disable utf8view
  src/config/src/config.rs
Labels: Review effort 1/5

#8288 fix: default value for enable_distinct_fields
  src/config/src/meta/stream.rs
Labels: ☢️ Bug, Review effort 2/5

#8283 chore: default disable utf8view for main
  src/config/src/config.rs
Labels: Review effort 1/5

#8293 test: e2e worker increment playwright tests
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright.config.js
Labels: 🧹 Updates

#8202 fix: port reactive config rc7
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/pausable_job.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/ingester/src/lib.rs
  src/job/alert_manager.rs
  src/job/compactor.rs
  src/job/files/parquet.rs
  src/job/flatten_compactor.rs
  src/job/mod.rs
  src/job/promql.rs
  src/job/stats.rs
  src/job/telemetry.rs
  src/service/enrichment/storage.rs
  src/service/metadata/distinct_values.rs
  src/service/self_reporting/mod.rs
Labels: ☢️ Bug

#8309 test: e2e-logs-table-testcases
  tests/ui-testing/playwright-tests/Logs/logstable.spec.js
Labels: 🧹 Updates, Review effort 2/5

#8303 test: add dashboard visualize test cases
  tests/ui-testing/pages/dashboardPages/visualise.js
  tests/ui-testing/pages/page-manager.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5

#8310 fix: add length filter for tantivy token
  src/config/src/config.rs
  src/config/src/ider.rs
  src/config/src/utils/tantivy/tokenizer/mod.rs
  src/config/src/utils/tantivy/tokenizer/o2_tokenizer.rs
  src/config/src/utils/tantivy/tokenizer/remove_short.rs
  src/job/files/mod.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 3/5

#8318 feat: add grpc health check
  src/job/grpc.rs
  src/job/mod.rs
  src/main.rs
Labels: ✏️ Feature

#8321 fix: async fs operations
  src/config/src/utils/file.rs
  src/infra/src/cache/file_data/disk.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#8331 fix: async fs operations (#8321)
  src/config/src/utils/file.rs
  src/infra/src/cache/file_data/disk.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#8342 fix: dashboard search text for variables SQL query
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ☢️ Bug, Review effort 2/5

#8347 fix: correct union query with wildcard[main]
  src/service/search/sql/visitor/column.rs
Labels: ☢️ Bug, Review effort 2/5

#8330 chore: shutdown ddl pool
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/migration/mod.rs
Labels: Review effort 2/5

#8335 fix: Dashboards Names needed on the QueryManager
  .vscode/launch.json
  src/config/src/meta/search.rs
  src/handler/grpc/request/search/mod.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/search/mod.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/queries/RunningQueries.vue
  web/src/components/queries/RunningQueriesList.spec.ts
  web/src/components/queries/RunningQueriesList.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useStreamingSearch.ts
  web/src/locales/languages/en.json
  web/src/services/search.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug, Review effort 3/5

#8358 chore: Move async scan_files_filtered() into appropriate async_file module
  src/config/src/utils/async_file.rs
  src/config/src/utils/file.rs
  src/service/search/grpc/wal.rs
Labels: Review effort 2/5

#8364 chore: Update canonnicalization step for scan_files_filtered to be more async
  src/config/src/utils/async_file.rs
  src/config/src/utils/file.rs
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates, Review effort 2/5

#8302 fix: restrict `select *` query for visualization
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#8398 fix: shutting down DDL connection
  src/config/src/meta/stream.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/lib.rs
  src/job/mod.rs
  src/migration/mod.rs
  tests/integration_test.rs
Labels: ☢️ Bug, Review effort 2/5

#8413 feat: use nats queue for cluster coordination
  src/cli/basic/cli.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/config.rs
  src/infra/src/cluster_coordinator/alerts.rs
  src/infra/src/cluster_coordinator/events.rs
  src/infra/src/cluster_coordinator/mod.rs
  src/infra/src/db/nats.rs
  src/infra/src/queue/mod.rs
  src/infra/src/queue/nats.rs
  src/infra/src/queue/nop.rs
  src/infra/src/schema/mod.rs
  src/service/db/alerts/alert.rs
  src/service/db/ofga.rs
  src/service/enrichment/mod.rs
Labels: ✏️ Feature, Review effort 3/5

#8426 fix: improve stream stats reset
  src/cli/basic/cli.rs
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8424 fix: dashboard ensure case-insensitive comparison for stream field validation for camelCase
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug, Review effort 2/5

#8432 fix: update table chart no data validation logic (#8422)
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug, 🧹 Updates

#8449 fix: support prefix star match_all
  src/service/search/index.rs
Labels: ☢️ Bug

#8450 fix: support prefix star match_all
  src/service/search/index.rs
Labels: ☢️ Bug

#8229 feat: tantivy index for multi stream [phase 2]
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cache/cacher.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/optimizer/logical_optimizer/mod.rs
  src/service/search/datafusion/optimizer/logical_optimizer/rewrite_match.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/physical_optimizer/distribute_analyze.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/count.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/distinct.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/histogram.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/mod.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/select.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/topn.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/utils.rs
  src/service/search/datafusion/optimizer/physical_optimizer/mod.rs
  src/service/search/datafusion/optimizer/physical_optimizer/remote_scan.rs
  src/service/search/datafusion/optimizer/physical_optimizer/rewrite_match.rs
  src/service/search/datafusion/optimizer/physical_optimizer/utils.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/request.rs
  src/service/search/sql/mod.rs
  src/service/search/sql/rewriter/index.rs
  src/service/search/sql/visitor/column.rs
  src/service/search/sql/visitor/index_optimize.rs
  src/service/search/sql/visitor/mod.rs
  src/service/search/super_cluster/leader.rs
Labels: ✏️ Feature, Review effort 5/5

#8454 fix: contains search for match_all
  src/cli/basic/cli.rs
  src/config/src/config.rs
  src/config/src/config_path_manager.rs
  src/config/src/lib.rs
  src/handler/http/request/status/mod.rs
  src/job/config_watcher.rs
  src/service/search/index.rs
Labels: ☢️ Bug

#8452 feat: use nats queue for cluster coordination (#8413)
  src/cli/basic/cli.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/config.rs
  src/config/src/config.rs
  src/infra/src/coordinator/alerts.rs
  src/infra/src/coordinator/destinations.rs
  src/infra/src/coordinator/events.rs
  src/infra/src/coordinator/mod.rs
  src/infra/src/coordinator/pipelines.rs
  src/infra/src/db/nats.rs
  src/infra/src/lib.rs
  src/infra/src/queue/mod.rs
  src/infra/src/queue/nats.rs
  src/infra/src/queue/nop.rs
  src/infra/src/schema/mod.rs
  src/service/db/alerts/alert.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/templates.rs
  src/service/db/keys.rs
  src/service/db/ofga.rs
  src/service/db/pipeline.rs
  src/service/enrichment/mod.rs
  src/super_cluster_queue/alerts.rs
  src/super_cluster_queue/cipher_keys.rs
  src/super_cluster_queue/destinations.rs
  src/super_cluster_queue/pipelines.rs
  src/super_cluster_queue/templates.rs
Labels: ✏️ Feature

#8451 fix: support prefix star match_all
  .devcontainer/Dockerfile
  .github/workflows/api-testing.yml
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/playwright.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  Cargo.lock
  deploy/build/Dockerfile
  deploy/build/Dockerfile.sccache.aarch64
  deploy/build/Dockerfile.sccache.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/buildspec-test.yml
  rust-toolchain.toml
  src/common/meta/user.rs
  src/flight/src/encoder.rs
  src/handler/http/auth/validator.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/table/migration/m20250125_133700_populate_destinations_table.rs
  src/infra/src/table/migration/mod.rs
  src/ingester/src/writer.rs
  src/service/db/schema.rs
  src/service/ingestion/mod.rs
  src/service/search/cache/cacher.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/distinct.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
Labels: ☢️ Bug, Review effort 2/5

#8443 fix: general management UI in sync
  web/src/components/settings/General.vue
Labels: ☢️ Bug

#8483 feat: support inverted index for metadata stream
  src/config/src/meta/stream.rs
  src/config/src/utils/inverted_index.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/grpc/storage.rs
Labels: ✏️ Feature

#8457 fix: clear the user searched value on selecting anystream
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#8479 fix: interesting field config rc9
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#8480 fix: interesting field config
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug, Review effort 2/5

#8485 refactor: replace feature_per_thread_lock with mem_table_bucket_num
  src/config/src/config.rs
  src/ingester/src/writer.rs
  src/main.rs
Labels: 🧹 Updates, ✏️ Feature

#8465 ci: updated oss strapi notification to pusblish content
  .github/workflows/release.yml
  tests/ui-testing/playwright-tests/Logs/join.spec.js
Labels: 🧹 Updates, Review effort 2/5

#8359 fix: update remote wal config
  src/config/src/config.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8462 feat: add custom env file path support (#8365)
  src/cli/basic/cli.rs
  src/config/src/config.rs
  src/config/src/config_path_manager.rs
  src/config/src/lib.rs
  src/config/src/utils/pausable_job.rs
  src/handler/http/request/status/mod.rs
  src/job/config_watcher.rs
  src/job/mod.rs
  src/job/stats.rs
Labels: ✏️ Feature

#8492 fix: nats consumer name for queue should be formatted
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug

#8481 chore: add search logs to breakdown datafusion get ctx physical plan
  src/service/search/cluster/flight.rs
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/utils.rs
Labels: ✏️ Feature

#8477 fix: added additional match_all pattern to the syntax guide
  web/src/plugins/logs/SyntaxGuide.vue
Labels: ☢️ Bug, ✏️ Feature

#8440 fix: UI sync with general settings on refresh
  web/src/components/settings/General.vue
Labels: ☢️ Bug

#8476 fix: added additional match_all pattern to the syntax guide
  web/src/plugins/logs/SyntaxGuide.vue
Labels: ☢️ Bug, ✏️ Feature

#8489 feat: add bulk enable/disable for alert and pipelines (rc7)
  src/common/utils/auth.rs
  src/config/src/meta/pipeline/mod.rs
  src/handler/http/models/alerts/requests.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/pipeline.rs
  src/handler/http/request/search/utils.rs
  src/handler/http/router/mod.rs
  web/src/components/alerts/AlertList.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/services/alerts.ts
  web/src/services/pipelines.ts
Labels: ✏️ Feature

#8488 feat: partial err warning if results exceeds query limit
  src/common/meta/search.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/search_stream.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/utils.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#8496 feat: partial err warning if results exceeds query limit
  src/common/meta/search.rs
  src/handler/http/request/search/utils.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/search_stream.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/utils.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#8497 fix: show error when there is an error in response for bulk pause and unpause rc9
  web/src/components/alerts/AlertList.vue
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#8501 chore: add logs to datafusion get_ctx_and_physical_plan
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/utils.rs
Labels: ✏️ Feature

#8503 fix: add required reloadable configs
  src/handler/http/request/search/utils.rs
  src/infra/src/cache/file_data/memory.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
  src/service/search/utils.rs
Labels: ☢️ Bug, ✏️ Feature

#8508 chore: compilation fix
  src/infra/src/cache/file_data/memory.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
Labels: ☢️ Bug, ✏️ Feature

#8509 fix: stream stats min_ts error
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/queue/mod.rs
  src/infra/src/queue/nop.rs
Labels: ☢️ Bug

#8438 feat: add bulk enable/disable for alert and pipelines
  src/common/utils/auth.rs
  src/handler/http/models/alerts/requests.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/models/pipelines.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/pipeline.rs
  src/handler/http/request/search/utils.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  web/src/components/alerts/AlertList.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/services/alerts.ts
  web/src/services/pipelines.ts
Labels: ✏️ Feature, Review effort 3/5

#8519 fix: ordering of events in a partition
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#8521 fix: ordering of events in a partition rc9
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#8517 fix: dashboard panel render issue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#8514 fix: `order_by_metadata` for responses from cache
  src/service/search/cache/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#8525 fix: disableed add to dashboard btn issue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug, ✏️ Feature

#8435 fix: sql query editor rapidly increases
  web/src/components/alerts/ScheduledAlert.vue
Labels: ☢️ Bug

#8209 fix: make ./data/download folder default for report server chrome download
  src/config/src/config.rs
  src/service/db/enrichment_table.rs
Labels: ☢️ Bug, Review effort 1/5

#8530 fix: streaming aggs issue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#8539 fix: dashboard toLowercase issue rc9
  web/src/utils/dashboard/aliasUtils.ts
Labels: ☢️ Bug

#8516 fix: fixed default field list issue
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#8544 fix: correct ent repo path
  src/job/config_watcher.rs
Labels: ☢️ Bug, Review effort 1/5

#8543 test: Reworked logs download tests, added 10 tests for json and sql w…
  .gitignore
  tests/ui-testing/pages/logsPages/logsPage.js
  tests/ui-testing/playwright-tests/Logs/logsDownloads.spec.js
Labels: 🧹 Updates, ✏️ Feature, Review effort 3/5

#8547 fix: refresh cache
  src/service/search/cache/mod.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#8549 fix: move cli loading to top so as to load the configs from custom file
  src/main.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug

#8553 fix: refresh cache
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#8559 fix: search parquet for wal
  src/config/src/utils/async_file.rs
  src/config/src/utils/time.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#8557 fix: orphaned database entries
  src/service/compact/retention.rs
Labels: ☢️ Bug

#8558 fix: search parquet for wal
  src/config/src/utils/async_file.rs
  src/config/src/utils/time.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug, Review effort 2/5

#8565 fix: do not allow select * query with share link
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#8562 fix: remove drilldown and compare against config on visualization rc7(#8534)
  web/src/components/dashboards/addPanel/ConfigPanel.vue
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8564 feat: add separate telemetry url
  src/common/meta/telemetry.rs
  src/config/src/config.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/cloud/billings.rs
  src/handler/http/request/cloud/marketing.rs
  src/job/cloud.rs
Labels: ✏️ Feature, Review effort 2/5

#8408 fix: trace id added for values api
  web/src/plugins/logs/IndexList.vue
  web/src/services/stream.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#8546 fix: improve dashboard API models & add field annotations
  src/config/src/meta/dashboards/v1/mod.rs
  src/config/src/meta/dashboards/v2/mod.rs
  src/config/src/meta/dashboards/v3/mod.rs
  src/config/src/meta/dashboards/v4/mod.rs
  src/config/src/meta/dashboards/v5/mod.rs
  src/handler/http/models/dashboards.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/router/openapi.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature, Review effort 2/5

#8580 fix: enrichment table delete event must be watched
  src/service/db/enrichment_table.rs
Labels: ☢️ Bug

#8605 fix: logs dedup from cache
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#8606 fix: logs dedup from cache
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#8607 fix: logs dedup from cache#8605
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#8612 fix: return search stream not found if schema is not found for the stream
  src/service/search/sql/mod.rs
Labels: ☢️ Bug

#8611 fix: alert module code splitting
  web/src/components/alerts/AddAlert.spec.ts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.spec.ts
  web/src/components/alerts/ScheduledAlert.vue
  web/src/utils/alerts/alertDataTransforms.ts
  web/src/utils/alerts/alertPayload.ts
  web/src/utils/alerts/alertQueryBuilder.ts
  web/src/utils/alerts/alertSqlUtils.ts
  web/src/utils/alerts/alertValidation.ts
  web/src/utils/validateAlerts.spec.ts
  web/src/utils/validateAlerts.ts
Labels: ☢️ Bug, Review effort 4/5

#8626 fix: Add CC0-1.0 license to allow list
  deny.toml
Labels: ☢️ Bug, ✏️ Feature, Review effort 1/5

#8617 fix: should not show checkbox before loading the pipelines page
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#8630 feat: support index optimizer topn asc
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/topn.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/tantivy_result.rs
  src/service/search/grpc/tantivy_result_cache.rs
  src/service/search/grpc/utils.rs
Labels: ✏️ Feature, Review effort 3/5

#8631 fix: add user ID & cluster URL to AI request
  src/handler/http/request/ai.rs
Labels: ☢️ Bug, ✏️ Feature

#8635 fix: distinct values has no _timestamp
  src/service/metadata/distinct_values.rs
Labels: ☢️ Bug

#8578 fix: enrichment table delete event must be watched
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/geoip.rs
  src/service/enrichment_table/mod.rs
  tests/integration_test.rs
Labels: ☢️ Bug, Review effort 3/5

#8649 fix: stream stats merge
  src/config/src/meta/stream.rs
  src/handler/http/request/ai.rs
Labels: ☢️ Bug

#8634 fix: distinct values has no _timestamp
  src/service/metadata/distinct_values.rs
Labels: ☢️ Bug, Review effort 2/5

#8648 fix: stream stats merge
  src/config/src/meta/stream.rs
Labels: ☢️ Bug, Review effort 2/5

#8584 feat: cloud email domains
  src/handler/http/auth/jwt.rs
  src/handler/http/request/status/mod.rs
Labels: ✏️ Feature, Review effort 2/5

#8654 fix: result cache histogram & `force_clear_cache` & result array skip vrl
  src/handler/http/request/search/multi_streams.rs
  src/service/functions.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/http.rs
  src/service/search/mod.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#8660 fix: for otlp ingestion with result array pipeline, read timestamp from record
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
Labels: ☢️ Bug

#8664 fix: enrichment table schema error
  src/service/search/datafusion/table_provider/enrich_table.rs
Labels: ☢️ Bug, Review effort 2/5

#8665 fix: fixed duplicated "No Permissions Found" message on IAM roles page
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/PermissionsTable.vue
Labels: ☢️ Bug

#8671 fix: optimize cache metadata
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  tests/api-testing/tests/test_streaming.py
Labels: ☢️ Bug, Review effort 2/5

#8672 feat: impl broadcast join for enrichment table
  src/config/src/config.rs
  src/handler/grpc/flight/visitor.rs
  src/handler/http/auth/jwt.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/db/enrichment_table.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/datafusion/distributed_plan/codec/enrichment_exec.rs
  src/service/search/datafusion/distributed_plan/codec/mod.rs
  src/service/search/datafusion/distributed_plan/codec/physical_plan_node.rs
  src/service/search/datafusion/distributed_plan/distribute_analyze_exec.rs
  src/service/search/datafusion/distributed_plan/enrich_exec.rs
  src/service/search/datafusion/distributed_plan/enrichment_exec.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/remote_scan_exec.rs
  src/service/search/datafusion/optimizer/logical_optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/physical_optimizer/distribute_analyze.rs
  src/service/search/datafusion/optimizer/physical_optimizer/enrichment.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/mod.rs
  src/service/search/datafusion/optimizer/physical_optimizer/index_optimizer/utils.rs
  src/service/search/datafusion/optimizer/physical_optimizer/join_reorder.rs
  src/service/search/datafusion/optimizer/physical_optimizer/mod.rs
  src/service/search/datafusion/optimizer/physical_optimizer/remote_scan.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/utils.rs
Labels: ✏️ Feature, Review effort 4/5

#8632 fix: Root user should not be added to any organization
  src/infra/src/table/migration/m20250923_000001_update_enrichment_table_data_size.rs
  src/infra/src/table/migration/mod.rs
  src/service/users.rs
  tests/integration_test.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#8675 fix: remove select all placeholder for metrics
  src/config/src/config.rs
  src/service/promql/engine.rs
  src/service/promql/mod.rs
  src/service/promql/rewrite.rs
  src/service/search/sql/rewriter/remove_dashboard_placeholder.rs
Labels: ☢️ Bug, 🧹 Updates

#8620 fix: return search stream not found if schema is not found for the stream
  src/service/search/cache/cacher.rs
  src/service/search/sql/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#8679 perf: improve load speed for enrichment table in `EnrichmentExec`
  src/common/utils/functions.rs
  src/config/src/config.rs
  src/service/db/enrichment_table.rs
  src/service/db/schema.rs
  src/service/enrichment/mod.rs
  src/service/search/datafusion/distributed_plan/enrichment_exec.rs
Labels: 🧹 Updates, Review effort 2/5

#8596 fix: added warning message to the pipeline default destination node
  web/src/components/ConfirmDialog.vue
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/plugins/pipelines/CustomNode.vue
  web/src/plugins/pipelines/useDnD.ts
  web/src/utils/pipelines/constants.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#8681 fix: rename regex patterns to sensitive data redaction
  web/src/components/logstream/schema.vue
  web/src/components/settings/NoRegexPatterns.spec.ts
  web/src/components/settings/NoRegexPatterns.vue
  web/src/components/settings/RegexPatternList.vue
  web/src/components/settings/index.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, Review effort 2/5

#8676 fix: pipeline UI revamp
  tests/ui-testing/pages/pipelinesPages/pipelinesPage.js
  tests/ui-testing/playwright-tests/Pipelines/pipeline-core.spec.js
  tests/ui-testing/playwright-tests/Pipelines/pipelines.spec.js
  web/src/assets/images/pipeline/input_query.png
  web/src/assets/images/pipeline/input_stream.png
  web/src/assets/images/pipeline/output_remote.png
  web/src/assets/images/pipeline/output_stream.png
  web/src/assets/images/pipeline/transform_condition.png
  web/src/assets/images/pipeline/transform_function.png
  web/src/components/pipeline/NodeForm/AssociateFunction.spec.js
  web/src/components/pipeline/NodeForm/AssociateFunction.vue
  web/src/components/pipeline/NodeSidebar.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelineView.spec.ts
  web/src/components/pipeline/PipelineView.vue
  web/src/locales/languages/en.json
  web/src/plugins/pipelines/CustomEdge.vue
  web/src/plugins/pipelines/CustomNode.vue
  web/src/plugins/pipelines/EdgeWithButton.vue
  web/src/plugins/pipelines/PipelineFlow.vue
Labels: ☢️ Bug, Review effort 4/5

#8680 test: add tests for enrichment table local storage functions
  src/service/enrichment/storage.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5

#8684 fix: resolve concurrency issue in put_file_contents
  src/config/src/utils/async_file.rs
  src/config/src/utils/file.rs
Labels: ☢️ Bug, Review effort 2/5

#8682 feat: add context support to chat requests and improve type safety
  src/handler/http/models/ai.rs
  src/handler/http/models/dashboards.rs
  src/handler/http/request/ai/chat.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5
