Repository openobserve/openobserve, pull requests merged in 2025-01, with the labels that each got.

#5524 fix: Dashboard panel height resize issue of concurrent changes error message
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/commons.ts
Labels: ☢️ Bug

#5525 fix: dashboard drilldown support to logs page, getting ` and query of unions not getting passed properly
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#5520 feat: check for new OpenFGA identifier for alerts
  src/service/alerts/alert.rs
Labels: ✏️ Feature

#5537 fix: enterprise build
  src/handler/http/request/promql/mod.rs
Labels: ☢️ Bug

#5548 feat: http tls support
  Cargo.lock
  Cargo.toml
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/cluster.rs
  src/config/src/config.rs
  src/main.rs
  src/service/enrichment_table/mod.rs
  src/service/mod.rs
  src/service/tls/mod.rs
Labels: ✏️ Feature

#5552 feat: add inverted index search for promql
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/utils.rs
  src/service/search/index.rs
Labels: ✏️ Feature

#5554 feat: http tls support v3
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/main.rs
  src/service/tls/mod.rs
Labels: ✏️ Feature

#5547 fix: WebSocket search issues
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#5555 fix: add changes for super_cluster for distinct_values
  src/infra/src/table/distinct_values.rs
  src/service/dashboards/mod.rs
  src/service/db/distinct_values.rs
  src/service/db/mod.rs
  src/service/stream.rs
Labels: ☢️ Bug, ✏️ Feature

#5559 feat: Move alert cluster coordinator event methods into `infra` crate
  src/infra/src/cluster_coordinator/alerts.rs
  src/infra/src/cluster_coordinator/mod.rs
  src/infra/src/lib.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5561 feat: emit super cluster events for alerts and dashboards
  src/service/dashboards/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5563 fix: v2 alert APIs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#5556 fix: dashboard when changing org it throws error as dashboardID is not found
  web/src/utils/commons.ts
Labels: ☢️ Bug

#5565 fix: function image in search bar
  web/src/assets/images/common/function_dark.svg
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#5567 fix: dashboard drilldown to logs support histogram issue when passing to url
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#5549 feat: functions UI design revamp
  src/config/src/meta/function.rs
  src/handler/http/request/functions/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/functions.rs
  tests/ui-testing/pages/pipelinePage.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/QueryEditor.vue
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/common/AppTabs.vue
  web/src/components/functions/AddFunction.vue
  web/src/components/functions/FullViewContainer.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/functions/FunctionsToolbar.vue
  web/src/components/functions/TestFunction.vue
  web/src/components/pipeline/NodeForm/AssociateFunction.vue
  web/src/locales/languages/en.json
  web/src/services/jstransform.ts
  web/src/ts/interfaces/function.ts
  web/src/views/Functions.vue
Labels: ✏️ Feature

#5571 fix: compactor with extended retention
  src/service/compact/retention.rs
Labels: ☢️ Bug

#5573 fix: tooltip issue for billing page usage chart
  web/src/utils/billing/convertBillingData.ts
Labels: ☢️ Bug

#5572 fix: added confirmation before unloading add function page
  web/src/components/functions/AddFunction.vue
  web/src/components/functions/FunctionsToolbar.vue
  web/src/components/functions/TestFunction.vue
  web/src/components/pipeline/NodeForm/AssociateFunction.vue
  web/src/components/pipeline/PipelineEditor.vue
Labels: ☢️ Bug, ✏️ Feature

#5570 test: New Folders API test cases in PyTest
  tests/api-testing/tests/test_foldersnew.py
Labels: 🧹 Updates

#5581 Middleware deprication release
  web/src/aws-exports.ts
  web/src/components/iam/organizations/AddUpdateOrganization.vue
  web/src/components/iam/organizations/AppOrganizations.vue
  web/src/components/iam/organizations/JoinOrganization.vue
  web/src/components/iam/organizations/ListAssociatedMembers.vue
  web/src/components/iam/organizations/ListOrganizations.vue
  web/src/components/iam/serviceAccounts/AddServiceAccount.vue
  web/src/components/iam/users/AddUser.vue
  web/src/components/iam/users/MemberInvitation.vue
  web/src/components/iam/users/User.vue
  web/src/components/iam/users/enterprise/User.vue
  web/src/components/settings/General.vue
  web/src/composables/iam/usePermissions.ts
  web/src/composables/router.ts
  web/src/composables/shared/router.ts
  web/src/enterprise/components/login/Login.vue
  web/src/enterprise/components/organizations/AddUpdateOrganization.vue
  web/src/enterprise/components/organizations/JoinOrganization.vue
  web/src/enterprise/components/organizations/ListAssociatedMembers.vue
  web/src/enterprise/components/organizations/Organization.vue
  web/src/enterprise/components/users/User.vue
  web/src/enterprise/composables/router.ts
  web/src/enterprise/mixins/mainLayout.mixin.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/services/organizations.ts
  web/src/services/users.ts
  web/src/utils/zincutils.ts
  web/src/views/HomeView.vue
  web/src/views/IdentityAccessManagement.vue
  web/src/views/User.vue
Labels: Invalid PR Title

#5574 feat: restrict max hours service account
  src/common/utils/stream.rs
  src/common/utils/websocket.rs
  src/config/src/config.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/request/websocket/search.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#5558 fix: debug the RUM deadlock
  src/common/meta/middleware_data.rs
  src/common/utils/functions.rs
  src/config/src/config.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/rum/ingest.rs
  src/job/mmdb_downloader.rs
  src/main.rs
  src/service/users.rs
Labels: ☢️ Bug

#5539 feat: Feat/extended retention days
  web/src/components/DateTime.vue
  web/src/components/logstream/schema.vue
  web/src/composables/useStreams.ts
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#5585 feat: add search job partition result and cache
  src/cli/data/export.rs
  src/config/src/meta/search.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/traces/mod.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/cache/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search_jobs.rs
Labels: ✏️ Feature

#5590 feat: add minimum allowed refresh interval
  src/common/meta/organization.rs
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
Labels: ✏️ Feature

#5592 fix: GET dashboard RBAC issue
  src/common/utils/auth.rs
Labels: ☢️ Bug

#5594 fix: return error if old dashboard delete fails in move dashboard
  src/handler/http/request/dashboards/mod.rs
  src/service/dashboards/mod.rs
Labels: ☢️ Bug

#5595 fix: Stream settings page design issues
  web/src/components/logstream/StreamFieldInputs.vue
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug

#5593 fix: only 1 source node is allowed while creating / editing pipeline
  web/src/components/pipeline/NodeSidebar.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/plugins/pipelines/useDnD.ts
Labels: ☢️ Bug

#5584 feat: batch read data to avoid metrics OOM
  src/config/src/config.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
Labels: ✏️ Feature

#5596 fix: dashboard maps data based on map json data
  web/src/utils/dashboard/convertMapsData.ts
Labels: ☢️ Bug

#5601 ci: add more debug tools
  deploy/build/Dockerfile.pr.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
Labels: ☢️ Bug, ✏️ Feature

#5616 feat: support limit join's right side
  src/config/src/config.rs
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/table_provider/empty_table.rs
Labels: ✏️ Feature

#5619 fix: added notification on cancelling query
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, ✏️ Feature

#5620 fix: allow geo lite db with enterprise mmdb
  src/job/mmdb_downloader.rs
Labels: ☢️ Bug

#5621 fix: restrict service accounts login to web
  src/handler/http/request/status/mod.rs
Labels: ☢️ Bug

#5623 fix: panic when mmdb download is disabled
  src/common/utils/functions.rs
Labels: ☢️ Bug

#5586 test: Have added negative test cases for new folders
  tests/api-testing/tests/test_foldersnew.py
Labels: 🧹 Updates, ✏️ Feature

#5615 feat: add option for compact old data
  src/config/src/config.rs
  src/handler/grpc/flight/mod.rs
  src/infra/src/cluster_coordinator/alerts.rs
  src/infra/src/cluster_coordinator/mod.rs
  src/infra/src/schema/mod.rs
  src/service/compact/merge.rs
  src/service/grpc.rs
  src/service/logs/mod.rs
  src/service/metrics/otlp.rs
  src/service/promql/search/grpc/storage.rs
  src/service/schema.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/wal.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/super_cluster/follower.rs
  src/service/stream.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature

#5611 fix: pipeline migration name
  src/common/meta/mod.rs
  src/common/meta/pipelines.rs
  src/common/migration/pipeline_func.rs
  src/config/src/meta/alerts/derived_streams.rs
  src/config/src/meta/alerts/mod.rs
Labels: ☢️ Bug

#5624 fix: Bar Chart not rendering as expected when breakdown is present
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5625 test: service accounts PyTest
  tests/api-testing/tests/test_serviceaccounts.py
Labels: 🧹 Updates

#5636 fix: mmdb client error after update asn file
  src/job/mmdb_downloader.rs
Labels: ☢️ Bug, 🧹 Updates

#5640 feat: add pagination for search job result
  src/config/src/meta/search.rs
  src/handler/http/request/search/search_job.rs
  src/infra/src/table/search_job/search_jobs.rs
  src/service/search_jobs.rs
Labels: ✏️ Feature

#5641 fix: fixed x-axis type for trellis chart
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5649 fix: metrics ingestion with otlp json
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/handler/http/router/middlewares/check_keep_alive.rs
  src/handler/http/router/middlewares/mod.rs
  src/handler/http/router/middlewares/slow_log.rs
  src/handler/http/router/mod.rs
  src/ingester/src/writer.rs
  src/job/metrics.rs
  src/service/exporter/otlp_metrics_exporter.rs
  src/service/ingestion/mod.rs
  tests/api-testing/tests/test_traces.py
Labels: ☢️ Bug

#5647 fix: Fix `UpdateAlert` v2 endpoint
  src/service/alerts/alert.rs
Labels: ☢️ Bug, 🧹 Updates

#5653 fix: add a distributed lock for database migration
  src/infra/src/table/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#5651 fix: Mirgration to use KSUIDs instead of auto-incrementing integers as PKs
  src/infra/src/table/dashboards.rs
  src/infra/src/table/entity/alerts.rs
  src/infra/src/table/entity/dashboards.rs
  src/infra/src/table/entity/folders.rs
  src/infra/src/table/folders.rs
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
  src/infra/src/table/migration/mod.rs
Labels: ☢️ Bug

#5652 fix: Fix new `UpdateAlert` endpoint
  src/handler/http/models/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#5655 feat: retention for search jobs
  src/config/src/config.rs
  src/job/alert_manager.rs
  src/service/db/search_job/search_jobs.rs
Labels: ✏️ Feature

#5657 fix: dashboard stacked chart with variables throwing error
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#5663 feat: search job return total result
  src/config/src/meta/search.rs
  src/handler/http/request/search/search_job.rs
Labels: ✏️ Feature

#5660 fix: aws ingestion
  src/common/infra/cluster/mod.rs
  src/handler/http/auth/validator.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug

#5665 fix: migration failing without specifying fetch order
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
Labels: ☢️ Bug

#5671 fix: move dashboard rbac ownership
  src/service/dashboards/mod.rs
Labels: ☢️ Bug

#5626 feat: New `MoveAlert` endpoint
  src/handler/http/models/alerts/requests.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/new.rs
Labels: ✏️ Feature

#5669 feat: add limit for uds
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/schema.rs
  src/service/stream.rs
Labels: ✏️ Feature

#5673 fix: metrics Mismatch between schema and batches
  src/infra/src/schema/mod.rs
  src/service/promql/search/grpc/wal.rs
Labels: ☢️ Bug

#5613 feat: improve trace max query range
  src/handler/http/request/traces/mod.rs
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#5674 fix: union all with order by
  src/service/search/datafusion/distributed_plan/rewrite.rs
Labels: ☢️ Bug

#5676 fix: dashboard move to another folder issue
  web/src/components/dashboards/MoveDashboardToAnotherFolder.vue
  web/src/views/Dashboards/ImportDashboard.vue
Labels: ☢️ Bug

#5678 fix: pipeine redirection issue resolved
  web/src/components/functions/FunctionList.vue
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#5681 fix: changing pipeline org in edit mode
  web/src/components/pipeline/PipelineEditor.vue
Labels: ☢️ Bug

#5682 test: Deleting logo Management to execute from Open Source
  tests/ui-testing/pages/logoManagementPage.js
  tests/ui-testing/pages/managementPage .js
  tests/ui-testing/playwright-tests/logoManagement.spec.js
Labels: 🧹 Updates

#5684 feat: ignore time_range when join on enrichment_tables
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/optimizer/add_timestamp.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
Labels: ✏️ Feature

#5685 fix: pipeline db event watch for updating in-memory cache
  src/infra/src/cluster_coordinator/mod.rs
  src/infra/src/cluster_coordinator/pipelines.rs
  src/infra/src/pipeline/mod.rs
  src/job/mod.rs
  src/service/db/pipeline.rs
Labels: ☢️ Bug

#5693 fix: use multi search api for multi stream search when web socket is enabled
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#5666 fix: refresh user list after edit and add and removed icon from button
  web/src/components/functions/AssociatedStreamFunction.vue
  web/src/components/iam/serviceAccounts/ServiceAccountsList.vue
  web/src/components/iam/users/User.vue
  web/src/components/iam/users/enterprise/User.vue
  web/src/enterprise/components/organizations/Organization.vue
  web/src/views/Ingestion.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#5697 test: e2e-enrichment-test
  tests/ui-testing/playwright-tests/enrichment.spec.js
Labels: 🧹 Updates

#5689 fix: Migration to enforce unique folder names
  src/common/utils/auth.rs
  src/handler/http/request/folders.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/folders.rs
  src/infra/src/table/migration/m20250113_144600_create_unique_folder_name_idx.rs
  src/infra/src/table/migration/mod.rs
  src/service/folders.rs
Labels: ☢️ Bug

#5699 fix: pipeline super_cluster update
  Cargo.lock
  src/common/infra/config.rs
  src/service/db/pipeline.rs
  src/super_cluster_queue/mod.rs
  src/super_cluster_queue/pipelines.rs
  src/super_cluster_queue/search_job/mod.rs
  src/super_cluster_queue/search_job/search_job_partitions.rs
  src/super_cluster_queue/search_job/search_job_results.rs
  src/super_cluster_queue/search_job/search_jobs.rs
Labels: ☢️ Bug, 🧹 Updates

#5700 feat: move FolderType into `config::meta` module
  src/config/src/meta/folder.rs
  src/handler/http/models/folders.rs
  src/handler/http/request/folders.rs
  src/infra/src/table/alerts/mod.rs
  src/infra/src/table/dashboards.rs
  src/infra/src/table/folders.rs
  src/service/alerts/alert.rs
  src/service/dashboards/mod.rs
  src/service/folders.rs
Labels: ✏️ Feature

#5695 fix: fixed exploring enrichment table from pipelines
  web/src/components/functions/EnrichmentTableList.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#5639 fix: dashboard search fixes
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug

#5702 fix: Emit supercluster events for folder creation/deletion/updates
  Cargo.lock
  src/infra/src/table/alerts/mod.rs
  src/infra/src/table/folders.rs
  src/service/dashboards/mod.rs
  src/service/db/alerts/alert/new.rs
  src/service/folders.rs
  src/super_cluster_queue/alerts.rs
  src/super_cluster_queue/dashboards.rs
  src/super_cluster_queue/folders.rs
  src/super_cluster_queue/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#5688 feat: impl metrics cache
  .github/workflows/unit-tests.yml
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/config/src/meta/promql.rs
  src/config/src/metrics.rs
  src/config/src/utils/md5.rs
  src/config/src/utils/schema.rs
  src/handler/http/request/promql/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/job/mod.rs
  src/router/http/mod.rs
  src/router/http/ws.rs
  src/service/alerts/mod.rs
  src/service/promql/mod.rs
  src/service/promql/search/cache/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/promql/value.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#5711 feat: remove old alert code that stored alerts in `meta` table
  src/service/db/alerts/alert/mod.rs
  src/service/db/alerts/alert/old.rs
Labels: 🧹 Updates, ✏️ Feature

#5712 feat: Clean up old alerts code
  src/service/db/alerts/alert.rs
  src/service/db/alerts/alert/mod.rs
Labels: ✏️ Feature

#5716 feat: keep optimize metrics cache
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/cache/storage.rs
  src/proto/proto/cluster/metrics.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/promql/engine.rs
  src/service/promql/exec.rs
  src/service/promql/search/cache/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/mod.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
Labels: ✏️ Feature

#5717 fix: renamed save function to save
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#5719 fix: multiple stream can't query with PromQL
  src/service/promql/engine.rs
  src/service/promql/exec.rs
Labels: ☢️ Bug

#5722 fix: failing migration for releases before 0.14.1
  src/infra/src/table/mod.rs
Labels: ☢️ Bug

#5546 fix: Import dashboard latest revamp
  web/src/composables/shared/router.ts
  web/src/locales/languages/en.json
  web/src/views/Dashboards/ImportDashboard.vue
Labels: ☢️ Bug, 🧹 Updates

#5725 fix: dashboard cache issue with websocket
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#5727 fix: check super_cluster_enabled before syncing
  src/service/folders.rs
Labels: ☢️ Bug

#5731 test: enrichment-pipeline-test
  tests/api-testing/tests/test_pipeline.py
  tests/ui-testing/playwright-tests/enrichment.spec.js
Labels: 🧹 Updates

#5732 fix: update error message for folder duplicate name error
  src/handler/http/request/folders.rs
  src/service/folders.rs
Labels: ☢️ Bug, 🧹 Updates

#5735 fix: use http domain for tls inner communication
  src/common/utils/http.rs
  src/config/src/config.rs
  src/main.rs
  src/router/http/mod.rs
  src/router/http/ws.rs
  src/service/grpc.rs
  src/service/tls/mod.rs
Labels: ☢️ Bug

#5739 fix: tls with router
  src/main.rs
  src/router/http/mod.rs
  src/router/http/ws.rs
  src/service/tls/mod.rs
Labels: ☢️ Bug

#5672 feat: enable trace ingestion for scheduled pipeline
  Cargo.lock
  Cargo.toml
  src/config/src/utils/download_utils.rs
  src/handler/grpc/request/ingest.rs
  src/job/mmdb_downloader.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/scheduler.rs
  src/service/pipeline/mod.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#5743 fix: dynamic filter issue
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ☢️ Bug

#5746 fix: ws path proxy
  src/router/http/mod.rs
Labels: ☢️ Bug

#5630 test: New alerts endpoints PyTest
  tests/api-testing/tests/test_alertsnew.py
Labels: 🧹 Updates

#5748 fix: dashboard on tab edit in dark mode input was not visible
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/TabsSettings.vue
Labels: ☢️ Bug

#5756 test: selected-duration-results
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
Labels: 🧹 Updates

#5755 fix: run upto the populate_alerts_table migration first
  src/infra/src/table/mod.rs
Labels: ☢️ Bug

#5758 perf: keep improve metrics performance
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/meta/promql.rs
  src/config/src/utils/arrow.rs
  src/config/src/utils/schema.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/schema/mod.rs
  src/job/mod.rs
  src/main.rs
  src/router/http/mod.rs
  src/service/db/compact/files.rs
  src/service/db/compact/organization.rs
  src/service/metrics/json.rs
  src/service/metrics/mod.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/promql/binaries/vector_operations.rs
  src/service/promql/engine.rs
  src/service/promql/functions/histogram.rs
  src/service/promql/functions/holt_winters.rs
  src/service/promql/functions/label_join.rs
  src/service/promql/functions/label_replace.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/mod.rs
  src/service/promql/value.rs
Labels: 🧹 Updates

#5763 fix: fix automation changes
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: ☢️ Bug

#5729 perf: keep improve metrics performance
  .github/workflows/playwright.yml
  src/config/src/meta/inverted_index.rs
  src/service/promql/engine.rs
  src/service/promql/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug, 🧹 Updates

#5744 feat: external destinations
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/alerts/destinations.rs
  src/config/src/meta/pipeline/components.rs
  src/config/src/meta/pipeline/mod.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/request/metrics/querier.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/infra/Cargo.toml
  src/infra/src/errors/mod.rs
  src/ingester/src/entry.rs
  src/ingester/src/lib.rs
  src/ingester/src/wal.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/job/pipeline.rs
  src/main.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  src/service/alerts/mod.rs
  src/service/logs/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/otlp.rs
  src/service/pipeline/batch_execution.rs
  src/service/pipeline/mod.rs
  src/service/pipeline/pipeline_entry.rs
  src/service/pipeline/pipeline_exporter.rs
  src/service/pipeline/pipeline_file_server.rs
  src/service/pipeline/pipeline_http_exporter_client.rs
  src/service/pipeline/pipeline_offset_manager.rs
  src/service/pipeline/pipeline_receiver.rs
  src/service/pipeline/pipeline_wal_writer.rs
  src/service/pipeline/pipeline_watcher.rs
  src/service/search/mod.rs
  src/service/tls/mod.rs
  src/service/traces/mod.rs
  src/wal/benches/write.rs
  src/wal/src/lib.rs
  src/wal/src/reader.rs
  src/wal/src/writer.rs
  src/wal/tests/wal.rs
  web/src/assets/images/pipeline/externalOutput.svg
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AlertsDestinationList.vue
  web/src/components/alerts/PipelinesDestinationList.vue
  web/src/components/alerts/index.ts
  web/src/components/pipeline/NodeForm/ExternalDestination.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelineView.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/useManagementRoutes.ts
  web/src/locales/languages/en.json
  web/src/plugins/pipelines/CustomNode.vue
  web/src/services/alert_destination.ts
  web/src/test/unit/components/alerts/DestinationList.spec.ts
  web/src/ts/interfaces/alert.ts
Labels: ✏️ Feature

#5749 fix: Retain 0 as a valid value instead of treating it as false or null
  web/src/plugins/logs/TenstackTable.vue
  web/src/utils/json.ts
Labels: Invalid PR Title, ☢️ Bug

#5776 feat: wal file size limit & modify retry frequency and retry bug
  src/config/src/config.rs
  src/job/pipeline.rs
  src/service/pipeline/mod.rs
  src/service/pipeline/pipeline_exporter.rs
  src/service/pipeline/pipeline_receiver.rs
  src/service/pipeline/pipeline_watcher.rs
Labels: ☢️ Bug, ✏️ Feature

#5781 fix: dashboard config value position not getting saved
  src/config/src/meta/dashboards/v5/mod.rs
Labels: ☢️ Bug

#5787 fix: pipeline multiple remote write
  src/service/pipeline/batch_execution.rs
  src/service/pipeline/pipeline_receiver.rs
  src/service/pipeline/pipeline_wal_writer.rs
Labels: ☢️ Bug

#5778 fix: import dashboard issues
  web/src/views/Dashboards/ImportDashboard.vue
Labels: ☢️ Bug

#5789 test: Updated Sanity Playwright for SELECT histogram
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#5790 feat: pipeline bugfix
  src/handler/http/request/alerts/destinations.rs
  src/service/alerts/destinations.rs
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/AlertsDestinationList.vue
  web/src/views/AppAlerts.vue
Labels: ☢️ Bug, ✏️ Feature

#5794 perf: keep improve metrics performance
  src/service/promql/aggregations/avg.rs
  src/service/promql/aggregations/bottomk.rs
  src/service/promql/aggregations/count.rs
  src/service/promql/aggregations/count_values.rs
  src/service/promql/aggregations/group.rs
  src/service/promql/aggregations/max.rs
  src/service/promql/aggregations/min.rs
  src/service/promql/aggregations/mod.rs
  src/service/promql/aggregations/quantile.rs
  src/service/promql/aggregations/stddev.rs
  src/service/promql/aggregations/stdvar.rs
  src/service/promql/aggregations/sum.rs
  src/service/promql/aggregations/topk.rs
  src/service/promql/binaries/mod.rs
  src/service/promql/binaries/scalar_operations.rs
  src/service/promql/binaries/vector_operations.rs
  src/service/promql/common.rs
  src/service/promql/engine.rs
  src/service/promql/exec.rs
  src/service/promql/functions/absent.rs
  src/service/promql/functions/absent_over_time.rs
  src/service/promql/functions/avg_over_time.rs
  src/service/promql/functions/changes.rs
  src/service/promql/functions/clamp.rs
  src/service/promql/functions/count_over_time.rs
  src/service/promql/functions/delta.rs
  src/service/promql/functions/deriv.rs
  src/service/promql/functions/histogram.rs
  src/service/promql/functions/holt_winters.rs
  src/service/promql/functions/idelta.rs
  src/service/promql/functions/increase.rs
  src/service/promql/functions/irate.rs
  src/service/promql/functions/label_join.rs
  src/service/promql/functions/label_replace.rs
  src/service/promql/functions/last_over_time.rs
  src/service/promql/functions/math_operations.rs
  src/service/promql/functions/max_over_time.rs
  src/service/promql/functions/min_over_time.rs
  src/service/promql/functions/mod.rs
  src/service/promql/functions/predict_linear.rs
  src/service/promql/functions/quantile_over_time.rs
  src/service/promql/functions/rate.rs
  src/service/promql/functions/resets.rs
  src/service/promql/functions/stddev_over_time.rs
  src/service/promql/functions/stdvar_over_time.rs
  src/service/promql/functions/sum_over_time.rs
  src/service/promql/functions/time_operations.rs
  src/service/promql/functions/vector.rs
  src/service/promql/mod.rs
  src/service/promql/name_visitor.rs
  src/service/promql/search/cache/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/search/mod.rs
  src/service/promql/selector_visitor.rs
  src/service/promql/utils.rs
  src/service/promql/value.rs
Labels: 🧹 Updates

#5798 fix: forbid dest delete if used by pipeline
  src/config/src/meta/pipeline/mod.rs
  src/service/alerts/destinations.rs
Labels: ☢️ Bug

#5800 fix: we should always create tantivy if the schema have the settings
  src/config/src/utils/schema_ext.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug, ✏️ Feature

#5764 feat: Unit tests for `AuthExtractor` (Part 1 of 2)
  src/common/utils/auth.rs
  src/common/utils/auth_tests.rs
  src/common/utils/mod.rs
  src/config/src/config.rs
Labels: 🧹 Updates, ✏️ Feature

#5797 test: rum search updated pytest
  tests/api-testing/tests/test_rum.py
  tests/api-testing/tests/test_search.py
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#5802 fix: Add license
  deny.toml
  src/handler/http/request/actions/action.rs
  src/handler/http/request/script_server/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#5803 test: skipping RUM Search Pytest sanity get history playwright
  tests/api-testing/tests/test_rum.py
  tests/api-testing/tests/test_search.py
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#5750 feat: streaming aggs ws
  src/handler/http/request/websocket/search.rs
  src/handler/http/request/websocket/utils.rs
  web/src/composables/useLogs.ts
  web/src/ts/interfaces/query.ts
Labels: ✏️ Feature

#5777 fix: dashboard Trellis layout issues
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/locales/languages/en.json
  web/src/utils/dashboard/calculateGridForSubPlot.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5796 fix: dashboard color option issue with numeric field
  web/src/utils/dashboard/colorPalette.ts
Labels: ☢️ Bug

#5805 fix: form validations fixed in the UI for external destination node
  web/src/components/pipeline/NodeForm/ExternalDestination.vue
Labels: ☢️ Bug

#5813 fix: use entire width for external destination form
  web/src/components/pipeline/NodeForm/ExternalDestination.vue
Labels: ☢️ Bug

#5810 fix: timestamp before pipeline processing
  Cargo.lock
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/pipeline/batch_execution.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#5801 feat: update saved view feature
  web/src/plugins/logs/SearchBar.vue
Labels: 🧹 Updates, ✏️ Feature

#5814 test: Added dependencies for cipher keys
  tests/api-testing/pyproject.toml
Labels: 🤖 Dependencies, 🧹 Updates, ✏️ Feature

#5812 fix: moved about option to help dropdown
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#5816 feat: improve proxy request handling with cookie preservation
  src/router/http/mod.rs
Labels: 🧹 Updates, ✏️ Feature

#5815 fix: about page locator and link
  tests/ui-testing/pages/aboutPage.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#5818 fix: permission issue for native users
  src/handler/http/request/websocket/utils.rs
Labels: ☢️ Bug

#5696 fix: added support for minimum auto refresh interval
  .github/workflows/playwright.yml
  web/src/components/AutoRefreshInterval.vue
  web/src/components/actionScripts/EditScript.vue
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/components/reports/CreateReport.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/metrics/Index.vue
  web/src/utils/zincutils.ts
  web/src/views/Dashboards/ViewDashboard.vue
  web/src/views/RUM/AppPerformance.vue
Labels: ☢️ Bug, ✏️ Feature

#5775 feat: Unit tests for `AuthExtractor` (Part 2 of 2)
  src/common/utils/auth_tests.rs
Labels: 🧹 Updates, ✏️ Feature

#5828 fix: changed dialog label and button label
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#5830 fix: test
  src/common/utils/auth_tests.rs
Labels: ☢️ Bug, 🧹 Updates

#5829 fix: Y-axis max value formatting issue in trellis
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#5831 fix: migrations for longtext
  src/config/src/config.rs
  src/infra/src/table/entity/alerts.rs
  src/infra/src/table/entity/search_jobs.rs
  src/infra/src/table/migration/m20241209_120000_create_alerts_table.rs
  src/infra/src/table/migration/m20241222_085111_search_jobs.rs
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/short_urls.rs
Labels: ☢️ Bug

#5610 fix: Omit cached responses older than stream min_ts
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#5835 fix: import dashboard issue with old versions
  web/src/views/Dashboards/ImportDashboard.vue
Labels: ☢️ Bug

#5837 fix: logs to debug db error
  src/service/db/short_url.rs
  tests/ui-testing/pages/logsPage.js
Labels: ☢️ Bug

#5838 fix: disable mmdb_download on alert_manager
  src/job/mod.rs
Labels: ☢️ Bug

#5604 fix: traces search ui fixes
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceHeader.vue
  web/src/plugins/traces/TraceTree.vue
Labels: ☢️ Bug

#5842 test: e2e-remote-pipeline
  .github/workflows/playwright.yml
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/pipelinePage.js
  tests/ui-testing/playwright-tests/remotepipeline.spec.js
Labels: 🧹 Updates

#5845 fix: use folder id and dashboard id to generate ksuid hash in recreate folder migration
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
Labels: ☢️ Bug, ✏️ Feature

#5841 fix: remove seaorm column type for entities
  src/infra/src/table/entity/action_scripts.rs
  src/infra/src/table/entity/cipher_keys.rs
  src/infra/src/table/entity/dashboards.rs
  src/infra/src/table/entity/folders.rs
  src/infra/src/table/entity/search_job_partitions.rs
  src/infra/src/table/entity/search_job_results.rs
  src/infra/src/table/entity/search_jobs.rs
  src/infra/src/table/migration/m20241115_150000_populate_folders_table.rs
  src/infra/src/table/migration/m20241119_000002_populate_dashboards_table.rs
  src/infra/src/table/migration/m20241119_000003_delete_metas.rs
  src/infra/src/table/migration/m20241215_190333_delete_metas.rs
  src/infra/src/table/migration/m20241217_155000_populate_alerts_table.rs
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
  src/infra/src/table/migration/m20250113_144600_create_unique_folder_name_idx.rs
  tests/ui-testing/pages/logsPage.js
Labels: ☢️ Bug, 🧹 Updates

#5783 feat: added search feature to saved function
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ✏️ Feature

#5832 fix: UI omitting first row of results in logs page
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug

#5848 fix: search canceled for super cluster
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/grpc/flight.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#5852 test: schema assertion for str_match
  tests/ui-testing/playwright-tests/schema.spec.js
Labels: 🧹 Updates

#5680 feat: dashboard annotations
  src/common/utils/auth.rs
  src/config/src/meta/mod.rs
  src/config/src/meta/timed_annotations.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/dashboards/timed_annotations.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/infra/src/table/entity/dashboards.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/entity/timed_annotation_panels.rs
  src/infra/src/table/entity/timed_annotations.rs
  src/infra/src/table/migration/m20250124_000001_create_timed_annotations_table.rs
  src/infra/src/table/migration/m20250124_000002_create_timed_annotation_panels_table.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/timed_annotation_panels.rs
  src/infra/src/table/timed_annotations.rs
  src/service/dashboards/mod.rs
  src/service/dashboards/timed_annotations.rs
  src/super_cluster_queue/dashboards.rs
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/AddAnnotation.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/composables/dashboard/useAnnotations.ts
  web/src/composables/dashboard/useAnnotationsData.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useNotifications.ts
  web/src/services/dashboard_annotations.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/getAnnotationsData.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#5851 fix: dashboard `with` query support
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/plugins/metrics/Index.vue
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/query/sqlUtils.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug
