Repository openobserve/openobserve, pull requests merged in 2025-05, with the labels that each got.

#6688 fix: ws `tokio::select`, `health_check` & `router_id` for router-querier conn
  src/handler/http/request/ws/mod.rs
  src/handler/http/request/ws/session.rs
  src/router/http/ws/connection.rs
  src/router/http/ws/error.rs
  src/router/http/ws/handler.rs
  src/service/db/short_url.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
  web/src/composables/useWebSocket.ts
Labels: ☢️ Bug

#6697 fix: otlp logs ingestion
  src/service/ingestion/mod.rs
  src/service/logs/otlp.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#6694 fix: scheduler query trace_id should be searchable in traces page
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/ws/session.rs
  src/service/alerts/mod.rs
  src/service/mod.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
Labels: ☢️ Bug

#6675 feat: separate ddl commands
  src/cli/basic/cli.rs
  src/common/mod.rs
  src/config/src/config.rs
  src/infra/src/db/mod.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/lib.rs
  src/infra/src/pipeline/mysql.rs
  src/infra/src/pipeline/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/infra/src/table/distinct_values.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/short_urls.rs
  src/lib.rs
  src/main.rs
  src/migration/dashboards.rs
  src/migration/file_list.rs
  src/migration/meta.rs
  src/migration/mod.rs
  src/migration/pipeline_func.rs
  src/migration/schema.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#6704 fix: always create db dir in infra::init
  src/infra/src/lib.rs
Labels: ☢️ Bug, ✏️ Feature

#6705 fix: streaming aggs support for http & ws server refactor (querier)
  src/common/infra/config.rs
  src/config/src/config.rs
  src/config/src/meta/websocket.rs
  src/config/src/router.rs
  src/handler/http/request/ws/mod.rs
  src/handler/http/request/ws/session.rs
  src/main.rs
  src/router/http/mod.rs
  src/router/http/ws/connection.rs
  src/router/http/ws/handler.rs
  src/router/http/ws/mod.rs
  src/router/http/ws/session.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/distributed_plan/streaming_aggs_exec.rs
  src/service/search/mod.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
  tests/ui-testing/playwright-tests/wsload.spec.js
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug, 🧹 Updates

#6605 feat: Make Align time optional for alerts/pipelines and reports
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/dashboards/reports.rs
  src/handler/http/models/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
  src/infra/src/table/entity/alerts.rs
  src/infra/src/table/migration/m20250422_000001_add_alert_align_time.rs
  src/infra/src/table/migration/mod.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ✏️ Feature

#6708 fix: channel closed
  src/handler/http/request/ws/mod.rs
  src/handler/http/request/ws/session.rs
  src/router/http/ws/connection.rs
  src/router/http/ws/handler.rs
Labels: ☢️ Bug

#6711 fix: dashboard match_all operator
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#6712 fix: err_ws_conn
  src/handler/http/request/ws/mod.rs
  src/router/http/ws/connection.rs
  src/router/http/ws/error.rs
  src/router/http/ws/handler.rs
Labels: ☢️ Bug

#6715 fix: update `config::DB_SCHEMA_VERSION` for alert table align time column
  src/config/src/config.rs
Labels: ☢️ Bug, 🧹 Updates

#6678 fix: promql parser adjust the cache_key
  src/service/promql/engine.rs
Labels: ☢️ Bug

#6667 feat: impl multiple storage accounts
  src/cli/basic/cli.rs
  src/cli/basic/load.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/meta/stream.rs
  src/config/src/metrics.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/cache/mod.rs
  src/infra/src/cache/storage.rs
  src/infra/src/cache/tmpfs.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/lib.rs
  src/infra/src/storage/accounts.rs
  src/infra/src/storage/local.rs
  src/infra/src/storage/mod.rs
  src/infra/src/storage/remote.rs
  src/infra/src/storage/wal.rs
  src/job/file_downloader.rs
  src/job/file_list_dump.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/migration/file_list.rs
  src/proto/proto/cluster/common.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/deleted.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/compact/worker.rs
  src/service/db/file_list/local.rs
  src/service/db/file_list/mod.rs
  src/service/file_list.rs
  src/service/file_list_dump.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/storage/file_list.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/mod.rs
  src/service/search/datafusion/storage/tmpfs.rs
  src/service/search/datafusion/storage/wal.rs
  src/service/search/grpc/storage.rs
  src/service/search/tantivy/puffin/reader.rs
  src/service/search/tantivy/puffin_directory/reader.rs
Labels: ✏️ Feature

#6716 fix: multiple object store for search_job & actions
  src/handler/grpc/request/search/mod.rs
  src/service/search_jobs.rs
  src/super_cluster_queue/action_scripts.rs
Labels: ☢️ Bug

#6720 fix: loading indicator while loading folders, dashboard or tabs in drilldown pop up
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
Labels: ☢️ Bug

#6723 fix: summary api should list all folder alerts
  src/service/alerts/alert.rs
  src/service/organization.rs
Labels: ☢️ Bug

#6727 fix: super cluster derived stream module key error
  src/super_cluster_queue/scheduler.rs
Labels: ☢️ Bug

#6693 fix: sort the nodes by id
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/metrics.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/search/search_inspector.rs
  src/job/file_downloader.rs
  src/service/compact/merge.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/grpc/storage.rs
  src/service/search/inspector.rs
Labels: ☢️ Bug

#6556 fix: encode search query if `ZO_UI_SQL_BASE64_ENABLED=true`
  src/service/websocket_events/search.rs
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6722 test(dashboard): add geomap and map test cases
  .github/workflows/playwright.yml
  tests/test-data/geo_map.json
  tests/ui-testing/pages/dashboardPages/dashboard-chart.js
  tests/ui-testing/pages/dashboardPages/dashboard-panel-configs.js
  tests/ui-testing/pages/dashboardPages/dashboard-variables.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-geoMap.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-maps.spec.js
  tests/ui-testing/playwright-tests/utils/dashIngestion.js
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: 🧹 Updates, ✏️ Feature

#6738 fix: realtime pipeline for trace ingestion into wrong stream
  src/service/traces/mod.rs
Labels: ☢️ Bug

#6726 fix: cache miss after NATs restarts
  src/common/infra/cluster/nats.rs
  src/common/infra/config.rs
  src/infra/src/db/nats.rs
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug

#6739 fix: multiple account with file_list_dump
  src/job/file_list_dump.rs
Labels: ☢️ Bug

#6732 fix: 4xx error showing issue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/services/alerts.ts
Labels: ☢️ Bug

#6740 fix: remove update compress size to db
  src/job/file_downloader.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug, 🧹 Updates

#6741 fix: metrics for storage
  src/config/src/metrics.rs
  src/infra/src/storage/local.rs
  src/infra/src/storage/remote.rs
  src/job/file_downloader.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#6743 fix: metrics report duplicated
  src/config/src/metrics.rs
Labels: ☢️ Bug

#6744 fix: enrichment_table::get returns error when both meta and stream_stats table is empty
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#6748 fix: added error message code for cancelled search query
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchResult.vue
  web/src/utils/common.ts
Labels: ☢️ Bug, ✏️ Feature

#6647 fix: highlight syntax in logs page
  web/src/components/HighLight.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: Invalid PR Title, ☢️ Bug

#6754 fix: add debug logs for required nodes
  src/common/utils/auth_tests.rs
  src/config/src/meta/cluster.rs
  src/handler/http/request/organization/org.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug, ✏️ Feature

#6706 fix: Stack Overflow when updating log search results
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6761 fix: is_querier error for super cluster
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/super_cluster/follower.rs
  tests/integration_test.rs
Labels: ☢️ Bug

#6764 test: e2e-stream-name
  .github/workflows/playwright.yml
  tests/ui-testing/pages/streamPage.js
  tests/ui-testing/playwright-tests/streamname.spec.js
  tests/ui-testing/utils/apiUtils.js
Labels: 🧹 Updates

#6763 fix: supercluster scan stats
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/request/search/mod.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/utils.rs
Labels: ☢️ Bug

#6762 fix: ZO_DEFAULT_MAX_QUERY_RANGE_DAYS env should be returned by streams list api
  src/common/utils/stream.rs
  src/handler/http/request/status/mod.rs
  src/service/stream.rs
  web/src/composables/useLogs.ts
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug

#6766 fix: supercluster scan stats (#6763)
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/request/search/mod.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/utils.rs
Labels: ☢️ Bug

#6769 fix: dashboard annotations api response for some charts
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6776 fix: pipeline panic due to empty input
  src/service/pipeline/batch_execution.rs
Labels: ☢️ Bug

#6777 fix: s3 ListBucket error
  src/infra/src/storage/remote.rs
Labels: ☢️ Bug

#6607 feat: add condition list for OR operator support in alerts
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/sql.rs
  src/handler/http/models/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6767 fix: ZO_DEFAULT_MAX_QUERY_RANGE_DAYS env should be returned by streams list api (#6762)
  src/common/utils/stream.rs
  src/handler/http/request/status/mod.rs
  src/service/stream.rs
  web/src/composables/useLogs.ts
  web/src/plugins/traces/Index.vue
Labels: ☢️ Bug

#6742 fix: scheduler query trace_id should be searchable in traces page
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/ws/session.rs
  src/service/alerts/mod.rs
  src/service/mod.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
Labels: ☢️ Bug

#6787 fix: dashboard panel error msg automation issue
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#6768 fix: internal error audit
  src/handler/http/request/search/error_utils.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/short_url/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/request/ws/session.rs
  src/infra/src/errors/mod.rs
  src/service/enrichment_table/mod.rs
  src/service/functions.rs
  src/service/logs/syslog.rs
  src/service/metrics/otlp.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/service/websocket_events/utils.rs
Labels: ☢️ Bug

#6793 fix: internal error audit (#6768)
  src/handler/http/request/search/error_utils.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/short_url/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/request/ws/session.rs
  src/infra/src/errors/mod.rs
  src/service/enrichment_table/mod.rs
  src/service/functions.rs
  src/service/logs/syslog.rs
  src/service/metrics/otlp.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/service/websocket_events/utils.rs
Labels: ☢️ Bug

#6770 fix: fixed page-count api for streaming aggs query
  web/src/components/QueryEditor.vue
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/utils/common.ts
Labels: ☢️ Bug

#6794 fix: Values API get partitions for no count
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#6800 fix: consider actual records size per page for search job
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6790 test: fix dashboard filter testcase
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
Labels: ☢️ Bug, 🧹 Updates

#6802 test: e2e-cmd+enter-test
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
Labels: 🧹 Updates

#6808 fix: pipeline list show cron expression if enabled
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#6819 fix: search partition `order_by` (#6817)
  src/service/search/mod.rs
Labels: ☢️ Bug

#6792 feat: download manager improvements
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/job/file_downloader.rs
  src/job/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: 🧹 Updates, ✏️ Feature

#6820 fix: parquet not found ingester
  src/job/files/parquet.rs
  src/service/db/file_list/local.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#6830 fix: parquet not found ingester
  src/common/infra/cluster/mod.rs
  src/handler/http/request/search/search_stream.rs
  src/job/files/parquet.rs
  src/service/db/file_list/local.rs
  src/service/search/grpc/wal.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#6822 fix: validate downlaod size with blob store and validate file
  src/infra/src/cache/file_data/mod.rs
Labels: ☢️ Bug

#6823 fix: validate download size with blob store and validate file
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/storage/mod.rs
  src/service/compact/flatten.rs
Labels: ☢️ Bug

#6814 fix: Update enrichment table cache with correct start time after meta table update and pipeline delayed timerange fix
  src/config/src/meta/triggers.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
  src/super_cluster_queue/meta.rs
Labels: ☢️ Bug, 🧹 Updates

#6832 fix: use real time id generator
  src/config/src/ider.rs
Labels: ☢️ Bug

#6836 fix: simple distinct sql for http api
  src/config/src/utils/sql.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/service/search/mod.rs
  src/service/search/search_stream.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#6838 fix: last page total not getting added in total count
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, ✏️ Feature

#6842 fix: ent build and clippy
  src/config/src/meta/search.rs
  src/handler/http/request/search/search_stream.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#6795 test: enabled streaming search playwright
  .github/workflows/playwright.yml
  tests/ui-testing/pages/managementPage.js
  tests/ui-testing/playwright-tests/streaming.spec.js
Labels: 🧹 Updates

#6846 fix: skip download if partial downalod after all retries
  src/infra/src/cache/file_data/mod.rs
Labels: ☢️ Bug

#6848 fix: match one join query with join key filter (#6845)
  src/service/search/datafusion/optimizer/mod.rs
Labels: ☢️ Bug

#6849 fix: auth for `_values_stream`
  src/common/utils/auth.rs
Labels: ☢️ Bug

#6803 test: streaming search pytest
  tests/api-testing/tests/test_streaming.py
Labels: 🧹 Updates

#6844 fix: Update enrichment table cache with correct start time after meta table update and pipeline delayed timerange fix
  src/config/src/meta/triggers.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
  src/super_cluster_queue/meta.rs
Labels: ☢️ Bug, 🧹 Updates

#6856 fix: delete stream over regions
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/search/search_stream.rs
  src/service/stream.rs
  src/super_cluster_queue/schemas.rs
Labels: ☢️ Bug

#6855 fix: delete stream over regions
  Cargo.lock
  Cargo.toml
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/search/search_stream.rs
  src/service/stream.rs
  src/super_cluster_queue/schemas.rs
Labels: ☢️ Bug

#6851 fix: truncate if more results from df
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#6860 fix: add nats logs
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug, ✏️ Feature

#6862 fix: dashboard go to logs vrl issue
  web/src/components/dashboards/PanelContainer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6866 feat: add env to enable use_stream_setting for partitions
  src/config/src/config.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#6853 fix: chery-pick fixes
  src/common/utils/auth.rs
  src/config/src/config.rs
  src/config/src/utils/sql.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/service/search/mod.rs
  src/service/search/search_stream.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#6868 fix: dashboard go to logs vrl issue
  web/src/components/dashboards/PanelContainer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6869 fix: truncate if more results from df (#6851)
  .github/workflows/playwright.yml
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#6870 fix: move event download to download manager
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/job/file_downloader.rs
  src/job/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#6861 fix: add nats logs (#6860)
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug, ✏️ Feature

#6852 feat: download manager improvements
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/job/file_downloader.rs
  src/job/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: 🧹 Updates, ✏️ Feature

#6873 fix: move event download to download manager
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/infra/src/cache/file_data/mod.rs
  src/job/file_downloader.rs
  src/job/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#6875 fix: add lock to download file
  src/job/file_downloader.rs
Labels: ☢️ Bug, ✏️ Feature

#6876 fix: consistent hashing
  src/cli/basic/cli.rs
  src/cli/basic/http.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/meta/search.rs
  src/config/src/metrics.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
Labels: Invalid PR Title, ☢️ Bug

#6878 fix: ent deadlock with sqlite
  src/migration/mod.rs
Labels: ☢️ Bug

#6881 fix: Partition stream stats handle case when end time is 0
  src/service/search/mod.rs
Labels: ☢️ Bug

#6882 fix: Partition stream stats handle case when end time is 0
  src/service/search/mod.rs
Labels: ☢️ Bug

#6888 fix: broadcast event use file id
  src/cli/basic/cli.rs
  src/common/migration/file_list.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/files/broadcast.rs
  src/job/files/parquet.rs
  src/proto/proto/cluster/common.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/compact/worker.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/file_list/mod.rs
  src/service/file_list.rs
Labels: ☢️ Bug

#6815 fix: pass query as single line for partition and search API call
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#6889 fix: cache miss after NATs restarts (#6726)
  src/common/infra/cluster/nats.rs
  src/common/infra/config.rs
  src/infra/src/db/nats.rs
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug

#6890 test: validate max_query_range for 1 hour pytest
  tests/api-testing/tests/test_streaming.py
Labels: 🧹 Updates

#6840 fix: ider init with machine id
  src/handler/http/request/search/mod.rs
  src/handler/http/request/ws/session.rs
  src/infra/src/db/nats.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/ingester/src/writer.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  src/service/dashboards/mod.rs
  src/service/file_list.rs
  src/service/search/datafusion/plan/tantivy_count_exec.rs
  src/service/search/grpc_search.rs
  src/service/search/super_cluster/follower.rs
  src/service/search_jobs.rs
  src/super_cluster_queue/search_job/search_jobs.rs
Labels: ☢️ Bug

#6891 fix: broadcast event use file id
  src/cli/basic/cli.rs
  src/cli/basic/http.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/meta/search.rs
  src/config/src/meta/stream.rs
  src/config/src/metrics.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/file_list_dump.rs
  src/job/files/broadcast.rs
  src/job/files/parquet.rs
  src/migration/file_list.rs
  src/proto/proto/cluster/common.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/flatten.rs
  src/service/compact/merge.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/file_list/mod.rs
  src/service/file_list.rs
  src/service/file_list_dump.rs
Labels: ☢️ Bug

#6896 fix: broadcast on compactor
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
Labels: ☢️ Bug

#6801 feat: add _timestamp to tantivy index to optimize histogram queries
  src/cli/basic/cli.rs
  src/common/infra/mod.rs
  src/common/utils/websocket.rs
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/meta/sql.rs
  src/config/src/utils/file.rs
  src/config/src/utils/sql.rs
  src/config/src/utils/time.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/migration/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/db/instance.rs
  src/service/db/metas.rs
  src/service/db/mod.rs
  src/service/db/version.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/plan/tantivy_count_exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/sql.rs
  src/service/search/tantivy/puffin_directory/mod.rs
  src/service/search/tantivy/puffin_directory/reader.rs
Labels: ✏️ Feature

#6898 fix: add more unit test for time parse
  src/config/src/meta/sql.rs
  src/config/src/utils/time.rs
  src/handler/http/request/traces/mod.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6900 fix: tantivy timestamp update time
  src/job/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#6894 feat: axis value support for drilldown
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
Labels: ✏️ Feature

#6909 feat: additional drilldown variable support to pass axis value
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/components/dashboards/addPanel/DrilldownUserGuide.vue
Labels: ✏️ Feature

#6905 fix: router with base_uri
  src/cli/basic/cli.rs
  src/config/src/router.rs
  src/main.rs
  src/router/http/mod.rs
Labels: ☢️ Bug

#6893 fix: Dashboard drilldown editor issue
  web/src/components/common/AppDialog.vue
  web/src/components/dashboards/addPanel/Drilldown.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
Labels: ☢️ Bug

#6914 fix: update `DB_SCHEMA_VERSION`
  src/config/src/config.rs
Labels: ☢️ Bug, 🧹 Updates

#6916 fix: stream stats for super cluster
  src/cli/basic/cli.rs
  src/handler/grpc/request/stream.rs
Labels: ☢️ Bug

#6908 fix: demote log level to debug when local cache insert fails
  src/infra/src/file_list/sqlite.rs
Labels: ☢️ Bug

#6913 fix: Dashboard drilldown editor issue (#6893)
  web/src/components/common/AppDialog.vue
  web/src/components/dashboards/addPanel/Drilldown.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
Labels: ☢️ Bug

#5668 fix: Add explicit ordering to pagination in migrations
  src/infra/src/table/migration/m20241217_155000_populate_alerts_table.rs
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
Labels: ☢️ Bug, ✏️ Feature

#6921 fix: stream stats for super cluster
  src/cli/basic/cli.rs
  src/handler/grpc/request/stream.rs
Labels: ☢️ Bug

#6929 fix: divide first
  src/service/search/mod.rs
Labels: ☢️ Bug

#6931 fix: do division first while calculating partitions
  src/service/search/mod.rs
Labels: ☢️ Bug

#6938 fix: handle stream unwrap in AI handler
  src/handler/http/request/ai.rs
Labels: ☢️ Bug

#6936 fix: values response total
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#6925 fix: if gRPC can't start we should stop the app
  src/main.rs
  src/router/http/mod.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/udf/match_all_udf.rs
  src/service/search/datafusion/udf/mod.rs
  src/service/search/sql.rs
  web/src/components/dashboards/QueryEditor.vue
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useSuggestions.ts
  web/src/plugins/metrics/SyntaxGuideMetrics.vue
  web/src/plugins/traces/SyntaxGuide.vue
  web/src/test/unit/helpers/setupTests.ts
  web/src/test/unit/helpers/store.ts
  web/src/utils/query/sqlUtils.ts
  web/src/views/Dashboards/addPanel/AddCondition.vue
Labels: ☢️ Bug

#6924 chore: update datafusion to v46.0.0
  Cargo.lock
  Cargo.toml
  src/config/src/meta/sql.rs
  src/service/search/datafusion/optimizer/join_reorder.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/udaf/percentile_cont.rs
  src/service/search/datafusion/udf/cast_to_timestamp_udf.rs
  src/service/search/datafusion/udf/histogram_udf.rs
  src/service/search/datafusion/udf/match_all_udf.rs
  src/service/search/datafusion/udf/regexp_matches_udf.rs
  src/service/search/datafusion/udf/regexp_udf.rs
Labels: 🧹 Updates

#6920 fix: use _all_ in org related api call
  src/common/utils/auth.rs
  tests/api-testing/tests/test_search.py
Labels: ☢️ Bug

#6952 fix: added missing org identifier in url
  web/src/components/settings/index.vue
Labels: ☢️ Bug, ✏️ Feature

#6917 refactor: Writer new method & Reader test
  src/ingester/src/writer.rs
  src/wal/benches/write.rs
  src/wal/src/errors.rs
  src/wal/src/writer.rs
  src/wal/tests/wal.rs
Labels: 🧹 Updates

#6939 fix: Added label for duration field in traces
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/fields-sidebar/BasicValuesFilter.vue
Labels: ☢️ Bug, ✏️ Feature

#6966 fix: `NOT IN` filter parsing issue for visualization
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#6970 fix: add use_cache for traces latest api
  src/common/meta/http.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/dashboards/timed_annotations.rs
  src/handler/http/request/keys/mod.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/metrics/ingest.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/request/pipeline.rs
  src/handler/http/request/promql/mod.rs
  src/handler/http/request/ratelimit/mod.rs
  src/handler/http/request/search/error_utils.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/search/search_stream.rs
  src/handler/http/request/service_accounts/mod.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/request/users/mod.rs
  src/service/alerts/destinations.rs
  src/service/alerts/templates.rs
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
  src/service/functions.rs
  src/service/logs/syslog.rs
  src/service/metrics/otlp.rs
  src/service/stream.rs
  src/service/syslogs_route.rs
  src/service/traces/mod.rs
  src/service/users.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6972 fix: plan error when join multiple tables
  src/service/compact/merge.rs
  src/service/search/cluster/flight.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/stream.rs
Labels: ☢️ Bug

#6877 fix: dashboard visualization-vrl flaky test case
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: ☢️ Bug, 🧹 Updates

#6912 test: Updated change organisation validation playwright
  tests/api-testing/tests/pages/pipeline_page.py
  tests/api-testing/tests/test_workflow.py
  tests/ui-testing/pages/createOrgPage.js
  tests/ui-testing/pages/homePage.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
Labels: 🧹 Updates

#6971 feat: return ai_enabled boolean in the config api
  src/handler/http/request/status/mod.rs
  web/src/components/functions/FunctionsToolbar.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/layouts/MainLayout.vue
Labels: ✏️ Feature

#6979 fix: return original query if not able to parse via parser
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#6983 fix: update stream stats timeout
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/service/compact/stats.rs
Labels: ☢️ Bug, 🧹 Updates

#6864 fix: http2 streaming pagination fix
  web/src/composables/useLogs.ts
  web/src/ts/interfaces/query.ts
  web/src/workers/streamWorker.js
Labels: ☢️ Bug

#6982 feat: add histogram metric for file access analysis
  src/config/src/metrics.rs
  src/service/search/grpc/storage.rs
Labels: ✏️ Feature
