Repository openobserve/openobserve, pull requests merged in 2025-04, with the labels that each got.

#6438 feat: add new ENV to set token for root user
  src/cli/basic/cli.rs
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/service_accounts/mod.rs
  src/job/mod.rs
  src/service/organization.rs
  src/service/users.rs
Labels: ✏️ Feature

#6439 fix: Removed dead code from websockets
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#6435 feat: cluster info api
  src/common/meta/organization.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/proto/build.rs
  src/proto/proto/cluster/cluster_info.proto
  src/proto/src/generated/cluster.rs
  src/service/cluster_info.rs
  src/service/grpc.rs
  src/service/mod.rs
  src/service/node.rs
Labels: ✏️ Feature

#6440 fix: fixed auto filter issue on TCP , CPU and memory usage
  web/src/components/settings/Nodes.vue
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#6441 fix: added folders in cloning of alerts
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug, ✏️ Feature

#6445 feat: add meta_store to report
  src/common/meta/telemetry.rs
Labels: ✏️ Feature

#6446 fix: add http api search error in the audit stream
  src/handler/http/request/search/error_utils.rs
  src/handler/http/router/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#6447 fix: alerts owner should be logged in user
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/ImportAlert.vue
Labels: ☢️ Bug

#6453 fix: remove scheduled_jobs delete calls from scheduler
  src/config/src/meta/self_reporting/usage.rs
  src/config/src/metrics.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#6455 test: histogram reappears when enabled and data exists playwright
  tests/ui-testing/playwright-tests/websocket.spec.js
Labels: 🧹 Updates

#6456 fix: #6454
  src/handler/http/request/stream/mod.rs
Labels: ☢️ Bug

#6449 fix: node list changes
  web/src/components/settings/Nodes.vue
  web/src/components/settings/index.vue
  web/src/composables/useIsMetaOrg.ts
Labels: ☢️ Bug

#6458 fix: Do not delete Scheduled jobs in derived stream trigger handler and use module key for db_query_nums metrics
  src/config/src/meta/self_reporting/usage.rs
  src/config/src/metrics.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#6459 fix: when uploading enrichment table with column name only, do not delete the enrichment table
  src/config/src/meta/triggers.rs
  src/handler/http/request/enrichment_table/mod.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/db/enrichment_table.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#6457 feat: dashboard filter value based on type
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#6461 fix: search in memtable
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug

#6460 fix: validate filters config while dashboard panel save
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
Labels: ☢️ Bug

#6465 fix: add num_rows for node response for query
  src/service/search/datafusion/distributed_plan/remote_scan.rs
Labels: ☢️ Bug, ✏️ Feature

#6466 fix: optimize update slow
  src/infra/src/table/ratelimit.rs
Labels: ☢️ Bug, 🧹 Updates

#6468 feat: add a index check
  src/infra/src/table/migration/m20250217_115548_ratelimit_table.rs
Labels: ✏️ Feature

#6472 chore: update screenshots
  README.md
  screenshots/function.png
  screenshots/iam_rbac.png
  screenshots/ingestion1.png
  screenshots/logs.png
  screenshots/map.png
  screenshots/pipeline.png
  screenshots/sso.png
  screenshots/zo_home.png
Labels: 🧹 Updates, 📒 Documentation

#6474 fix: improve tokio task consume
  Cargo.lock
  Cargo.toml
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/router/middlewares/slow_log.rs
  src/infra/src/db/etcd.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/job/mmdb_downloader.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
Labels: ☢️ Bug, 🧹 Updates

#6462 fix: rbac migration for service accounts for existing organizations
  src/common/infra/ofga/mod.rs
  src/common/utils/auth_tests.rs
  src/config/src/meta/enrichment_table.rs
Labels: ☢️ Bug

#6477 fix: use new sql replace old sql parser
  src/config/src/meta/sql.rs
  src/handler/http/request/search/mod.rs
  src/service/pipeline/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#6478 fix: reset histogram only when user clicks run query
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6482 fix: dynamic stream name should be taken for search job
  web/src/plugins/logs/SearchSchedulersList.vue
Labels: ☢️ Bug

#6495 fix: cpu usage
  src/config/src/utils/sysinfo/mod.rs
Labels: ☢️ Bug

#6496 fix: additional resources in data source
  web/src/assets/images/ingestion/databricks.svg
  web/src/assets/images/ingestion/heroku.svg
  web/src/assets/images/ingestion/nats.svg
  web/src/assets/images/ingestion/vercel.svg
  web/src/components/ingestion/Database.vue
  web/src/components/ingestion/MessageQueues.vue
  web/src/components/ingestion/Others.vue
  web/src/components/ingestion/databases/Databricks.vue
  web/src/components/ingestion/others/Heroku.vue
  web/src/components/ingestion/others/Vercel.vue
  web/src/components/ingestion/recommended/AWSConfig.vue
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/composables/useIngestion.ts
  web/src/locales/languages/en.json
Labels: ☢️ Bug, ✏️ Feature

#6498 feat: debug ws logs
  src/handler/http/request/ws_v2/session.rs
  src/router/http/ws_v2/handler.rs
  src/router/http/ws_v2/pool.rs
Labels: ☢️ Bug, ✏️ Feature

#6499 fix: ws `Router-Querier` conn reset & remove ws v1
  src/common/utils/auth_tests.rs
  src/common/utils/websocket.rs
  src/config/src/config.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/websocket/mod.rs
  src/handler/http/request/websocket/session.rs
  src/handler/http/request/ws_v2/session.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/router/http/mod.rs
  src/router/http/ws.rs
  src/router/http/ws_v2/connection.rs
  src/router/http/ws_v2/error.rs
  src/router/http/ws_v2/handler.rs
  src/router/http/ws_v2/mod.rs
  src/router/http/ws_v2/pool.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#6500 test(dashboard): add test cases for dashboard folder
  .github/workflows/playwright.yml
  tests/ui-testing/pages/dashboardPages/dashboard-folder.js
  tests/ui-testing/pages/dashboardPages/dashboard-list.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-folder.spec.js
Labels: 🧹 Updates, ✏️ Feature

#6489 feat: add file_time strategy for cache gc
  Cargo.lock
  Cargo.toml
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/config/src/utils/time.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/mod.rs
  src/infra/src/lib.rs
  src/lib.rs
  src/service/promql/search/cache/mod.rs
  src/service/promql/search/mod.rs
Labels: ✏️ Feature

#6512 fix: read and write locks
  src/common/infra/cluster/mod.rs
  src/common/infra/config.rs
  src/handler/http/request/ws_v2/session.rs
  src/router/http/ws_v2/connection.rs
  src/router/http/ws_v2/handler.rs
  src/router/http/ws_v2/pool.rs
  src/router/http/ws_v2/session.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
Labels: ☢️ Bug

#6513 fix: ingest route incorrectly recognized as ws route
  src/config/src/router.rs
  src/router/http/mod.rs
Labels: ☢️ Bug

#6506 fix: show total events in distinct query when histogram is on
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6514 feat: check s3 config
  src/common/infra/mod.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/infra/src/lib.rs
  src/infra/src/storage/remote.rs
  src/job/stats.rs
  src/main.rs
Labels: ✏️ Feature

#6518 fix: logs page issues
  web/src/components/alerts/AlertList.vue
  web/src/components/common/sidebar/FolderList.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#6519 fix: ws error code to match http code
  src/service/websocket_events/utils.rs
Labels: ☢️ Bug

#6525 fix: upgrade actix-ws 0.3.0 to allow large payload limit
  Cargo.toml
  src/config/src/config.rs
  src/handler/http/request/ws_v2/mod.rs
  src/handler/http/request/ws_v2/session.rs
  src/router/http/ws_v2/handler.rs
Labels: ☢️ Bug

#6528 fix: ws locks
  src/router/http/ws_v2/connection.rs
  src/router/http/ws_v2/handler.rs
Labels: ☢️ Bug

#6526 feat: add query parquet cache metrics
  Cargo.lock
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/handler/grpc/request/event.rs
  src/infra/src/cache/file_data/delete.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/service/compact/merge.rs
  src/service/db/file_list/mod.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
Labels: ✏️ Feature

#6516 fix: variable should not be escaped
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#6529 test: sql vrl satisfied and no satisfied alert pytest
  tests/api-testing/tests/create_objects.py
  tests/api-testing/tests/pages/alertV2_page.py
  tests/api-testing/tests/pages/folder_page.py
Labels: 🧹 Updates

#6531 fix: multiple api calls issue while creating pipelines , alerts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/ImportAlert.vue
  web/src/components/pipeline/PipelineEditor.vue
Labels: ☢️ Bug

#6476 test: websocket version 2 connection pytest
  tests/api-testing/tests/conftest.py
  tests/api-testing/tests/test_websocket2.py
  tests/api-testing/tests/test_workflow.py
Labels: 🧹 Updates

#6532 fix: return proper error when report cron is invalid and enrichment table payload condition
  src/handler/http/request/enrichment_table/mod.rs
  src/service/dashboards/reports.rs
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#6533 fix: trace_id for search
  Cargo.lock
  src/common/utils/http.rs
  src/config/Cargo.toml
  src/config/src/ider.rs
  src/config/src/utils/rand.rs
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/mod.rs
  src/service/alerts/mod.rs
  src/service/db/search_job/search_jobs.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#6494 feat: add mini search partitions
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
Labels: ✏️ Feature

#6543 fix: base64 encode should be only in logs page
  web/src/components/alerts/AddAlert.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6537 fix: show 4xx error message on UI
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/dashboards/panels/CustomChartRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/plugins/metrics/Index.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#6545 feat: implement `aligntime` for alert manager alerts/pipelines
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/meta/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ✏️ Feature

#6552 fix: `LIKE` query parsing issue for visualization
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#6534 fix: added validation for six * cron expression
  web/src/components/reports/CreateReport.vue
Labels: ☢️ Bug, ✏️ Feature

#6547 fix: mini partitions ordering
  src/service/search/mod.rs
  src/service/search/partition.rs
Labels: ☢️ Bug

#6550 feat: dashboard when loading and no data is present show blank chart
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#6492 fix: pass trace id from alert manager to queries
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#6508 feat: search inspector
  src/common/infra/cluster/mod.rs
  src/config/src/utils/time.rs
  src/handler/grpc/flight/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/router/mod.rs
  src/service/file_list.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
  src/service/search/inspector.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#6554 feat: add keepalive for scheduler_jobs
  src/common/migration/dashboards.rs
  src/common/migration/file_list.rs
  src/common/migration/schema.rs
  src/config/src/ider.rs
  src/config/src/meta/triggers.rs
  src/config/src/utils/prom_json_encoder.rs
  src/handler/grpc/auth/mod.rs
  src/handler/http/request/keys/mod.rs
  src/handler/http/request/promql/mod.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/request/users/service_accounts.rs
  src/handler/http/request/ws_v2/session.rs
  src/handler/http/router/mod.rs
  src/infra/src/db/nats.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/infra/src/table/search_queue.rs
  src/infra/src/table/short_urls.rs
  src/job/files/parquet.rs
  src/job/flatten_compactor.rs
  src/report_server/src/report.rs
  src/service/alerts/scheduler/mod.rs
  src/service/alerts/scheduler/worker.rs
  src/service/compact/worker.rs
  src/service/dashboards/mod.rs
  src/service/dashboards/reports.rs
  src/service/db/alerts/alert.rs
  src/service/db/schema.rs
  src/service/db/search_job/search_job_partitions.rs
  src/service/db/search_job/search_jobs.rs
  src/service/logs/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/mod.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/promql/search/mod.rs
  src/service/schema.rs
  src/service/search/cache/cacher.rs
  src/service/search/cluster/flight.rs
  src/service/search/grpc_search.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
  src/service/stream.rs
  src/service/traces/mod.rs
  src/super_cluster_queue/schemas.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#6560 fix: any responses with function error will not be result cached
  src/service/search/cache/mod.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#6553 feat: enforce mandatory _timestamp field selection in scheduled pipeline
  src/config/src/utils/sql.rs
  src/service/alerts/derived_streams.rs
Labels: ✏️ Feature

#6548 fix: ws locks debug
  src/handler/http/request/ws_v2/mod.rs
  src/handler/http/request/ws_v2/session.rs
  src/router/http/ws_v2/connection.rs
  src/router/http/ws_v2/handler.rs
  src/service/websocket_events/utils.rs
Labels: ☢️ Bug

#6562 fix: log improve
  src/handler/grpc/request/stream.rs
Labels: ☢️ Bug, 🧹 Updates

#6434 fix: Sql mode skip query validation
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#6566 fix: add supercluster inspector
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug, ✏️ Feature

#6574 fix: Enrichment table additional info added and schema page added
  web/src/components/functions/EnrichmentSchema.vue
  web/src/components/functions/EnrichmentTableList.vue
Labels: ☢️ Bug, ✏️ Feature

#6243 feat: pipeline import and export
  web/src/components/iam/roles/EditRole.vue
  web/src/components/pipeline/ImportPipeline.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/composables/shared/router.ts
  web/src/locales/languages/en.json
Labels: Invalid PR Title, ✏️ Feature

#6573 fix: cache file for alert querier
  .github/workflows/release.yml
  deploy/build/Dockerfile.tag-simd.amd64
  src/config/src/meta/search.rs
  src/config/src/metrics.rs
  src/handler/grpc/request/event.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/openapi.rs
  src/proto/proto/cluster/common.proto
  src/proto/src/generated/cluster.rs
  src/service/promql/search/mod.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/search_jobs.rs
Labels: ☢️ Bug

#6580 fix: expand row needs to have unique row id in search history
  web/src/plugins/logs/SearchHistory.vue
Labels: ☢️ Bug

#6578 fix: Add missing translation keys and improve Japanese
  web/src/locales/languages/ja.json
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6587 feat: support stream delete for object store
  src/config/src/config.rs
  src/handler/http/request/organization/org.rs
  src/infra/src/storage/mod.rs
  src/job/file_downloader.rs
  src/service/cluster_info.rs
  src/service/grpc.rs
  src/service/ingestion/ingestion_service.rs
  src/service/node.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/cache_multi.rs
  src/service/search/cluster/cacher.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc_search.rs
  src/service/search/mod.rs
  src/service/search_jobs.rs
Labels: ✏️ Feature

#6588 fix: align time for alerts
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/self_reporting/usage.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#6540 feat: add support for OR and NOT operators in alert conditions
  src/config/src/meta/alerts/mod.rs
  src/handler/http/models/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/mod.rs
Labels: ✏️ Feature

#6592 test: alert-folder-testcases
  .github/workflows/playwright.yml
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/playwright-tests/alertsfolders.spec.js
Labels: 🧹 Updates

#6597 fix: add new file & delete merged file should be in one transcation
  src/config/src/meta/alerts/mod.rs
  src/handler/http/models/alerts/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/file_list.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, ✏️ Feature

#6604 feat: add ratelimit for websocket
  src/config/src/config.rs
  src/handler/http/request/search/error_utils.rs
  src/infra/src/errors/mod.rs
  src/main.rs
  src/router/http/ws_v2/handler.rs
  src/router/ratelimit/resource_extractor.rs
Labels: ✏️ Feature

#6598 fix: if pipeline node is function or condition skip org validation
  web/src/components/pipeline/ImportPipeline.vue
Labels: ☢️ Bug

#6608 fix: added timezone offset for pipeline cron
  web/src/components/alerts/AddAlert.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature

#6609 fix: revert OR operator support
  src/config/src/meta/alerts/mod.rs
  src/handler/http/models/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#6600 feat: support role group for super cluster
  src/config/src/cluster.rs
  src/handler/http/request/clusters/mod.rs
  src/handler/http/request/organization/org.rs
  src/job/alert_manager.rs
  src/router/http/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/grpc_search.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/search_jobs.rs
Labels: ✏️ Feature

#6601 feat: dashboard when data is loading show 0 as value for gauge
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#6615 fix: if `streaming_aggs` allow entire query to be processed
  src/service/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/values.rs
Labels: ☢️ Bug

#6612 fix: import dest , alert issues
  web/src/components/alerts/ImportAlert.vue
  web/src/components/alerts/ImportDestination.vue
Labels: ☢️ Bug

#6606 fix: Traces UI Issues
  web/src/composables/useTraces.ts
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchBar.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceTree.vue
Labels: ☢️ Bug

#6205 test: Import Template Destination Alerts Playwright
  .github/workflows/playwright.yml
  tests/test-data/AlertMultiTemplateEmail.json
  tests/test-data/AlertMultiTemplateWebHook.json
  tests/ui-testing/pages/alertTemplate.js
  tests/ui-testing/playwright-tests/alertImportTDA.spec.js
  tests/ui-testing/playwright-tests/alerts.spec.js
Labels: 🧹 Updates

#6620 feat: align time for alerts/pipelines
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/self_reporting/usage.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
Labels: ✏️ Feature

#6623 fix: ws remove locks from querier
  src/common/infra/config.rs
  src/handler/http/request/ws_v2/session.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
Labels: ☢️ Bug, 🧹 Updates

#6619 test: visualize test cases
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: 🧹 Updates

#6624 fix: lock handling
  src/common/infra/config.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/ws/mod.rs
  src/handler/http/request/ws/session.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/router/http/mod.rs
  src/router/http/ws/connection.rs
  src/router/http/ws/error.rs
  src/router/http/ws/handler.rs
  src/router/http/ws/mod.rs
  src/router/http/ws/pool.rs
  src/router/http/ws/session.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
Labels: ☢️ Bug

#6625 fix: removed console logs from logs page
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#6627 fix: otel logs fields type is not correct
  src/service/ingestion/grpc.rs
Labels: ☢️ Bug

#6467 feat: file list dump
  src/cli/basic/test.rs
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/file_list_dump.rs
  src/job/mod.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/file_list/mod.rs
  src/service/file_list.rs
  src/service/file_list_dump.rs
  src/service/mod.rs
  src/service/promql/search/grpc/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
Labels: ✏️ Feature

#6633 fix: indexing for the nodelist UI should be done in FE
  web/src/components/settings/Nodes.vue
Labels: ☢️ Bug

#6636 fix: default histogram enabled
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#6637 fix: do not use distinct stream if where clause contains match_all
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#6639 fix: enrichment table old data should not be used in vrls
  src/config/src/meta/stream.rs
  src/handler/http/request/search/mod.rs
  src/service/db/enrichment_table.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/stream.rs
Labels: ☢️ Bug

#6616 feat: delay for scheduled pipelines
  src/common/migration/pipeline_func.rs
  src/config/src/meta/pipeline/components.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/scheduler/handlers.rs
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/locales/languages/en.json
Labels: ✏️ Feature

#6643 fix: track canceled search and do not retry if search is canceled
  web/src/composables/useSearchWebSocket.ts
Labels: ☢️ Bug

#6649 fix: cherry-pick rc7 fixes
  src/handler/http/request/ws/session.rs
  src/router/http/ws/connection.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/values.rs
  web/src/composables/useLogs.ts
  web/src/composables/useSearchWebSocket.ts
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#6650 fix: dashboard table wrap in reports
  web/src/components/dashboards/panels/TableRenderer.vue
Labels: ☢️ Bug

#6644 fix: select star in wal maybe very slow for thousands fields
  src/service/search/grpc/wal.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#6651 fix: node list UI issues
  web/src/components/settings/Nodes.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#6652 fix: changed the start time of explore of enrichment table from 1min to 1sec
  web/src/components/functions/EnrichmentTableList.vue
Labels: ☢️ Bug

#6631 test: Import destination alert playwright
  tests/test-data/AlertMultiDestinationEmail.json
  tests/test-data/AlertMultiDestinationWebHook.json
  tests/test-data/AlertMultiRealTime.json
  tests/test-data/AlertMultiScheduled.json
  tests/ui-testing/pages/alertDestination.js
  tests/ui-testing/pages/alertTemplate.js
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/playwright-tests/alertImportTDA.spec.js
Labels: 🧹 Updates

#6632 feat: impl grpc get files from other nodes
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/job/files/parquet.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/event.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/db/file_list/broadcast.rs
Labels: ✏️ Feature

#6641 test: multi y-axis test case fix
  tests/ui-testing/pages/dashboardPages/dashboard-chart.js
  tests/ui-testing/pages/dashboardPages/dashboard-panel-actions.js
  tests/ui-testing/pages/dashboardPages/dashboard-time.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-multi-y-axis.spec.js
Labels: ☢️ Bug, 🧹 Updates

#6663 fix: `values` event sql
  src/config/src/meta/sql.rs
  src/handler/http/request/search/mod.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#6664 fix: download multiple files
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/event.proto
  src/proto/src/generated/cluster.rs
Labels: ☢️ Bug

#6659 fix: add retry if download file get size mismatch
  src/handler/grpc/request/event.rs
  src/infra/src/cache/file_data/delete.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/cache/file_data/mod.rs
  src/job/file_downloader.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/service/compact/merge.rs
  src/service/promql/search/cache/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug, ✏️ Feature

#6596 fix: base64 encode cookies
  src/common/utils/auth.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/mod.rs
  tests/api-testing/tests/pages/enrichment_page.py
  tests/api-testing/tests/test_websocket2.py
Labels: ☢️ Bug

#6672 feat: report cluster_coordinator
  src/common/meta/telemetry.rs
Labels: ✏️ Feature

#6676 fix: remove cron if frequency changed to minutes
  src/service/alerts/alert.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/stream.rs
Labels: ☢️ Bug, 🧹 Updates

#6677 fix: remove cron if frequency changed to minutes (#6676)
  src/service/alerts/alert.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/stream.rs
Labels: ☢️ Bug, 🧹 Updates

#6673 feat: Merge ingestion logic for logs using OTLP proto SDK
  src/handler/grpc/request/logs.rs
  src/handler/http/request/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp.rs
  src/service/logs/otlp_grpc.rs
Labels: ✏️ Feature

#6680 feat: add `event_progress` event
  src/config/src/meta/websocket.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
  tests/api-testing/tests/test_websocket2.py
  web/src/components/common/LoadingProgress.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
Labels: ✏️ Feature

#6668 feat: add `EventProgress` server event
  src/config/src/meta/websocket.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/utils.rs
  src/service/websocket_events/values.rs
  tests/api-testing/tests/test_websocket2.py
  web/src/components/common/LoadingProgress.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
Labels: 🧹 Updates, ✏️ Feature

#6682 fix: `cleanup` querier conn if `send_message` fails
  src/router/http/ws/connection.rs
  src/router/http/ws/handler.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#6683 fix: missing prom labels
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
Labels: ☢️ Bug

#6671 test: add dashboard methods for pom
  tests/ui-testing/pages/dashboardPages/dashboard-chart.js
  tests/ui-testing/pages/dashboardPages/dashboard-panel-configs.js
  tests/ui-testing/pages/dashboardPages/dashboard-panel-edit.js
  tests/ui-testing/pages/dashboardPages/dashboard-refresh.js
  tests/ui-testing/pages/dashboardPages/dashboard-settings.js
Labels: 🧹 Updates, ✏️ Feature

#6691 fix: duplicate usage reporting for alerts
  src/service/search/mod.rs
Labels: ☢️ Bug
