Repository openobserve/openobserve, pull requests merged in 2025-08, with the labels that each got.

#7807 fix: expand logs side panel giving blank space
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#7827 fix: enrichment table rewrite should not create compact jobs
  src/service/compact/retention.rs
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
  src/service/stream.rs
  src/super_cluster_queue/enrichment_table.rs
  src/super_cluster_queue/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#7829 fix: limit, hist_alignment by factors of 24 hrs, order_by
  src/common/utils/auth_tests.rs
  src/config/src/meta/search.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/http.rs
  src/service/search/partition.rs
  src/service/search/search_stream.rs
  src/service/search/sql/mod.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/sort.rs
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7804 perf: improve high frequency term search speed
  src/config/src/config.rs
  src/handler/http/request/authz/fga.rs
  src/service/search/cluster/flight.rs
  src/service/search/grpc/storage.rs
Labels: 🧹 Updates, Review effort 4/5

#7769 fix: convert microseconds to seconds for delay_in_secs in triggers stream
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug, Review effort 1/5

#7835 fix: only show message when histogram is eligible is false
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#7703 fix: delete scheduled job if the associated alert not found
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug, Review effort 3/5

#7683 test: add e2e tests for HTML chart
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboards/dashboard-html-chart.spec.js
Labels: 🧹 Updates, ✏️ Feature, Review effort 3/5

#7840 fix: readonly stream type for visualization
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug

#7846 chore: refactor sql.rs
  src/cli/basic/http.rs
  src/common/infra/config.rs
  src/config/src/meta/actions/action.rs
  src/config/src/meta/dashboards/mod.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_inspector.rs
  src/ingester/src/immutable.rs
  src/service/search/cache/cacher.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/sql/mod.rs
  src/service/search/sql/rewriter/add_new_filter.rs
  src/service/search/sql/rewriter/add_o2_id.rs
  src/service/search/sql/rewriter/add_ordering_term.rs
  src/service/search/sql/rewriter/add_timestamp.rs
  src/service/search/sql/rewriter/approx_percentile.rs
  src/service/search/sql/rewriter/index.rs
  src/service/search/sql/rewriter/mod.rs
  src/service/search/sql/rewriter/remove_dashboard_placeholder.rs
  src/service/search/sql/rewriter/track_total_hits.rs
  src/service/search/sql/schema.rs
  src/service/search/sql/visitor/cipher_key.rs
  src/service/search/sql/visitor/column.rs
  src/service/search/sql/visitor/group_by.rs
  src/service/search/sql/visitor/histogram_interval.rs
  src/service/search/sql/visitor/index_optimize.rs
  src/service/search/sql/visitor/match_all.rs
  src/service/search/sql/visitor/mod.rs
  src/service/search/sql/visitor/partition_column.rs
  src/service/search/sql/visitor/pickup_where.rs
  src/service/search/sql/visitor/prefix_column.rs
  src/service/search/sql/visitor/utils.rs
Labels: 🧹 Updates, Review effort 5/5

#7760 feat: add run ID management and panel ID for dashboard refresh
  src/common/utils/http.rs
  src/config/src/meta/dashboards/mod.rs
  src/config/src/meta/dashboards/usage_report.rs
  src/config/src/meta/self_reporting/usage.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/request/traces/mod.rs
  src/service/search/cache/mod.rs
  src/service/search/streaming/execution.rs
  src/service/self_reporting/ingestion.rs
  src/service/self_reporting/mod.rs
  src/service/self_reporting/queues.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useStreamingSearch.ts
  web/src/services/search.ts
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature, Review effort 4/5

#7850 fix: remove module key from zo_db_query_nums metrics (#7845)
  src/config/src/metrics.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 3/5

#7861 feat: merge index optmize from rc7 to rc9
  src/cli/basic/cli.rs
  src/common/infra/mod.rs
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/meta/sql.rs
  src/config/src/utils/file.rs
  src/config/src/utils/sql.rs
  src/config/src/utils/tantivy/query/contains_query.rs
  src/config/src/utils/time.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_stream.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/ingester/src/immutable.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/main.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/db/instance.rs
  src/service/db/metas.rs
  src/service/db/mod.rs
  src/service/db/schema.rs
  src/service/db/version.rs
  src/service/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/plan/mod.rs
  src/service/search/datafusion/plan/tantivy_count_exec.rs
  src/service/search/datafusion/plan/tantivy_optimize_exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/utils.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/search_stream.rs
  src/service/search/sql/mod.rs
  src/service/search/tantivy/mod.rs
  src/service/search/utils.rs
  src/service/tantivy/mod.rs
  src/service/tantivy/puffin/mod.rs
  src/service/tantivy/puffin/reader.rs
  src/service/tantivy/puffin/writer.rs
  src/service/tantivy/puffin_directory/caching_directory.rs
  src/service/tantivy/puffin_directory/footer_cache.rs
  src/service/tantivy/puffin_directory/mod.rs
  src/service/tantivy/puffin_directory/reader.rs
  src/service/tantivy/puffin_directory/reader_cache.rs
  src/service/tantivy/puffin_directory/writer.rs
  src/service/websocket_events/values.rs
Labels: ✏️ Feature

#7775 feat: add disable_distinct_fields setting to StreamSettings
  src/config/src/meta/stream.rs
  src/handler/http/request/search/mod.rs
  src/service/logs/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/stream.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature

#7863 fix: merge rc7 to rc9 part1
  src/config/src/config.rs
  src/config/src/utils/sql.rs
  src/handler/http/request/search/error_utils.rs
  src/handler/http/request/stream/mod.rs
  src/infra/src/errors/mod.rs
  src/job/files/idx.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/search/cache/cacher.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/sql/histogram.rs
  src/service/search/sql/mod.rs
Labels: ☢️ Bug

#7874 fix: csv export overlapping the fields
  web/package.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#7873 fix: dashboard time conversion (#7869)
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#7872 fix: dashboard time conversion (#7869)
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#7867 fix: sync rc7 to rc9 part2
  src/config/src/meta/search.rs
  src/config/src/utils/sql.rs
  src/handler/http/request/search/search_stream.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
  src/service/search/sql/histogram.rs
  src/service/search/sql/mod.rs
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#7879 feat: remove default partition key for traces
  src/ingester/src/entry.rs
  src/ingester/src/immutable.rs
  src/ingester/src/partition.rs
  src/service/db/enrichment_table.rs
  src/service/db/session.rs
  src/service/enrichment_table/mod.rs
  src/service/metadata/trace_list_index.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#7786 fix: SYNC optimize remote wal [phase 2] (#7664)
  src/config/src/config.rs
  src/config/src/meta/alerts/mod.rs
  src/config/src/metrics.rs
  src/job/mod.rs
  src/job/pipeline.rs
  src/main.rs
  src/service/pipeline/batch_execution.rs
  src/wal/src/reader.rs
  tests/api-testing/tests/test_streaming.py
Labels: ☢️ Bug, Review effort 4/5

#7852 fix: always use same query for table chart on visualization page
  src/config/src/utils/sql.rs
  src/service/search/datafusion/plan/projections.rs
  src/service/search/mod.rs
  src/service/search/sql/histogram.rs
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
Labels: ☢️ Bug

#7880 fix: json to csv converter using npm package
  web/package.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#7882 fix: unit test cases for reports module
  web/coverage.sh
  web/src/components/reports/CreateReport.spec.js
  web/src/components/reports/ReportList.spec.js
Labels: ☢️ Bug, 🧹 Updates, Review effort 4/5

#7881 fix: use json2csv package for conversion
  web/package-lock.json
  web/package.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#7836 fix: enrichment table issues #7815
  tests/ui-testing/playwright-tests/GeneralTests/enrichment.spec.js
  web/src/components/functions/AddEnrichmentTable.vue
  web/src/components/functions/EnrichmentTableList.vue
Labels: ☢️ Bug

#7888 fix: sync changes from rc7 to rc9
  src/config/src/meta/search.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/schema/history/mysql.rs
  src/infra/src/schema/history/postgres.rs
  src/service/enrichment_table/mod.rs
Labels: ☢️ Bug

#7896 fix: query running number metrics
  src/service/search/cluster/flight.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#7891 fix: make insert task to query manager later
  src/service/search/cluster/flight.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug, Review effort 2/5

#7841 fix: enrichment table rewrite should not create compact jobs
  src/service/compact/retention.rs
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
  src/service/stream.rs
  src/super_cluster_queue/enrichment_table.rs
  src/super_cluster_queue/mod.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 3/5

#7905 fix: change `updated_at` AI prompts table to bigint
  src/infra/src/table/migration/m20250801_000001_create_system_prompts_table.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#7890 feat: impl tantivy result cache
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/metrics.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/tantivy_result_cache.rs
  src/service/search/grpc/utils.rs
  src/service/search/index.rs
Labels: ✏️ Feature, Review effort 4/5

#7894 fix: track_total_hits to consider multiple distinct cols
  src/service/search/sql/rewriter/track_total_hits.rs
Labels: ☢️ Bug, Review effort 3/5

#7784 fix: added json download feature to main
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.spec.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/test/unit/helpers/setupTests.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 3/5

#7913 feat: impl tantivy result cache for rc9
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/metrics.rs
  src/service/search/grpc/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/tantivy_result_cache.rs
  src/service/search/grpc/utils.rs
  src/service/search/index.rs
  src/service/search/mod.rs
Labels: ✏️ Feature

#7917 feat: improve internal error report
  src/config/src/config.rs
  src/config/src/meta/self_reporting/error.rs
  src/config/src/utils/str.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/lib.rs
  src/service/self_reporting/queues.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5

#7907 test: Multi mode execution for logs
  .github/workflows/playwright.yml
  tests/ui-testing/pages/commonActions.js
  tests/ui-testing/playwright-tests/Logs/indexquery.spec.js
  tests/ui-testing/playwright-tests/Logs/join.spec.js
  tests/ui-testing/playwright-tests/Logs/logshistogram.spec.js
  tests/ui-testing/playwright-tests/Logs/logspage.spec.js
  tests/ui-testing/playwright-tests/Logs/logsqueries.cte.spec.js
  tests/ui-testing/playwright-tests/Logs/logsqueries.matchall.spec.js
  tests/ui-testing/playwright-tests/Logs/logsqueries.spec.js
  tests/ui-testing/playwright-tests/Logs/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/Logs/pagination.spec.js
  tests/ui-testing/playwright-tests/Logs/region.spec.js
  tests/ui-testing/playwright-tests/Logs/searchpartition.spec.js
  tests/ui-testing/playwright-tests/Logs/secondsPrecisionAdded.spec.js
  tests/ui-testing/playwright-tests/Logs/unflattened.spec.js
  tests/ui-testing/playwright.config.js
Labels: 🧹 Updates, Review effort 3/5

#7929 feat: add parquet cache size in status
  src/cli/basic/cli.rs
  src/cli/basic/http.rs
  src/config/src/metrics.rs
  src/config/src/utils/schema_ext.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/schema/mod.rs
  src/job/metrics.rs
  src/service/enrichment/storage.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
  src/service/self_reporting/ingestion.rs
Labels: ✏️ Feature, Review effort 3/5

#7932 fix: result cache with func
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#7933 fix: result cache with func
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#7934 fix: result cache with func
  src/service/search/cache/cacher.rs
Labels: ☢️ Bug

#7908 feat: add ZO_ROUTE_STRATEGY env to choose between workload and random…
  src/config/src/config.rs
  src/router/http/mod.rs
Labels: ✏️ Feature

#7816 fix: consider uds fields if uds in enabled
  src/job/files/parquet.rs
Labels: Invalid PR Title, ☢️ Bug

#7898 feat: add metrics to count wal files in ingester
  .gitignore
  deploy/build/Dockerfile.pr.amd64
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/job/metrics.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 3/5

#7945 fix: add more logs for follower
  src/common/infra/cluster/mod.rs
  src/service/search/datafusion/storage/file_statistics_cache.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug, ✏️ Feature

#7952 fix: datatype mismatch #7951
  src/service/search/sql/mod.rs
Labels: ☢️ Bug

#7956 fix: local cache table for alert manager
  src/job/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#7958 fix: build error
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug

#7976 test: Updated yml file
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/Alerts/alerts-import.spec.js
Labels: 🧹 Updates, Review effort 2/5

#7981 fix: search doesn't work with comments
  src/service/search/cache/mod.rs
Labels: ☢️ Bug, 📒 Documentation

#7980 fix: search doesn't work with comments
  src/service/search/cache/mod.rs
Labels: ☢️ Bug, 📒 Documentation, Review effort 2/5

#7948 fix: dashboard variables changes (#7475)
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/locales/languages/en.json
  web/src/views/Dashboards/DashboardSettings.vue
Labels: ☢️ Bug

#7947 fix: dashboard conflict issue (#7558)
  web/src/utils/commons.ts
  web/src/views/Dashboards/ImportDashboard.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#7959 fix: duplicate stream getting appended while changing url
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7974 fix: Sql query with comments
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 📒 Documentation

#7975 fix: commented query with sql mode
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 📒 Documentation, Review effort 2/5

#7955 ci: Added github workflow to update the release notes in strapi
  .github/workflows/github-release-public.yml
Labels: 🧹 Updates, ✏️ Feature, Review effort 2/5

#7988 feat: dashboard query editor vertical scroll (#7453)
  tests/ui-testing/playwright-tests/dashboards/custom-charts.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard2.spec.js
  web/src/components/dashboards/addPanel/DashboardQueryEditor.vue
  web/src/composables/useDashboardPanel.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#7456 feat: visualization enhancement
  .github/workflows/playwright.yml
  src/common/utils/auth.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/service/db/mod.rs
  src/service/search/cache/cacher.rs
  src/service/search/datafusion/plan/mod.rs
  src/service/search/datafusion/plan/projections.rs
  tests/ui-testing/pages/dashboardPages/visualise.js
  tests/ui-testing/pages/logsPages/logsPage.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useLogs.ts
  web/src/composables/useNotifications.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.spec.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/TransformSelector.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/services/search.ts
  web/src/ts/interfaces/logs.ts
  web/src/ts/interfaces/query.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/query/sqlUtils.ts
  web/src/utils/query/visualizationUtils.ts
Labels: ✏️ Feature, Review effort 5/5

#7992 ci: bump version
  Cargo.lock
  Cargo.toml
  deny.toml
  src/common/meta/middleware_data.rs
  src/handler/http/router/middlewares/check_keep_alive.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/service/search/grpc/utils.rs
  src/service/search/super_cluster/follower.rs
Labels: 🤖 Dependencies, Review effort 2/5

#7990 fix: show error for threshold while user provides invalid input
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
Labels: ☢️ Bug, Review effort 2/5

#7999 fix: dashboard api call of variables for its child variables
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ☢️ Bug

#8008 feat: remove tantivy footer cache
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/tantivy_result_cache.rs
  src/service/tantivy/puffin_directory/mod.rs
  src/service/tantivy/puffin_directory/reader_cache.rs
Labels: 🧹 Updates, ✏️ Feature

#7995 fix: `is_multi_stream_search` and `enable_align_histogram`
  .github/workflows/playwright.yml
  src/common/utils/auth_tests.rs
  src/common/utils/http.rs
  src/config/src/meta/search.rs
  src/config/src/utils/sql.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_inspector.rs
  src/handler/http/request/search/search_stream.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/search/search_stream.rs
  src/service/search/sql/histogram.rs
  src/service/websocket_events/search.rs
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
  web/src/components/common/AppTabs.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
  web/src/components/logstream/schema.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/services/search.ts
Labels: ☢️ Bug

#8016 fix: handle non-empty base-uri in router
  deploy/build/Dockerfile.pr.amd64
  src/router/http/mod.rs
Labels: ☢️ Bug

#7998 refactor: try move remotescan, stream aggregate, topk from rewrite to optimize rule
  src/common/meta/organization.rs
  src/config/src/config.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cache/cacher.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/context.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/remote_scan.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/plan/projections.rs
  src/service/search/grpc/flight.rs
  src/service/search/mod.rs
  src/service/search/sql/mod.rs
  src/service/search/sql/visitor/group_by.rs
  src/service/search/sql/visitor/match_all.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  web/src/components/settings/General.vue
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: 🧹 Updates, Review effort 4/5

#8018 fix: oldest file pick logic (#8012)
  src/config/src/config.rs
Labels: ☢️ Bug

#8022 fix: fix error disaply while changing organization
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#8025 fix: added more unit test cases
  web/src/components/alerts/AddAlert.spec.ts
  web/src/components/iam/users/AddUser.spec.js
  web/src/components/iam/users/User.spec.js
  web/src/components/reports/CreateReport.spec.js
  web/src/components/reports/ReportList.spec.js
  web/src/composables/useStreams.spec.ts
  web/src/services/auth.spec.ts
  web/src/services/billings.spec.ts
  web/src/services/organizations.spec.ts
  web/src/services/tickets.spec.ts
  web/src/services/users.spec.ts
  web/src/test/unit/helpers/handlers.ts
  web/src/utils/common.spec.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.spec.ts
  web/src/views/LogStream.spec.ts
  web/src/views/__snapshots__/LogStream.spec.ts.snap
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature, Review effort 4/5

#8042 fix: blank chart issue on visualization page rc7
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#8043 fix: add logs for compactor
  src/config/src/config.rs
  src/router/http/mod.rs
  src/service/compact/retention.rs
Labels: ☢️ Bug, ✏️ Feature

#8021 fix: return proper error for incorrect function panic (#7708)
  src/service/search/cluster/http.rs
Labels: ☢️ Bug

#8045 fix: add logs for compactor
  src/service/compact/retention.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#7705 fix: Logs page field-list Interesting Fields improvements
  tests/ui-testing/pages/logsPages/logsPage.js
  tests/ui-testing/pages/logsPages/unflattened.js
  tests/ui-testing/pages/streamsPages/streamsPage.js
  tests/ui-testing/playwright-tests/GeneralTests/sanity.spec.js
  tests/ui-testing/playwright-tests/GeneralTests/schema.spec.js
  tests/ui-testing/playwright-tests/Logs/join.spec.js
  tests/ui-testing/playwright-tests/Logs/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/Logs/unflattened.spec.js
  tests/ui-testing/playwright-tests/Pipelines/pipeline-core.spec.js
  tests/ui-testing/playwright-tests/Pipelines/pipelines.spec.js
  tests/ui-testing/playwright-tests/Streams/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/Streams/streaming.spec.js
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.spec.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.spec.ts
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates, Review effort 4/5

#8002 fix: new sso admin/viewer/editor should be able to enjoy given permissions
  src/common/infra/ofga/mod.rs
  src/handler/http/auth/jwt.rs
  src/service/users.rs
Labels: ☢️ Bug, Review effort 3/5

#8048 fix: skip when start time > end time for delayed derived stream
  src/config/src/meta/pipeline/components.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/pipeline/mod.rs
Labels: ☢️ Bug

#8058 feat: create data retention by day
  src/handler/http/request/stream/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/db/compact/retention.rs
Labels: ✏️ Feature

#8073 fix: improve error msg of nats
  src/infra/src/db/nats.rs
  src/infra/src/queue/nats.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8063 feat: impl distribute query analyze
  src/config/src/utils/sql.rs
  src/flight/Cargo.toml
  src/flight/src/common.rs
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/flight/stream.rs
  src/handler/grpc/flight/visitor.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/common.rs
  src/service/search/datafusion/distributed_plan/decoder_stream.rs
  src/service/search/datafusion/distributed_plan/display.rs
  src/service/search/datafusion/distributed_plan/distribute_analyze.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/optimizer/distribute_analyze.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/remote_scan.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ✏️ Feature, Review effort 4/5

#8079 fix: add debug logs
  src/service/search/grpc/flight.rs
Labels: ☢️ Bug, ✏️ Feature

#8085 fix: parse nested with queries in pipeline query node
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
Labels: ☢️ Bug

#8086 fix: return from pipeline batch_execution if batch size is zero
  src/service/pipeline/batch_execution.rs
Labels: ☢️ Bug

#8084 test: Add tests for derived streams
  tests/integration_test.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 3/5

#8087 fix: dashboard stream fields not found
  web/src/components/dashboards/addPanel/FieldList.vue
Labels: ☢️ Bug, Review effort 2/5

#8090 fix: data retention with extended retention
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/service/compact/retention.rs
Labels: ☢️ Bug

#8077 fix: normalize the limit to 100 by default rc9 (#8075)
  web/src/components/pipeline/NodeForm/Query.vue
Labels: ☢️ Bug

#8081 chore: add node_name to analyze
  src/flight/src/common.rs
  src/service/search/datafusion/distributed_plan/distribute_analyze.rs
Labels: ✏️ Feature, Review effort 2/5

#8083 fix: dashboard editor getting overlap for custom chart
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug, Review effort 1/5

#8071 fix: useLogs test cases added
  web/src/components/alerts/AlertList.spec.ts
  web/src/composables/useErrorTracking.spec.ts
  web/src/composables/useLoading.spec.ts
  web/src/composables/useLogs.spec.ts
  web/src/composables/useRateLimiter.spec.ts
  web/src/plugins/logs/Index.spec.ts
  web/src/plugins/logs/useLogs.spec.ts
  web/src/services/api_keys.spec.ts
  web/src/services/common.spec.ts
  web/src/services/config.spec.ts
  web/src/services/dashboards.spec.ts
  web/src/services/iam.spec.ts
  web/src/services/metrics.spec.ts
  web/src/services/search.spec.ts
  web/src/services/stream.spec.ts
  web/src/utils/commons.spec.ts
  web/src/utils/cookies.spec.ts
  web/src/utils/date.spec.ts
  web/src/utils/json.spec.ts
  web/src/utils/validateAlerts.spec.ts
  web/src/utils/validatePipeline.spec.ts
  web/src/views/LogStream.spec.ts
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature, Review effort 3/5

#8101 fix: added test cases for cipher keys
  web/src/components/cipherkeys/AddAkeylessType.spec.ts
  web/src/components/cipherkeys/AddCipherKey.spec.ts
  web/src/components/cipherkeys/AddEncryptionMechanism.spec.ts
  web/src/components/cipherkeys/AddOpenobserveType.spec.ts
  web/src/test/unit/fixtures/cipherKeyTestFixtures.ts
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature, Review effort 3/5

#8051 feat: dashboard unique colors to the table column automatically.
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/OverrideConfigPopup.vue
  web/src/components/dashboards/addPanel/OverrideConfig.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/utils/dashboard/colorPalette.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature, Review effort 3/5

#8100 fix: config sync on logs to visualization toggle
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug

#8110 feat: dashboard unique colors to the table column automatically. (#8051)
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/OverrideConfigPopup.vue
  web/src/components/dashboards/addPanel/OverrideConfig.vue
  web/src/components/dashboards/panels/TableRenderer.vue
  web/src/utils/dashboard/colorPalette.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ✏️ Feature

#8102 fix: parse cte query to extract stream name
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#8078 fix: normalize the limit to 100 by default (#8075)
  web/src/components/pipeline/NodeForm/Query.vue
Labels: ☢️ Bug, Review effort 2/5

#8122 chore: add UTs, run fmt and clipyy
  src/config/src/meta/folder.rs
  src/config/src/utils/base64.rs
  src/config/src/utils/file.rs
  src/config/src/utils/hash/mod.rs
  src/config/src/utils/json.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/table/migration/m20241217_155000_populate_alerts_table.rs
  src/infra/src/table/migration/m20250611_000002_populate_reports_table.rs
  src/service/file_list_dump.rs
  src/service/metrics/otlp.rs
  src/service/search/grpc/utils.rs
  src/service/search/index.rs
  src/service/search/streaming/cache.rs
  src/service/search/streaming/execution.rs
  src/service/search/streaming/sorting.rs
  src/service/search/streaming/utils.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature, Review effort 3/5

#8127 fix: tantivy result cache to access plan
  src/service/search/grpc/storage.rs
  src/service/search/grpc/tantivy_result_cache.rs
Labels: ☢️ Bug

#8123 feat: impl grpc get files from other nodes rc9
  src/config/src/config.rs
  src/handler/grpc/request/event.rs
  src/job/files/parquet.rs
  src/job/mod.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/event.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/merge.rs
  src/service/db/file_list/broadcast.rs
  src/service/self_reporting/mod.rs
  src/service/tantivy/mod.rs
Labels: ✏️ Feature

#8117 fix: parse cte query to extract stream name (#8102)
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#8129 fix: do not cache latest files for indexes (tantivy)
  src/service/tantivy/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#8115 fix: config sync on logs to visualization toggle main
  web/src/composables/useLogs.spec.ts
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, Review effort 3/5

#8116 fix: parse cte query to extract stream name (#8102)
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#7877 fix: Traces Component Testing
  web/packages/rrweb-player/.eslintrc.json
  web/packages/rrweb-player/.gitignore
  web/packages/rrweb-player/.release-it.json
  web/packages/rrweb-player/CHANGELOG.md
  web/packages/rrweb-player/README.md
  web/packages/rrweb-player/package.json
  web/packages/rrweb-player/public/events.js
  web/packages/rrweb-player/public/global.css
  web/packages/rrweb-player/public/index.html
  web/packages/rrweb-player/rollup.config.js
  web/packages/rrweb-player/src/Controller.svelte
  web/packages/rrweb-player/src/Player.svelte
  web/packages/rrweb-player/src/components/Switch.svelte
  web/packages/rrweb-player/src/main.ts
  web/packages/rrweb-player/src/utils.ts
  web/packages/rrweb-player/tsconfig.json
  web/packages/rrweb-player/typings/index.d.ts
  web/src/components/tickets/AddUpdateTicket.spec.ts
  web/src/components/tickets/AddUpdateTicket.vue
  web/src/components/tickets/TicketAttachments.vue
  web/src/composables/shared/router.ts
  web/src/plugins/traces/AppCollapse.vue
  web/src/plugins/traces/DetailTable.vue
  web/src/plugins/traces/IndexList.spec.ts
  web/src/plugins/traces/IndexList.vue
  web/src/plugins/traces/SearchBar.spec.ts
  web/src/plugins/traces/SearchResult.spec.ts
  web/src/plugins/traces/SearchResult.vue
  web/src/plugins/traces/SpanBlock.spec.ts
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/SpanDetails.vue
  web/src/plugins/traces/SpanRenderer.spec.ts
  web/src/plugins/traces/SpanRenderer.vue
  web/src/plugins/traces/SyntaxGuide.spec.ts
  web/src/plugins/traces/SyntaxGuide.vue
  web/src/plugins/traces/TraceBlock.spec.ts
  web/src/plugins/traces/TraceBlock.vue
  web/src/plugins/traces/TraceDetails.spec.ts
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.spec.ts
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceHeader.spec.ts
  web/src/plugins/traces/TraceHeader.vue
  web/src/plugins/traces/TraceTree.spec.ts
  web/src/plugins/traces/TraceTree.vue
  web/src/services/stream.spec.ts
  web/src/services/stream.ts
  web/src/test/unit/helpers/handlers.ts
  web/src/test/unit/helpers/setupTests.ts
  web/src/test/unit/mockData/traces.ts
  web/src/utils/zincutils.ts
  web/src/views/TicketsView.vue
  web/vitest.config.ts
Labels: ☢️ Bug, 🧹 Updates, 📒 Documentation, Review effort 5/5

#8132 fix; UI unit test case v7.2
  web/src/components/settings/AddRegexPattern.spec.ts
  web/src/components/settings/CipherKeys.spec.ts
  web/src/components/settings/General.spec.ts
  web/src/components/settings/NoRegexPatterns.spec.ts
  web/src/components/settings/index.spec.ts
  web/src/plugins/traces/TraceBlock.spec.ts
  web/src/test/unit/helpers/handlers.ts
  web/src/test/unit/mockData/regexPatterns.ts
Labels: Invalid PR Title, ☢️ Bug, 🧹 Updates, Review effort 4/5

#8136 chore: update datafusion to v49.0.2
  Cargo.lock
  Cargo.toml
Labels: 🧹 Updates, Review effort 1/5

#8139 fix: indexlist field select issue fixed
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, Review effort 2/5

#8134 fix: regex patterns introduce search as well
  web/src/components/logstream/AssociatedRegexPatterns.vue
  web/src/services/stream.ts
Labels: ☢️ Bug, Review effort 2/5

#8131 chore: add metrics for custom `ExecutionPlan`
  src/flight/src/decoder.rs
  src/service/search/datafusion/distributed_plan/decoder_stream.rs
  src/service/search/datafusion/distributed_plan/enrich_exec.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/plan/deduplication_exec.rs
  src/service/search/datafusion/plan/tantivy_optimize_exec.rs
  src/service/search/datafusion/table_provider/enrich_table.rs
  src/service/search/grpc/flight.rs
Labels: ✏️ Feature, Review effort 3/5

#8141 fix: remove environment option from list
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8149 fix: added spacing between box
  web/src/views/HomeView.vue
Labels: ☢️ Bug, ✏️ Feature, Review effort 1/5

#8140 feat: added oracle database page under datasource
  web/src/assets/images/ingestion/oracle.svg
  web/src/components/ingestion/Database.spec.ts
  web/src/components/ingestion/Database.vue
  web/src/components/ingestion/databases/Oracle.spec.ts
  web/src/components/ingestion/databases/Oracle.vue
  web/src/composables/shared/useIngestionRoutes.ts
  web/src/composables/useIngestion.spec.ts
  web/src/composables/useIngestion.ts
  web/src/locales/languages/en.json
Labels: ✏️ Feature, Review effort 2/5

#8143 fix: 8107 Correct alert URL query for condition
  src/service/alerts/alert.rs
  src/service/alerts/mod.rs
Labels: Invalid PR Title, ☢️ Bug

#8133 fix: unit test cases added
  web/src/components/ingestion/logs/OtelConfig.spec.ts
  web/src/components/ingestion/logs/OtelConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.spec.ts
  web/src/components/pipeline/ImportPipeline.spec.ts
  web/src/components/pipeline/ImportPipeline.vue
  web/src/components/queries/QueryList.spec.ts
  web/src/components/queries/QueryList.vue
  web/src/components/queries/RunningQueries.spec.ts
  web/src/components/queries/RunningQueries.vue
  web/src/components/queries/RunningQueriesList.spec.ts
  web/src/components/queries/SummaryList.spec.ts
  web/src/enterprise/components/billings/enterprisePlan.spec.ts
  web/src/enterprise/components/billings/invoiceHistory.spec.ts
  web/src/enterprise/components/billings/invoiceTable.spec.ts
  web/src/enterprise/components/billings/plans.spec.ts
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature, Review effort 3/5

#8154 fix: ingester writer channel closed
  src/ingester/src/writer.rs
Labels: ☢️ Bug

#8153 chore: add UTs, run fmt and clippy
  coverage.sh
  src/service/logs/bulk.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/plan/regex_projections.rs
  src/service/search/datafusion/udaf/percentile_cont.rs
  src/service/search/datafusion/udaf/summary_percentile.rs
  src/service/search/grpc/storage.rs
  src/service/search/sql/schema.rs
  src/service/traces/mod.rs
  src/service/users.rs
Labels: ✏️ Feature, Review effort 4/5

#8158 fix: enhance machine id check
  src/cli/basic/cli.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/nats.rs
  src/config/src/cluster.rs
  src/config/src/ider.rs
  src/config/src/meta/cluster.rs
  src/job/files/mod.rs
  src/service/db/schema.rs
  src/service/ingestion/mod.rs
  src/service/schema.rs
Labels: ☢️ Bug

#8159 fix: enhance machine id check
  src/cli/basic/cli.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/cluster.rs
  src/config/src/ider.rs
  src/config/src/meta/cluster.rs
  src/job/files/mod.rs
  src/service/db/schema.rs
  src/service/ingestion/mod.rs
  src/service/schema.rs
Labels: ☢️ Bug

#8160 fix: enhance machine id check
  src/cli/basic/cli.rs
  src/common/infra/cluster/etcd.rs
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/config/src/cluster.rs
  src/config/src/ider.rs
  src/config/src/meta/cluster.rs
  src/job/files/mod.rs
  src/service/db/schema.rs
  src/service/ingestion/mod.rs
  src/service/schema.rs
Labels: ☢️ Bug, Review effort 3/5

#8128 fix: Inc UT coverage
  src/common/meta/organization.rs
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/common/utils/http.rs
  src/config/src/meta/ratelimit.rs
  src/config/src/meta/timed_annotations.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/main.rs
  src/service/metrics/otlp.rs
  tests/integration_test.rs
Labels: ☢️ Bug

#8070 test: e2e-cte-queries
  tests/test-data/cte_queries.json
  tests/ui-testing/pages/logsPages/logsPage.js
  tests/ui-testing/playwright-tests/Logs/logsqueries.cte.spec.js
Labels: 🧹 Updates, Review effort 2/5

#8169 fix: sql generation for quick alerts
  src/service/alerts/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#8172 chore: remove bogus unit tests
  src/common/infra/config.rs
  src/common/meta/authz.rs
  src/common/meta/loki.rs
  src/common/meta/organization.rs
  src/common/meta/proxy.rs
  src/common/meta/service.rs
  src/common/meta/service_account.rs
  src/common/meta/traces.rs
  src/common/meta/user.rs
  src/common/utils/auth.rs
  src/common/utils/auth_tests.rs
  src/common/utils/mod.rs
  src/config/src/meta/actions/action.rs
  src/config/src/meta/dashboards/mod.rs
  src/config/src/meta/dashboards/reports.rs
  src/config/src/meta/destinations.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/meta/meta_store.rs
  src/config/src/meta/pipeline/mod.rs
  src/config/src/meta/ratelimit.rs
  src/config/src/meta/timed_annotations.rs
  src/handler/grpc/request/event.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/table/migration/m20250611_000002_populate_reports_table.rs
  src/main.rs
  src/router/http/mod.rs
  src/service/folders.rs
  src/service/logs/bulk.rs
  src/service/search/sql/schema.rs
  src/service/self_reporting/ingestion.rs
  src/service/tantivy/puffin/mod.rs
  src/service/tantivy/puffin_directory/footer_cache.rs
  src/service/tantivy/puffin_directory/mod.rs
  src/service/traces/mod.rs
  src/service/users.rs
  tests/integration_test.rs
Labels: 🧹 Updates, Review effort 2/5

#8174 fix: unify cache delay secs across result cache, aggs cache and metrics
  src/config/src/config.rs
  src/service/promql/search/cache/mod.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
Labels: ☢️ Bug

#8179 fix: skip alert evaluation when stream not found
  src/infra/src/schema/mod.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#8184 fix: redirect to login page on unauthorised error with http2 streaming
  web/src/composables/useStreamingSearch.ts
Labels: ☢️ Bug

#8187 feat: deprecated syslog
  src/common/infra/config.rs
  src/common/meta/mod.rs
  src/common/meta/syslog.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/syslog/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/handler/tcp_udp/mod.rs
  src/job/mod.rs
  src/job/syslog_server.rs
  src/service/db/mod.rs
  src/service/db/syslog.rs
  src/service/logs/mod.rs
  src/service/logs/syslog.rs
  src/service/mod.rs
  src/service/syslogs_route.rs
  web/src/components/ingestion/Custom.spec.ts
  web/src/components/ingestion/Custom.vue
  web/src/components/ingestion/logs/Index.vue
  web/src/components/ingestion/logs/SysLog.spec.ts
  web/src/components/ingestion/logs/SysLog.vue
  web/src/components/ingestion/logs/ingestionIndex.spec.ts
  web/src/composables/shared/useIngestionRoutes.spec.ts
  web/src/composables/shared/useIngestionRoutes.ts
Labels: 🧹 Updates, ✏️ Feature

#8188 fix: issue 8180 remove add to table icon from timestamp
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature, Review effort 2/5

#8189 feat: support use cookie to do cli command
  src/cli/basic/http.rs
  src/config/src/config.rs
  src/service/db/syslog.rs
Labels: ✏️ Feature, Review effort 2/5

#8199 fix: histogram not getting reloaded on changing visualise tab to logs
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#8213 chore: remove special handler for negative index search
  src/config/src/config.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
Labels: 🧹 Updates, Review effort 3/5

#8216 fix: sync issue for index
  src/service/search/cluster/flight.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#8203 fix: manually clear the input using updateInputValue function
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#8059 feat: logs page highlighting
  tests/ui-testing/pages/generalPages/enrichmentPage.js
  tests/ui-testing/pages/logsPages/unflattened.js
  tests/ui-testing/playwright-tests/Pipelines/pipeline-core.spec.js
  web/src/components/logs/LogsHighLighting.spec.ts
  web/src/components/logs/LogsHighLighting.vue
  web/src/composables/useLogs.ts
  web/src/composables/useTextHighlighter.spec.ts
  web/src/composables/useTextHighlighter.ts
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/utils/logs/keyValueParser.ts
  web/src/utils/logs/statusParser.ts
Labels: testing, ✏️ Feature, Review effort 4/5
