Repository openobserve/openobserve, pull requests merged in 2025-02, with the labels that each got.

#5855 fix: vrl ws
  src/handler/http/request/websocket/search.rs
Labels: ☢️ Bug

#5857 fix: optimize job id for search
  src/service/promql/search/mod.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  web/src/utils/zincutils.ts
  web/src/views/HomeView.vue
Labels: ☢️ Bug

#5860 fix: Revert "fix: disable mmdb_download on alert_manager (#5838)"
  src/job/mod.rs
Labels: ☢️ Bug

#5858 fix: realtime pipeline init from cache instead of db query
  src/service/db/pipeline.rs
Labels: ☢️ Bug

#5867 fix: dashboard promql chart fails to render
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#5859 fix: stream stats negative issue
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/config/src/metrics.rs
  src/handler/grpc/request/event.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/lib.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/db/instance.rs
  src/service/file_list.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#5701 feat: migrate template & destination
  Cargo.lock
  src/common/infra/config.rs
  src/common/utils/auth_tests.rs
  src/config/src/meta/alerts/destinations.rs
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/alerts/templates.rs
  src/config/src/meta/destinations.rs
  src/config/src/meta/mod.rs
  src/handler/http/models/destinations.rs
  src/handler/http/models/mod.rs
  src/handler/http/request/alerts/destinations.rs
  src/handler/http/request/alerts/templates.rs
  src/handler/http/router/openapi.rs
  src/infra/src/cluster_coordinator/destinations.rs
  src/infra/src/cluster_coordinator/mod.rs
  src/infra/src/errors/mod.rs
  src/infra/src/table/destinations.rs
  src/infra/src/table/entity/README.md
  src/infra/src/table/entity/destinations.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/entity/templates.rs
  src/infra/src/table/migration/m20250125_102300_create_destinations_table.rs
  src/infra/src/table/migration/m20250125_115400_create_templates_table.rs
  src/infra/src/table/migration/m20250125_132500_populate_templates_table.rs
  src/infra/src/table/migration/m20250125_133700_populate_destinations_table.rs
  src/infra/src/table/migration/m20250125_153005_delete_metas_destinations.rs
  src/infra/src/table/migration/m20250125_172300_delete_metas_templates.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/templates.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  src/service/alerts/templates.rs
  src/service/db/alerts/destinations.rs
  src/service/db/alerts/templates.rs
  src/service/pipeline/pipeline_receiver.rs
  src/super_cluster_queue/destinations.rs
  src/super_cluster_queue/mod.rs
  src/super_cluster_queue/templates.rs
  tests/integration_test.rs
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/AddTemplate.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/AlertsDestinationList.vue
  web/src/components/alerts/PipelinesDestinationList.vue
  web/src/components/pipeline/NodeForm/ExternalDestination.vue
  web/src/services/alert_destination.ts
  web/src/ts/interfaces/alert.ts
  web/src/views/AppAlerts.vue
Labels: ✏️ Feature, 📒 Documentation

#5871 fix: multi region search in web sockets
  web/src/composables/useLogs.ts
  web/src/ts/interfaces/query.ts
Labels: ☢️ Bug

#5872 fix: result cache
  src/service/search/cache/cacher.rs
  src/service/search/cache/multi.rs
Labels: ☢️ Bug

#5865 fix: moved all options to end
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SyntaxGuide.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#5861 fix: upgraded playwright version
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/playwright.yml
  .github/workflows/release.yml
  Cargo.lock
  tests/ui-testing/package-lock.json
  tests/ui-testing/package.json
  web/package-lock.json
  web/package.json
  web/src/components/alerts/AddDestination.vue
  web/src/components/dashboards/SelectFolderDropdown.vue
  web/src/components/dashboards/panels/GeoMapRenderer.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/plugins/traces/IndexList.vue
  web/src/test/unit/components/alerts/AddDestination.spec.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/vite.config.ts
Labels: ☢️ Bug

#5869 fix: place holder text for select stream
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/alerts/AlertList.vue
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#5887 fix: rbac for GET for individual folders, destinations, alerts and templates
  src/common/utils/auth.rs
  src/common/utils/auth_tests.rs
Labels: ☢️ Bug

#5884 fix: 5870 UI improvements
  tests/ui-testing/pages/rumPage.js
  web/package-lock.json
  web/src/composables/useLogs.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates

#5893 fix: search api pagination when cache enabled
  src/service/search/cache/mod.rs
Labels: ☢️ Bug

#5876 refactor: Split `openfga` and `dex` modules into their own crates
  src/common/infra/ofga.rs
  src/common/migration/schema.rs
  src/common/utils/auth.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/handler/http/request/authz/fga.rs
  src/handler/http/request/pipeline.rs
  src/handler/http/request/promql/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/utils.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/request/users/mod.rs
  src/handler/http/request/users/service_accounts.rs
  src/handler/http/request/websocket/utils.rs
  src/job/mod.rs
  src/service/dashboards/mod.rs
  src/service/db/ofga.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/users.rs
Labels: 🧹 Updates

#5896 fix: Fix compiler error in enterprise unit test
  src/common/utils/auth_tests.rs
  tests/ui-testing/playwright-tests/logsqueries.spec.js
Labels: ☢️ Bug, 🧹 Updates

#5898 test: fix stream-selection flakiness
  .github/workflows/playwright.yml
  tests/api-testing/tests/test_fuzzy.py
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/enrichment.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/sanity2.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
Labels: ☢️ Bug, 🧹 Updates

#5877 fix: stream stats negative issue
  Cargo.lock
  Cargo.toml
  src/cli/basic/cli.rs
  src/cli/basic/load.rs
  src/cli/basic/mod.rs
  src/cli/data/cli.rs
  src/cli/data/export.rs
  src/cli/data/import.rs
  src/cli/data/mod.rs
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/rand.rs
  src/config/src/utils/str.rs
  src/infra/Cargo.toml
  src/infra/src/cluster_coordinator/alerts.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/infra/src/storage/mod.rs
  src/infra/src/storage/remote.rs
  src/job/stats.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/alerts/alert.rs
  src/service/db/compact/stats.rs
  src/service/db/dashboards/reports.rs
  src/service/db/file_list/broadcast.rs
  src/service/db/file_list/local.rs
  src/service/db/functions.rs
  src/service/db/kv.rs
  src/service/db/metrics.rs
  src/service/db/ofga.rs
  src/service/db/organization.rs
  src/service/db/session.rs
  src/service/db/syslog.rs
  src/service/db/user.rs
  src/service/file_list.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#5905 fix: stream stats with data retention
  src/handler/http/router/middlewares/slow_log.rs
  src/service/compact/merge.rs
  src/service/compact/retention.rs
  src/service/stream.rs
Labels: ☢️ Bug

#5904 feat: super cluster stream stats
  src/config/src/meta/stream.rs
  src/handler/grpc/request/mod.rs
  src/handler/grpc/request/stream.rs
  src/main.rs
  src/proto/build.rs
  src/proto/proto/cluster/stream.proto
  src/proto/src/generated/cluster.rs
  src/service/db/file_list/mod.rs
Labels: ✏️ Feature

#5910 fix: 5891 rum improvement
  web/src/components/login/Login.vue
  web/src/components/rum/AppTable.vue
  web/src/composables/dashboard/useAnnotations.ts
  web/src/utils/rum/errors.json
  web/src/utils/rum/overview.json
  web/src/utils/rum/web_vitals.json
Labels: ☢️ Bug, 🧹 Updates

#5913 feat: bring the debug change to stable branch
  Cargo.lock
  src/common/infra/cluster/mod.rs
  src/common/meta/ingestion.rs
  src/config/src/config.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/router/middlewares/slow_log.rs
  src/handler/http/router/mod.rs
  src/infra/src/schema/mod.rs
  src/ingester/src/errors.rs
  src/ingester/src/lib.rs
  src/ingester/src/writer.rs
  src/main.rs
  src/service/circuit_breaker.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/distinct_values.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/mod.rs
  src/service/schema.rs
  src/service/traces/mod.rs
  src/wal/src/errors.rs
Labels: ☢️ Bug, ✏️ Feature

#5853 feat: dashboard side by side bar chart
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#5916 fix: ent but not enable super cluster
  src/service/db/file_list/mod.rs
Labels: ☢️ Bug

#5922 test: internal user for login and super cluster steps refactoring
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/pages/reportsPage.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
  tests/ui-testing/playwright-tests/join.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
  tests/ui-testing/playwright-tests/reportsUpdated2.spec.js
  tests/ui-testing/playwright-tests/secondsPrecisionAdded.spec.js
  tests/ui-testing/playwright-tests/serviceAccount.spec.js
Labels: 🧹 Updates

#5923 fix: cherry pick fixes v0.14.2-pb1
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
  web/src/composables/useLogs.ts
  web/src/ts/interfaces/query.ts
Labels: ☢️ Bug

#5927 test: Updated logged out steps for reports refactoring playwright
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
  tests/ui-testing/playwright-tests/reportsUpdated2.spec.js
Labels: 🧹 Updates

#5929 fix: ws update histogram interval sql
  src/common/utils/websocket.rs
  src/handler/http/request/websocket/search.rs
Labels: ☢️ Bug, 🧹 Updates

#5935 feat: add local lock
  src/infra/src/lib.rs
  src/infra/src/local_lock.rs
  src/service/schema.rs
Labels: ✏️ Feature

#5936 fix: schema db update
  src/service/schema.rs
Labels: ☢️ Bug, 🧹 Updates

#5937 fix: add quotes for fixing values api for reserved keywords
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#5948 perf: search improve
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/infra/src/storage/remote.rs
Labels: 🧹 Updates

#5952 fix: Force cluster unit tests to run sequentially
  src/common/infra/cluster/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#5951 fix: dashboard promql dashboard to logs drilldown issue
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#5938 test: Summary PyTest in super cluster
  .github/workflows/api-testing.yml
  .github/workflows/playwright.yml
  tests/api-testing/tests/test_summary.py
Labels: 🧹 Updates

#5793 feat: impl downsampling for metrics
  Cargo.lock
  src/common/migration/file_list.rs
  src/common/utils/auth_tests.rs
  src/config/src/meta/promql.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/parquet.rs
  src/config/src/utils/time.rs
  src/ingester/src/partition.rs
  src/job/compactor.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/db/compact/downsampling.rs
  src/service/db/compact/mod.rs
  src/service/db/file_list/local.rs
  src/service/search/datafusion/exec.rs
Labels: ✏️ Feature

#5957 fix: grpc token issue with super cluster
  src/common/utils/redirect_response.rs
  src/handler/grpc/auth/mod.rs
Labels: ☢️ Bug

#5963 fix: custom charts issues
  web/src/assets/dashboard/purify.min.js
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/CustomChartEditor.vue
  web/src/components/dashboards/panels/CustomChartRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/plugins/metrics/Index.vue
  web/src/utils/dashboard/convertCustomChartData.ts
Labels: ☢️ Bug

#5962 fix: instance value error for promql
  src/service/promql/engine.rs
  src/service/promql/exec.rs
Labels: ☢️ Bug

#5971 test: e2e-logs-loadtest
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/schemaload.spec.js
Labels: 🧹 Updates

#5961 fix: show warning and allow data parsing if there is a function error
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#5878 test: Websocket PyTest Super Cluster
  .github/workflows/api-testing.yml
  .github/workflows/playwright.yml
  tests/api-testing/pyproject.toml
  tests/api-testing/requirements-dev.lock
  tests/api-testing/requirements.lock
  tests/api-testing/tests/test_websocket.py
Labels: 🧹 Updates

#5931 fix: 5891 rum issue v1
  web/src/layouts/MainLayout.vue
  web/src/views/RUM/AppSessions.vue
Labels: ☢️ Bug

#5980 test: e2e-fix-flaky-tests
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
Labels: ☢️ Bug, 🧹 Updates

#5979 fix: reset cancel query on search error or new search request
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#5982 fix: search around error
  src/common/utils/auth_tests.rs
  src/common/utils/redirect_response.rs
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/handler/grpc/request/search/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/query_manager.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/websocket/search.rs
  src/handler/http/router/mod.rs
  src/infra/src/table/migration/m20250213_000001_add_dashboard_updated_at.rs
  src/main.rs
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/utils.rs
Labels: ☢️ Bug

#5970 fix: web socket streaming aggregates search for dashboards and logs
  src/config/src/config.rs
  src/config/src/meta/websocket.rs
  src/handler/http/request/websocket/mod.rs
  src/handler/http/request/websocket/search.rs
  src/handler/http/request/websocket/session.rs
  src/handler/http/request/websocket/sort.rs
  src/handler/http/request/websocket/utils.rs
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#5990 fix: web socket streaming aggregates search for dashboards and logs (#5970)
  src/config/src/config.rs
  src/config/src/meta/websocket.rs
  src/handler/http/request/websocket/mod.rs
  src/handler/http/request/websocket/search.rs
  src/handler/http/request/websocket/session.rs
  src/handler/http/request/websocket/sort.rs
  src/handler/http/request/websocket/utils.rs
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#5978 feat: reduced rows per page to 50
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/sanity2.spec.js
  web/src/composables/useLogs.ts
Labels: ✏️ Feature

#5996 fix: dashboard when api is loading set panel refresh disable
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#5994 fix: remove order_by from search request
  src/cli/data/export.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/request/traces/mod.rs
  src/ingester/src/writer.rs
  src/job/files/parquet.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/optimizer/add_sort_and_limit.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/mod.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/grpc/storage.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
Labels: ☢️ Bug, 🧹 Updates

#5998 fix: short url in super cluster
  src/service/db/short_url.rs
  src/service/short_url.rs
  src/super_cluster_queue/alerts.rs
  src/super_cluster_queue/short_urls.rs
Labels: ☢️ Bug

#5995 fix: dashboard cancel query for web socket
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6000 fix: metrics with cache
  src/service/promql/search/cache/mod.rs
  src/super_cluster_queue/alerts.rs
  src/super_cluster_queue/short_urls.rs
Labels: ☢️ Bug

#5933 perf: ws search using cache & fix s3 multipart upload
  src/config/src/config.rs
  src/handler/http/request/websocket/search.rs
  src/infra/src/storage/mod.rs
  src/job/mmdb_downloader.rs
  src/service/promql/search/cache/mod.rs
  src/service/search/cache/multi.rs
  src/service/self_reporting/mod.rs
Labels: ☢️ Bug

#5873 refactor: move pipeline remote write to enterprise
  src/job/mod.rs
  src/job/pipeline.rs
  src/main.rs
  src/service/pipeline/batch_execution.rs
  src/service/pipeline/mod.rs
  src/service/pipeline/pipeline_entry.rs
  src/service/pipeline/pipeline_exporter.rs
  src/service/pipeline/pipeline_file_server.rs
  src/service/pipeline/pipeline_http_exporter_client.rs
  src/service/pipeline/pipeline_offset_manager.rs
  src/service/pipeline/pipeline_receiver.rs
  src/service/pipeline/pipeline_wal_writer.rs
  src/service/pipeline/pipeline_watcher.rs
Labels: 🧹 Updates

#6016 fix: do not show histogram for alert urls
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#5997 feat: Add temporary catch-all logic for fields on "put dashboard" super cluster messages
  src/super_cluster_queue/dashboards.rs
Labels: ✏️ Feature

#6001 feat: Move dashboards by updating the `folder_id`
  src/infra/src/table/dashboards.rs
  src/service/dashboards/mod.rs
  src/super_cluster_queue/dashboards.rs
Labels: ✏️ Feature

#5823 feat: Dispatch job with same branch name
  .github/workflows/dispatch-event-enterprise.yml
Labels: ✏️ Feature

#5757 feat: dashboard call variables api call on dropdown open
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
Labels: ✏️ Feature

#5882 feat: dashboard variables added new streamType metadata
  web/src/components/dashboards/settings/AddSettingVariable.vue
Labels: ✏️ Feature

#6022 test: Updated URL variable for UI Super Cluster
  .github/workflows/playwright.yml
  tests/ui-testing/pages/loginPage.js
  tests/ui-testing/playwright-tests/reportsUpdated.spec.js
  tests/ui-testing/playwright-tests/reportsUpdated2.spec.js
Labels: 🧹 Updates

#5885 feat: dashboard reorder feature for variables listing
  web/src/components/dashboards/settings/TabsSettings.vue
  web/src/components/dashboards/settings/VariableSettings.vue
Labels: ✏️ Feature

#6024 fix: panic for min_step with value 0
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#5925 feat: Action scripts [phase 2]
  src/cli/data/export.rs
  src/config/src/meta/actions/action.rs
  src/config/src/meta/search.rs
  src/handler/http/models/action.rs
  src/handler/http/models/destinations.rs
  src/handler/http/request/actions/action.rs
  src/handler/http/request/actions/mod.rs
  src/handler/http/request/actions/operations.rs
  src/handler/http/request/script_server/mod.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/table/action_scripts.rs
  src/main.rs
  src/proto/proto/cluster/search.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/db/alerts/destinations.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/http.rs
  src/super_cluster_queue/action_scripts.rs
Labels: ✏️ Feature

#6027 feat: directly replay wal to parquet
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/config/src/utils/tantivy/tokenizer/mod.rs
  src/ingester/src/immutable.rs
  src/ingester/src/lib.rs
  src/ingester/src/wal.rs
  src/job/files/parquet.rs
  src/job/metrics.rs
  src/service/compact/merge.rs
  src/service/search/sql.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature

#6021 fix: Boolean breakdown field issue for dashboard stacked chart
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#6030 fix: ws close wait
  src/router/http/ws.rs
Labels: ☢️ Bug

#5911 feat: metrics page added legend option
  web/src/locales/languages/en.json
  web/src/plugins/metrics/Index.vue
  web/src/plugins/metrics/MetricLegends.vue
Labels: ✏️ Feature

#6032 fix: ws close wait (#6030)
  src/router/http/ws.rs
Labels: ☢️ Bug

#6012 fix: cancel query status is finished issue
  src/service/db/search_job/search_jobs.rs
  src/service/search_jobs.rs
Labels: ☢️ Bug

#5892 feat: Option on Dashboard panel to navigate to logs UI based on the dashboard panel query
  web/src/components/dashboards/PanelContainer.vue
Labels: ✏️ Feature

#6037 fix: promql return type error when the step over max_file_retention
  src/job/alert_manager.rs
  src/main.rs
  src/service/promql/search/mod.rs
Labels: ☢️ Bug

#6039 fix: disable resize and drag panel, if saveDashboard is ongoing
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#6040 fix: disable resize and drag panel, if saveDashboard is ongoing
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#6042 fix: histogram visitor
  src/service/search/sql.rs
Labels: ☢️ Bug

#6026 fix: vrl toggle fix while applying saved view
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#6035 feat: Use user-provided `owner` when creating alerts and reports
  src/handler/http/request/alerts/deprecated.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/dashboards/reports.rs
Labels: ✏️ Feature

#6038 fix: ws connection optimizations
  src/config/src/config.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/websocket/mod.rs
  src/handler/http/request/websocket/search.rs
  src/handler/http/request/websocket/session.rs
  src/handler/http/request/websocket/utils.rs
  src/main.rs
  src/router/http/mod.rs
Labels: ☢️ Bug

#6036 fix: lowercase variant serde fix
  src/config/src/meta/actions/action.rs
Labels: ☢️ Bug

#6054 feat: remove ENV ZO_COLUMN_TIMESTAMP
  src/cli/data/export.rs
  src/common/utils/stream.rs
  src/config/src/config.rs
  src/config/src/meta/sql.rs
  src/config/src/utils/parquet.rs
  src/config/src/utils/record_batch_ext.rs
  src/config/src/utils/schema.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/ingester/src/entry.rs
  src/job/files/parquet.rs
  src/service/alerts/alert.rs
  src/service/alerts/mod.rs
  src/service/compact/merge.rs
  src/service/enrichment_table/mod.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metadata/distinct_values.rs
  src/service/metadata/trace_list_index.rs
  src/service/metrics/json.rs
  src/service/metrics/mod.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/promql/engine.rs
  src/service/promql/search/grpc/storage.rs
  src/service/promql/search/grpc/wal.rs
  src/service/promql/utils.rs
  src/service/schema.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/mod.rs
  src/service/search/datafusion/distributed_plan/empty_exec.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/add_timestamp.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/plan/deduplication_exec.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/traces/mod.rs
Labels: 🧹 Updates, ✏️ Feature

#6023 fix: Alerts preview not getting rendered
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#6056 fix: health check shouldn't remove node for etcd
  src/common/infra/cluster/mod.rs
  src/config/src/config.rs
  src/config/src/meta/meta_store.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/db/sqlite.rs
  src/service/search/sql.rs
Labels: ☢️ Bug, 🧹 Updates

#5899 feat: dashboard step setting for promql query
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/services/search.ts
Labels: ✏️ Feature

#5920 test: dashboard login test cases
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboards/dashboard-general-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-tabs-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-variables-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard2.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: 🧹 Updates, ✏️ Feature

#6064 fix: dashboard promql step undefined error
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6060 feat: add query ingester timeout for UI
  src/cli/data/export.rs
  src/common/utils/auth.rs
  src/common/utils/auth_tests.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/meta/stream.rs
  src/handler/grpc/flight/mod.rs
  src/handler/http/request/alerts/deprecated.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/stream/mod.rs
  src/infra/src/table/alerts/mod.rs
  src/ingester/src/partition.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/codec.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/distributed_plan/streaming_aggs_exec.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
Labels: ✏️ Feature

#6061 test: Websocket Playwright
  tests/ui-testing/pages/managementPage.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
  tests/ui-testing/playwright-tests/websocket.spec.js
Labels: 🧹 Updates

#5944 feat: dashboard y-axis range by giving min, max values
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#6073 perf: improve search in memory
  src/common/infra/cluster/mod.rs
  src/handler/grpc/flight/mod.rs
  src/ingester/src/errors.rs
  src/ingester/src/wal.rs
  src/service/promql/engine.rs
  src/service/promql/search/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/plan/tantivy_count_exec.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/wal.rs
  src/service/search/mod.rs
  src/service/search/super_cluster/follower.rs
Labels: 🧹 Updates

#6076 fix: added support for config options in promql charts
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/utils/dashboard/convertPromQLData.ts
Labels: ☢️ Bug, ✏️ Feature

#6007 test: e2e-custom-charts
  .github/workflows/playwright.yml
  tests/test-data/line.json
  tests/test-data/line2.json
  tests/test-data/pictorial.json
  tests/ui-testing/pages/dashboardPage.js
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/playwright-tests/dashboards/custom-charts.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
Labels: 🧹 Updates

#6084 feat: implement cast_to_timestamp
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/udf/cast_to_timestamp_udf.rs
  src/service/search/datafusion/udf/mod.rs
Labels: ✏️ Feature

#6081 fix: changes action script schedule types to lowercase
  web/src/components/actionScripts/ActionScipts.vue
  web/src/components/actionScripts/EditScript.vue
Labels: ☢️ Bug

#6029 fix: dashboard promql queries metric, gauge chart not getting plot properly
  web/src/utils/dashboard/convertPromQLData.ts
Labels: ☢️ Bug

#6091 fix: dashboard move to logs throwing 404
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug

#6094 feat: add debug logs for alert manager and source node to triggers stream
  src/config/src/meta/self_reporting/usage.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/service/alerts/scheduler.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#6096 fix: websocket frontend issues
  web/src/composables/useLogs.ts
  web/src/composables/useWebSocket.ts
  web/src/plugins/logs/Index.vue
  web/src/ts/interfaces/query.ts
Labels: ☢️ Bug

#5976 fix: dashboard when switching to auto mode issue of query creation
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#6047 fix: ws connection optimizations cherry-pick
  src/config/src/config.rs
  src/handler/http/request/organization/settings.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/websocket/mod.rs
  src/handler/http/request/websocket/search.rs
  src/handler/http/request/websocket/session.rs
  src/handler/http/request/websocket/utils.rs
  src/main.rs
  src/router/http/mod.rs
  src/router/http/ws.rs
  tests/api-testing/tests/test_websocket.py
Labels: ☢️ Bug

#6100 fix: Filter items returned by `ListDashboards` by permissions
  src/common/meta/http.rs
  src/handler/http/request/dashboards/mod.rs
  src/service/dashboards/mod.rs
  src/service/organization.rs
  tests/integration_test.rs
Labels: ☢️ Bug

#6101 fix: change ubicloud runner specs
  .github/workflows/playwright.yml
Labels: Invalid PR Title, 🧹 Updates

#6106 fix: remove `CloseFrame` delay
  src/config/src/config.rs
  src/handler/http/request/websocket/session.rs
Labels: ☢️ Bug, 🧹 Updates

#6097 feat: add source_node to triggers stream
  src/config/src/meta/self_reporting/usage.rs
  src/config/src/meta/triggers.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/job/alert_manager.rs
  src/service/alerts/scheduler.rs
  src/service/ingestion/mod.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#6111 fix: remove all RPP options which are more than 100
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug, 🧹 Updates

#6108 fix: Dedup UDS fields
  src/config/src/meta/stream.rs
Labels: ☢️ Bug

#6113 fix: cherry-pick udf & closeframe
  src/config/src/config.rs
  src/handler/http/request/websocket/session.rs
  src/service/search/datafusion/udf/regexp_matches_udf.rs
Labels: ☢️ Bug

#6112 fix: re_matches udf
  src/common/utils/auth_tests.rs
  src/service/search/datafusion/udf/regexp_matches_udf.rs
Labels: ☢️ Bug

#6093 fix: dashboard freeze issue with more than 100 series in single panel
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#6107 fix: dashboard ws cancel query
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6117 fix: ingester replay panic
  .github/workflows/playwright.yml
  src/cli/basic/http.rs
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/ingester/src/partition.rs
  src/ingester/src/wal.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#6078 fix: Pipeline improvements
  src/config/src/meta/pipeline/components.rs
  src/config/src/meta/pipeline/mod.rs
  src/handler/grpc/request/ingest.rs
  src/job/promql_self_consume.rs
  src/proto/proto/cluster/ingest.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/scheduler.rs
  src/service/self_reporting/ingestion.rs
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/pipelinePage.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/common/sidebar/FieldList.vue
  web/src/components/functions/TestFunction.vue
  web/src/components/logstream/AddStream.vue
  web/src/components/pipeline/NodeForm/AssociateFunction.vue
  web/src/components/pipeline/NodeForm/PreviewPromqlQuery.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/pipelines/CustomEdge.vue
  web/src/plugins/pipelines/CustomNode.vue
  web/src/plugins/pipelines/useDnD.ts
Labels: ☢️ Bug, 🧹 Updates

#6114 fix: custom chart rerendering issues
  web/src/components/dashboards/panels/CustomChartRenderer.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertCustomChartData.ts
  web/src/utils/dashboard/convertPanelData.ts
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#6128 fix: filter dashboard list based on dashboard:{dashboar_id}
  src/service/dashboards/mod.rs
Labels: ☢️ Bug

#6131 fix: add `msg_in_flight` flag and `yield` with retries before closing
  src/handler/http/request/websocket/session.rs
Labels: ☢️ Bug, ✏️ Feature

#6125 fix: extractvalue query fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6124 feat: Alert manager improve pb (move last_satisfied_at and use mpsc)
  src/common/migration/schema.rs
  src/config/src/meta/alerts/alert.rs
  src/config/src/meta/mod.rs
  src/config/src/meta/triggers.rs
  src/handler/http/models/alerts/mod.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/request/alerts/deprecated.rs
  src/handler/http/request/alerts/mod.rs
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/infra/src/table/alerts/mod.rs
  src/job/alert_manager.rs
  src/service/alerts/alert.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/alerts/scheduler/mod.rs
  src/service/alerts/scheduler/worker.rs
  src/service/db/alerts/alert.rs
  src/service/db/alerts/realtime_triggers.rs
  src/service/db/scheduler.rs
  src/super_cluster_queue/scheduler.rs
  tests/integration_test.rs
Labels: testing, 🧹 Updates, ✏️ Feature

#6134 fix: change in text from Move To Logs -> Go To Logs
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug

#6137 fix: Misc V2 alerts routes fixes
  src/config/src/meta/alerts/alert.rs
  src/handler/http/models/alerts/requests.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/request/alerts/mod.rs
  src/infra/src/table/alerts/mod.rs
  tests/api-testing/tests/test_alertsnew.py
Labels: ☢️ Bug
