Repository openobserve/openobserve, pull requests merged in 2025-07, with the labels that each got.

#7404 test:pipeline-core-tests
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/pipeline-core.spec.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  tests/ui-testing/playwright.config.js
Labels: 🧹 Updates, Review effort 3/5

#7416 fix: cancel query multiple panels
  tests/ui-testing/pages/pipelinePage.js
  web/src/composables/dashboard/useCancelQuery.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, Review effort 3/5

#7414 fix: dashboard cancel api on unmounted
  tests/ui-testing/pages/pipelinePage.js
  web/src/composables/dashboard/useCancelQuery.ts
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#7426 fix: group by fields pickup
  src/config/src/utils/sql.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/exec.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#7427 chore: remove `bucket_num` from `histogram` UDF
  src/service/search/cache/cacher.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/sql.rs
Labels: 🧹 Updates

#7430 fix: openfga migration for ai
  src/common/infra/ofga/mod.rs
  src/common/utils/auth.rs
Labels: ☢️ Bug

#7437 fix: sort order for merge response
  src/common/meta/search.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
  src/service/websocket_events/search.rs
Labels: ☢️ Bug

#7452 feat: remove parquet format inverted index
  src/config/src/config.rs
  src/config/src/meta/inverted_index.rs
  src/config/src/utils/inverted_index.rs
  src/handler/grpc/request/event.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/job/files/idx.rs
  src/job/files/mod.rs
  src/job/files/parquet.rs
  src/proto/proto/cluster/common.proto
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/compact/deleted.rs
  src/service/compact/merge.rs
  src/service/mod.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/tantivy/mod.rs
  src/service/tantivy/mod.rs
  src/service/tantivy/puffin/mod.rs
  src/service/tantivy/puffin/reader.rs
  src/service/tantivy/puffin/writer.rs
  src/service/tantivy/puffin_directory/caching_directory.rs
  src/service/tantivy/puffin_directory/footer_cache.rs
  src/service/tantivy/puffin_directory/mod.rs
  src/service/tantivy/puffin_directory/reader.rs
  src/service/tantivy/puffin_directory/reader_cache.rs
  src/service/tantivy/puffin_directory/writer.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 4/5

#7461 ci: unit test
  .github/workflows/unit-tests.yml
  coverage.sh
  src/config/src/config.rs
  src/service/tantivy/mod.rs
  src/service/tantivy/puffin/mod.rs
  src/service/tantivy/puffin/reader.rs
  src/service/tantivy/puffin/writer.rs
Labels: 🧹 Updates, Review effort 3/5

#7463 test: Added POM Folder structure to Streams tests, Removed unused fil…
  .github/workflows/playwright.yml
  tests/ui-testing/pages/streamsPages/streamsPage.js
  tests/ui-testing/playwright-tests/Streams/streaming.spec.js
  tests/ui-testing/playwright-tests/Streams/streamname.spec.js
  tests/ui-testing/playwright-tests/alerts.spec.js
  tests/ui-testing/playwright-tests/alertsfolders.spec.js
  tests/ui-testing/playwright-tests/streaming.spec.js.backup
  tests/ui-testing/playwright-tests/streamname.spec.js.backup
Labels: 🧹 Updates, ✏️ Feature, Review effort 3/5

#7467 ci: add more unit tests for tantivy
  coverage.sh
  src/service/tantivy/mod.rs
  src/service/tantivy/puffin/mod.rs
  src/service/tantivy/puffin/reader.rs
  src/service/tantivy/puffin_directory/caching_directory.rs
  src/service/tantivy/puffin_directory/footer_cache.rs
  src/service/tantivy/puffin_directory/mod.rs
  src/service/tantivy/puffin_directory/reader_cache.rs
  src/service/tantivy/puffin_directory/writer.rs
Labels: 🧹 Updates, ✏️ Feature

#7464 chore: add UT for CI
  src/common/utils/auth.rs
  src/service/users.rs
Labels: ✏️ Feature, Review effort 2/5

#7444 feat: add env to show dashboard symbol
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature, Review effort 2/5

#7446 chore: clippy delints
  src/cli/data/mod.rs
  src/common/infra/cluster/scheduler.rs
  src/common/infra/wal.rs
  src/common/meta/authz.rs
  src/common/meta/middleware_data.rs
  src/common/utils/functions.rs
  src/common/utils/stream.rs
  src/config/src/utils/schema.rs
  src/infra/src/table/mod.rs
  src/ingester/src/lib.rs
  src/router/http/ws/handler.rs
  src/service/alerts/alert.rs
  src/service/compact/retention.rs
  src/service/ingestion/grpc.rs
  src/service/logs/bulk.rs
  src/service/logs/hec.rs
  src/service/metadata/trace_list_index.rs
  src/service/promql/aggregations/avg.rs
  src/service/promql/aggregations/bottomk.rs
  src/service/promql/aggregations/count.rs
  src/service/promql/aggregations/group.rs
  src/service/promql/aggregations/max.rs
  src/service/promql/aggregations/min.rs
  src/service/promql/aggregations/stddev.rs
  src/service/promql/aggregations/stdvar.rs
  src/service/promql/aggregations/sum.rs
  src/service/promql/functions/label_join.rs
  src/service/promql/functions/label_replace.rs
  src/service/promql/functions/time_operations.rs
  src/service/search/cache/cacher.rs
  src/service/search/datafusion/udaf/percentile_cont.rs
  src/service/search/datafusion/udaf/summary_percentile.rs
  src/service/search/datafusion/udf/transform_udf.rs
  src/service/search/grpc/storage.rs
  src/service/search/partition.rs
  src/service/search/sql.rs
  src/service/tantivy/puffin_directory/footer_cache.rs
  src/service/tantivy/puffin_directory/reader.rs
  src/service/websocket_events/utils.rs
  tests/integration_test.rs
Labels: Review effort 4/5

#7435 fix: show unauthorised error in o2 ai chat
  web/src/components/O2AIChat.vue
Labels: ☢️ Bug

#7472 chore: add some logs
  src/handler/http/request/search/search_stream.rs
  src/service/search/cache/multi.rs
  src/service/search/search_stream.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/values.rs
Labels: ✏️ Feature

#7451 fix: O2 ai add info
  web/src/components/O2AIChat.vue
  web/src/components/functions/AddFunction.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/functions/TestFunction.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
  web/src/views/Functions.vue
Labels: ☢️ Bug, ✏️ Feature

#7417 fix: pass role to list_objects function to list only the resources the user has access to
  src/handler/http/auth/validator.rs
Labels: ☢️ Bug, Review effort 2/5

#7476 fix: dashboard variables custom value if present in option set that
  web/src/components/dashboards/settings/VariableQueryValueSelector.vue
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/getAnnotationsData.ts
Labels: ☢️ Bug

#7457 fix: multiselect stream share URL fix
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, Review effort 2/5

#7485 fix: disck cache max metric
  src/job/metrics.rs
Labels: ☢️ Bug

#7481 fix: change some error to warn
  src/handler/http/request/search/search_stream.rs
  src/handler/http/request/status/mod.rs
  src/job/metrics.rs
  src/main.rs
  src/service/logs/loki.rs
  src/service/search/cache/multi.rs
  src/service/search/datafusion/distributed_plan/empty_exec.rs
  src/service/search/search_stream.rs
  src/service/tantivy/puffin/mod.rs
  src/service/tantivy/puffin/writer.rs
  src/service/websocket_events/search.rs
  src/service/websocket_events/values.rs
Labels: ☢️ Bug, Review effort 4/5

#7489 fix: count number jump
  src/service/search/cluster/flight.rs
  src/service/search/search_stream.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#7492 fix: improve target_partition logic
  src/service/search/datafusion/exec.rs
Labels: ☢️ Bug, 🧹 Updates

#7475 fix: dashboard variables changes
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/settings/AddSettingVariable.vue
  web/src/components/dashboards/settings/VariableSettings.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/locales/languages/en.json
  web/src/views/Dashboards/DashboardSettings.vue
Labels: ☢️ Bug, Review effort 3/5

#7494 fix: count number jump
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/exec.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug, Review effort 3/5

#7497 feat: add env to show dashboard symbol
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#7500 fix: aggs cache ratio usage reporting
  src/service/search/cluster/flight.rs
  src/service/search/super_cluster/leader.rs
Labels: ☢️ Bug

#7483 feat: support path based value extraction in cipher functions
  src/common/utils/auth_tests.rs
  src/config/src/utils/json.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/cipher.rs
  src/service/search/datafusion/udf/cipher_udf.rs
  src/service/search/sql.rs
Labels: ✏️ Feature, Review effort 4/5

#7516 fix: remove sql_mode support for FE
  tests/api-testing/tests/pages/search_page.py
  tests/api-testing/tests/test_fuzzy.py
  tests/api-testing/tests/test_joinqueries.py
  tests/api-testing/tests/test_rum.py
  tests/api-testing/tests/test_search.py
  tests/api-testing/tests/test_streaming.py
  tests/api-testing/tests/test_try_castqueries.py
  tests/api-testing/tests/test_websocket.py
  tests/api-testing/tests/test_websocket2.py
  web/src/components/alerts/AlertList.spec.ts
  web/src/components/rum/performance/ApiDashboard.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/traces/Index.vue
  web/src/test/unit/mockData/alerts.ts
  web/src/ts/interfaces/query.ts
  web/src/views/RUM/AppErrors.vue
  web/src/views/RUM/AppSessions.vue
  web/src/views/RUM/ErrorViewer.vue
  web/src/views/RUM/SessionViewer.vue
  web/src/views/StreamExplorer.vue
Labels: ☢️ Bug, 🧹 Updates, Review effort 4/5

#7517 ci: updated openobserve binary path
  .github/workflows/release.yml
Labels: 🧹 Updates, Review effort 1/5

#7520 fix: o2 ai addtional info main
  web/src/components/functions/AddFunction.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/TenstackTable.vue
Labels: ☢️ Bug, ✏️ Feature, Review effort 3/5

#7522 fix: case-insensitive stream search (#7462)
  src/handler/http/request/stream/mod.rs
Labels: ☢️ Bug

#7478 fix: O2 ai additional info
  web/src/components/O2AIChat.vue
  web/src/components/functions/AddFunction.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/functions/TestFunction.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/layouts/MainLayout.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
  web/src/views/Functions.vue
Labels: ☢️ Bug, ✏️ Feature

#7525 feat: remote wal exponential retry
  src/config/src/config.rs
Labels: ✏️ Feature

#7490 test: Logs Page Major Overhaul
  .github/workflows/playwright.yml
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/logsPages/logsPage.js
  tests/ui-testing/pages/logsPages/logsQueryPage.js
  tests/ui-testing/pages/streamsPages/streamsPage.js
  tests/ui-testing/playwright-tests/Logs/logshistogram.spec.js
  tests/ui-testing/playwright-tests/Logs/logspage.spec.js
  tests/ui-testing/playwright-tests/Logs/logsqueries.spec.js
  tests/ui-testing/playwright-tests/Logs/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/Streams/streaming.spec.js
  tests/ui-testing/playwright-tests/Streams/streamname.spec.js
  tests/ui-testing/playwright-tests/changeOrg.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-folder.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  tests/ui-testing/playwright-tests/enrichment.spec.js
  tests/ui-testing/playwright-tests/indexquery.spec.js
  tests/ui-testing/playwright-tests/join.spec.js
  tests/ui-testing/playwright-tests/logshistogram.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/pagination.spec.js
  tests/ui-testing/playwright-tests/pipeline-core.spec.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  tests/ui-testing/playwright-tests/region.spec.js
  tests/ui-testing/playwright-tests/remotepipeline.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/sanity2.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  tests/ui-testing/playwright-tests/schemaload.spec.js
  tests/ui-testing/playwright-tests/searchpartition.spec.js
  tests/ui-testing/playwright-tests/secondsPrecisionAdded.spec.js
  tests/ui-testing/playwright-tests/streaming.spec.js.backup
  tests/ui-testing/playwright-tests/streamname.spec.js.backup
  tests/ui-testing/playwright-tests/unflattened.spec.js
  tests/ui-testing/playwright-tests/websocket.spec.js
Labels: 🧹 Updates, Review effort 5/5

#7536 fix: remote_scan on single node
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/mod.rs
Labels: ☢️ Bug

#7304 feat: json editor for pipeline and alert
  web/src/components/O2AIChat.vue
  web/src/components/alerts/AddAlert.vue
  web/src/components/common/JsonEditor.vue
  web/src/components/pipeline/ImportPipeline.vue
  web/src/components/pipeline/NodeForm/Stream.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/composables/usePipelines.ts
  web/src/types/chat.ts
  web/src/utils/validateAlerts.ts
  web/src/utils/validatePipeline.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 5/5

#7528 fix: single node should push down the whole plan
  src/common/utils/zo_logger.rs
  src/config/src/ider.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/mod.rs
Labels: ☢️ Bug, Review effort 1/5

#7539 fix: fir for replace drops "$'" from while replacing value
  web/src/composables/useLogs.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/traces/fields-sidebar/BasicValuesFilter.vue
Labels: ☢️ Bug

#7537 test: Folder movement
  tests/ui-testing/pages/alertsPage.js
  tests/ui-testing/pages/dashboardPages/dashboard-list.js
  tests/ui-testing/pages/dashboardPages/dashboard-time.js
  tests/ui-testing/playwright-tests/dashboards/attachment/imagesAuto.png
  tests/ui-testing/playwright-tests/dashboards/custom-charts.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-folder.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-general-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-geoMap.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-import.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-maps.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-multi-y-axis.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-snaps/areachart-screenshot.png
  tests/ui-testing/playwright-tests/dashboards/dashboard-tabs-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-variables-setting.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.utils.js
  tests/ui-testing/playwright-tests/dashboards/dashboard2.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
  tests/ui-testing/playwright-tests/dashboards/utils/dashCreation.js
  tests/ui-testing/playwright-tests/dashboards/utils/dashIngestion.js
  tests/ui-testing/playwright-tests/dashboards/utils/dashLogin.js
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
Labels: 🧹 Updates, Review effort 2/5

#7438 fix: cancelled queries before switching stream in logs
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/components/pipeline/StreamSelection.vue
  web/src/composables/useLogs.ts
  web/src/composables/usePromqlSuggestions.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.vue
  web/src/plugins/pipelines/useDnD.ts
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceTree.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, Review effort 3/5

#7540 fix: fix histogram issue when user redirected from streams to logs an…
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, Review effort 1/5

#7549 feat: aggregation topk optimize
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/config/src/utils/record_batch_ext.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/scheduler/worker.rs
  src/service/compact/stats.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/codec/aggregate_topk_exec.rs
  src/service/search/datafusion/distributed_plan/codec/empty_exec.rs
  src/service/search/datafusion/distributed_plan/codec/mod.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/search/super_cluster/leader.rs
Labels: ✏️ Feature

#7550 feat :add allowed domains
  src/handler/http/request/status/mod.rs
Labels: Invalid PR Title, ✏️ Feature

#7551 fix: optimize steaming agg check logic
  src/service/search/mod.rs
Labels: ☢️ Bug

#7554 fix: dashboard height issue
  web/src/views/Dashboards/RenderDashboardCharts.vue
Labels: ☢️ Bug

#7556 fix: default role
  src/handler/http/auth/jwt.rs
Labels: ☢️ Bug

#7557 chore: add more agg to list
  src/config/src/utils/sql.rs
Labels: ✏️ Feature

#7045 fix: logs page unit test improvement
  web/src/components/MenuLink.spec.ts
  web/src/components/alerts/AddAlert.spec.ts
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AddDestination.spec.ts
  web/src/components/alerts/AddTemplate.spec.ts
  web/src/components/alerts/AlertList.spec.ts
  web/src/components/alerts/DestinationList.spec.ts
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/TemplateList.spec.ts
  web/src/components/functions/AddEnrichmentTable.spec.ts
  web/src/components/ingestion/logs/Curl.spec.ts
  web/src/components/ingestion/logs/FluentBit.spec.ts
  web/src/components/ingestion/logs/Fluentd.spec.ts
  web/src/components/ingestion/logs/Vector.spec.ts
  web/src/components/logstream/Schema.spec.ts
  web/src/components/pipeline/pipeline.spec.js
  web/src/components/pipeline/utils/pipelineCommonValidation.ts
  web/src/composables/useFunctions.ts
  web/src/composables/useLogs.ts
  web/src/composables/useStreamingSearch.spec.ts
  web/src/composables/useStreamingSearch.ts
  web/src/layouts/MainLayout.spec.ts
  web/src/plugins/logs/DetailTable.spec.ts
  web/src/plugins/logs/Index.spec.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.spec.ts
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/QueryEditor.spec.ts
  web/src/plugins/logs/SearchBar.spec.ts
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SearchResult.spec.ts
  web/src/plugins/logs/useLogs.spec.ts
  web/src/test/unit/helpers/store.ts
  web/src/views/AppAlerts.spec.ts
  web/src/views/Functions.spec.ts
  web/src/views/LogStream.spec.ts
  web/src/views/Logs.spec.ts
  web/src/views/MemberSubscription.spec.ts
  web/src/views/RUM/AppErrors.spec.ts
  web/src/views/ShortUrl.spec.ts
  web/src/views/User.spec.ts
Labels: ☢️ Bug, 🧹 Updates, Review effort 5/5

#7565 test: table transpose validation updates
  tests/ui-testing/playwright-tests/dashboards/dashboard-transpose.spec.js
Labels: 🧹 Updates, Review effort 3/5

#7560 fix: RBAC default role
  src/handler/http/auth/jwt.rs
  tests/api-testing/tests/test_streaming.py
Labels: ☢️ Bug, Review effort 2/5

#7570 fix: made get ingestion url function as util
  web/src/components/ingestion/logs/Curl.vue
  web/src/components/ingestion/logs/FileBeat.vue
  web/src/components/ingestion/logs/FluentBit.vue
  web/src/components/ingestion/logs/Fluentd.vue
  web/src/components/ingestion/logs/LogstashDatasource.vue
  web/src/components/ingestion/logs/OtelConfig.vue
  web/src/components/ingestion/logs/SyslogNg.vue
  web/src/components/ingestion/logs/Vector.vue
  web/src/components/ingestion/metrics/CloudWatchMetrics.vue
  web/src/components/ingestion/metrics/OtelCollector.vue
  web/src/components/ingestion/metrics/PrometheusConfig.vue
  web/src/components/ingestion/metrics/TelegrafConfig.vue
  web/src/components/ingestion/recommended/AWSConfig.vue
  web/src/components/ingestion/recommended/FrontendRumConfig.vue
  web/src/components/ingestion/recommended/GCPConfig.vue
  web/src/components/ingestion/recommended/KubernetesConfig.vue
  web/src/components/ingestion/recommended/LinuxConfig.vue
  web/src/components/ingestion/recommended/OtelConfig.vue
  web/src/components/ingestion/recommended/WindowsConfig.vue
  web/src/components/ingestion/traces/OpenTelemetry.vue
  web/src/composables/useIngestion.ts
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, Review effort 3/5

#7571 fix: add alert page UI changes
  tests/ui-testing/pages/alertsPages/alertsPage.js
  web/src/assets/images/common/ai_icon_blue.svg
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertsContainer.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/alerts/VariablesInput.vue
  web/src/components/common/sidebar/SelectFolderDropDown.vue
  web/src/components/functions/FullViewContainer.vue
Labels: ☢️ Bug, ✏️ Feature, Review effort 4/5

#7562 feat: use tantivy to improve value api
  src/config/src/meta/inverted_index.rs
  src/config/src/utils/sql.rs
  src/job/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/db/metas.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/plan/mod.rs
  src/service/search/datafusion/plan/tantivy_optimize_exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/utils.rs
  src/service/search/index.rs
  src/service/search/sql.rs
  src/service/search/utils.rs
  src/service/tantivy/mod.rs
  src/service/tantivy/puffin_directory/reader.rs
Labels: 🧹 Updates, ✏️ Feature, Review effort 4/5

#7576 chore: added new download script for openobserve and o2-enterprise
  downloadO2.sh
Labels: ✏️ Feature, Review effort 2/5

#7584 fix: stream loading issue and console error while page refresh
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/plugins/logs/Index.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#7588 fix: non-sql mode added common fields filter for multi stream histogram
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, ✏️ Feature

#7590 perf: fix slowness by improving file movement for the ingester
  src/job/files/parquet.rs
  src/service/search/grpc/wal.rs
Labels: ☢️ Bug, Review effort 3/5

#7563 feat: Domain management APIs
  src/handler/http/request/domain_management/mod.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/router/mod.rs
  src/job/mod.rs
  src/super_cluster_queue/domain_management.rs
  src/super_cluster_queue/mod.rs
  web/src/components/settings/DomainManagement.integration.spec.ts
  web/src/components/settings/DomainManagement.spec.ts
  web/src/components/settings/DomainManagement.test-helpers.ts
  web/src/components/settings/DomainManagement.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/useManagementRoutes.ts
  web/src/locales/languages/en.json
  web/src/services/domainManagement.spec.ts
  web/src/services/domainManagement.ts
Labels: ✏️ Feature, Review effort 3/5

#7555 feat: support hec format for ingestion for rc7
  src/common/meta/ingestion.rs
  src/config/src/config.rs
  src/config/src/meta/self_reporting/usage.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/router/mod.rs
  src/service/logs/hec.rs
  src/service/logs/ingest.rs
  src/service/logs/mod.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#7592 feat: sync from rc7 to rc9 without AI
  .github/workflows/build-pr-image.yml
  src/common/infra/cluster/mod.rs
  src/common/infra/ofga/mod.rs
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/config/src/meta/search.rs
  src/config/src/meta/self_reporting/usage.rs
  src/config/src/meta/stream.rs
  src/config/src/router.rs
  src/config/src/utils/json.rs
  src/config/src/utils/sysinfo/mod.rs
  src/handler/http/auth/jwt.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_stream.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/job/files/parquet.rs
  src/router/http/mod.rs
  src/service/compact/deleted.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/retention.rs
  src/service/compact/stats.rs
  src/service/db/file_list/local.rs
  src/service/functions.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/cipher.rs
  src/service/search/datafusion/udf/cipher_udf.rs
  src/service/search/grpc/wal.rs
  src/service/search/index.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/search_jobs.rs
  src/service/self_reporting/mod.rs
Labels: ✏️ Feature

#7598 fix: panel load issue on panel visible
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#7593 feat: use tantivy to optimzie distinct value search
  src/config/src/meta/inverted_index.rs
  src/config/src/utils/tantivy/query/contains_query.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/plan/tantivy_optimize_exec.rs
  src/service/search/grpc/flight.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/utils.rs
  src/service/search/index.rs
  src/service/search/sql.rs
  src/service/tantivy/puffin_directory/reader.rs
Labels: ✏️ Feature, Review effort 5/5

#7605 fix: remove stream from histogram query if filter field not exist in …
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, 🧹 Updates

#7608 fix: remote wal sink wait
  src/common/meta/ingestion.rs
  src/config/src/config.rs
Labels: ☢️ Bug

#7617 fix: UI loading scansize fix rc7
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7625 fix: UDFs panic for invalid JSON (#7614)
  src/service/search/datafusion/udf/arr_descending_udf.rs
  src/service/search/datafusion/udf/arrcount_udf.rs
  src/service/search/datafusion/udf/arrindex_udf.rs
  src/service/search/datafusion/udf/arrjoin_udf.rs
  src/service/search/datafusion/udf/arrsort_udf.rs
  src/service/search/datafusion/udf/arrzip_udf.rs
  src/service/search/datafusion/udf/cast_to_arr_udf.rs
  src/service/search/datafusion/udf/to_arr_string_udf.rs
Labels: ☢️ Bug

#7626 fix: UDFs panic for invalid JSON (#7614) (rc7)
  src/service/search/datafusion/udf/arr_descending_udf.rs
  src/service/search/datafusion/udf/arrcount_udf.rs
  src/service/search/datafusion/udf/arrindex_udf.rs
  src/service/search/datafusion/udf/arrjoin_udf.rs
  src/service/search/datafusion/udf/arrsort_udf.rs
  src/service/search/datafusion/udf/arrzip_udf.rs
  src/service/search/datafusion/udf/cast_to_arr_udf.rs
  src/service/search/datafusion/udf/to_arr_string_udf.rs
Labels: ☢️ Bug

#7619 fix: UI loading scansize fix rc9
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7585 fix: stream loading issue and console error
  web/src/composables/useLogs.ts
  web/src/composables/useStreams.ts
  web/src/plugins/logs/Index.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, Review effort 2/5

#7618 fix: streaming aggregates scansize tooktime and noevents found issue fix
  web/src/composables/useLogs.ts
Labels: ☢️ Bug, Review effort 2/5

#7631 fix: Issue 7629 fields not persist tablegrid rc9
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#7634 fix: added reset selected table fields button
  web/src/locales/languages/en.json
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug, ✏️ Feature

#7635 fix: column reordering fix
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#7179 fix: not overwrite pipeline_id when imported
  src/handler/http/request/alerts/deprecated.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/pipeline.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert.rs
  src/service/pipeline/mod.rs
Labels: ☢️ Bug, Review effort 1/5

#7121 fix: avoid deleting pipelines, alerts directly when deleting a stream
  src/handler/http/request/stream/mod.rs
  src/service/stream.rs
  web/src/services/stream.ts
  web/src/views/LogStream.vue
Labels: ☢️ Bug, Review effort 2/5

#7495 fix: org dropdown typeahead
  web/src/layouts/MainLayout.vue
Labels: ☢️ Bug

#7523 fix: ignore super cluster event if org_user already exists
  src/super_cluster_queue/org_user.rs
Labels: ☢️ Bug, Review effort 2/5

#7620 fix: remote wal changes
  src/config/src/config.rs
Labels: ☢️ Bug, Review effort 2/5

#7630 chore: add UTs, run fmt and clippy
  src/common/utils/stream.rs
  src/config/src/utils/time.rs
  src/ingester/bin/wal-reader.rs
  src/service/promql/common.rs
  src/service/promql/functions/math_operations.rs
  src/service/search/cache/result_utils.rs
  src/service/search/utils.rs
  src/service/short_url.rs
Labels: ✏️ Feature, Review effort 4/5

#7636 fix: cargo clippy
  src/common/utils/auth_tests.rs
  src/handler/http/request/users/mod.rs
  src/super_cluster_queue/org_user.rs
Labels: ☢️ Bug, Review effort 3/5

#7637 fix: Alerts , Dashboards, pipeline Tables made consistent with other tables
  web/src/components/alerts/AlertList.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug, Review effort 3/5

#7638 fix: only show o2 ai btn when ai chat is enabled
  web/src/components/functions/TestFunction.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
Labels: ☢️ Bug, Review effort 2/5

#7643 fix: partitions for index searches rc9
  src/config/src/config.rs
  src/service/search/mod.rs
Labels: ☢️ Bug

#7644 fix: align partitions for indexed search (#7642)
  src/config/src/config.rs
  src/service/search/mod.rs
Labels: ☢️ Bug, Review effort 3/5

#7586 feat: add derived stream to stream meta
  src/common/meta/stream.rs
  src/handler/grpc/request/ingest.rs
  src/handler/http/request/logs/ingest.rs
  src/handler/http/request/rum/ingest.rs
  src/infra/src/schema/mod.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/hec.rs
  src/service/logs/ingest.rs
  src/service/logs/loki.rs
  src/service/logs/mod.rs
  src/service/logs/otlp.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/schema.rs
  src/service/self_reporting/ingestion.rs
  src/service/stream.rs
  src/service/traces/mod.rs
Labels: ✏️ Feature, Review effort 4/5

#7639 fix: fix for equal and other operator used it adds unwanted space.
  web/src/composables/useLogs.ts
  web/src/composables/useQuery.ts
  web/src/plugins/logs/IndexList.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature

#7654 perf: improve disk cache lock time
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/service/search/datafusion/distributed_plan/enrich_exec.rs
  src/service/search/grpc/storage.rs
Labels: 🧹 Updates

#7650 feat: Enrichment redesign
  src/config/src/config.rs
  src/config/src/utils/enrichment_local_cache.rs
  src/config/src/utils/mod.rs
  src/config/src/utils/record_batch_ext.rs
  src/infra/src/table/enrichment_tables.rs
  src/infra/src/table/entity/enrichment_tables.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/migration/m20250716_000001_create_enrichment_table.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/job/cipher.rs
  src/job/compactor.rs
  src/job/promql_self_consume.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/db/enrichment_table.rs
  src/service/db/schema.rs
  src/service/enrichment/mod.rs
  src/service/enrichment/storage.rs
  src/service/enrichment_table/mod.rs
  src/service/promql/search/grpc/wal.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/enrich_exec.rs
  src/service/search/datafusion/distributed_plan/mod.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/table_provider/enrich_table.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/flight.rs
  src/service/search/super_cluster/follower.rs
  src/service/stream.rs
  src/super_cluster_queue/alerts.rs
  src/super_cluster_queue/cipher_keys.rs
  src/super_cluster_queue/dashboards.rs
  src/super_cluster_queue/destinations.rs
  src/super_cluster_queue/distinct_values.rs
  src/super_cluster_queue/folders.rs
  src/super_cluster_queue/meta.rs
  src/super_cluster_queue/mod.rs
  src/super_cluster_queue/pipelines.rs
  src/super_cluster_queue/scheduler.rs
  src/super_cluster_queue/schemas.rs
  src/super_cluster_queue/search_job/mod.rs
  src/super_cluster_queue/search_job/search_job_partitions.rs
  src/super_cluster_queue/search_job/search_job_results.rs
  src/super_cluster_queue/search_job/search_jobs.rs
  src/super_cluster_queue/short_urls.rs
  src/super_cluster_queue/templates.rs
Labels: ✏️ Feature, Review effort 5/5

#7669 fix: use str_match replace LIKE for contains for alert
  src/handler/http/request/status/mod.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#7670 fix: use str_match replace LIKE for contains for alert
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#7673 fix: show index size when search tantivy
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#7674 fix: show index size when search tantivy
  src/service/search/cluster/flight.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug, Review effort 2/5

#7323 feat: re_patterns
  .github/workflows/playwright.yml
  Cross.toml
  cross/Dockerfile.musl
  src/common/meta/stream.rs
  src/common/utils/auth.rs
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/handler/http/request/mod.rs
  src/handler/http/request/re_pattern/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/entity/re_pattern_stream_map.rs
  src/infra/src/table/entity/re_patterns.rs
  src/infra/src/table/migration/m20250612_000001_create_re_pattern_table.rs
  src/infra/src/table/migration/m20250612_000002_create_re_pattern_stream_map_table.rs
  src/infra/src/table/migration/mod.rs
  src/infra/src/table/mod.rs
  src/infra/src/table/re_pattern.rs
  src/infra/src/table/re_pattern_stream_map.rs
  src/job/mod.rs
  src/service/db/mod.rs
  src/service/db/re_pattern.rs
  src/service/logs/ingest.rs
  src/service/stream.rs
  src/super_cluster_queue/mod.rs
  src/super_cluster_queue/re_pattern.rs
  tests/ui-testing/pages/dashboardPages/dashboardPage.js
  tests/ui-testing/pages/generalPages/homePage.js
  tests/ui-testing/pages/reportsPages/reportsPage.js
  tests/ui-testing/playwright-tests/Reports/reportsUpdated2.spec.js
  tests/ui-testing/playwright-tests/dashboards/utils/dashCreation.js
  web/src/assets/images/common/ai_icon_primary.svg
  web/src/assets/images/regex_pattern/no_applied_pattern.svg
  web/src/assets/images/regex_pattern/no_data_regex_pattern.svg
  web/src/assets/images/regex_pattern/regex_icon_dark.svg
  web/src/assets/images/regex_pattern/regex_icon_light.svg
  web/src/components/alerts/ImportAlert.vue
  web/src/components/alerts/TemplateList.vue
  web/src/components/functions/FullViewContainer.vue
  web/src/components/logstream/AssociatedRegexPatterns.vue
  web/src/components/logstream/schema.vue
  web/src/components/settings/AddRegexPattern.vue
  web/src/components/settings/ImportRegexPattern.vue
  web/src/components/settings/NoRegexPatterns.vue
  web/src/components/settings/RegexPatternList.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/useManagementRoutes.ts
  web/src/composables/useStreams.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/JsonPreview.vue
  web/src/services/regex_pattern.ts
  web/src/stores/index.ts
Labels: ✏️ Feature, Review effort 4/5

#7682 chore: make_builder for utf8view
  src/config/src/utils/record_batch_ext.rs
Labels: Review effort 2/5

#7681 fix: o2 ai button should only show when ai chat is enabled
  web/src/components/common/O2AIContextAddBtn.vue
  web/src/components/functions/TestFunction.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
Labels: ☢️ Bug

#7675 fix: add alert UI issues
  tests/ui-testing/pages/alertsPages/alertsPage.js
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertsContainer.vue
  web/src/components/alerts/PreviewAlert.vue
  web/src/components/alerts/RealTimeAlert.vue
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/functions/AddFunction.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/utils/zincutils.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 4/5

#7695 perf: improve concurrency for index search
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/config/src/utils/record_batch_ext.rs
  src/service/search/grpc/storage.rs
  src/service/search/streaming/mod.rs
Labels: 🧹 Updates, Review effort 4/5

#7691 chore: add UTs, run fmt and clipyy
  src/cli/basic/test.rs
  src/cli/data/cli.rs
  src/common/meta/middleware_data.rs
  src/config/src/meta/inverted_index.rs
Labels: ✏️ Feature, Review effort 3/5

#7704 test: e2e-cte(with-queries)-testcases
  .github/workflows/playwright.yml
  tests/test-data/cte_queries.json
  tests/ui-testing/playwright-tests/GeneralTests/sanity.spec.js
  tests/ui-testing/playwright-tests/Logs/logsqueries.cte.spec.js
Labels: 🧹 Updates, Review effort 3/5

#7666 fix: dashboard 16 digit numeric value conversion
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertSQLData.ts
  web/src/utils/dashboard/convertTableData.ts
Labels: ☢️ Bug

#7710 perf: improve search memtable
  src/service/search/grpc/wal.rs
Labels: 🧹 Updates, Review effort 3/5

#7686 fix: o2 ai add context button as component
  web/src/components/common/O2AIContextAddBtn.spec.js
  web/src/components/common/O2AIContextAddBtn.vue
  web/src/components/functions/TestFunction.vue
  web/src/plugins/logs/DetailTable.vue
  web/src/plugins/logs/TenstackTable.vue
  web/src/plugins/logs/data-table/CellActions.vue
  web/src/utils/validatePipeline.ts
Labels: ☢️ Bug, ✏️ Feature, Review effort 3/5

#7684 fix: use single event for alert skipped event triggers reporting
  src/config/src/meta/self_reporting/usage.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug

#7658 fix: check email validity when creating new user
  src/handler/http/request/users/mod.rs
Labels: ☢️ Bug

#7701 fix: rbac migration for re_patterns
  src/common/infra/ofga/mod.rs
Labels: ☢️ Bug, Review effort 2/5

#7707 fix: Logs field-list Interesting fields improvements
  tests/ui-testing/playwright-tests/join.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/pipelines.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/schema.spec.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug, 🧹 Updates

#7722 ci: update rust to nightly-2025-05-20
  .devcontainer/Dockerfile
  .github/workflows/api-testing.yml
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/playwright.yml
  .github/workflows/unit-tests.yml
  deploy/build/Dockerfile
  deploy/build/Dockerfile.sccache.aarch64
  deploy/build/Dockerfile.sccache.amd64
  deploy/build/Dockerfile.tag-debug.aarch64
  deploy/build/Dockerfile.tag-debug.amd64
  deploy/build/Dockerfile.tag-simd.amd64
  deploy/build/Dockerfile.tag.aarch64
  deploy/build/Dockerfile.tag.amd64
  deploy/build/buildspec-test.yml
Labels: 🧹 Updates, Review effort 2/5

#7720 chore: add UTs, run fmt and clippy
  src/cipher/mod.rs
  src/cipher/registry.rs
  src/common/meta/saved_view.rs
  src/common/utils/jwt.rs
  src/config/src/utils/hash/mod.rs
  src/handler/http/auth/token.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/users/service_accounts.rs
  src/job/cipher.rs
  src/service/search/grpc/wal.rs
Labels: ✏️ Feature, Review effort 4/5

#7712 fix: dashboard go to logs with long url
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug, Review effort 2/5

#7717 feat: skip UT when code unchanged for UI/API
  .github/workflows/api-testing.yml
  .github/workflows/build-fork-pr-image.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/js-license-checker.yml
  .github/workflows/unit-tests.yml
Labels: ✏️ Feature, Review effort 2/5

#7736 fix: improve log message of partition file by consistent hashing
  src/service/search/cluster/flight.rs
Labels: ☢️ Bug, 🧹 Updates

#7729 ci: updated github action role
  .github/workflows/release.yml
Labels: 🧹 Updates, Review effort 2/5

#7738 fix: improve log message of partition file by consistent hashing
  src/service/alerts/scheduler/worker.rs
  src/service/search/cluster/flight.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#7716 fix: environment FTS and secondary fields default selected
  web/src/components/logstream/schema.vue
Labels: ☢️ Bug, Review effort 3/5

#7732 feat: support not query for index rc9
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/udf/match_all_udf.rs
  src/service/search/datafusion/udf/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
  src/service/search/sql.rs
  tests/api-testing/tests/test_search.py
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  web/src/components/CodeQueryEditor.vue
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useSuggestions.ts
  web/src/plugins/metrics/SyntaxGuideMetrics.vue
  web/src/plugins/traces/SyntaxGuide.vue
  web/src/test/unit/helpers/setupTests.ts
  web/src/test/unit/helpers/store.ts
  web/src/utils/query/sqlUtils.ts
  web/src/views/Dashboards/addPanel/AddCondition.vue
Labels: ✏️ Feature

#7743 fix: dashboard values api filter query
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
Labels: ☢️ Bug, Review effort 2/5

#7724 fix: dashboard go to logs with long url (#7712)
  web/src/components/dashboards/PanelContainer.vue
Labels: ☢️ Bug

#7747 chore: increase required coverage limit
  coverage.sh
Labels: Review effort 1/5

#7622 feat: visualization enhancement rc7
  .github/workflows/playwright.yml
  src/common/utils/auth.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/router/mod.rs
  src/service/search/cache/cacher.rs
  src/service/search/datafusion/plan/mod.rs
  src/service/search/datafusion/plan/projections.rs
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/ChartSelection.vue
  web/src/components/dashboards/addPanel/FieldList.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useDashboardPanel.ts
  web/src/composables/useLogs.ts
  web/src/composables/useNotifications.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
  web/src/services/search.ts
  web/src/ts/interfaces/logs.ts
  web/src/ts/interfaces/query.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/query/sqlUtils.ts
  web/src/utils/query/visualizationUtils.ts
Labels: ✏️ Feature

#7649 feat: upgrade datafusion to v49
  Cargo.lock
  Cargo.toml
  src/common/utils/jwt.rs
  src/config/src/config.rs
  src/handler/http/auth/validator.rs
  src/infra/src/cache/storage.rs
  src/infra/src/errors/grpc.rs
  src/infra/src/storage/accounts.rs
  src/infra/src/storage/local.rs
  src/infra/src/storage/mod.rs
  src/infra/src/storage/remote.rs
  src/service/alerts/mod.rs
  src/service/search/datafusion/distributed_plan/empty_exec.rs
  src/service/search/datafusion/distributed_plan/rewrite.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/cipher.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/rewrite_histogram.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/optimizer/utils.rs
  src/service/search/datafusion/plan/deduplication_exec.rs
  src/service/search/datafusion/storage/memory.rs
  src/service/search/datafusion/storage/wal.rs
  src/service/search/datafusion/table_provider/helpers.rs
  src/service/search/datafusion/table_provider/memtable.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/udaf/percentile_cont.rs
  src/service/search/datafusion/udaf/summary_percentile.rs
  src/service/search/datafusion/udf/arr_descending_udf.rs
  src/service/search/datafusion/udf/arrcount_udf.rs
  src/service/search/datafusion/udf/arrindex_udf.rs
  src/service/search/datafusion/udf/arrjoin_udf.rs
  src/service/search/datafusion/udf/arrsort_udf.rs
  src/service/search/datafusion/udf/arrzip_udf.rs
  src/service/search/datafusion/udf/cast_to_arr_udf.rs
  src/service/search/datafusion/udf/cipher_udf.rs
  src/service/search/datafusion/udf/date_format_udf.rs
  src/service/search/datafusion/udf/fuzzy_match_udf.rs
  src/service/search/datafusion/udf/regexp_udf.rs
  src/service/search/datafusion/udf/spath_udf.rs
  src/service/search/datafusion/udf/str_match_udf.rs
  src/service/search/datafusion/udf/time_range_udf.rs
  src/service/search/datafusion/udf/to_arr_string_udf.rs
  src/service/search/index.rs
  src/service/search/sql.rs
  tests/api-testing/tests/test_search.py
  web/src/components/DateTime.vue
  web/src/components/functions/AssociatedStreamFunction.vue
  web/src/components/logstream/schema.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/plugins/logs/useLogs.spec.ts
  web/src/views/LogStream.vue
Labels: ✏️ Feature, Review effort 5/5

#7754 fix: value api with complex query
  src/handler/http/request/search/mod.rs
  src/service/search/sql/mod.rs
Labels: ☢️ Bug

#7741 fix: hist interval bug fixes
  Cargo.lock
  Cargo.toml
  src/common/utils/auth_tests.rs
  src/config/src/meta/search.rs
  src/config/src/utils/sql.rs
  src/handler/http/request/search/error_utils.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_stream.rs
  src/infra/src/errors/mod.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/search/partition.rs
  src/service/search/sql/histogram.rs
  src/service/search/super_cluster/leader.rs
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/ts/interfaces/query.ts
Labels: ☢️ Bug

#7664 fix: optimize remote wal [phase 2]
  src/config/src/config.rs
  src/config/src/metrics.rs
  src/job/mod.rs
  src/job/pipeline.rs
  src/main.rs
  src/service/pipeline/batch_execution.rs
  src/wal/src/reader.rs
Labels: ☢️ Bug

#7755 fix: value api with complex query
  src/handler/http/request/search/mod.rs
  src/service/search/sql.rs
Labels: ☢️ Bug

#7753 chore: add UTs, run fmt and clipyy
  Cargo.lock
  src/common/utils/jwt.rs
  src/config/Cargo.toml
  src/config/src/meta/dashboards/reports.rs
  src/config/src/meta/destinations.rs
  src/config/src/meta/pipeline/mod.rs
  src/config/src/meta/sql.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/enrichment_local_cache.rs
  src/config/src/utils/file.rs
  src/config/src/utils/flatten.rs
  src/config/src/utils/hash/cityhash.rs
  src/config/src/utils/hash/fnv.rs
  src/config/src/utils/hash/gxhash.rs
  src/config/src/utils/hash/murmur3.rs
  src/config/src/utils/json.rs
  src/config/src/utils/parquet.rs
  src/config/src/utils/query_select_utils.rs
  src/config/src/utils/sort.rs
  src/config/src/utils/sql.rs
  src/config/src/utils/time.rs
  src/handler/http/request/authz/fga.rs
  src/infra/src/table/migration/m20250320_000001_remove_alert_name_unique_constraint.rs
  src/service/dashboards/reports.rs
  src/service/search/datafusion/plan/tantivy_optimize_exec.rs
  src/wal/tests/wal.rs
Labels: ✏️ Feature, Review effort 5/5

#7744 feat: support not equal and not inlist in `IndexCondition`
  src/config/src/config.rs
  src/service/search/grpc/storage.rs
  src/service/search/index.rs
  src/service/search/sql.rs
Labels: ✏️ Feature, Review effort 4/5

#7766 fix: convert microseconds to seconds for delay_in_secs in triggers stream
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#7773 fix: hist_http2_streaming
  src/handler/http/request/search/search_stream.rs
  src/service/search/sql/mod.rs
Labels: ☢️ Bug

#7765 fix: update string matching logic to include 'Contains' operator
  web/src/composables/useDashboardPanel.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug, 🧹 Updates, Review effort 2/5

#7749 chore: updated statefulset.yaml with o2cr.ai/openobserve
  deploy/k8s/statefulset.yaml
Labels: 🧹 Updates, Review effort 1/5

#7776 chore: remove some deprecated code
  src/config/src/meta/sql.rs
  src/config/src/utils/sql.rs
  src/handler/http/request/authz/fga.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: 🧹 Updates, Review effort 2/5

#7757 fix: alert list refresh when user tries to refresh in non default folder
  web/src/components/alerts/AlertList.vue
  web/src/components/common/sidebar/FolderList.vue
  web/src/utils/commons.ts
Labels: ☢️ Bug

#7779 fix: re-cal hist interval http2 streaming if `is_ui_histogram`
  src/handler/http/request/search/search_stream.rs
Labels: ☢️ Bug

#7778 perf: pushdown plan
  .github/workflows/api-testing.yml
  .github/workflows/playwright.yml
  Cargo.lock
  src/handler/http/request/authz/fga.rs
  src/proto/Cargo.toml
  src/proto/build.rs
  src/proto/proto/cluster/plan.proto
  src/proto/proto/datafusion/datafusion.proto
  src/proto/proto/datafusion_common/datafusion_common.proto
  src/proto/src/generated/cluster.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/codec/aggregate_topk_exec.rs
  src/service/search/datafusion/distributed_plan/codec/empty_exec.rs
  src/service/search/datafusion/distributed_plan/codec/mod.rs
  src/service/search/datafusion/distributed_plan/codec/physical_plan_node.rs
  src/service/search/datafusion/distributed_plan/codec/streaming_aggs_exec.rs
  src/service/search/sql.rs
  tests/api-testing/pyproject.toml
  tests/api-testing/requirements-dev.lock
  tests/api-testing/requirements.lock
  tests/api-testing/tests/test_websocket.py
  tests/api-testing/tests/test_websocket2.py
  tests/ui-testing/playwright-tests/Logs/websocket.spec.js
Labels: Review effort 4/5

#7780 fix: histogram interval bug fixes
  src/config/src/meta/search.rs
  src/service/search/search_stream.rs
  web/src/composables/useLogs.ts
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#7759 fix: visualization enhancement minor fixes
  src/service/search/sql/histogram.rs
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/TransformSelector.vue
  web/src/plugins/logs/VisualizeLogsQuery.vue
Labels: ☢️ Bug

#7782 fix: Logs page download json data
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#7787 fix: http2_streaming bugs with new histogram flow
  src/handler/http/request/search/search_stream.rs
  src/handler/http/request/stream/mod.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#7659 fix: check for blank spaces in path parameters
  src/handler/http/request/enrichment_table/mod.rs
Labels: ☢️ Bug

#7740 feat: add download search event
  src/config/src/meta/search.rs
  src/handler/http/models/alerts/mod.rs
  src/infra/src/table/alerts/intermediate.rs
Labels: ✏️ Feature

#7794 fix: Logs undefined error on clicking add-column-to-table button from field list
  web/src/plugins/logs/Index.vue
Labels: ☢️ Bug, ✏️ Feature

#7796 fix: missing last bucket for tantivy histogram
  src/service/search/sql/mod.rs
Labels: ☢️ Bug

#7798 fix: removal from processing table
  src/ingester/src/immutable.rs
Labels: ☢️ Bug

#7799 fix: memtable persist conflict
  src/ingester/src/immutable.rs
Labels: ☢️ Bug

#7795 fix: tantivy histogram interval
  src/service/search/sql.rs
Labels: ☢️ Bug, Review effort 2/5
