Repository openobserve/openobserve, pull requests merged in 2025-03, with the labels that each got.

#6140 fix: dashboard invalid sql for custom sql regex change
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#6138 fix: fields missing issue
  src/config/src/utils/flatten.rs
  src/job/compactor.rs
  src/job/files/parquet.rs
  src/service/db/file_list/broadcast.rs
Labels: ☢️ Bug

#6141 fix: send trigger data to additional orgs
  src/config/src/config.rs
  src/service/self_reporting/queues.rs
Labels: ☢️ Bug, ✏️ Feature

#6142 feat: remove configure ZO_USAGE_ORG
  src/config/src/config.rs
  src/config/src/ider.rs
  src/config/src/lib.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/status/mod.rs
  src/infra/src/dist_lock.rs
  src/job/mod.rs
  src/job/promql.rs
  src/job/promql_self_consume.rs
  src/job/syslog_server.rs
  src/job/telemetry.rs
  src/lib.rs
  src/main.rs
  src/service/folders.rs
  src/service/functions.rs
  src/service/grpc.rs
  src/service/kv.rs
  src/service/organization.rs
  src/service/search/grpc_search.rs
  src/service/search/request.rs
  src/service/search_jobs.rs
  src/service/self_reporting/ingestion.rs
  src/service/self_reporting/mod.rs
  src/service/self_reporting/queues.rs
  src/service/session.rs
  src/service/short_url.rs
  src/service/stream.rs
  src/service/syslogs_route.rs
  src/service/users.rs
  tests/integration_test.rs
Labels: 🧹 Updates, ✏️ Feature

#6143 fix: Enhance compactor metrics
  src/job/compactor.rs
Labels: ☢️ Bug

#6144 fix: dashboard invalid sql for custom sql regex change
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#6121 feat: Scheduler redesign with mpsc channels
  src/infra/src/scheduler/mod.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/job/alert_manager.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/alerts/scheduler/mod.rs
  src/service/alerts/scheduler/worker.rs
  src/service/db/scheduler.rs
  src/super_cluster_queue/mod.rs
  src/super_cluster_queue/scheduler.rs
  tests/integration_test.rs
Labels: ✏️ Feature

#6003 feat: upgrade datafusion to v44.0.0
  Cargo.lock
  Cargo.toml
  src/common/utils/auth_tests.rs
  src/config/src/meta/sql.rs
  src/service/search/datafusion/distributed_plan/empty_exec.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/datafusion/distributed_plan/streaming_aggs_exec.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/optimizer/add_timestamp.rs
  src/service/search/datafusion/optimizer/join_reorder.rs
  src/service/search/datafusion/optimizer/limit_join_right_side.rs
  src/service/search/datafusion/optimizer/rewrite_match.rs
  src/service/search/datafusion/plan/deduplication_exec.rs
  src/service/search/datafusion/plan/tantivy_count_exec.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#6146 feat: update to datafusion 45
  Cargo.lock
  Cargo.toml
  src/config/Cargo.toml
  src/config/src/meta/sql.rs
  src/service/logs/syslog.rs
  src/service/search/datafusion/optimizer/add_timestamp.rs
  src/service/search/datafusion/optimizer/join_reorder.rs
  src/service/search/datafusion/udf/regexp_udf.rs
Labels: 🧹 Updates, ✏️ Feature

#6148 fix: reduce query time and silence column removal
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#6157 fix: ws malformed data
  src/handler/http/request/websocket/session.rs
  src/router/http/ws.rs
Labels: ☢️ Bug

#6159 fix: ws malformed data (#6157)
  src/handler/http/request/websocket/session.rs
  src/router/http/ws.rs
Labels: ☢️ Bug

#6147 fix: scheduled pipeline don't pause after retries
  src/config/src/config.rs
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/self_reporting/usage.rs
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/PipelinesList.vue
Labels: ☢️ Bug

#6160 feat: improve router scheduler with weight 2/2
  Cargo.lock
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/scheduler.rs
  src/router/http/mod.rs
Labels: 🧹 Updates, ✏️ Feature

#6162 fix: Fix query in V2 `ListAlerts`
  src/infra/src/table/alerts/mod.rs
Labels: ☢️ Bug

#6164 fix: ws open fds at router
  src/router/http/ws.rs
Labels: ☢️ Bug

#6163 fix: ws open fds at router
  src/router/http/ws.rs
Labels: ☢️ Bug

#6156 fix: handle incomplete files during download
  src/config/src/utils/async_file.rs
  src/config/src/utils/file.rs
  src/handler/http/router/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/errors/mod.rs
  src/router/http/ws.rs
  src/service/alerts/mod.rs
Labels: ☢️ Bug

#6082 fix: parallel download
  .github/workflows/cargo-deny.yml
  src/config/src/config.rs
  src/job/file_downloader.rs
  src/job/mod.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#6174 fix: scheduled pipeline don't pause after retries
  src/config/src/meta/alerts/mod.rs
  src/config/src/meta/self_reporting/usage.rs
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/traces/mod.rs
Labels: ☢️ Bug

#6165 feat: Bulk move dashboards endpoint
  src/handler/http/models/dashboards.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/service/dashboards/mod.rs
Labels: ✏️ Feature

#6167 feat: improve remote pipeline
  src/service/pipeline/batch_execution.rs
Labels: 🧹 Updates, ✏️ Feature

#6172 fix: dashboard variable value replacement if no data is found in values
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6177 feat: remove stream level metrics
  Cargo.lock
  Cargo.toml
  src/common/utils/auth_tests.rs
  src/config/Cargo.toml
  src/config/src/config.rs
  src/config/src/lib.rs
  src/config/src/metrics.rs
  src/handler/grpc/flight/mod.rs
  src/handler/grpc/request/event.rs
  src/handler/grpc/request/ingest.rs
  src/handler/grpc/request/logs.rs
  src/handler/grpc/request/metrics/ingester.rs
  src/handler/grpc/request/metrics/querier.rs
  src/handler/grpc/request/traces.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/status/mod.rs
  src/handler/http/request/traces/mod.rs
  src/handler/http/router/mod.rs
  src/infra/src/db/nats.rs
  src/infra/src/schema/mod.rs
  src/job/metrics.rs
  src/job/promql_self_consume.rs
  src/job/stats.rs
  src/main.rs
  src/service/db/schema.rs
  src/service/enrichment_table/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/metrics/json.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/service/search/cache/mod.rs
  src/service/self_reporting/mod.rs
  src/service/stream.rs
  src/service/traces/mod.rs
Labels: 🧹 Updates, ✏️ Feature

#6178 fix: use schema fields for uds
  src/service/schema.rs
Labels: ☢️ Bug

#6182 fix: #6170
  src/job/metrics.rs
  src/service/search/sql.rs
  src/service/search/utils.rs
Labels: ☢️ Bug

#6161 feat: support multiple y axis for stacked chart
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/composables/useDashboardPanel.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ✏️ Feature

#6180 fix: use established schema fields when setting up uds
  src/service/schema.rs
Labels: ☢️ Bug

#6192 feat: Global default max query range
  src/common/utils/stream.rs
  src/config/src/config.rs
Labels: ✏️ Feature

#6184 test: dashboard timeout testcases
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.utils.js
  tests/ui-testing/playwright-tests/dashboards/dashboard2.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboardtype.spec.js
Labels: ☢️ Bug, 🧹 Updates

#6207 fix: check for root user even if org_id is provided in db::user::get
  src/service/db/user.rs
Labels: ☢️ Bug

#6209 fix: search type issue for reports
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#6208 fix: ignore count field from user stream for distinct values
  .cargo/audit.toml
  src/common/migration/dashboards.rs
  src/handler/http/request/search/mod.rs
  src/job/files/parquet.rs
  src/service/dashboards/mod.rs
  src/service/metadata/distinct_values.rs
  src/service/stream.rs
Labels: ☢️ Bug

#6200 feat: improve search around
  src/cli/data/export.rs
  src/common/utils/auth.rs
  src/common/utils/http.rs
  src/config/src/config.rs
  src/handler/http/request/alerts/deprecated.rs
  src/handler/http/request/dashboards/mod.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/search/search_job.rs
  src/handler/http/request/stream/mod.rs
  src/handler/http/router/mod.rs
  src/handler/http/router/openapi.rs
  src/router/http/mod.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/sql.rs
  src/service/search/utils.rs
  web/src/composables/useLogs.ts
  web/src/plugins/logs/DetailTable.vue
  web/src/services/search.ts
Labels: 🧹 Updates, ✏️ Feature

#6166 feat: add stream pagination
  Cargo.lock
  src/common/meta/stream.rs
  src/handler/http/request/stream/mod.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/service/stream.rs
  web/src/composables/useStreams.ts
  web/src/services/stream.ts
  web/src/views/LogStream.vue
Labels: ✏️ Feature

#6215 feat: use local node for load enrichmentable
  .cargo/audit.toml
  src/cli/data/export.rs
  src/config/src/config.rs
  src/config/src/meta/cluster.rs
  src/config/src/meta/search.rs
  src/handler/http/request/search/around.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/traces/mod.rs
  src/proto/proto/cluster/plan.proto
  src/proto/src/generated/cluster.rs
  src/service/alerts/mod.rs
  src/service/db/enrichment_table.rs
  src/service/metrics/prom.rs
  src/service/search/cluster/flight.rs
  src/service/search/datafusion/distributed_plan/node.rs
  src/service/search/datafusion/distributed_plan/remote_scan.rs
  src/service/search/mod.rs
  src/service/search/request.rs
  src/service/search/super_cluster/follower.rs
Labels: ✏️ Feature

#5897 feat: Import alert feature
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/AlertsDestinationList.vue
  web/src/components/alerts/ImportAlert.vue
  web/src/components/alerts/ImportDestination.vue
  web/src/components/alerts/ImportTemplate.vue
  web/src/components/alerts/TemplateList.vue
  web/src/components/settings/index.vue
Labels: ✏️ Feature

#6188 fix: pipeline query node improvements
  web/src/components/alerts/PipelinesDestinationList.vue
  web/src/components/common/sidebar/FieldList.vue
  web/src/components/functions/EnrichmentTableList.vue
  web/src/components/functions/FullViewContainer.vue
  web/src/components/functions/FunctionList.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
  web/src/components/pipeline/PipelineEditor.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/locales/languages/en.json
  web/src/plugins/pipelines/CustomNode.vue
Labels: ☢️ Bug, 🧹 Updates

#6211 fix: Dashboard folders improvements
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug, 🧹 Updates

#6236 fix: cherry pick perf related changed from main
  src/config/src/config.rs
  src/job/file_downloader.rs
  src/job/mod.rs
  src/service/search/grpc/storage.rs
Labels: ☢️ Bug

#6241 fix: cluster info in values api.
  web/src/plugins/logs/IndexList.vue
Labels: ☢️ Bug

#6242 fix: dashboards folder search extra padding removed
  web/src/views/Dashboards/Dashboards.vue
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6237 feat: report node config over super cluster
  src/common/infra/cluster/mod.rs
  src/common/meta/organization.rs
  src/config/src/meta/cluster.rs
  src/handler/http/request/organization/org.rs
  src/handler/http/router/mod.rs
  src/main.rs
  src/proto/build.rs
  src/proto/proto/cluster/node.proto
  src/proto/src/generated/cluster.rs
  src/service/grpc.rs
  src/service/mod.rs
  src/service/node.rs
Labels: ✏️ Feature

#6249 fix: NATS list value error for edge case
  Cargo.lock
  Cargo.toml
  src/infra/src/db/nats.rs
  src/infra/src/queue/nats.rs
  src/ingester/src/partition.rs
Labels: ☢️ Bug

#6246 fix: splitter limit in management page
  web/src/components/settings/index.vue
Labels: ☢️ Bug

#6193 feat: dashboard set show_symbol bydefault as true
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#6197 fix: search type to lowercase
  src/config/src/meta/self_reporting/usage.rs
  src/handler/http/request/pipeline.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/self_reporting/ingestion.rs
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  web/src/components/pipeline/NodeForm/PreviewPromqlQuery.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/queries/RunningQueries.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/plugins/logs/JsonPreview.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/traces/Index.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/services/search.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
  web/src/views/StreamExplorer.vue
Labels: ☢️ Bug

#6260 fix: first page pagination offset fix
  web/src/views/LogStream.vue
Labels: ☢️ Bug

#6261 fix: unflattened data expand in logs page fixed
  web/src/composables/useLogs.ts
  web/src/plugins/logs/JsonPreview.vue
Labels: ☢️ Bug

#6262 fix: Alert table changes
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug

#6267 feat: add `zo_node_open_fds` & `zo_node_tcp_conn_resets` metrics
  src/common/infra/cluster/mod.rs
  src/common/infra/cluster/nats.rs
  src/common/infra/cluster/scheduler.rs
  src/config/src/metrics.rs
  src/config/src/utils/sysinfo/mod.rs
  src/config/src/utils/sysinfo/net.rs
  src/config/src/utils/sysinfo/os.rs
  src/proto/proto/cluster/node.proto
  src/proto/src/generated/cluster.rs
  src/service/node.rs
Labels: ✏️ Feature

#6271 fix: check base64 parts for camelCase tokenizer
  src/config/src/utils/tantivy/tokenizer/mod.rs
  src/config/src/utils/tantivy/tokenizer/o2_tokenizer.rs
  src/service/compact/merge.rs
Labels: ☢️ Bug

#6272 fix: handle timestamp after pipeline processing
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/syslog.rs
  src/service/pipeline/batch_execution.rs
Labels: ☢️ Bug

#6020 fix: table chart when dashboard drilldown to logs page, having custom selected passing value of selected row
  web/src/components/dashboards/PanelSchemaRenderer.vue
Labels: ☢️ Bug

#6226 feat: dashboard `JSON` schema editor
  web/src/composables/useDashboardPanel.ts
  web/src/locales/languages/en.json
  web/src/utils/dashboard/convertDashboardSchemaVersion.ts
  web/src/utils/dashboard/convertDataIntoUnitValue.ts
  web/src/views/Dashboards/DashboardJsonEditor.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ✏️ Feature

#6284 test: dashboard filter testcases
  .github/workflows/playwright.yml
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
  tests/ui-testing/playwright-tests/dashboards/dashboard.spec.js
  tests/ui-testing/playwright-tests/utils/dashCreation.js
  tests/ui-testing/playwright-tests/utils/dashIngestion.js
  tests/ui-testing/playwright-tests/utils/dashLogin.js
Labels: 🧹 Updates

#6183 feat: dashboard variables support in html markdown
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/addPanel/CustomHTMLEditor.vue
  web/src/components/dashboards/addPanel/CustomMarkdownEditor.vue
  web/src/components/dashboards/panels/HTMLRenderer.vue
  web/src/components/dashboards/panels/MarkdownRenderer.vue
  web/src/utils/dashboard/variables/variablesUtils.ts
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ✏️ Feature

#6264 fix: replace * in alert and report cron expression with the now second
  src/service/alerts/alert.rs
  src/service/alerts/derived_streams.rs
  src/service/alerts/mod.rs
  src/service/dashboards/reports.rs
Labels: ☢️ Bug

#6286 test: dashboard filters remove failed test case
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
Labels: 🧹 Updates

#6287 fix: Alert list table changes
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug

#6018 feat: Add temporary catch-all logic for dashboard super cluster message variants
  src/super_cluster_queue/dashboards.rs
Labels: ✏️ Feature

#6034 feat: Use new error types to model service layer errors for reports
  src/handler/http/request/dashboards/reports.rs
  src/service/dashboards/reports.rs
Labels: ✏️ Feature

#6175 feat: download raw data as csv/json for dashboard panel
  web/src/components/dashboards/PanelContainer.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/TableRenderer.vue
Labels: ✏️ Feature

#6291 fix: enhance error log for parquet error
  .cargo/audit.toml
  Cargo.lock
  Cargo.toml
  src/infra/src/storage/local.rs
  src/infra/src/storage/remote.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/datafusion/table_provider/parquet_reader.rs
Labels: ☢️ Bug

#6252 feat: dashboard havingCondition for aggregation fields
  src/config/src/meta/dashboards/v5/mod.rs
  web/src/components/dashboards/addPanel/DashboardGeoMapsQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardMapsQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardQueryBuilder.vue
  web/src/components/dashboards/addPanel/DashboardSankeyChartBuilder.vue
  web/src/composables/useDashboardPanel.ts
Labels: ✏️ Feature

#6293 fix: changes to tracing
  src/main.rs
Labels: ☢️ Bug

#6297 fix: disable query cache if disk_cache is disabled
  src/config/src/config.rs
  src/service/promql/search/cache/mod.rs
Labels: ☢️ Bug

#6129 feat: Actions in Logs and Alert Destinations
  src/handler/http/request/status/mod.rs
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/sanity2.spec.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
  web/src/assets/images/common/transform.svg
  web/src/components/actionScripts/ActionScipts.vue
  web/src/components/actionScripts/EditScript.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/functions/TestFunction.vue
  web/src/components/pipeline/NodeForm/ExternalDestination.vue
  web/src/composables/useActions.ts
  web/src/composables/useLogs.ts
  web/src/composables/useSearchWebSocket.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/logs/FunctionSelector.vue
  web/src/plugins/logs/Index.vue
  web/src/plugins/logs/IndexList.vue
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/TransformSelector.vue
  web/src/services/search.ts
  web/src/services/stream.ts
  web/src/stores/index.ts
  web/src/ts/interfaces/alert.ts
  web/src/ts/interfaces/query.ts
Labels: ✏️ Feature

#6300 feat: exact limit from SQL when the query limit is known
  src/config/src/meta/search.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
Labels: ✏️ Feature

#6295 fix: remove semaphore in alert manager
  src/common/utils/auth.rs
  src/config/src/meta/self_reporting/usage.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/alerts/scheduler/mod.rs
  src/service/alerts/scheduler/worker.rs
  src/service/ingestion/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#6304 fix: playwrite test selecting quick mode
  tests/ui-testing/pages/logsPage.js
Labels: ☢️ Bug, 🧹 Updates

#6305 fix: fixed histogram toggle playwright test
  tests/ui-testing/pages/logsPage.js
Labels: ☢️ Bug, 🧹 Updates

#6299 fix: _original in pipeline query
  src/config/src/ider.rs
  src/handler/http/request/websocket/search.rs
  src/service/db/enrichment_table.rs
  src/service/enrichment_table/mod.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/mod.rs
  src/service/search/sql.rs
  src/service/stream.rs
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
Labels: ☢️ Bug

#6303 fix: pipeline query node validation issue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
Labels: ☢️ Bug

#6309 fix: caching pipeline after enrichment_table is cached
  src/job/mod.rs
  src/main.rs
Labels: ☢️ Bug

#6302 fix: alert v2 cache
  src/common/infra/ofga/migrations/alert_folders.rs
  src/common/infra/ofga/migrations/mod.rs
  src/common/infra/ofga/mod.rs
  src/common/utils/auth.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/dashboards/mod.rs
  src/infra/src/cluster_coordinator/alerts.rs
  src/service/alerts/alert.rs
  src/service/db/alerts/alert.rs
  src/service/search/cluster/flight.rs
  src/super_cluster_queue/alerts.rs
Labels: ☢️ Bug

#6312 fix: Partial error fix main
  src/config/src/meta/search.rs
  src/handler/http/request/search/multi_streams.rs
  src/handler/http/request/websocket/search.rs
  src/service/alerts/mod.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/http.rs
  src/service/search/mod.rs
  src/service/search_jobs.rs
Labels: ☢️ Bug

#6318 fix: alert and pipeline frequency warning message change
  web/src/components/alerts/ScheduledAlert.vue
  web/src/components/pipeline/NodeForm/Query.vue
  web/src/components/pipeline/NodeForm/ScheduledPipeline.vue
Labels: ☢️ Bug

#6327 fix: cancel init cache stat
  src/job/mod.rs
Labels: ☢️ Bug

#6329 fix: when pipeline reaches max retries by watch_timeout, skip to next run
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#6316 fix: histogram stream sync
  src/common/infra/ofga/migrations/alert_folders.rs
  src/common/infra/ofga/mod.rs
  src/job/stats.rs
  src/service/db/ofga.rs
  src/service/metrics/otlp.rs
  src/service/metrics/prom.rs
  src/super_cluster_queue/alerts.rs
Labels: ☢️ Bug

#6334 fix: with query fields validation issue
  web/src/composables/useDashboardPanel.ts
Labels: ☢️ Bug

#6336 fix: allow patch requests on router
  src/router/http/mod.rs
Labels: ☢️ Bug

#6339 fix: ofga version compare
  src/common/infra/ofga/mod.rs
Labels: ☢️ Bug

#6325 fix: Actions UI issues
  src/config/src/meta/destinations.rs
  src/handler/http/models/destinations.rs
  web/src/components/actionScripts/EditScript.vue
  web/src/components/alerts/AlertsDestinationList.vue
  web/src/components/alerts/ImportDestination.vue
  web/src/components/functions/TestFunction.vue
  web/src/composables/shared/useEnterpriseRoutes.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug

#6338 fix: Alert folder rbac migration issues
  src/common/infra/ofga/mod.rs
  src/common/utils/auth.rs
  src/handler/http/auth/token.rs
  src/handler/http/auth/validator.rs
  src/service/alerts/alert.rs
  src/service/folders.rs
Labels: ☢️ Bug

#6342 fix: added errors when actions are not enabled while creating destination
  web/src/components/actionScripts/ActionScipts.vue
  web/src/components/alerts/AddDestination.vue
  web/src/components/alerts/ImportDestination.vue
  web/src/composables/useActions.ts
  web/src/layouts/MainLayout.vue
  web/src/locales/languages/en.json
  web/src/plugins/traces/TraceDetails.vue
Labels: ☢️ Bug, ✏️ Feature

#6343 fix: when dashboard owner not present in creation payload, use currently logged in user
  src/config/src/meta/dashboards/mod.rs
  src/handler/http/request/dashboards/mod.rs
Labels: ☢️ Bug

#6344 fix: dashboard breakdown value not present chart not getting plot
  web/src/components/dashboards/addPanel/ConfigPanel.vue
  web/src/components/dashboards/addPanel/DrilldownPopUp.vue
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#6350 fix: dashboard variables dependency not working properly
  web/src/components/dashboards/VariablesValueSelector.vue
Labels: ☢️ Bug

#6352 fix: alert move rbac issues
  src/common/utils/auth.rs
  src/handler/http/request/actions/action.rs
  src/handler/http/request/actions/operations.rs
  src/handler/http/request/alerts/mod.rs
  src/handler/http/request/service_accounts/mod.rs
  src/handler/http/request/users/mod.rs
  src/service/alerts/alert.rs
  src/service/folders.rs
  src/service/users.rs
Labels: ☢️ Bug

#6356 ci: update object_store
  Cargo.lock
  Cargo.toml
Labels: 🧹 Updates

#6228 feat: alerts folder implementation (UI)
  src/service/alerts/mod.rs
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/ImportAlert.vue
  web/src/components/common/sidebar/AddFolder.vue
  web/src/components/common/sidebar/FolderList.vue
  web/src/components/common/sidebar/MoveAcrossFolders.vue
  web/src/components/common/sidebar/SelectFolderDropDown.vue
  web/src/components/iam/roles/EditRole.vue
  web/src/components/iam/roles/PermissionsTable.vue
  web/src/locales/languages/en.json
  web/src/services/alerts.ts
  web/src/services/common.ts
  web/src/stores/index.ts
  web/src/utils/commons.ts
  web/src/views/Dashboards/Dashboards.vue
Labels: ✏️ Feature

#6348 fix: dashboard empty error issue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/viewPanel/ViewPanel.vue
  web/src/plugins/metrics/Index.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#6358 feat: support db replicas
  src/common/utils/auth_tests.rs
  src/config/src/config.rs
  src/infra/src/db/mysql.rs
  src/infra/src/db/postgres.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/pipeline/mysql.rs
  src/infra/src/pipeline/postgres.rs
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
Labels: ✏️ Feature

#6361 fix: disable add stream & add field when user doesn't enable UDS
  src/service/stream.rs
  web/src/components/logstream/AddStream.vue
  web/src/components/logstream/schema.vue
  web/src/views/LogStream.vue
Labels: ☢️ Bug, ✏️ Feature

#6364 fix: dashboard panel name and folder text changes
  web/src/views/Dashboards/Dashboards.vue
  web/src/views/Dashboards/addPanel/AddPanel.vue
Labels: ☢️ Bug

#6362 fix: changes for icon bar in logs page
  tests/ui-testing/pages/logsPage.js
  tests/ui-testing/pages/unflattened.js
  tests/ui-testing/playwright-tests/dashboards/visualization-vrl.spec.js
  tests/ui-testing/playwright-tests/dashboards/visualize.spec.js
  tests/ui-testing/playwright-tests/logspage.spec.js
  tests/ui-testing/playwright-tests/logsqueries.spec.js
  tests/ui-testing/playwright-tests/logsquickmode.spec.js
  tests/ui-testing/playwright-tests/multiselect-stream.spec.js
  tests/ui-testing/playwright-tests/sanity.spec.js
  tests/ui-testing/playwright-tests/sanity2.spec.js
  tests/ui-testing/playwright-tests/unflattened.spec.js
  web/src/assets/images/common/bar_chart_histogram.svg
  web/src/assets/images/common/bar_chart_histogram_light.svg
  web/src/assets/images/common/create_scheduled_search.svg
  web/src/assets/images/common/create_scheduled_search_light.svg
  web/src/assets/images/common/custom_range.svg
  web/src/assets/images/common/custom_range_light.svg
  web/src/assets/images/common/download_table.svg
  web/src/assets/images/common/download_table_light.svg
  web/src/assets/images/common/histogram_image.svg
  web/src/assets/images/common/hugeicons_sql.svg
  web/src/assets/images/common/hugeicons_sql_light.svg
  web/src/assets/images/common/list_scheduled_search.svg
  web/src/assets/images/common/list_scheduled_search_light.svg
  web/src/assets/images/common/quick_mode.svg
  web/src/assets/images/common/quick_mode_light.svg
  web/src/assets/images/common/search_history.svg
  web/src/assets/images/common/search_history_light.svg
  web/src/assets/images/common/visualize_icon_dark.svg
  web/src/assets/images/common/visualize_icon_light.svg
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
Labels: ☢️ Bug

#6366 fix: dashboard error message getting removed
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, 🧹 Updates

#6355 fix: triggers stream error field should contain message when status is failed
  src/service/alerts/mod.rs
  src/service/alerts/scheduler/handlers.rs
Labels: ☢️ Bug

#6346 fix: previous histogram getting display even after there is no data
  tests/ui-testing/playwright-tests/sanity.spec.js
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#6371 fix: added tooltip for all icons in icon bar
  web/src/locales/languages/en.json
  web/src/plugins/logs/SearchBar.vue
  web/src/plugins/logs/SyntaxGuide.vue
Labels: ☢️ Bug, ✏️ Feature

#6372 fix: Actions UI improvements
  web/src/components/actionScripts/EditScript.vue
  web/src/composables/useLogs.ts
  web/src/locales/languages/en.json
Labels: ☢️ Bug, 🧹 Updates

#6365 fix: Migration for scheduled_jobs table to use alert id as module_key
  src/common/infra/config.rs
  src/common/meta/telemetry.rs
  src/config/src/meta/alerts/alert.rs
  src/handler/http/models/alerts/responses.rs
  src/handler/http/request/alerts/mod.rs
  src/infra/src/cluster_coordinator/alerts.rs
  src/infra/src/table/migration/m20250109_092400_recreate_tables_with_ksuids.rs
  src/infra/src/table/migration/m20250320_000001_remove_alert_name_unique_constraint.rs
  src/infra/src/table/migration/mod.rs
  src/service/alerts/alert.rs
  src/service/alerts/destinations.rs
  src/service/alerts/scheduler/handlers.rs
  src/service/db/alerts/alert.rs
  src/service/db/alerts/realtime_triggers.rs
  src/service/ingestion/mod.rs
  src/service/logs/mod.rs
  src/service/traces/mod.rs
  src/super_cluster_queue/alerts.rs
  src/super_cluster_queue/scheduler.rs
  tests/integration_test.rs
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug

#6376 fix: nobody can update root except root user
  src/service/users.rs
Labels: ☢️ Bug, 🧹 Updates

#6377 chore: remove unnecessary logging
  src/infra/src/pipeline/mysql.rs
  src/infra/src/pipeline/postgres.rs
  src/infra/src/pipeline/sqlite.rs
  src/service/alerts/destinations.rs
Labels: 🧹 Updates

#6379 fix: `m20250320_000001_remove_alert_name_unique_constraint` migration
  src/infra/src/table/migration/m20250320_000001_remove_alert_name_unique_constraint.rs
Labels: ☢️ Bug, 🧹 Updates

#6378 fix: pending delete on single node
  .cargo/audit.toml
  Cargo.lock
  src/ingester/src/lib.rs
  src/service/compact/deleted.rs
  src/service/compact/retention.rs
  src/service/db/file_list/local.rs
  src/service/file_list.rs
  src/service/search/datafusion/optimizer/utils.rs
Labels: ☢️ Bug

#6382 fix: add unit test for is_wal_file
  src/config/src/utils/schema_ext.rs
  src/ingester/src/lib.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6374 fix: Updated actions execution type label
  web/src/components/actionScripts/ActionScipts.vue
Labels: ☢️ Bug, 🧹 Updates

#6385 fix: passing variables of dashboard drilldown to same dashboard
  web/src/components/dashboards/VariablesValueSelector.vue
  web/src/views/Dashboards/RenderDashboardCharts.vue
  web/src/views/Dashboards/ViewDashboard.vue
Labels: ☢️ Bug

#6387 feat: add variables for trigger time in seconds, millis for alert template
  src/service/alerts/alert.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ✏️ Feature

#6389 fix: Action as a destination input format
  src/service/alerts/alert.rs
Labels: ☢️ Bug

#6388 fix: alert enable or disable is not updated in the UI when filter applied
  web/src/components/alerts/AlertList.vue
Labels: ☢️ Bug, 🧹 Updates

#6390 fix: UI changes on datasource page
  web/src/components/ingestion/languages/Python.vue
  web/src/components/ingestion/recommended/AWSConfig.vue
  web/src/components/ingestion/recommended/AzureConfig.vue
  web/src/components/ingestion/recommended/GCPConfig.vue
  web/src/components/ingestion/recommended/LinuxConfig.vue
Labels: ☢️ Bug

#6400 fix: escape control characters in templates
  src/service/alerts/alert.rs
Labels: ☢️ Bug, 🧹 Updates, ✏️ Feature

#6395 fix: pipeline dynamic stream
  src/config/src/meta/pipeline/mod.rs
  src/service/alerts/alert.rs
  src/service/ingestion/mod.rs
  src/service/logs/bulk.rs
  src/service/logs/ingest.rs
  src/service/logs/otlp_grpc.rs
  src/service/logs/otlp_http.rs
  src/service/logs/syslog.rs
  src/service/pipeline/batch_execution.rs
Labels: ☢️ Bug

#6406 fix: remove clean_complete job in scheduler
  src/infra/src/scheduler/mysql.rs
  src/infra/src/scheduler/postgres.rs
  src/infra/src/scheduler/sqlite.rs
  src/job/alert_manager.rs
  src/service/alerts/derived_streams.rs
  src/service/pipeline/mod.rs
Labels: ☢️ Bug, 🧹 Updates

#6408 fix: fixed reset pagecount search on error in web-socket
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#6398 fix: alerts folders UI improvements
  src/handler/http/models/alerts/responses.rs
  web/src/components/alerts/AlertList.vue
  web/src/components/alerts/ImportAlert.vue
  web/src/components/common/sidebar/SelectFolderDropDown.vue
  web/src/locales/languages/en.json
Labels: ☢️ Bug, 🧹 Updates

#6409 fix: service account search range restriction
  src/common/utils/stream.rs
Labels: ☢️ Bug

#6410 fix: value api for enrichment table
  src/handler/http/request/search/mod.rs
Labels: ☢️ Bug

#6411 feat: add variables for trigger time in seconds, millis for alert template
  src/service/alerts/alert.rs
  web/src/components/alerts/AddTemplate.vue
Labels: ✏️ Feature

#6399 test(dashboards): add import test cases
  .github/workflows/playwright.yml
  tests/test-data/dashboard1-import.json
  tests/test-data/dashboard2-import.json
  tests/test-data/dashboardAzure.json
  tests/test-data/dashboardV3-import.json
  tests/test-data/dashboards-import.json
  tests/ui-testing/playwright-tests/dashboards/dashboard-import.spec.js
Labels: 🧹 Updates, ✏️ Feature

#6414 fix: router incorrectly route routes to querier
  src/router/http/mod.rs
Labels: ☢️ Bug

#6418 feat: add a span when FlightSenderStream drop
  src/handler/grpc/flight/mod.rs
Labels: ✏️ Feature

#6421 fix: dashboard color option changed based on theme
  web/src/components/dashboards/addPanel/ColorPaletteDropDown.vue
  web/src/utils/dashboard/colorPalette.ts
  web/src/utils/dashboard/convertPromQLData.ts
  web/src/utils/dashboard/convertSQLData.ts
Labels: ☢️ Bug

#6393 feat: add new feature to disable compression for parquet on ingester
  .gitignore
  Cargo.toml
  src/cli/basic/cli.rs
  src/cli/basic/http.rs
  src/cli/basic/mod.rs
  src/cli/basic/test.rs
  src/config/src/config.rs
  src/config/src/meta/stream.rs
  src/config/src/utils/parquet.rs
  src/infra/src/cache/file_data/disk.rs
  src/infra/src/cache/file_data/memory.rs
  src/infra/src/file_list/mod.rs
  src/infra/src/file_list/mysql.rs
  src/infra/src/file_list/postgres.rs
  src/infra/src/file_list/sqlite.rs
  src/ingester/src/partition.rs
  src/job/files/idx.rs
  src/job/files/parquet.rs
  src/service/compact/merge.rs
  src/service/compact/mod.rs
  src/service/compact/worker.rs
  src/service/db/file_list/mod.rs
  src/service/promql/search/grpc/storage.rs
  src/service/search/datafusion/exec.rs
  src/service/search/datafusion/table_provider/mod.rs
  src/service/search/grpc/storage.rs
  src/service/search/grpc/wal.rs
Labels: ✏️ Feature

#6422 fix: let the scheduled only work for ingestion
  src/common/infra/cluster/mod.rs
  src/router/http/mod.rs
  src/service/grpc.rs
Labels: ☢️ Bug

#6424 fix: ui fixed for datasources page
  web/src/components/ingestion/languages/Python.vue
  web/src/components/ingestion/recommended/AWSConfig.vue
  web/src/components/ingestion/recommended/GCPConfig.vue
Labels: ☢️ Bug

#6423 feat: add separate ingestion url
  src/config/src/config.rs
  src/handler/http/request/status/mod.rs
  web/src/stores/index.ts
Labels: ✏️ Feature

#6419 fix: histogram issue
  web/src/composables/useLogs.ts
  web/src/plugins/logs/SearchResult.vue
Labels: ☢️ Bug

#6427 feat: nodes page implementation
  web/src/components/settings/Nodes.vue
  web/src/components/settings/index.vue
  web/src/composables/shared/useManagementRoutes.ts
  web/src/locales/languages/en.json
  web/src/services/common.ts
Labels: ✏️ Feature

#6433 test: root and admin search automation using pytest
  tests/api-testing/tests/create_objects.py
  tests/api-testing/tests/pages/search_page.py
Labels: 🧹 Updates

#6430 fix: ws session drain
  src/config/src/config.rs
  src/handler/http/request/ws_v2/mod.rs
  src/router/http/ws_v2/error.rs
  src/router/http/ws_v2/handler.rs
  src/router/http/ws_v2/session.rs
  web/src/composables/dashboard/usePanelDataLoader.ts
  web/src/composables/useLogs.ts
  web/src/composables/useSearchWebSocket.ts
  web/src/composables/useWebSocket.ts
Labels: ☢️ Bug
