Repository openobserve/openobserve, pull requests merged in 2025-10, with the labels that each got.

#8700 feat: create alert from dashboard
  web/src/components/alerts/AddAlert.vue
  web/src/components/alerts/AlertList.vue
  web/src/components/dashboards/PanelContainer.vue
  web/src/composables/shared/router.ts
  web/src/locales/languages/en.json
  web/src/views/AddAlertView.vue
Labels: ✏️ Feature, Review effort 3/5

#8695 feat: pipeline errors on ui
  src/config/src/config.rs
  src/handler/http/models/pipelines.rs
  src/handler/http/request/pipeline.rs
  src/infra/src/table/entity/mod.rs
  src/infra/src/table/entity/pipeline_last_errors.rs
  src/infra/src/table/entity/prelude.rs
  src/infra/src/table/migration/m20250930_000001_create_pipeline_last_errors_table.rs
  src/infra/src/table/migration/mod.rs
  src/service/db/mod.rs
  src/service/db/pipeline_errors.rs
  src/service/ingestion/mod.rs
  src/service/self_reporting/mod.rs
  src/service/self_reporting/queues.rs
  web/src/components/pipeline/PipelineView.vue
  web/src/components/pipeline/PipelinesList.vue
  web/src/plugins/pipelines/CustomNode.vue
Labels: ✏️ Feature, Review effort 3/5

#8705 fix: pipeline_last_errors existing index issue
  src/infra/src/table/migration/m20250930_000001_create_pipeline_last_errors_table.rs
Labels: ☢️ Bug, Review effort 1/5

#8704 fix: home page minor changes
  web/src/assets/images/home/dashboards_tile_icon.svg
  web/src/assets/images/home/forward_dark.svg
  web/src/assets/images/home/forward_light.svg
  web/src/assets/images/home/function_tile_icon.svg
  web/src/assets/images/home/function_tile_icon_dark.svg
  web/src/components/shared/HomeViewSkeleton.vue
  web/src/components/shared/SkeletonBox.vue
  web/src/views/HomeView.vue
Labels: ☢️ Bug, Review effort 3/5

#8702 fix: skip query limit error only for ui
  src/common/meta/search.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_stream.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/cluster/http.rs
  src/service/search/super_cluster/leader.rs
  src/service/search/utils.rs
  web/src/composables/useLogs.ts
  web/src/utils/query/sqlUtils.ts
Labels: ☢️ Bug

#8691 fix: add aws-lc-rs feature to lettre to avoid smtp client initialization error
  Cargo.lock
  Cargo.toml
Labels: ☢️ Bug, ✏️ Feature, Review effort 1/5

#8667 fix: new import path
  src/service/search/datafusion/distributed_plan/codec/aggregate_topk_exec.rs
  src/service/search/datafusion/distributed_plan/codec/physical_plan_node.rs
Labels: ☢️ Bug, Review effort 2/5

#8715 fix: add retry for enrichment table failure
  src/service/db/enrichment_table.rs
  src/service/enrichment/mod.rs
Labels: ☢️ Bug, ✏️ Feature

#8712 fix: histogram total count was getting set as 0 in case of streaming aggs
  src/service/search/cache/mod.rs
  src/service/search/cluster/flight.rs
  src/service/search/search_stream.rs
  tests/ui-testing/playwright-tests/pipelines.spec.js
  web/src/composables/useLogs.ts
Labels: ☢️ Bug

#8719 fix: menu item + home page ux changes
  web/src/components/MenuLink.vue
  web/src/layouts/MainLayout.vue
  web/src/styles/_menu-animations.scss
  web/src/styles/_menu-variables.scss
  web/src/views/HomeView.vue
Labels: ☢️ Bug, Review effort 4/5

#8711 fix: alerts with threshold from dashboards
  web/src/components/alerts/AddAlert.vue
  web/src/components/dashboards/AlertContextMenu.vue
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/components/dashboards/panels/ChartRenderer.vue
Labels: ☢️ Bug, Review effort 3/5

#8725 fix: menu item and home view changes
  web/src/components/MenuLink.vue
  web/src/views/HomeView.vue
Labels: ☢️ Bug, Review effort 2/5

#8729 fix: build manifest of both builds succeed plus more
  .github/workflows/api-testing.yml
  .github/workflows/build-pr-image.yml
  .github/workflows/js-license-checker.yml
  .github/workflows/playwright.yml
  .github/workflows/release.yml
  .github/workflows/unit-tests.yml
  deploy/build/Dockerfile.pr
  web/src/components/ingestion/recommended/KubernetesConfig.vue
Labels: ☢️ Bug, Review effort 2/5

#8720 fix: add retry for enrichment table failure (#8716)
  src/service/db/enrichment_table.rs
  src/service/enrichment/mod.rs
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#8728 chore: traces UI changes
  web/src/plugins/traces/SpanBlock.vue
  web/src/plugins/traces/TraceDetails.vue
  web/src/plugins/traces/TraceDetailsSidebar.vue
  web/src/plugins/traces/TraceHeader.spec.ts
  web/src/plugins/traces/TraceHeader.vue
  web/src/plugins/traces/TraceTree.spec.ts
  web/src/plugins/traces/TraceTree.vue
Labels: ☢️ Bug, Review effort 3/5

#8732 fix: dashboard filter flaky testcases
  tests/ui-testing/pages/dashboardPages/dashboard-filter.js
  tests/ui-testing/playwright-tests/dashboards/dashboard-filter.spec.js
Labels: ☢️ Bug, 🧹 Updates, Review effort 3/5

#8736 fix: fetch annotations in parallel with queries
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug, Review effort 2/5

#8741 fix: fetch annotations in parallel with queries
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#8740 fix: node list ttl rc9
  src/common/infra/cluster/mod.rs
Labels: ☢️ Bug

#8743 fix: fetch annotations in parallel with queries
  web/src/components/dashboards/PanelSchemaRenderer.vue
  web/src/composables/dashboard/usePanelDataLoader.ts
Labels: ☢️ Bug

#8748 fix: promql editor issues in add alert page
  web/src/components/alerts/ScheduledAlert.vue
Labels: ☢️ Bug, ✏️ Feature, Review effort 2/5

#8750 fix: `timed_annotations.end_time` column update type
  src/infra/src/table/timed_annotations.rs
Labels: ☢️ Bug, 🧹 Updates

#8755 fix: show query limit error only for dashboard rc7
  src/common/meta/search.rs
  src/handler/http/request/ai.rs
  src/handler/http/request/search/mod.rs
  src/handler/http/request/search/search_stream.rs
  src/service/search/cache/mod.rs
  src/service/search/cluster/http.rs
  src/service/search/utils.rs
Labels: ☢️ Bug

#8756 fix: alert querier should pick interactive querier when given role group is interactive
  src/service/search/cluster/flight.rs
Labels: ☢️ Bug

#8754 fix: alert querier should pick interactive querier when given role group is interactive
  src/service/search/cluster/flight.rs
Labels: ☢️ Bug

#8731 feat: cache hist query with non ts col order by
  src/common/meta/search.rs
  src/handler/grpc/request/query_cache.rs
  src/service/search/cache/cacher.rs
  src/service/search/cache/mod.rs
  src/service/search/cache/multi.rs
  src/service/search/cache/result_utils.rs
  src/service/search/cluster/cache_multi.rs
  src/service/search/cluster/cacher.rs
  src/service/websocket_events/search.rs
Labels: ✏️ Feature

#8761 fix: cache and http2 steaming for multi order by clause
  src/service/search/cache/multi.rs
  src/service/search/search_stream.rs
Labels: ☢️ Bug

#8751 fix: `timed_annotations.end_time` column update type
  src/infra/src/table/timed_annotations.rs
Labels: ☢️ Bug, 🧹 Updates, Review effort 1/5
